/* Движок универсальной анкеты: старт (компания и тип бизнеса) → разделы по модулям → итоговое ТЗ.
   Хранение: браузер + сервер Pllato (id и ключ выдаются при старте, ссылка с ключом — единственный доступ). */
const WB='https://pllato-elc-worker.uurraa.workers.dev/api/public/';
const QS=new URLSearchParams(location.search);
let ID=QS.get('id')||'',KEY=QS.get('key')||'';const REF=QS.get('ref')||'';
if(!ID){try{const l=JSON.parse(localStorage.getItem('briefu:last')||'null');if(l&&l.id){ID=l.id;KEY=l.key||''}}catch(e){}}
const LS=()=>'briefu:'+(ID||'new');
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const js=s=>JSON.stringify(s).replace(/"/g,'&quot;');
let A={},META={},dirty={},saveT=null,srvOK=null,lastSave=null,SECS=[];
let view=ID?(QS.get('s')?'sec':(location.hash==='#tz'?'tz':'home')):'start',cur=QS.get('s')||'about';
const AUTOQ=[{id:'extra',q:'Что мы не учли в этом разделе? Опишите своими словами',t:'ta',auto:1,ph:'Всё, что важно для вашей компании и о чём не спросили выше'},{id:'custom',q:'Добавьте свои вопросы и ответы',t:'tbl',cols:['Ваш вопрос / тема','Ответ'],rows:[['','']],auto:1}];
const OWN={k:'own',n:'Свои разделы и дополнения',ic:'+',who:'Собственник',intro:'Если в вашей компании есть процессы или отделы, которых нет в анкете, — опишите их здесь. Всё попадёт в ТЗ.',qs:[{id:'secs',q:'Разделы и процессы, которые мы не учли',t:'tbl',cols:['Раздел / процесс','Что в нём происходит и что должна делать система'],rows:[['',''],['','']]},{id:'free',q:'Всё, что ещё важно знать о вашем бизнесе',t:'ta'}]};
function mods(){const m=A['_mods']||META.mods||[];return Array.isArray(m)?m:[]}
function buildSecs(){const ms=mods();SECS=[...BRIEFU.core.slice(0,7),...ms.filter(k=>BRIEFU.mods[k]).map(k=>BRIEFU.mods[k]),...BRIEFU.core.slice(7),BRIEFU.tail,OWN].map(s=>({...s,qs:s.k==='own'?s.qs:[...s.qs,...AUTOQ]}))}
const S=k=>SECS.find(s=>s.k===k)||SECS[0],Q=(sk,id)=>S(sk).qs.find(q=>q.id===id),qk=(s,q)=>s.k+'.'+q.id;
function initVal(s,q){if(q.t==='tbl')return (q.rows||[['']]).map(r=>r.slice());if(q.t==='mu')return [];if(q.t==='yn')return {v:'',c:''};return ''}
function val(s,q){const k=qk(s,q);return A[k]!==undefined?A[k]:initVal(s,q)}
function filled(s,q){const v=A[qk(s,q)];if(v===undefined||v===null)return false;if(q.t==='tbl')return v.some(r=>(q.cols.length>2?r.slice(1):r).some(c=>String(c).trim()));if(q.t==='mu')return v.length>0;if(q.t==='yn')return !!v.v;return String(v).trim().length>0}
const base=s=>s.qs.filter(q=>!q.auto);
function secPct(s){const b=base(s);return b.length?Math.round(b.filter(q=>filled(s,q)).length/b.length*100):0}
function totPct(){let a=0,b=0;SECS.forEach(s=>base(s).forEach(q=>{b++;if(filled(s,q))a++}));return b?Math.round(a/b*100):0}
const totQ=()=>SECS.reduce((a,s)=>a+base(s).length,0);
const extras=()=>SECS.reduce((a,s)=>a+s.qs.filter(q=>q.auto&&filled(s,q)).length,0);
const who=()=>{try{return localStorage.getItem('briefu:who')||''}catch(e){return ''}};
/* хранение */
function loadLocal(){try{const r=JSON.parse(localStorage.getItem(LS())||'{}');A=r.answers||{};META=r.meta||META}catch(e){}}
function saveLocal(){try{localStorage.setItem(LS(),JSON.stringify({answers:A,meta:META}));if(ID)localStorage.setItem('briefu:last',JSON.stringify({id:ID,key:KEY,company:META.company||''}))}catch(e){}}
async function loadServer(){if(!ID||!KEY||ID==='local')return;try{const r=await fetch(WB+'brief/'+ID+'?key='+encodeURIComponent(KEY));if(!r.ok)throw 0;const d=await r.json();srvOK=true;Object.entries(d.answers||{}).forEach(([k,v])=>{if(A[k]===undefined)A[k]=v});META=Object.assign({},d.meta||{},META);lastSave=d.updatedAt;saveLocal()}catch(e){srvOK=false}}
async function create(){try{const r=await fetch(WB+'brief-new',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company:META.company,contact:META.contact,phone:META.phone,kinds:META.kinds,mods:mods(),ref:META.ref||REF})});if(!r.ok)throw 0;const d=await r.json();
 const old=LS();ID=d.id;KEY=d.key;try{localStorage.removeItem(old)}catch(e){}dirty=Object.assign({},A);saveLocal();return true}catch(e){return false}}
function setA(k,v){A[k]=v;dirty[k]=v;saveLocal();status('pending');clearTimeout(saveT);saveT=setTimeout(push,1200);live();const[sk,id]=k.split('.');ring(sk);const q=SECS.length&&Q(sk,id),el=document.getElementById('q_'+sk+'_'+id);if(q&&el)el.classList.toggle('done',filled(S(sk),q))}
async function push(extra){if(ID==='local'){if(!(await create())){status('local');return}render()}
 if(!ID||!KEY){status('local');return}const patch=dirty;dirty={};
 try{const r=await fetch(WB+'brief/'+ID,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,answers:patch,meta:Object.assign({lastBy:who(),lastSection:cur,company:META.company,contact:META.contact,phone:META.phone,kinds:META.kinds,mods:mods(),ref:META.ref||REF},extra||{})})});if(!r.ok)throw 0;const d=await r.json();srvOK=true;lastSave=d.updatedAt;status('ok')}
 catch(e){Object.assign(dirty,patch);srvOK=false;status('local')}}
function status(st){const el=document.getElementById('sv');if(!el)return;const t=lastSave?new Date(lastSave).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'';el.className='sv '+st;el.innerHTML=st==='pending'?'<i></i>Сохраняю…':st==='ok'?`<i></i>Сохранено в Pllato · ${t}`:st==='local'?'<i></i>Сохранено на этом устройстве':'<i></i>Готово к работе'}
/* поля */
function field(s,q){const k=qk(s,q),v=val(s,q),a=`'${s.k}','${q.id}'`;
 if(q.t==='t')return `<input class="in" value="${esc(v)}" placeholder="${esc(q.ph||'')}" oninput="setA('${k}',this.value)">`;
 if(q.t==='ta')return `<textarea class="in ta" rows="3" placeholder="${esc(q.ph||'')}" oninput="setA('${k}',this.value);grow(this)">${esc(v)}</textarea>`;
 if(q.t==='ch')return `<div class="chips">${q.o.map(o=>`<a class="chip ${v===o?'on':''}" onclick="setA('${k}',${js(o)});rq(${a})">${esc(o)}</a>`).join('')}<input class="in other" placeholder="Свой вариант" value="${q.o.includes(v)?'':esc(v)}" onchange="setA('${k}',this.value);rq(${a})"></div>`;
 if(q.t==='mu'){const arr=Array.isArray(v)?v:[];return `<div class="chips">${q.o.map(o=>`<a class="chip ${arr.includes(o)?'on':''}" onclick="tg('${k}',${js(o)},${a})">${arr.includes(o)?'✓ ':''}${esc(o)}</a>`).join('')}${arr.filter(x=>!q.o.includes(x)).map(x=>`<a class="chip on" onclick="tg('${k}',${js(x)},${a})">✓ ${esc(x)}</a>`).join('')}<input class="in other" placeholder="+ своё, Enter" onkeydown="if(event.key==='Enter'&&this.value.trim()){tg('${k}',this.value.trim(),${a})}"></div>`}
 if(q.t==='yn'){const o=v||{};return `<div class="chips">${['Да','Нет','Пока не знаю'].map(x=>`<a class="chip ${o.v===x?'on':''}" onclick="setA('${k}',{v:'${x}',c:(A['${k}']||{}).c||''});rq(${a})">${x}</a>`).join('')}</div><input class="in" placeholder="Комментарий" value="${esc(o.c||'')}" oninput="setA('${k}',{v:(A['${k}']||{}).v||'',c:this.value})">`}
 if(q.t==='tbl')return `<div class="tblw"><table class="tb"><thead><tr>${q.cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th></th></tr></thead><tbody>${v.map((r,i)=>`<tr>${q.cols.map((c,j)=>`<td><input value="${esc(r[j]||'')}" oninput="tc('${k}',${i},${j},this.value,${a})"></td>`).join('')}<td class="x"><a onclick="trw('${k}',${i},${a})">×</a></td></tr>`).join('')}</tbody></table><a class="addrow" onclick="tad('${k}',${a})">+ строка</a></div>`;
 return ''}
function tg(k,o,sk,id){const x=Array.isArray(A[k])?A[k].slice():[];const i=x.indexOf(o);if(i>=0)x.splice(i,1);else x.push(o);setA(k,x);rq(sk,id)}
function tc(k,i,j,v,sk,id){const s=S(sk),q=Q(sk,id);const rows=val(s,q).map(r=>r.slice());while(rows[i].length<q.cols.length)rows[i].push('');rows[i][j]=v;setA(k,rows)}
function tad(k,sk,id){const s=S(sk),q=Q(sk,id);const rows=val(s,q).map(r=>r.slice());rows.push(q.cols.map(()=>''));setA(k,rows);rq(sk,id)}
function trw(k,i,sk,id){const s=S(sk),q=Q(sk,id);const rows=val(s,q).map(r=>r.slice());rows.splice(i,1);setA(k,rows.length?rows:[q.cols.map(()=>'')]);rq(sk,id)}
function rq(sk,id){const s=S(sk),q=Q(sk,id);const el=document.getElementById('q_'+sk+'_'+id);if(el)el.outerHTML=qcard(s,q,s.qs.indexOf(q));ring(sk)}
function grow(t){t.style.height='auto';t.style.height=Math.min(420,t.scrollHeight+2)+'px'}
function qcard(s,q,i){const f=filled(s,q);return `<div class="qc ${f?'done':''} ${q.auto?'auto':''}" id="q_${s.k}_${q.id}"><div class="qn">${q.auto?'<b>+</b>':`<b>${String(i+1).padStart(2,'0')}</b>`}${f?'<i>✓</i>':''}</div><div class="qb"><h3>${esc(q.q)}</h3>${q.why?`<p class="why">Зачем: ${esc(q.why)}</p>`:''}${field(s,q)}</div></div>`}
/* экраны */
function ringSvg(p,sz){const r=(sz-6)/2,c=2*Math.PI*r;return `<svg class="ring" width="${sz}" height="${sz}" viewBox="0 0 ${sz} ${sz}"><circle cx="${sz/2}" cy="${sz/2}" r="${r}" class="rb"/><circle cx="${sz/2}" cy="${sz/2}" r="${r}" class="rf" stroke-dasharray="${c}" stroke-dashoffset="${c*(1-p/100)}"/></svg>`}
function ring(sk){const s=SECS.find(x=>x.k===sk);if(!s)return;const p=secPct(s);document.querySelectorAll(`[data-ring="${sk}"]`).forEach(el=>{el.innerHTML=ringSvg(p,+el.dataset.sz||34)+`<b>${p}</b>`});const t=totPct();document.querySelectorAll('[data-tot]').forEach(el=>el.textContent=t+'%');const b=document.getElementById('topbar');if(b)b.style.width=t+'%'}
function hdr(){return `<header class="hb"><div class="lg">${LOGO}<b>Pllato</b><span>· ${esc(META.company||BRIEFU.title)}</span></div><div class="hr"><span id="sv" class="sv"></span>${ID?'<a class="bt ghost" onclick="openHome()">Карта компании</a>':''}</div><div class="topbar"><i id="topbar" style="width:${ID?totPct():0}%"></i></div></header>`}
function nav(){return `<aside class="nv"><div class="nvh"><b>Разделы</b><span><b data-tot>${totPct()}%</b> описано</span></div>${SECS.map((s,i)=>`<a class="ni ${s.k===cur&&view==='sec'?'on':''}" onclick="openSec('${s.k}')"><span class="rg" data-ring="${s.k}" data-sz="30">${ringSvg(secPct(s),30)}<b>${secPct(s)}</b></span><span class="nt"><b>${i+1}. ${esc(s.n)}</b><em>${esc(s.who)}</em></span></a>`).join('')}<a class="ni fin ${view==='tz'?'on':''}" onclick="openTz()"><span class="rg">★</span><span class="nt"><b>Итоговое ТЗ</b><em>собирается из ответов</em></span></a></aside>`}
let ST={kinds:[],mods:[]};
function start(){return `${hdr()}<main class="home"><section class="hero st"><div class="hl"><span class="kick">Опросник для технического задания · Pllato</span><h1>Опишите ваш бизнес — <em>а мы соберём систему под него</em></h1><p>Около часа, можно частями. Анкета подстроится под тип вашего бизнеса: вопросы только про то, что у вас есть. В каждом разделе можно дописать то, что мы не учли, и добавить свои вопросы. По ответам мы соберём техническое задание.</p></div></section>
 <section class="stf"><div class="f2"><label>Компания<input class="in" id="st_c" placeholder="Название компании"></label><label>Ваше имя и должность<input class="in" id="st_n" placeholder="Имя, должность"></label><label>Телефон<input class="in" id="st_p" placeholder="+7 …"></label><input id="st_w" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px" aria-hidden="true"></div>
 <h3>Чем занимается компания? Можно несколько</h3><div class="chips">${BRIEFU.kinds.map(([n])=>`<a class="chip ${ST.kinds.includes(n)?'on':''}" onclick="stKind(${js(n)})">${ST.kinds.includes(n)?'✓ ':''}${esc(n)}</a>`).join('')}</div>
 <h3>Какие блоки включить в анкету</h3><p class="why">Отмечены по типу бизнеса — поправьте, если нужно. Общие разделы (клиенты, продажи, деньги, отчёты и др.) будут в любом случае.</p><div class="mods">${Object.entries(BRIEFU.modNames).map(([k,n])=>`<a class="md ${ST.mods.includes(k)?'on':''}" onclick="stMod('${k}')"><i>${ST.mods.includes(k)?'✓':''}</i>${esc(n)}</a>`).join('')}</div>
 <div class="hbtns"><a class="bt p big" onclick="stGo()">Начать анкету →</a></div></section></main>`}
function stKind(n){const i=ST.kinds.indexOf(n);if(i>=0)ST.kinds.splice(i,1);else{ST.kinds.push(n);(BRIEFU.kinds.find(x=>x[0]===n)||[0,[]])[1].forEach(m=>{if(!ST.mods.includes(m))ST.mods.push(m)})}keepStart(render)}
function stMod(k){const i=ST.mods.indexOf(k);if(i>=0)ST.mods.splice(i,1);else ST.mods.push(k);keepStart(render)}
function keepStart(fn){const v={c:document.getElementById('st_c')?.value,n:document.getElementById('st_n')?.value,p:document.getElementById('st_p')?.value};fn();['c','n','p'].forEach(x=>{const el=document.getElementById('st_'+x);if(el&&v[x])el.value=v[x]})}
async function stGo(){const c=document.getElementById('st_c').value.trim(),n=document.getElementById('st_n').value.trim(),p=document.getElementById('st_p').value.trim();if(document.getElementById('st_w').value)return;if(!c&&!n){toastB('Укажите компанию или ваше имя');return}
 META={company:c,contact:n,phone:p,kinds:ST.kinds.slice(),mods:ST.mods.slice(),ref:REF};A={'_mods':ST.mods.slice(),'about.name':c};try{localStorage.setItem('briefu:who',n)}catch(e){}
 ID='local';const ok=await create();if(!ok){ID='local';saveLocal()}else{await push()}buildSecs();view='home';render();
 modal(`<h3>Ваша личная ссылка на анкету</h3><p>Ответы сохраняются сами. По этой ссылке можно вернуться в любой момент и с любого устройства — сохраните её.</p><textarea class="in ta" rows="3" readonly>${esc(myLink())}</textarea><div class="hbtns"><a class="bt p" onclick="try{navigator.clipboard.writeText(myLink())}catch(e){};closeMod();toastB('Ссылка скопирована')">Скопировать и продолжить</a></div>`)}
const myLink=()=>location.origin+location.pathname+(ID&&ID!=='local'?'?id='+ID+'&key='+KEY:'');
function home(){const t=totPct();return `${hdr()}<main class="home"><section class="hero"><div class="hl"><span class="kick">Опросник для технического задания</span><h1>${esc(META.contact?META.contact.split(/[ ,]/)[0]+', ':'')}опишем <em>${esc(META.company||'вашу компанию')}</em> отдел за отделом</h1><p>Ответы сохраняются сами — можно делать перерывы и возвращаться по своей ссылке. Разделы можно переслать руководителям отделов. В каждом разделе есть место для того, что мы не учли.</p><div class="hs"><div><b>${SECS.length}</b><span>разделов</span></div><div><b>${totQ()}</b><span>вопросов</span></div><div><b>${extras()}</b><span>ваших дополнений</span></div><div><b data-tot>${t}%</b><span>описано</span></div></div><div class="hbtns"><a class="bt p" onclick="openSec('${(SECS.find(s=>secPct(s)<100)||SECS[0]).k}')">${t?'Продолжить':'Начать'} →</a><a class="bt" onclick="openTz()">Посмотреть ТЗ</a><a class="bt" onclick="cfgMods()">Настроить блоки</a><a class="bt" onclick="try{navigator.clipboard.writeText(myLink())}catch(e){};toastB('Ваша ссылка скопирована')">Моя ссылка</a></div></div><div class="hr2">${ringSvg(t,190)}<div class="big"><b data-tot>${t}%</b><span>бизнеса описано</span></div></div></section>
 <h2 class="mh">Карта вашей компании</h2><p class="mp">Нажмите на блок, чтобы ответить, или перешлите раздел тому, кто знает лучше.</p>
 <div class="map">${SECS.map((s,i)=>`<div class="mc ${secPct(s)===100?'full':''} ${s.k==='own'?'own':''}" onclick="openSec('${s.k}')"><div class="mt"><span class="mi">${s.ic}</span><span class="rg" data-ring="${s.k}" data-sz="40">${ringSvg(secPct(s),40)}<b>${secPct(s)}</b></span></div><b>${i+1}. ${esc(s.n)}</b><span>${base(s).length} вопросов · отвечает: ${esc(s.who)}</span><a class="fw" onclick="event.stopPropagation();share('${s.k}')">Переслать раздел ↗</a></div>`).join('')}</div></main>`}
function cfgMods(){modal(`<h3>Блоки анкеты</h3><p>Включите блоки, которые есть в вашей компании. Ответы в выключенных блоках сохраняются.</p><div class="mods">${Object.entries(BRIEFU.modNames).map(([k,n])=>`<a class="md ${mods().includes(k)?'on':''}" onclick="tgMod('${k}')"><i>${mods().includes(k)?'✓':''}</i>${esc(n)}</a>`).join('')}</div><div class="hbtns"><a class="bt p" onclick="closeMod()">Готово</a></div>`)}
function tgMod(k){const m=mods().slice();const i=m.indexOf(k);if(i>=0)m.splice(i,1);else m.push(k);setA('_mods',m);META.mods=m;buildSecs();render();cfgMods()}
function secView(){const s=S(cur),i=SECS.indexOf(s),nx=SECS[i+1];return `${hdr()}<div class="wrap">${nav()}<main class="sec"><div class="sh"><span class="kick">Раздел ${i+1} из ${SECS.length} · отвечает: ${esc(s.who)}</span><h1>${s.ic} ${esc(s.n)}</h1><p>${esc(s.intro)}</p><div class="shb"><span class="rg" data-ring="${s.k}" data-sz="44">${ringSvg(secPct(s),44)}<b>${secPct(s)}</b></span><a class="bt ghost" onclick="share('${s.k}')">Переслать раздел ↗</a></div></div>
 ${s.qs.map((q,j)=>qcard(s,q,j)).join('')}
 <div class="nx">${i>0?`<a class="bt" onclick="openSec('${SECS[i-1].k}')">← ${esc(SECS[i-1].n)}</a>`:'<span></span>'}${nx?`<a class="bt p" onclick="push();openSec('${nx.k}')">Дальше: ${esc(nx.n)} →</a>`:`<a class="bt p" onclick="push({done:true});openTz()">Собрать итоговое ТЗ ★</a>`}</div></main>
 <aside class="lv"><div class="lvh"><span class="dot"></span>ТЗ собирается в реальном времени</div><div id="live">${tzSec(s)}</div></aside></div>`}
function fmtAns(q,v){if(v===undefined||v===null)return '';if(q.t==='tbl'){const rows=v.filter(r=>r.some(c=>String(c).trim()));if(!rows.length)return '';return `<table class="tzt"><tr>${q.cols.map(c=>`<th>${esc(c)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${q.cols.map((c,j)=>`<td>${esc(r[j]||'')}</td>`).join('')}</tr>`).join('')}</table>`}
 if(q.t==='mu')return (v||[]).length?`<ul>${v.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';if(q.t==='yn')return v.v?`<p>${esc(v.v)}${v.c?' — '+esc(v.c):''}</p>`:'';return String(v).trim()?`<p>${esc(v).replace(/\n/g,'<br>')}</p>`:''}
function tzSec(s){const i=SECS.indexOf(s);const items=s.qs.map(q=>{if(!filled(s,q))return '';const a=fmtAns(q,A[qk(s,q)]);return a?`<div class="tzi ${q.auto?'add':''}"><b>${q.auto?'Дополнение клиента':esc(q.q)}</b>${a}</div>`:''}).join('');return `<h3>${i+1}. ${esc(s.n)}</h3>${items||'<p class="emp">Пока пусто — начните отвечать, и раздел ТЗ появится здесь.</p>'}`}
function live(){const el=document.getElementById('live');if(el&&view==='sec')el.innerHTML=tzSec(S(cur))}
function tz(){const t=totPct();return `${hdr()}<main class="tzw"><div class="tzd"><div class="tzc"><span class="kick">Техническое задание · черновик из опросника</span><h1>${esc(META.company||'Компания')}</h1><p>${esc([META.contact,META.phone].filter(Boolean).join(' · '))} · Исполнитель: Pllato · ${new Date().toLocaleDateString('ru-RU')}</p><p>${esc((META.kinds||[]).join(', '))}</p><div class="tzs"><div><b>${t}%</b><span>описано</span></div><div><b>${SECS.reduce((a,s)=>a+base(s).filter(q=>filled(s,q)).length,0)} / ${totQ()}</b><span>ответов</span></div><div><b>${extras()}</b><span>дополнений клиента</span></div></div><div class="hbtns np"><a class="bt p" onclick="window.print()">Печать / PDF</a><a class="bt" onclick="push({done:true});toastB('Анкета отправлена в Pllato. Спасибо! Мы вернёмся с вопросами, если что-то уточнить.')">Отправить в Pllato</a></div></div>
 ${SECS.map(s=>`<section class="tzsec">${tzSec(s)}</section>`).join('')}</div></main>`}
function render(){if(view!=='start')buildSecs();document.getElementById('root').innerHTML=view==='start'?start():view==='home'?home():view==='tz'?tz():secView();status(srvOK===false||ID==='local'?'local':srvOK?'ok':'idle');document.querySelectorAll('textarea').forEach(grow);
 try{const q=[];if(ID&&ID!=='local'){q.push('id='+ID,'key='+KEY)}if(REF&&!ID)q.push('ref='+encodeURIComponent(REF));if(view==='sec')q.push('s='+cur);history.replaceState(null,'',location.pathname+(q.length?'?'+q.join('&'):'')+(view==='tz'?'#tz':''))}catch(e){}}
function openSec(k){cur=k;view='sec';render();scrollTo(0,0)}
function openHome(){view='home';render();scrollTo(0,0)}
function openTz(){view='tz';render();scrollTo(0,0)}
function share(sk){const s=S(sk);const u=location.origin+location.pathname+'?'+(ID&&ID!=='local'?'id='+ID+'&key='+KEY+'&':'')+'s='+sk;const txt=`Здравствуйте! Помогите, пожалуйста, заполнить раздел «${s.n}» для техзадания нашей новой системы: ${u}`;try{navigator.clipboard.writeText(txt)}catch(e){}
 modal(`<h3>Переслать раздел «${esc(s.n)}»</h3><p>Ссылка ведёт сразу в этот раздел. Ответы появятся в общей анкете.</p><textarea class="in ta" rows="4" readonly>${esc(txt)}</textarea><div class="hbtns"><a class="bt p" href="https://wa.me/?text=${encodeURIComponent(txt)}" target="_blank" rel="noopener">Отправить в WhatsApp</a><a class="bt" onclick="closeMod()">Скопировано ✓</a></div>`)}
function modal(h){const m=document.getElementById('mod');m.innerHTML=`<div class="mbx">${h}</div>`;m.classList.add('show');m.onclick=e=>{if(e.target===m)closeMod()}}
function closeMod(){document.getElementById('mod').classList.remove('show')}
function toastB(t){const el=document.getElementById('tst');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),4500)}
function askWho(){if(who())return;modal(`<h3>Кто заполняет раздел?</h3><p>Чтобы в ТЗ было видно, кто описал раздел.</p><input class="in" id="whoin" placeholder="Имя и должность"><div class="hbtns"><a class="bt p" onclick="try{localStorage.setItem('briefu:who',document.getElementById('whoin').value.trim()||'—')}catch(e){};closeMod()">Начать</a></div>`)}
window.addEventListener('beforeunload',()=>{if(Object.keys(dirty).length&&ID&&KEY&&ID!=='local'){try{fetch(WB+'brief/'+ID,{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify({key:KEY,answers:dirty,meta:{lastBy:who()}})})}catch(e){}}});
(async function(){if(view==='start'){render();return}loadLocal();buildSecs();render();await loadServer();buildSecs();render();if(QS.get('s'))askWho()})();
