import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {handleLeadDistribution,assignLeadManagers,distributionSlots} from './lead-distribution.js';
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(uid TEXT PRIMARY KEY,active INTEGER);CREATE TABLE pipelines(id TEXT PRIMARY KEY,stages TEXT);INSERT INTO users VALUES('a',1),('b',1),('k',1),('off',0);INSERT INTO pipelines VALUES('p','{"NEW":{"statusId":"NEW","name":"Новая"}}');`);
 const DB={prepare(sql){let args=[];return{bind(...v){args=v;return this;},async first(){return db.prepare(sql).get(...args)||null;},async run(){return db.prepare(sql).run(...args);},exec(){const stmt=db.prepare(sql);return stmt.columns().length?{results:stmt.all(...args).map(r=>({...r}))}:{results:[],meta:stmt.run(...args)};}};},async batch(stmts){db.exec('BEGIN');try{const results=stmts.map(s=>s.exec());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};
 const env={DB};const deps={requireAdmin:async r=>r.headers.get('X-Role')==='agent'?{error:'forbidden',status:403}:{},json:(v,s)=>Response.json(v,{status:s})};
 const req=(body,role='admin')=>handleLeadDistribution(new Request('https://test/api/pipelines/p/lead-distribution',{method:body?'PUT':'GET',headers:{'X-Role':role},body:body?JSON.stringify(body):undefined}),env,deps,'p');
 const config={enabled:true,stageId:'NEW',mode:'equal',rows:[{leadUid:'a',kepUid:'k',weight:1},{leadUid:'b',kepUid:null,weight:1}]};
 return{db,env,req,config,assign:id=>assignLeadManagers(env,'p','NEW',id)};
}
test('равномерная очередь, пара КЭП и повтор webhook',async()=>{const f=fixture();assert.equal((await f.req(f.config)).status,200);assert.deepEqual(await f.assign('1'),{leadUid:'a',kepUid:'k'});assert.equal((await f.assign('2')).leadUid,'b');assert.equal((await f.assign('1')).leadUid,'a');assert.equal((await f.assign('3')).leadUid,'a');assert.equal(f.db.prepare('SELECT cursor FROM lead_distribution').get().cursor,3);});
test('параллельные обращения не получают одну позицию',async()=>{const f=fixture();await f.req(f.config);const rows=await Promise.all(Array.from({length:20},(_,i)=>f.assign(String(i))));assert.equal(rows.filter(r=>r.leadUid==='a').length,10);assert.equal(rows.filter(r=>r.leadUid==='b').length,10);});
test('пропорции 70/30 соблюдаются за полный цикл',async()=>{const f=fixture();f.config.mode='weighted';f.config.rows[0].weight=70;f.config.rows[1].weight=30;await f.req(f.config);const rows=[];for(let i=0;i<100;i++)rows.push(await f.assign(String(i)));assert.equal(rows.filter(r=>r.leadUid==='a').length,70);assert.equal(rows.filter(r=>r.leadUid==='b').length,30);assert.ok(distributionSlots(f.config.rows,'weighted').slice(0,10).some(r=>r.leadUid==='b'));});
test('выключено, другая стадия и другая воронка не назначаются',async()=>{const f=fixture();assert.equal(await f.assign('0'),null);await f.req(f.config);assert.equal(await assignLeadManagers(f.env,'p','WON','1'),null);assert.equal(await assignLeadManagers(f.env,'other','NEW','2'),null);await f.req({...f.config,enabled:false});assert.equal(await f.assign('3'),null);});
test('неактивные сотрудники пропускаются',async()=>{const f=fixture();await f.req(f.config);f.db.exec("UPDATE users SET active=0 WHERE uid IN ('a','k')");assert.deepEqual(await f.assign('1'),{leadUid:'b',kepUid:null});f.db.exec("UPDATE users SET active=0 WHERE uid='b'");assert.equal(await f.assign('2'),null);});
test('правила меняются только для следующих лидов',async()=>{const f=fixture();await f.req(f.config);await f.assign('1');await f.req({...f.config,rows:[{leadUid:'b',kepUid:'b',weight:1}]});assert.deepEqual(await f.assign('1'),{leadUid:'a',kepUid:'k'});assert.deepEqual(await f.assign('2'),{leadUid:'b',kepUid:'b'});});
test('сохранение доступно только админу; проверяет сотрудников и доли',async()=>{const f=fixture();assert.equal((await f.req(f.config,'agent')).status,403);assert.equal((await f.req(null,'agent')).status,403);for(const patch of [{rows:[]},{rows:[{leadUid:'off'}]},{rows:[{leadUid:'missing'}]},{rows:[{leadUid:'a',kepUid:'missing'}]},{rows:[{leadUid:'a'},{leadUid:'a'}]},{stageId:'missing'},{mode:'weighted',rows:[{leadUid:'a',weight:0}]},{mode:'weighted',rows:[{leadUid:'a',weight:1.5}]}])assert.equal((await f.req({...f.config,...patch})).status,400);});
