
const SC={};
const stg=k=>{const s=STN(k);return `<span class="stg" style="--sc:${s.c}">${s.n}</span>`};
const pbar=p=>`<div class="pbr"><i style="width:${p}%"></i></div>`;

SC.today=()=>{const act=PRJ.filter(p=>p.st!=='done');const late=DOCS.filter(d=>d[5]==='late').length;
 return `<div class="hd"><div><h2>Пульт директора · ${TODAY}</h2><p>Проектирование, стройка и слаботочка — в одной системе. Не нужно открывать пять Excel-файлов: какой проект на какой стадии, кто из 40 проектировщиков чем занят, что горит на экспертизе и сколько денег пришло.</p></div><div class="btns"><button class="bt p" onclick="card('newpr')">+ Проект</button></div></div>
 <div class="wid">
  <div class="clk" onclick="go('projects')"><small>Проектов в работе</small><b>${act.length}</b><span>на ${mln(act.reduce((a,p)=>a+p.sum,0))}</span></div>
  <div class="clk" onclick="go('expert')"><small>На экспертизе</small><b class="w">${PRJ.filter(p=>p.st==='exp').length}</b><span>${EXP.filter(e=>e.st!=='done').length} замечаний открыто</span></div>
  <div class="clk" onclick="go('docs')"><small>Разделы просрочены</small><b class="r">${late}</b><span>П-2611 · ОВ и ЭЭ</span></div>
  <div class="clk" onclick="go('load')"><small>Загрузка отдела</small><b>81 %</b><span>2 человека перегружены</span></div>
  <div class="clk" onclick="go('finance')"><small>Получено в октябре</small><b class="g">18,6 млн</b><span>ждём ещё 31,4 млн</span></div>
 </div>
 <div class="g3">
  <div class="pan dir"><h3>Проектирование</h3><p class="mini">40 человек · Тимур</p>${ST.slice(0,6).map(s=>`<div class="kv"><span>${s.n}</span><b>${PRJ.filter(p=>p.st===s.k).length}</b></div>`).join('')}<button class="bt sm" onclick="go('projects')">Канбан проектов →</button></div>
  <div class="pan dir"><h3>Строительство</h3><p class="mini">40 человек · Мурат</p>${BLD.map(b=>`<div class="kv"><span>${b.n}</span><b>${b.done}%</b></div>`).join('')}<button class="bt sm" onclick="go('build')">Стройка →</button></div>
  <div class="pan dir"><h3>Монтаж слаботочных систем</h3><p class="mini">бригады · Тимур, Даурен</p>${LOW.map(b=>`<div class="kv"><span>${b.n.split(',')[0]}</span><b>${b.done}%</b></div>`).join('')}<button class="bt sm" onclick="go('lowcur')">Слаботочка →</button></div>
 </div>
 <div class="g2"><div class="pan"><h3>Требует внимания</h3>
  <div class="rf bad" onclick="go('expert')"><i></i><div><b>П-2611 · детский сад — ответ экспертизе до 09.10</b><span>2 замечания просрочены: ОВ (Руслан), ЭЭ (Нурсултан)</span></div></div>
  <div class="rf bad" onclick="go('load')"><i></i><div><b>Руслан загружен на 118 %</b><span>три проекта одновременно — ОВ по П-2611 уже просрочен</span></div></div>
  <div class="rf" onclick="go('ird')"><i></i><div><b>П-2619 · школа — ТУ на газ ждём 24-й день</b><span>срок по закону 15 рабочих дней — написать письмо</span></div></div>
  <div class="rf" onclick="go('leads')"><i></i><div><b>К-299 · «Алтай Девелопмент», второй блок — договор на подписи</b><span>58 млн · проект + стройка + слаботочка</span></div></div></div>
 <div class="pan"><h3>Проекты и сроки</h3><div class="tw"><table class="t"><thead><tr><th>Проект</th><th>Стадия</th><th>Готово</th><th>Срок</th></tr></thead><tbody>${act.map(p=>`<tr class="clk" onclick="curPr='${p.id}';go('project')"><td><b>${p.id}</b> ${esc(p.n)}</td><td>${stg(p.st)}</td><td style="width:22%">${pbar(p.done)}<span class="mini">${p.done}%</span></td><td class="mono">${p.due}</td></tr>`).join('')}</tbody></table></div></div></div>
 ${said('«Хочется, чтобы была какая-то платформа, где все эти данные хранились в одном месте — а не переезд с документа на документ, с Excel-ки в Excel-ку».')}`};

SC.analytics=()=>`<div class="hd"><div><h2>Аналитика и стоимость проектов</h2><p>Сколько стоит каждый проект для компании: часы проектировщиков по разделам, субподряд, экспертиза — против суммы договора. Сколько дней проект стоит на каждой стадии.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Проект</th><th class="r">Договор</th><th class="r">Часы</th><th class="r">Себестоимость</th><th class="r">Маржа</th><th class="r">Получено</th></tr></thead><tbody>${PRJ.map((p,i)=>{const h=[2140,1980,620,1240,310,180,1320][i]||0;const c=h*6500+([2.1,1.8,.4,3.2,.2,.3,1.1][i]||0)*1e6;return `<tr class="clk" onclick="curPr='${p.id}';go('project')"><td><b>${p.id}</b> ${esc(p.n)}</td><td class="r mono">${mln(p.sum)}</td><td class="r mono">${fmt(h)}</td><td class="r mono">${mln(c)}</td><td class="r mono ${p.sum-c>0?'pos':'neg'}">${pct(p.sum-c,p.sum)}%</td><td class="r mono">${mln(p.paid)}</td></tr>`}).join('')}</tbody></table></div>
 <div class="g2"><div class="pan"><h3>Среднее время на стадии, дней</h3>${[['Земельный участок',21],['ИРД: АПЗ и ТУ',34],['Эскизный проект',14],['Проект (стадия П)',45],['Экспертиза',38],['Рабочая документация',40]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${x[1]*2}%"></i><b class="mono">${x[1]}</b></div>`).join('')}<p class="mini">Дольше всего — проект и экспертиза. Экспертиза: 60 % времени уходит на повторные замечания по ОВ и ЭОМ.</p></div>
 <div class="pan"><h3>Замечания экспертизы по разделам за год</h3>${[['ОВ',41],['ЭОМ',36],['КЖ',22],['СМ',19],['АР',14],['ВК',9]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${x[1]*2}%;background:var(--warn)"></i><b class="mono">${x[1]}</b></div>`).join('')}</div></div>`;

SC.calendar=()=>{const days=['пн 05','вт 06','ср 07','чт 08','пт 09','пн 12','вт 13','ср 14','чт 15','пт 16'];const EV={'чт 08':[['Ответ экспертизе П-2611 · ОВ, ЭЭ','r']],'пт 09':[['Ответ экспертизе П-2611 · КЖ, ЭОМ','w'],['Встреча · «Алтай Девелопмент», подписание','i']],'ср 07':[['Выезд на участок · П-2622','']],'пн 12':[['Сдача РД ресторана · П-2617','g']],'вт 13':[['Подача на экспертизу · П-2614','w']],'ср 14':[['Комиссия · кафе «Ульба», слаботочка','i']],'пт 16':[['Пусконаладка СКУД · ЖК «Иртыш»','']]};
 return `<div class="hd"><div><h2>Календарь</h2><p>Сроки разделов, ответы экспертизе, выезды на участки, встречи с клиентами, комиссии на стройке — одним календарём. Каждый видит своё, директор — всё.</p></div></div>
 <div class="cal">${days.map(d=>`<div class="cd ${d==='ср 07'?'on':''}"><b>${d}</b>${(EV[d]||[]).map(e=>`<div class="ce ${e[1]}">${e[0]}</div>`).join('')}</div>`).join('')}</div>`};

SC.leads=()=>`<div class="hd"><div><h2>Воронка клиентов</h2><p>Отдела продаж нет — клиентов приводите вы и учредитель. Но каждое обращение заводится в воронку, чтобы не потерялось: встреча и ТЗ, КП, договор — и проект сам появляется в канбане проектирования.</p></div><div class="btns"><button class="bt p" onclick="card('newlead')">+ Обращение</button></div></div>
 <div class="kb k5">${LST2.map(([k,n])=>{const L=LEADS.filter(l=>l.st===k);return `<div class="kc" style="--sc:var(--brand)"><div class="kh"><b>${n}</b><span>${L.length}</span></div>${L.map(l=>`<div class="kd" onclick="leadNext('${l.id}')"><div class="kt"><b>${l.id}</b><span class="src">${l.src}</span></div><div class="kr">${esc(l.n)}</div><div class="km">${esc(l.t)}</div><div class="kf">${l.who} · ${l.d}<b>${mln(l.sum)}</b></div></div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 <p class="mini">Клик по карточке — на следующий этап. На «Договор → Передан в проект» создаётся проект со стадией «Земельный участок» и разделами по шаблону.</p>`;
function leadNext(id){const l=LEADS.find(x=>x.id===id),o=LST2.map(x=>x[0]),i=o.indexOf(l.st);if(i>=o.length-1){toast('Уже передан в проект.');return}l.st=o[i+1];if(l.st==='work'){const nid='П-'+(2623+PRJ.length-7);PRJ.push({id:nid,n:l.t,cl:l.n,addr:'—',st:'land',gip:'не назначен',sum:l.sum,paid:0,due:'—',done:0,docs:20,late:0,full:true});render();toast(`${l.id} → проект ${nid} создан в стадии «Земельный участок». Разделы — по шаблону, ГИП назначьте в карточке.`);return}render();toast(`${l.id} → «${LST2[i+1][1]}».`)}

SC.clients=()=>`<div class="hd"><div><h2>Клиенты и объекты</h2><p>Один клиент — несколько объектов и направлений: проект, стройка, слаботочка, узаконение. Вся история и долги — в одном месте.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Объекты</th><th>Направления</th><th class="r">Договоры</th><th class="r">Долг</th></tr></thead><tbody>${[['ГУ «Отдел строительства г. Усть-Каменогорска»','Детский сад на 280 мест','проект',48.6,24.3],['ТОО «Алтай Девелопмент»','Жилой дом 9 эт. · второй блок','проект, стройка, слаботочка',61.2,6.1],['ТОО «ВостокЭнергоСервис»','Административное здание','проект, стройка, слаботочка',62.4,4.8],['ИП Нурланов','Ресторан','проект',14.8,4.4],['ГУ «Управление образования ВКО»','Школа на 600 мест','проект',72.4,0],['Сергей Пак','Коттедж','проект',3.9,0]].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="mini">${r[2]}</td><td class="r mono">${String(r[3]).replace('.',',')} млн</td><td class="r mono ${r[4]?'neg':''}">${r[4]?String(r[4]).replace('.',',')+' млн':'—'}</td></tr>`).join('')}</tbody></table></div>`;

SC.projects=()=>`<div class="hd"><div><h2>Проекты · канбан проектирования</h2><p>Ваш путь «под ключ»: участок → разрешительные документы → эскиз → проект → экспертиза → рабочая документация → стройка. На карточке — ГИП, готовность разделов и просрочки.</p></div><div class="btns"><button class="bt p" onclick="card('newpr')">+ Проект</button></div></div>
 <div class="kb">${ST.map(s=>{const L=PRJ.filter(p=>p.st===s.k);return `<div class="kc" style="--sc:${s.c}"><div class="kh"><b>${s.n}</b><span>${L.length}</span></div>${L.map(p=>`<div class="kd ${p.late?'alarm':''}" onclick="curPr='${p.id}';go('project')"><div class="kt"><b>${p.id}</b><span class="src">ГИП ${p.gip}</span></div><div class="kr">${esc(p.n)}</div><div class="km">${esc(p.cl)}</div>${pbar(p.done)}<div class="kf">${p.docs} разделов<b>${p.due}</b></div>${p.late?`<div class="lack">${p.late} раздела просрочено</div>`:''}</div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>`;

SC.project=()=>{const p=PR(curPr),si=STI(p.st),D=p.id==='П-2611'?DOCS:DOCS.slice(0,8).map((d,i)=>[d[0],d[1],d[2],Math.min(100,Math.max(0,p.done+(i%3-1)*15)),d[4],p.done>90?'done':'work']);
 return `<div class="hd"><div><div class="mini"><a class="lk" onclick="go('projects')">Проекты</a> / ${p.id}</div><h2>${p.id} · ${esc(p.n)}</h2><p>${esc(p.cl)} · ${esc(p.addr)} · ГИП ${p.gip} · срок ${p.due}</p></div><div class="btns"><button class="bt" onclick="go('chat')">Переписка</button><button class="bt p" onclick="prNext('${p.id}')">→ ${si<ST.length-1?ST[si+1].n:'готово'}</button></div></div>
 <div class="stp">${ST.map((s,i)=>`<div class="${i<si?'ok':i===si?'on':''}" style="--sc:${s.c}"><i>${i<si?'✓':i+1}</i>${s.n}</div>`).join('')}</div>
 <div class="wid"><div><small>Готовность</small><b class="a">${p.done}%</b><span>по разделам</span></div><div class="clk" onclick="go('docs')"><small>Разделов</small><b>${p.docs}</b><span>${p.late?p.late+' просрочено':'в срок'}</span></div><div class="clk" onclick="go('finance')"><small>Договор</small><b>${mln(p.sum)}</b><span>получено ${mln(p.paid)}</span></div><div><small>Направления</small><b>${p.full?'3':'1'}</b><span>${p.full?'проект · стройка · слаботочка':'только проект'}</span></div></div>
 <div class="g2"><div class="pan"><h3>Разделы и исполнители</h3><div class="tw"><table class="t"><thead><tr><th>Шифр</th><th>Раздел</th><th>Исполнитель</th><th style="width:22%">Готово</th><th>Статус</th></tr></thead><tbody>${D.slice(0,10).map(d=>`<tr><td class="mono"><b>${d[0]}</b></td><td>${d[1]}</td><td>${d[2]}</td><td>${pbar(d[3])}</td><td><span class="tag ${DST[d[5]][1]}">${DST[d[5]][0]}</span></td></tr>`).join('')}</tbody></table></div><button class="bt sm" onclick="go('docs')">Все разделы →</button></div>
 <div class="pan"><h3>Файлы проекта</h3>${[['АР_ДС280_изм3.dwg','AutoCAD · Айгерим · сегодня'],['ДС280_модель.rvt','Revit · Олег · 05.10'],['ПЗ_ДС280.docx','Word · Ерлан · 03.10'],['Замечания_экспертизы_№1.pdf','PDF · экспертиза · 30.09'],['Смета_ДС280.xlsx','Excel · Гульмира · 06.10'],['АПЗ_и_ТУ.pdf','PDF · ИРД · 14.07']].map(f=>`<div class="fl"><i>${f[0].split('.').pop().toUpperCase()}</i><span><b>${f[0]}</b><em>${f[1]}</em></span></div>`).join('')}<p class="mini">Файлы хранятся у вас на сервере, у каждого — версия и автор. Работаете в AutoCAD, Revit, ArchiCAD как прежде — система хранит результат и сроки.</p></div></div>
 <div class="pan"><h3>Ход проекта</h3>${[['07.10','Айгерим','АР: исправлено замечание № 5 — ширина выхода 1,2 м'],['06.10','Ерлан','ОВ просрочен — Руслану перенесён срок на 08.10, ГИП уведомлён'],['30.09','Экспертиза','Получено 6 замечаний — розданы исполнителям'],['12.09','Тимур','Стадия «Проект» → «Экспертиза», оплачено 50 %']].map(x=>`<div class="evt"><span class="mono">${x[0]}</span><b>${x[1]}</b><em>${x[2]}</em></div>`).join('')}</div>`};
function prNext(id){const p=PR(id),i=STI(p.st);if(i>=ST.length-1){toast('Проект передан на стройку.');return}if(p.st==='exp'&&EXP.some(e=>e.st!=='done')){toast('Нельзя перевести в рабочую документацию: открыто '+EXP.filter(e=>e.st!=='done').length+' замечаний экспертизы. Так задумано — стадия закрывается, когда закрыты замечания.');return}p.st=ST[i+1].k;render();toast(`${p.id} → «${ST[i+1].n}». ГИП и исполнители разделов получили уведомление.`)}

SC.docs=()=>{const my=role==='Проектировщик';const D=my?DOCS.filter(d=>d[2]==='Айгерим'):DOCS;
 return `<div class="hd"><div><h2>Разделы и исполнители · ${my?'мои разделы':'П-2611 детский сад'}</h2><p>На один проект — 20–30 документов, у каждого свой исполнитель и срок. ГИП видит всю матрицу, проектировщик — только свои разделы. Просрочка видна сразу, без звонков.</p></div><div class="btns"><button class="bt" onclick="toast('Шаблон разделов для детского сада применён: 24 раздела.')">Шаблон разделов</button></div></div>
 <div class="dgrid">${D.map((d,i)=>`<div class="dc ${d[5]}" onclick="docStep(${DOCS.indexOf(d)})"><div class="dh"><b>${d[0]}</b><span class="tag ${DST[d[5]][1]}">${DST[d[5]][0]}</span></div><div class="dn">${d[1]}</div>${pbar(d[3])}<div class="kf">${d[2]}<b>срок ${d[4]}</b></div></div>`).join('')}</div>
 <p class="mini">Клик по разделу — +10 % готовности (в демо). В рабочей системе исполнитель загружает файл и отмечает готовность, ГИП проверяет.</p>
 ${said('«Для одного проекта двадцать-тридцать документов, у каждого документа свои исполнители. Штат — сорок человек только на проектировании».')}`};
function docStep(i){const d=DOCS[i];if(d[3]>=100){toast(`${d[0]} уже готов.`);return}d[3]=Math.min(100,d[3]+10);if(d[3]>=100)d[5]='done';render();toast(`${d[0]} · ${d[1]} — ${d[3]}%.${d[3]>=100?' ГИП получил раздел на проверку.':''}`)}
