
/* ===== Рабочее место клиента ===== */
SC.ws=()=>{const c=CL(curCl)||CLIENTS[0];const R=REQS.filter(r=>r.cl===c.id&&vis(r)),grp=c.group?CLIENTS.filter(x=>x.group===c.group):[];
 return `<div class="wsh"><div class="wsa">${esc(ini(c.sh))}</div><div class="wsn"><h2>${esc(c.n)}</h2><p><span class="mono">БИН ${c.bin}</span> · ${esc(c.boss)} · ${esc(c.ph)} · ${c.staff} ${plural(c.staff,['сотрудник','сотрудника','сотрудников'])}</p><div class="wst">${c.dirs.map(dirm).join(' ')}<span class="flag">тариф «${esc(c.tariff)}» · ${tg(c.fee)}/мес</span>${c.debt?`<span class="flag no">долг ${tg(c.debt)}</span>`:'<span class="flag ok">оплачено</span>'}</div></div>
  <div class="btns"><button class="bt" onclick="callNow('audio','${c.id}')">Аудиозвонок</button><button class="bt" onclick="callNow('video','${c.id}')">Видео</button><button class="bt p" onclick="card('newreq','${c.id}')">+ Заявка</button></div></div>
 <div class="kbd"><span>Переключиться на другого клиента — список слева или</span><kbd>Ctrl</kbd>+<kbd>K</kbd><span>и первые буквы названия · последние:</span>${['C1','C7','C9','C4'].filter(x=>x!==c.id).map(x=>`<a onclick="pickCl('${x}')">${esc(CL(x).sh)}</a>`).join('')}</div>
 ${grp.length>1?`<div class="note" style="--tone:var(--brand)"><b>Группа «${esc(c.group)}» · ${grp.length} ${plural(grp.length,['компания','компании','компаний'])} одного владельца</b><p>${grp.map(x=>x.id===c.id?`<strong>${esc(x.sh)}</strong>`:`<a class="lk" onclick="pickCl('${x.id}')">${esc(x.sh)}</a>`).join(' · ')} — владелец видит все свои компании в одном кабинете и переключается между ними.</p></div>`:''}
 <div class="g21" style="margin-top:12px"><div><div class="pan"><h3>Открытые заявки · ${R.filter(r=>r.st!=='done').length}</h3>${R.filter(r=>r.st!=='done').map(r=>`<div class="kv" style="cursor:pointer" onclick="openReq('${r.id}')"><span>${dirm(r.dir)} ${esc(r.t)}</span><b>${rst(r.st)} · ${slaLeft(r)}</b></div>`).join('')||'<p class="mini">Нет открытых заявок.</p>'}</div>
  <div class="pan"><h3>Сроки клиента</h3>${DEADLINES.filter(d=>c.dirs.includes(d.dir)).slice(0,4).map(d=>`<div class="kv"><span>${dirm(d.dir)} ${esc(d.t)}</span><b class="mono ${daysBetween(TODAY,d.d)<=7?'warnt':''}">${dd(d.d)}</b></div>`).join('')}</div>
  <div class="pan"><h3>Последние документы</h3>${R.flatMap(r=>r.docs.map(f=>[f,r])).slice(0,5).map(([f,r])=>`<div class="file"><i>${f.split('.').pop().toUpperCase().slice(0,4)}</i><div><b>${esc(f)}</b><span>${r.id} · ${dd(r.d)}</span></div></div>`).join('')||'<p class="mini">Нет.</p>'}</div></div>
 <div><div class="pan"><h3>Команда клиента</h3>${Object.entries(c.resp).map(([d,p])=>`<div class="kv"><span>${dirm(d)}</span><b>${STAFF[p]}</b></div>`).join('')}<div class="kv"><span>Менеджер клиента</span><b>Асем</b></div></div>
  <div class="pan"><h3>Переписка</h3><div class="chat mini2">${(CHATS[c.id]||[['cl',c.boss,c.last,c.lt]]).slice(-3).map(m=>m[0]==='call'?`<div class="msg sys">${esc(m[2])}</div>`:`<div class="msg ${m[0]==='me'?'out':m[0]==='in'?'note':'in'}"><b>${esc(m[1])}</b>${esc(m[2])}<small>${m[3]}</small></div>`).join('')}</div><button class="bt" style="margin-top:8px" onclick="go('chat')">Открыть мессенджер</button></div>
  <div class="pan"><h3>Договор и оплата</h3>${[['Договор','№ '+c.id.slice(1)+'/2025 · до 31.12.2026'],['Абонентская плата',tg(c.fee)+' в месяц'],['Счёт за октябрь',c.debt?'не оплачен':'выставлен 01.10']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div></div>
 ${said('«В личном кабинете должен быть функционал переключения — с клиента на клиента.»','Слева — список клиентов как в мессенджере; выбрали — всё рабочее место показывает этого клиента.')}`};

/* ===== Мессенджер ===== */
function callNow(kind,id){const c=CL(id);toast(`${kind==='video'?'Видеозвонок':'Аудиозвонок'} ${esc(c.boss)} · ${esc(c.sh)} — идёт вызов в приложении клиента. Запись разговора прикрепится к клиенту.`);CALLS.unshift({t:NOW,cl:id,who:c.boss,me:ROLES[role].p==='CL'?'AS':ROLES[role].p,kind,dur:'0:00',via:'Портал',rec:true,live:true})}
function chatSend(){const i=document.getElementById('chin');if(!i||!i.value.trim())return;(CHATS[curCl]=CHATS[curCl]||[]).push(['me',STAFF[ROLES[role].p]||'Сотрудник',i.value.trim(),NOW]);render();toast('Отправлено — клиенту push в приложении.')}
SC.chat=()=>{const c=CL(curCl)||CLIENTS[0];const M=CHATS[c.id]||[['cl',c.boss,c.last,c.lt]];
 return `<div class="hd"><div><h2>Мессенджер · ${esc(c.sh)}</h2><p>Переписка с клиентом — внутри платформы: история не теряется при смене сотрудника, файлы сразу в архиве клиента, внутренние заметки клиент не видит. Аудио- и видеозвонки — из чата, с записью.</p></div><div class="btns"><button class="bt" onclick="callNow('audio','${c.id}')">Аудиозвонок</button><button class="bt p" onclick="callNow('video','${c.id}')">Видеозвонок</button></div></div>
 <div class="pan chatp big"><div class="chat">${M.map(m=>m[0]==='call'?`<div class="msg sys">${esc(m[2])}<small>${m[3]}</small></div>`:`<div class="msg ${m[0]==='me'?'out':m[0]==='in'?'note':'in'}"><b>${esc(m[1])}</b>${esc(m[2])}<small>${m[3]}</small></div>`).join('')}</div>
 <div class="chs"><button class="bt" onclick="toast('Файл прикреплён — он же появится в архиве документов клиента.')">Файл</button><button class="bt" onclick="toast('Голосовое сообщение записано.')">Голосовое</button><input id="chin" placeholder="Сообщение клиенту…" onkeydown="if(event.key==='Enter')chatSend()"><button class="bt p" onclick="chatSend()">Отправить</button></div></div>
 <div class="g3"><div class="note"><b>Каналы клиента</b><p>Общий чат компании, чат по каждой заявке и внутренний чат команды по клиенту — без групп в WhatsApp на каждого.</p></div><div class="note"><b>Кто видит</b><p>Клиент — свои чаты. Сотрудник — клиентов своего направления. Руководитель — всё.</p></div><div class="note"><b>Уйдёт сотрудник — история останется</b><p>Переписка принадлежит компании, а не личному телефону бухгалтера.</p></div></div>
 ${said('«Там должен быть мессенджер и аудиозвонки.»','Сделали мессенджер с аудио- и видеозвонками — и в портале, и в приложении.')}`};

/* ===== Звонки ===== */
SC.calls=()=>`<div class="hd"><div><h2>Звонки</h2><p>Аудио- и видеозвонки между командой и клиентами — внутри платформы, без личных номеров. Каждый звонок привязан к клиенту и заявке, запись хранится на вашем сервере.</p></div></div>
 <div class="g12"><div class="callui"><div class="cav">${esc(ini(CL('C3').sh))}</div><b>Айдос Сарсенов</b><span>QazLogistic · видеозвонок · 04:12</span><div class="cbtn"><i>микрофон</i><i>камера</i><i>экран</i><i class="end">завершить</i></div><small>Заявка R-1041 · уведомление КГД</small></div>
 <div class="pan"><h3>Сегодня</h3><div class="tw"><table class="t"><thead><tr><th>Время</th><th>Клиент</th><th>Сотрудник</th><th>Тип</th><th>Откуда</th><th class="r">Длительность</th><th>Запись</th></tr></thead><tbody>${CALLS.map(x=>`<tr onclick="pickCl('${x.cl}')"><td class="mono">${x.t}</td><td>${esc(x.who)}<span class="sub">${esc(CL(x.cl).sh)}</span></td><td>${STAFF[x.me]||'—'}</td><td>${x.kind==='video'?'видео':'аудио'}</td><td>${esc(x.via)}</td><td class="r mono">${x.missed?'<span class="neg">пропущен</span>':x.live?'<span class="pos">идёт</span>':x.dur}</td><td>${x.rec&&!x.live?'<a class="lk" onclick="event.stopPropagation();toast(\'Воспроизведение записи.\')">слушать</a>':'—'}</td></tr>`).join('')}</tbody></table></div></div></div>`;

/* ===== Все клиенты ===== */
let clsF='all';
SC.clients=()=>{let L=CLIENTS.filter(c=>clsF==='all'||c.dirs.includes(clsF));if(myDir())L=L.filter(c=>c.dirs.includes(myDir()));
 return `<div class="hd"><div><h2>Клиенты · ${TOTAL_CLIENTS}</h2><p>Карточка компании: БИН, руководитель, направления, ответственные, тариф, долг, заявки. Владелец с несколькими компаниями — одна группа, один вход в кабинет. В демо показаны 13 из ${TOTAL_CLIENTS}.</p></div><div class="btns"><button class="bt" onclick="go('migrate')">Импорт из Битрикс24</button><button class="bt p" onclick="toast('Новый клиент: БИН — реквизиты подтянутся из открытых источников, затем направления и ответственные.')">+ Клиент</button></div></div>
 <div class="filt"><button class="${clsF==='all'?'on':''}" onclick="clsF='all';render()">Все</button>${Object.keys(DIRS).map(k=>`<button class="${clsF===k?'on':''}" onclick="clsF='${k}';render()"><i class="sq" style="background:${DIRS[k].c}"></i>${DIRS[k].n}</button>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Компания</th><th>БИН/ИИН</th><th>Направления</th><th>Ответственные</th><th>Тариф</th><th class="r">В месяц</th><th class="r">Открытых заявок</th><th class="r">Долг</th></tr></thead><tbody>${L.map(c=>`<tr onclick="pickCl('${c.id}')"><td><b>${esc(c.n)}</b>${c.group?`<span class="sub">группа «${esc(c.group)}»</span>`:''}</td><td class="mono">${c.bin}</td><td>${c.dirs.map(dirm).join(' ')}</td><td class="mini">${Object.values(c.resp).map(p=>STAFF[p]).join(', ')}</td><td>${esc(c.tariff)}</td><td class="r mono">${fmt(c.fee)}</td><td class="r mono">${REQS.filter(r=>r.cl===c.id&&r.st!=='done').length}</td><td class="r mono ${c.debt?'neg':''}">${c.debt?fmt(c.debt):'—'}</td></tr>`).join('')}</tbody></table></div>`};
