
/* ===== Направления ===== */
const dirHead=(k,txt)=>{const R=REQS.filter(r=>r.dir===k);return `<div class="hd"><div><h2>${DIRS[k].n}</h2><p>${txt}</p></div><div class="btns"><button class="bt" onclick="inDir='${k}';inF='all';go('inbox')">Заявки направления</button></div></div>
 <div class="wid"><div><small>Клиентов направления</small><b>${{buh:243,law:118,tax:96,hr:131}[k]}</b><span>в демо ${CLIENTS.filter(c=>c.dirs.includes(k)).length}</span></div><div><small>Открытых заявок</small><b class="a">${R.filter(r=>r.st!=='done').length}</b></div><div><small>Ждём клиента</small><b>${R.filter(r=>r.st==='wait').length}</b></div><div><small>Закрыто за сентябрь</small><b class="g">${{buh:412,law:96,tax:71,hr:268}[k]}</b></div><div><small>Специалистов</small><b>${{buh:3,law:2,tax:1,hr:1}[k]}</b><span>${{buh:'Айгуль, Динара, Ерлан',law:'Алия, Тимур',tax:'Марат',hr:'Мария'}[k]}</span></div></div>`};
/* бухгалтерия */
const PRIM=[['C1',1,1,1,0],['C3',1,1,0,1],['C4',1,0,0,1],['C7',1,1,1,1],['C9',1,1,1,1],['C12',1,0,1,1],['C2',1,1,1,1],['C8',0,1,1,1]];
function askDocs(id){toast(`${esc(CL(id).sh)}: в кабинет и приложение ушёл запрос «загрузите недостающие документы за сентябрь» — со списком.`)}
SC.buh=()=>`${dirHead('buh','Сроки отчётности и платежей по всем клиентам сразу, готовность первички за месяц, запрос недостающего — одной кнопкой в кабинет клиента. Без напоминаний вручную в WhatsApp.')}
 <div class="g2"><div class="pan"><h3>Ближайшие сроки</h3>${DEADLINES.filter(d=>d.dir!=='law').map(d=>`<div class="dlr"><div class="dld"><b>${dd(d.d)}</b><small>${daysBetween(TODAY,d.d)} дн.</small></div><div><b>${esc(d.t)}</b><span>${dirm(d.dir)} · ${d.n} ${plural(d.n,['клиент','клиента','клиентов'])}</span></div><div class="dlp"><span class="pbar"><i style="width:${pct(d.done,d.n)}%;background:${DIRS[d.dir].c}"></i></span><em>${d.done}/${d.n}</em></div></div>`).join('')}</div>
 <div class="pan"><h3>Первичка за сентябрь</h3><div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Выписка</th><th>ЭСФ</th><th>Акты</th><th>Зарплата</th><th></th></tr></thead><tbody>${PRIM.map(p=>`<tr onclick="pickCl('${p[0]}')"><td>${esc(CL(p[0]).sh)}</td>${p.slice(1).map(v=>`<td>${v?'<b class="pos">✓</b>':'<b class="neg">нет</b>'}</td>`).join('')}<td>${p.slice(1).includes(0)?`<button class="bt sm" onclick="event.stopPropagation();askDocs('${p[0]}')">Запросить</button>`:''}</td></tr>`).join('')}</tbody></table></div></div></div>`;
/* юридическое */
const LAW=[['C9','Договор аренды офиса','проверка','AL','2026-10-02','4 риска найдено'],['C6','Договор с врачом-совместителем','подготовка','AL','2026-10-02','по шаблону'],['C11','Претензия за просрочку поставки','отправлена','TM','2026-10-15','ждём ответ 15 дней'],['C4','Договор субподряда','согласование','TM','2026-10-05','правки контрагента'],['C3','Соглашение о расторжении','подписано','AL','2026-09-28','ЭЦП обеих сторон'],['C12','Регистрация филиала','в госорганах','TM','2026-10-09','подано через eGov']];
SC.law=()=>`${dirHead('law','Договоры, претензии, регистрационные действия по всем клиентам. Шаблоны с ИИ дают черновик за минуты, юрист проверяет и отправляет на подпись — клиент подписывает ЭЦП прямо в кабинете.')}
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Документ</th><th>Этап</th><th>Юрист</th><th>Срок</th><th>Комментарий</th></tr></thead><tbody>${LAW.map(l=>`<tr onclick="pickCl('${l[0]}')"><td>${esc(CL(l[0]).sh)}</td><td><b>${esc(l[1])}</b></td><td>${esc(l[2])}</td><td>${STAFF[l[3]]}</td><td class="mono">${dd(l[4])}</td><td class="mini">${esc(l[5])}</td></tr>`).join('')}</tbody></table></div>
 <div class="g3" style="margin-top:12px">${TPLS.filter(t=>t.dir==='law').map(t=>`<div class="pan tplc" onclick="aiTpl='${t.id}';go('ai')"><h3>${esc(t.n)}</h3><p>${t.f.join(' · ')}</p><span class="mini">использован ${t.used} раз</span></div>`).join('')}</div>`;
/* налоги */
const TAXQ=[['C3','Уведомление КГД о расхождениях по ЭСФ','2026-11-12','ответ готовится','MR'],['C10','Возврат превышения НДС','2026-10-07','пакет документов','MR'],['C1','Камеральный контроль: КПН','2026-10-20','пояснения отправлены','MR'],['C11','Консультация: льготы для ВИЭ','2026-10-03','назначен созвон','MR']];
SC.tax=()=>`${dirHead('tax','Уведомления КГД, камеральный контроль, возврат НДС, консультации. У каждого запроса — срок по уведомлению, документы и история ответа; клиент видит, на каком этапе его вопрос.')}
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Вопрос</th><th>Срок</th><th class="r">Осталось</th><th>Этап</th><th>Консультант</th></tr></thead><tbody>${TAXQ.map(q=>`<tr onclick="pickCl('${q[0]}')"><td>${esc(CL(q[0]).sh)}</td><td><b>${esc(q[1])}</b></td><td class="mono">${dl(q[2])}</td><td class="r mono ${daysBetween(TODAY,q[2])<=7?'warnt':''}">${daysBetween(TODAY,q[2])} дн.</td><td>${esc(q[3])}</td><td>${STAFF[q[4]]}</td></tr>`).join('')}</tbody></table></div>
 <div class="note" style="margin-top:12px"><b>Срок — из документа</b><p>Срок ответа берётся из уведомления: консультант вносит его один раз, дальше система напоминает и ставит задачу за 5 дней.</p></div>`;
/* HR */
const HRQ=[['C7','Приём','3 бариста с 05.10','договоры и приказы','MA','wait'],['C5','Отпуск','водитель с 12.10, 14 дней','приказ','MA','new'],['C1','Табель','сентябрь, 46 человек','на проверке','MA','check'],['C3','Увольнение','водитель, соглашение сторон','подписано','MA','done'],['C9','Приём','разработчик с 15.10','договор','MA','new'],['C7','Больничный','бариста, 5 дней','оплата в зарплате','MA','work']];
SC.hr=()=>`${dirHead('hr','Кадровые события клиентов: приёмы, отпуска, увольнения, больничные, табели. Клиент создаёт заявку в приложении — HR готовит документы по шаблону, руководитель клиента подписывает ЭЦП.')}
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Событие</th><th>Кто / когда</th><th>Документы</th><th>Статус</th></tr></thead><tbody>${HRQ.map(h=>`<tr onclick="pickCl('${h[0]}')"><td>${esc(CL(h[0]).sh)}<span class="sub">${CL(h[0]).staff} сотр.</span></td><td><b>${esc(h[1])}</b></td><td>${esc(h[2])}</td><td>${esc(h[3])}</td><td>${rst(h[5])}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Сотрудников у клиентов</h3><div class="kv"><span>Всего на кадровом учёте</span><b class="mono">4 870</b></div><div class="kv"><span>Кадровых событий за сентябрь</span><b class="mono">268</b></div><div class="kv"><span>Документов по шаблону</span><b class="mono">91%</b></div></div><div class="pan"><h3>Шаблоны HR</h3>${TPLS.filter(t=>t.dir==='hr').map(t=>`<div class="kv" style="cursor:pointer" onclick="aiTpl='${t.id}';go('ai')"><span>${esc(t.n)}</span><b class="mono">${t.used}</b></div>`).join('')}</div></div>`;
