
/* ===== Внутренние задачи ===== */
const TST={new:['Новая','#2f5bea'],work:['В работе','#c98a1b'],done:['Готово','#23935f']};
function taskDone(i){TASKS[i].st='done';render();toast('Задача закрыта.')}
function newTask(){TASKS.unshift({t:'Новая задача',who:ROLES[role].p==='CL'?'AS':ROLES[role].p,due:addDays(TODAY,2),st:'new'});render();toast('Задача создана.')}
SC.tasks=()=>`<div class="hd"><div><h2>Внутренние задачи</h2><p>Внутренние процессы команды — тоже здесь: задачи, сроки, ответственные, планёрки. Битрикс24 для этого больше не нужен — всё в одной системе с заявками и клиентами.</p></div><div class="btns"><button class="bt p" onclick="newTask()">+ Задача</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Задача</th><th>Кто</th><th>Срок</th><th>Статус</th><th></th></tr></thead><tbody>${TASKS.map((x,i)=>`<tr><td><b>${esc(x.t)}</b></td><td>${STAFF[x.who]||'—'}</td><td class="mono ${x.st!=='done'&&x.due<=TODAY?'neg':''}">${dd(x.due)}</td><td><span class="st" style="--sc:${TST[x.st][1]}">${TST[x.st][0]}</span></td><td>${x.st!=='done'?`<button class="bt sm" onclick="taskDone(${i})">Готово</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Это приложение, которое с клиентами, — она же ещё и наши внутренние процессы.»','Платон: «Зачем вам две системы? Задачи, воронки — всё будет внутри одной». Битрикс24 уберёте за ненадобностью.')}`;

/* ===== Команда ===== */
const TEAM=[['AY','buh','Бухгалтер',64,9],['DN','buh','Бухгалтер',71,6],['ER','buh','Бухгалтер',58,7],['AL','law','Юрист',38,5],['TM','law','Юрист',41,4],['MR','tax','Налоговый консультант',96,6],['MA','hr','HR-специалист',131,8],['AS','','Менеджер клиентов',512,14]];
SC.team=()=>`<div class="hd"><div><h2>Команда и загрузка</h2><p>Сколько клиентов и открытых заявок у каждого сотрудника, как быстро отвечает, есть ли просрочки. Новый клиент назначается тому, у кого есть запас.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Сотрудник</th><th>Направление</th><th class="r">Клиентов</th><th class="r">Открытых заявок</th><th>Загрузка</th><th class="r">Первый ответ</th></tr></thead><tbody>${TEAM.map(t=>`<tr><td><b>${STAFF[t[0]]}</b><span class="sub">${t[2]}</span></td><td>${t[1]?dirm(t[1]):'все'}</td><td class="r mono">${t[3]}</td><td class="r mono">${t[4]}</td><td><span class="adh"><span class="pbar"><i style="width:${Math.min(100,t[4]*10)}%;background:${t[4]>=8?'var(--bad)':'var(--ok)'}"></i></span><em>${Math.min(100,t[4]*10)}%</em></span></td><td class="r mono">${[22,35,41,48,52,63,30,12][TEAM.indexOf(t)]} мин</td></tr>`).join('')}</tbody></table></div>`;

/* ===== Тарифы и счета ===== */
let INV=CLIENTS.map((c,i)=>({no:1020+i,cl:c.id,sum:c.fee,st:c.debt?'debt':i%3===0?'paid':'sent'}));
function invPaid(no){const v=INV.find(x=>x.no===no);v.st='paid';const c=CL(v.cl);c.debt=0;render();toast('Оплата отмечена — клиент видит «оплачено» в кабинете.')}
SC.billing=()=>{const tot=INV.reduce((s,v)=>s+v.sum,0);
 return `<div class="hd"><div><h2>Тарифы и счета</h2><p>Абонентская плата и разовые услуги: 1-го числа счета всем клиентам формируются автоматически и уходят в кабинет и приложение. Рутину — счёт на оплату, акт, напоминание о долге — делает система.</p></div><div class="btns"><button class="bt p" onclick="toast('Счета за октябрь сформированы и отправлены: '+INV.length+' клиентам в демо, 512 — в реальной базе.')">Выставить за октябрь</button></div></div>
 <div class="wid"><div><small>Счетов за октябрь</small><b>${INV.length}</b><span>в реальной базе — 512</span></div><div><small>На сумму</small><b class="a">${tg(tot)}</b></div><div><small>Оплачено</small><b class="g">${INV.filter(v=>v.st==='paid').length}</b></div><div><small>Долги</small><b class="r">${tg(INV.filter(v=>v.st==='debt').reduce((s,v)=>s+v.sum,0))}</b></div><div><small>Средний чек</small><b>${tg(tot/INV.length)}</b></div></div>
 <div class="g12"><div class="pan"><h3>Тарифы</h3>${[['Упрощёнка ИП','30 000 ₸','910, платежи, консультации'],['Стандарт','150–180 000 ₸','бухгалтерия ТОО до 40 сотрудников'],['Стандарт + HR','210 000 ₸','плюс кадровый учёт'],['Полный','280–320 000 ₸','бух, юр, налоги, HR'],['Юрист','90 000 ₸','договоры и претензии']].map(x=>`<div class="kv"><span>${x[0]}<span class="sub">${x[2]}</span></span><b class="mono">${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Счета · октябрь</h3><div class="tw"><table class="t"><thead><tr><th>№</th><th>Клиент</th><th class="r">Сумма</th><th>Статус</th><th></th></tr></thead><tbody>${INV.map(v=>`<tr onclick="pickCl('${v.cl}')"><td class="mono">${v.no}</td><td>${esc(CL(v.cl).sh)}</td><td class="r mono">${fmt(v.sum)}</td><td>${v.st==='paid'?'<span class="pos">оплачен</span>':v.st==='debt'?'<span class="neg">долг с сентября</span>':'<span class="mini">отправлен</span>'}</td><td>${v.st!=='paid'?`<button class="bt sm" onclick="event.stopPropagation();invPaid(${v.no})">Оплачен</button>`:''}</td></tr>`).join('')}</tbody></table></div></div></div>
 ${said('«Хотелось бы какую-то автоматизацию через портал, чтобы счёт на оплату… базовые рутинные моменты автоматизировать.»')}`};

/* ===== Аналитика ===== */
const MON=[['май',612,71],['июн',640,69],['июл',588,74],['авг',655,78],['сен',702,86]];
SC.analytics=()=>`<div class="hd"><div><h2>Аналитика</h2><p>Сколько заявок по направлениям, как быстро отвечаем, сколько в срок, кто перегружен, какие клиенты приносят больше и где риск оттока. Раньше это было не посчитать — всё лежало в переписках.</p></div></div>
 <div class="wid"><div><small>Клиентов</small><b>512</b><span>+14 за квартал</span></div><div><small>Заявок за сентябрь</small><b class="a">702</b></div><div><small>Решено в срок</small><b class="g">86%</b></div><div><small>Первый ответ</small><b>38 мин</b></div><div><small>Выручка в месяц</small><b>48,6 млн</b><span>абонентская плата</span></div></div>
 <div class="g2"><div class="pan"><h3>Заявки и доля в срок</h3><div class="mcols">${MON.map(m=>`<div class="mc"><div class="mcb"><i style="height:${m[1]/7.2}%"></i></div><b>${m[1]}</b><small>${m[0]} · ${m[2]}%</small></div>`).join('')}</div></div>
 <div class="pan"><h3>Заявки по направлениям · сентябрь</h3>${[['buh',356],['hr',198],['law',84],['tax',64]].map(x=>`<div class="fr"><span>${dirm(x[0])} ${DIRS[x[0]].n}</span><span class="pbar w"><i style="width:${x[1]/3.56}%;background:${DIRS[x[0]].c}"></i></span><b>${x[1]}</b></div>`).join('')}<div class="note" style="--tone:var(--warn)"><b>Риск оттока</b><p>7 клиентов: 3 месяца без заявок и с долгом — менеджеру задача позвонить.</p></div></div></div>`;
