
let scopeLoaded=true;
SC.scope=()=>`<div class="hd"><div><h2>Объём работ из проекта · ПС «Шолак»</h2><p>Проект, который вам дают на руки в начале, загружается в систему: ИИ читает ведомость объёмов работ и раскладывает её по разделам. Можно и вручную. Из любой строки — задача на площадку в один клик.</p></div><div class="btns"><button class="bt" onclick="card('scopeadd')">+ Строка вручную</button><button class="bt p" onclick="card('scopeai')">Загрузить проект (PDF) → ИИ</button></div></div>
 <div class="wid"><div><small>Разделов</small><b>${SCOPE.length}</b><span>из рабочего проекта, том 3 «ВОР»</span></div><div><small>Позиций объёма</small><b>${SCOPE.reduce((a,s)=>a+s.items.length,0)}</b><span>в демо — часть, в проекте 214</span></div><div><small>Выполнено по объёму</small><b class="a">${scopeTot()}%</b><span>считается из журналов</span></div><div><small>Задач создано</small><b>${TASKS.length}</b><span>из строк объёма</span></div></div>
 ${SCOPE.map(s=>`<div class="pan"><h3>${s.sec}</h3><div class="tw"><table class="t"><thead><tr><th>Работа по проекту</th><th>Ед.</th><th class="r">По проекту</th><th class="r">Выполнено</th><th style="width:22%">Готовность</th><th></th></tr></thead><tbody>${s.items.map(i=>{const p=Math.min(100,Math.round(i[3]/i[2]*100));return `<tr><td>${i[0]}</td><td class="mini">${i[1]}</td><td class="r mono">${fmt(i[2])}</td><td class="r mono">${String(i[3]).replace('.',',')}</td><td>${bar(p,p)}<div class="sub">${p}%</div></td><td class="r">${p<100?`<button class="bt sm" onclick="mkTask('${esc(i[0])}','${esc(s.sec)}')">→ задача</button>`:'<span class="tag g">закрыто</span>'}</td></tr>`}).join('')}</tbody></table></div></div>`).join('')}
 ${said('«Когда ты ознакамливаешься с проектом с самого начала, тебе дают весь проект на руки — там описан весь объём работ. То, что есть в проекте, я хочу внедрить в приложение: с помощью ИИ или просто вручную ввести все эти задачи».')}`;
function mkTask(t,sec){const n='T-'+(130+TASKS.length);TASKS.push({id:n,t,sec,who:'не назначено',due:'—',st:'new',p:'norm',done:0,why:'Создано из объёма работ'});go('tasks');toast(`${n} «${t}» создана из объёма работ — в конце списка. Поднимите приоритет стрелками.`)}

let tF='open';
SC.tasks=()=>{const L=TASKS.filter(t=>tF==='all'||(tF==='open'?t.st!=='done':t.st==='done'));
 return `<div class="hd"><div><h2>Задачи и приоритеты · ПС «Шолак»</h2><p>Руководитель проекта ставит задачи вручную или из объёма работ и двигает их по приоритету: что выше — то бригады делают первым. Перепрыгнуть с одной задачи на другую — одна стрелка; люди на площадке сразу видят новый порядок.</p></div><div class="btns"><button class="bt p" onclick="card('newtask')">+ Задача</button></div></div>
 <div class="seg">${[['open','Открытые'],['done','Готовые'],['all','Все']].map(x=>`<a class="${tF===x[0]?'on':''}" onclick="tF='${x[0]}';render()">${x[1]}</a>`).join('')}</div>
 <div class="tl2">${L.map(t=>{const i=TASKS.indexOf(t);return `<div class="tk ${t.p}"><div class="tk-n"><b>${i+1}</b><span><a onclick="mv(${i},-1)" title="выше">▲</a><a onclick="mv(${i},1)" title="ниже">▼</a></span></div><div class="tk-b"><div class="tk-t"><b>${esc(t.t)}</b><span class="tag ${PRI[t.p][1]}">${PRI[t.p][0]}</span><span class="tag ${TST[t.st][1]}">${TST[t.st][0]}</span></div><div class="tk-m">${t.id} · ${esc(t.sec)} · ${esc(t.who)} · срок ${t.due}</div>${t.why?`<div class="tk-w">${esc(t.why)}</div>`:''}</div><div class="tk-r">${bar(t.done,t.done)}<span class="mono">${t.done}%</span><select onchange="TASKS[${i}].p=this.value;render();toast('Приоритет изменён — бригада получила уведомление.')">${Object.entries(PRI).map(([k,v])=>`<option value="${k}" ${k===t.p?'selected':''}>${v[0]}</option>`).join('')}</select></div></div>`}).join('')}</div>
 ${said('«Мне хотелось бы, чтобы приоритетность этих задач можно было менять — в зависимости от срочности с одной задачи перепрыгнуть на другую».')}`};
function mv(i,d){const j=i+d;if(j<0||j>=TASKS.length)return;[TASKS[i],TASKS[j]]=[TASKS[j],TASKS[i]];render();toast(`«${TASKS[j].t.slice(0,48)}…» — теперь №${j+1}. Начальник участка и бригадир получили новый порядок.`)}

let CHAT=[['Талгат','08:12','Сегодня на лотки ставлю всю бригаду Серика, ограждение — подсобники.'],['Асель','09:40','Лоток 600 м: «КабельСистем» отгрузит 11.10, если оплатим завтра до обеда. Счёт приложила.'],['Бейбарс','11:30','Поднял T-118 на первое место. Гульнара, ЗМ-213 — в оплату сегодня, пожалуйста.'],['Гульнара','11:52','Принято, платёжка будет до 17:00.'],['ИИ','15:22','На фото «Кабельные лотки, ячейка 4»: нет перемычек заземления между секциями в 3 местах. Создать задачу Серику?'],['Нурлан','15:31','Да, исправим завтра с утра.']];
SC.chat=()=>`<div class="hd"><div><h2>Переписка по объекту · ${OB(curObj).sh}</h2><p>Вся переписка объекта — в системе, а не в десяти чатах WhatsApp. Каждое сообщение можно превратить в задачу, к сообщению прикрепить фото, счёт, чертёж.</p></div></div>
 ${objSw()}
 <div class="g2"><div class="pan"><div class="msgs">${CHAT.map(m=>`<div class="mg ${m[0]==='ИИ'?'ai':''} ${m[0]===ROLES[role].n.split(' ')[0]?'me':''}"><small>${m[0]} · ${m[1]}</small>${esc(m[2])}</div>`).join('')}</div>
 <div class="qin"><input id="chin" placeholder="Сообщение всем на объекте…" onkeydown="if(event.key==='Enter')chSend()"><button class="bt p" onclick="chSend()">Отправить</button></div></div>
 <div class="pan"><h3>Кто в переписке</h3>${[['Бейбарс','Руководитель проекта'],['Талгат','Начальник участка'],['Нурлан','Прораб'],['Асель','Снабженец'],['Гульнара','Бухгалтер'],['Ерлан Кадырович','Основатель · читает']].map(x=>`<div class="kv"><span>${x[0]}</span><b class="mini">${x[1]}</b></div>`).join('')}<p class="mini">Подсобники и бригады в систему не входят — задачи им передаёт прораб или бригадир.</p></div></div>`;
function chSend(){const v=document.getElementById('chin');if(!v||!v.value.trim())return;CHAT.push([ROLES[role].n.split(' ')[0],NOW,v.value.trim()]);render()}

SC.daily=()=>`<div class="hd"><div><h2>Дневной отчёт · ${OB(curObj).sh} · ${TODAY}</h2><p>Прораб в конце дня пишет или надиктовывает коротко, как привык. ИИ раскладывает текст по журналам, считает объём, людей и технику — и сравнивает с планом.</p></div><div class="btns"><button class="bt" onclick="toast('Отчёт отправлен руководителю проекта и основателю.')">Отправить</button></div></div>
 ${objSw()}
 <div class="g2"><div class="pan"><h3>Что написал прораб · 18:04</h3><div class="voice">«Сегодня лотки по ячейкам 3–4 сто двенадцать метров, бригада Серика восемь человек, кран два часа. Сварщики поставили три опоры под ТТ на пятой. Подсобники шесть человек — ограждение, стойки сорок шесть метров. Новеньких четверо, Марат инструктаж провёл. Электроды кончаются.»</div><div class="btns l"><button class="bt" onclick="toast('Удерживайте кнопку и говорите — запись распознаётся на казахском и русском.')">Надиктовать</button><button class="bt" onclick="toast('Можно написать текстом — ИИ поймёт так же.')">Написать</button></div></div>
 ${ai('ИИ разложил по журналам',`${[['Общий журнал работ','3 записи: лотки 112 м · опоры под ТТ 3 шт · стойки ограждения 46 м'],['Журнал ТБ','инструктаж 4 новых подсобников, Марат'],['Сварочный журнал','опорные конструкции, ячейка 5 — 3 шт'],['Табель','электромонтажники 8, сварщики 4, подсобники 6'],['Спецтехника','автокран 50 т — 2 ч'],['Заявка снабжению','электроды УОНИ 13/55 — остаток на 6 дней, заявка уже в пути (ЗМ-212)']].map(x=>`<div class="kv"><span>${x[0]}</span><b class="mini">${x[1]}</b></div>`).join('')}<p class="mini">План на день по лоткам — 100 м, факт 112 м. Первый день недели с перевыполнением.</p><div class="btns l"><button class="bt p" onclick="toast('Записи внесены в 4 журнала и табель. Прораб подписал электронно.')">Подтвердить и записать</button></div>`)}</div>`;

let jCur='ozr';
SC.journals=()=>{const j=JOURN.find(x=>x.k===jCur);
 return `<div class="hd"><div><h2>Журналы работ · ${OB(curObj).sh}</h2><p>Все журналы, которые сейчас ведутся ручкой на бумаге, — в системе. Записи приходят из дневного отчёта прораба, ИИ проверяет полноту и готовит форму к распечатке — для технадзора и заказчика.</p></div><div class="btns"><button class="bt" onclick="card('jadd')">+ Запись</button><button class="bt p" onclick="card('jprint')">Подготовить к печати</button></div></div>
 <div class="g2 jl"><div class="pan"><h3>Журналы объекта</h3>${JOURN.map(x=>`<div class="kv clk ${x.k===jCur?'on':''}" onclick="jCur='${x.k}';render()"><span><b>${x.n}</b><br><span class="mini">${x.who} · последняя запись ${x.last}</span></span><b class="mono">${x.cnt}</b></div>`).join('')}</div>
 <div class="pan"><h3>${j.n}</h3>${jCur==='ozr'?`<div class="tw"><table class="t"><thead><tr><th>Дата</th><th>Работа</th><th>Объём</th><th>Кто</th><th>Техника</th><th>Записал</th></tr></thead><tbody>${OZR.map(r=>`<tr><td class="mono">${r[0]}</td><td>${r[1]}</td><td class="mono">${r[2]}</td><td class="mini">${r[3]}</td><td class="mini">${r[4]}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div>`:`<p class="mini">${j.cnt} записей. Форма журнала — как бумажная, графы те же; последняя запись ${j.last}.</p>`}
 ${ai('Проверка ИИ',`<div class="rf"><i></i><div><b>06.10 — нет записи о входном контроле лотка</b><span>лоток пришёл 03.10, в журнале входного контроля нет — технадзор спросит</span></div></div><div class="rf"><i></i><div><b>Кабельный журнал отстаёт на 2 дня</b><span>в общем журнале прокладка есть, в кабельном — последняя запись 05.10</span></div></div><button class="bt sm" onclick="toast('Прорабу отправлено напоминание с готовым текстом записей.')">Напомнить прорабу</button>`)}</div></div>
 ${said('«Постоянно заполняются журналы разного рода — по старинке, физические журналы, ручкой. Хотелось бы, чтобы ИИ эту отчётность затрагивал, анализировал введённую информацию и подготовил отчёт к распечатке».')}`};

const PHSVG={tray:'<rect x="0" y="0" width="200" height="120" fill="#c9d3dc"/><rect x="0" y="80" width="200" height="40" fill="#a89a80"/><path d="M10 52h180v10H10z" fill="#7d8792"/><path d="M10 52h180" stroke="#59616b" stroke-width="2"/><path d="M30 62v26M90 62v26M150 62v26" stroke="#59616b" stroke-width="3"/><rect x="120" y="44" width="70" height="8" fill="#9aa4ae"/>',crane:'<rect width="200" height="120" fill="#cfd8df"/><rect y="88" width="200" height="32" fill="#a89a80"/><path d="M40 88V20l90 0" stroke="#d6a400" stroke-width="5" fill="none"/><path d="M120 20v30" stroke="#333" stroke-width="1.5"/><rect x="108" y="50" width="24" height="30" fill="#6f7a86"/><circle cx="80" cy="76" r="5" fill="#f2b705"/><circle cx="150" cy="78" r="5" fill="#e9e3d6"/><circle cx="162" cy="78" r="5" fill="#e9e3d6"/>',drum:'<rect width="200" height="120" fill="#d3d9de"/><rect y="84" width="200" height="36" fill="#a89a80"/><circle cx="60" cy="80" r="26" fill="#8a6a3a"/><circle cx="60" cy="80" r="8" fill="#5a4426"/><circle cx="130" cy="82" r="22" fill="#8a6a3a"/><circle cx="130" cy="82" r="7" fill="#5a4426"/>',earth:'<rect width="200" height="120" fill="#d2d8dd"/><rect y="60" width="200" height="60" fill="#9d8a6a"/><path d="M0 80h200" stroke="#555" stroke-width="4"/><path d="M60 80v30M140 80v30" stroke="#555" stroke-width="4"/>'};
SC.photos=()=>`<div class="hd"><div><h2>Фотоотчёт и разбор ИИ</h2><p>Прораб или начальник участка фотографирует работу с телефона. ИИ смотрит фото: соответствует ли работа проекту, сколько сделано, есть ли нарушения по технике безопасности — и даёт обратную связь сразу.</p></div><div class="btns"><button class="bt p" onclick="toast('С телефона: кнопка «Фото» — камера — отправить. Разбор ИИ приходит за 10–20 секунд.')">+ Фото с площадки</button></div></div>
 <div class="phs">${PHOTOS.map(p=>`<div class="ph"><svg viewBox="0 0 200 120" preserveAspectRatio="xMidYMid slice">${PHSVG[p.kind]}</svg><div class="ph-b"><b>${p.t}</b><span class="mini">${p.who} · ${p.time}</span>${p.ok.map(x=>`<div class="pk ok">✓ ${x}</div>`).join('')}${p.bad.map(x=>`<div class="pk bad">! ${x}</div>`).join('')}${p.bad.length?`<button class="bt sm" onclick="toast('Создано ${p.bad.length} задачи ответственным, фото приложено. Инженер по ТБ получил уведомление.')">Замечания → задачи</button>`:'<span class="tag g">без замечаний</span>'}</div></div>`).join('')}</div>
 ${said('«Чтобы ИИ мог анализировать информацию — если отправить фотографию рабочих процессов, чтобы это проанализировал и дал фидбэк».')}`;

SC.crew=()=>`<div class="hd"><div><h2>Люди на площадке · ${OB(curObj).sh}</h2><p>Постоянный состав — те, кто руководит процессами, — заходит в систему. Подсобники, монтажники, сварщики меняются под объём и сроки: их учитывает прораб в табеле, система считает, хватает ли людей.</p></div></div>
 ${objSw()}
 <div class="wid"><div><small>На площадке сегодня</small><b class="a">${CREW.reduce((a,c)=>a+c[2],0)+CORE.length}</b><span>из них постоянных ${CORE.length}</span></div><div><small>Вышли / по списку</small><b>${CREW.reduce((a,c)=>a+c[2],0)} / ${CREW.reduce((a,c)=>a+c[1],0)}</b><span>переменный состав</span></div><div><small>Нужно с 14.10</small><b class="r">+8</b><span>электромонтажников — прогноз ИИ</span></div><div><small>Инструктаж ТБ</small><b class="g">все</b><span>4 новых прошли 07.10</span></div></div>
 <div class="g2"><div class="pan"><h3>Переменный состав сегодня</h3><div class="tw"><table class="t"><thead><tr><th>Специальность</th><th class="r">По списку</th><th class="r">Вышли</th><th>Старший</th></tr></thead><tbody>${CREW.map(c=>`<tr><td>${c[0]}</td><td class="r mono">${c[1]}</td><td class="r mono ${c[2]<c[1]?'neg':''}">${c[2]}</td><td>${c[3]}</td></tr>`).join('')}</tbody></table></div><button class="bt sm" onclick="toast('Табель за октябрь выгружен в Excel для бухгалтера.')">Табель за месяц → Excel</button></div>
 <div class="pan"><h3>Постоянный состав объекта</h3>${CORE.map(c=>`<div class="kv"><span>${c[0]}</span><b class="mini">${c[1]}</b></div>`).join('')}</div></div>`;

SC.machines=()=>`<div class="hd"><div><h2>Спецтехника · ${OB(curObj).sh}</h2><p>Что стоит на площадке, сколько часов отработало, что простаивает и что понадобится. Простой техники — это деньги: система их показывает.</p></div><div class="btns"><button class="bt p" onclick="card('mreq')">+ Заявка на технику</button></div></div>
 ${objSw()}
 <div class="tw"><table class="t"><thead><tr><th>Техника</th><th>Чья</th>${['03.10','04.10','05.10','06.10','07.10'].map(d=>`<th class="r">${d}</th>`).join('')}<th>План</th><th>Статус</th></tr></thead><tbody>${MACH.map(m=>`<tr class="${m.st==='idle'?'rowwarn':m.st==='need'?'rowbad':''}"><td><b>${m.n}</b></td><td class="mini">${m.own}</td>${m.h.map(h=>`<td class="r mono">${h||'—'}</td>`).join('')}<td class="mini">${m.plan}</td><td><span class="tag ${m.st==='work'?'g':m.st==='idle'?'w':m.st==='need'?'r':''}">${{work:'работает',idle:'простой',need:'нужна',off:'не нужна'}[m.st]}</span></td></tr>`).join('')}</tbody></table></div>
 ${ai('ИИ по технике',`<p>Каток 6 т простаивает 5 дней — на ПС «Шолак» до весны не нужен. На РП «Нурсат» с 09.10 обратная засыпка траншей: перебросить, экономия аренды ~150 000 ₸.</p><p>Автовышка 28 м нужна с 14.10 под молниеотводы (T-126) — не заказана.</p><button class="bt sm" onclick="toast('Создана заявка на автовышку 14–19.10 и задача на переброску катка.')">Сделать обе заявки</button>`)}`;
