
SC.supply=()=>`<div class="hd"><div><h2>Заявки на материалы</h2><p>Прораб создаёт заявку с телефона → снабженец находит поставщика → выше лимита согласует основатель → бухгалтер оплачивает → материал на площадке, прораб принимает и пишет входной контроль.</p></div><div class="btns"><button class="bt p" onclick="card('newreq')">+ Заявка</button></div></div>
 <div class="mvs">${RST.map(([k,n],i)=>`<div class="mv ${REQS.some(r=>r.st===k)?'on':''}"><i>${i+1}</i><b>${n}</b><span>${REQS.filter(r=>r.st===k).length} заявок</span></div>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>№</th><th>Объект</th><th>Что</th><th>Кол-во</th><th class="r">Сумма</th><th>Поставщик</th><th>Кто</th><th>Статус</th><th></th></tr></thead><tbody>${REQS.map((r,i)=>`<tr class="${r.st==='agree'?'rowwarn':''}"><td class="mono">${r.id}</td><td>${OB(r.obj).sh}</td><td><b>${esc(r.g)}</b>${r.note?`<div class="sub">${esc(r.note)}</div>`:''}</td><td class="mono">${r.q}</td><td class="r mono">${fmt(r.sum)}</td><td class="mini">${esc(r.sup)}</td><td>${r.who}</td><td><span class="tag ${r.st==='done'?'g':r.st==='agree'?'w':r.st==='way'?'i':''}">${RST.find(x=>x[0]===r.st)[1]}</span></td><td>${r.st!=='done'?`<button class="bt sm" onclick="reqNext(${i})">${{new:'Взять в работу',agree:'Согласовать',pay:'Оплачено',way:'Принято на площадке'}[r.st]}</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 <p class="mini">Лимит без согласования основателя — 10 млн ₸ (настраивается). Срочные заявки, которые держат задачу с приоритетом «Срочно», поднимаются наверх у снабженца и бухгалтера.</p>`;
function reqNext(i){const r=REQS[i],o=RST.map(x=>x[0]);let n=o[o.indexOf(r.st)+1];if(r.st==='new'&&r.sum<10000000)n='pay';if(r.st==='agree'&&role!=='Основатель'){toast('Согласовать сумму выше 10 млн может только основатель. Переключите роль.');return}r.st=n;if(r.sup==='—')r.sup='ТОО «МеталлСнаб»';render();toast(`${r.id} → «${RST.find(x=>x[0]===n)[1]}». ${n==='done'?'Прорабу создана запись во входной контроль.':'Следующий по цепочке получил уведомление.'}`)}

SC.materials=()=>`<div class="hd"><div><h2>Материалы на объекте · ${OB(curObj).sh}</h2><p>Сколько есть на площадке, сколько нужно по проекту до конца, сколько уходит в день и на сколько дней хватит. Красное — закончится раньше, чем придёт заказ.</p></div></div>
 ${objSw()}
 <div class="tw"><table class="t"><thead><tr><th>Материал</th><th class="r">На площадке</th><th class="r">Нужно до конца</th><th class="r">Расход в день</th><th class="r">Хватит на</th><th class="r">Заказано</th><th>Придёт</th></tr></thead><tbody>${MAT.map(m=>{const d=m.day?Math.floor(m.have/m.day):null;const eta=m.eta!=='—'?parseInt(m.eta):99;const late=d!==null&&m.ord&&d<eta-7;const bad=(d!==null&&d<7&&!m.ord)||late||(m.have===0&&m.need>0&&m.eta>='28');return `<tr class="${bad?'rowbad':d!==null&&d<10?'rowwarn':''}"><td><b>${m.n}</b></td><td class="r mono">${String(m.have).replace('.',',')} ${m.u}</td><td class="r mono">${String(m.need).replace('.',',')}</td><td class="r mono">${m.day?String(m.day).replace('.',','):'—'}</td><td class="r mono">${d===null?'—':d+' дн.'}</td><td class="r mono">${m.ord?String(m.ord).replace('.',','):'—'}</td><td class="mono">${m.eta}</td></tr>`}).join('')}</tbody></table></div>
 ${ai('ИИ: что заказать сейчас',`<p>Профиль ограждения закончится через 6 дней, заказа нет — заявка ЗМ-214 создана, отправить снабженцу. Контрольный кабель: остатка на 5 дней, заказ придёт 16.10 — разрыв 2 дня, попросить поставщика отгрузить 4 км раньше.</p>`)}`;

SC.money=()=>`<div class="hd"><div><h2>Деньги по объектам</h2><p>Сумма договора по госзакупке, сколько получено по актам, сколько потрачено на материалы, ФОТ, технику и субподряд — по каждому объекту.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Объект</th><th class="r">Договор</th><th class="r">Выполнено (по актам)</th><th class="r">Получено</th><th class="r">Потрачено</th><th class="r">Результат сейчас</th><th class="r">Остаток к получению</th></tr></thead><tbody>${OBJS.map(o=>`<tr class="clk" onclick="curObj='${o.id}';go('object')"><td><b>${o.sh}</b><div class="sub">${o.cust}</div></td><td class="r mono">${mln(o.sum)}</td><td class="r mono">${mln(o.sum*o.fact/100)}</td><td class="r mono">${mln(o.got)}</td><td class="r mono">${mln(o.spent)}</td><td class="r mono ${o.got-o.spent>=0?'pos':'neg'}">${mln(o.got-o.spent)}</td><td class="r mono">${mln(o.sum-o.got)}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2"><div class="pan"><h3>Расходы ПС «Шолак» по статьям</h3>${[['Материалы',318],['ФОТ и табель',164],['Аренда спецтехники',58],['Субподряд',49],['Проживание и питание',23]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${x[1]/3.4}%"></i><b class="mono">${x[1]} млн</b></div>`).join('')}</div>
 <div class="pan"><h3>Платежи на неделю</h3>${[['08.10','ЗМ-213 лоток — «КабельСистем»','5,88 млн'],['10.10','Аванс электромонтажникам за октябрь','6,4 млн'],['10.10','Аренда автокрана — «ТуркестанКран»','2,85 млн'],['11.10','Бетон — «Алаколь Бетон»','2,34 млн']].map(x=>`<div class="kv"><span class="mono">${x[0]}</span><span>${x[1]}</span><b class="mono">${x[2]}</b></div>`).join('')}</div></div>`;

SC.acts=()=>`<div class="hd"><div><h2>Акты выполненных работ</h2><p>Объём из журналов → акт КС-2 и справка КС-3 по месяцу. Система показывает, что мешает подписать акт: чаще всего — не готова исполнительная документация.</p></div><div class="btns"><button class="bt p" onclick="toast('Черновик КС-2 за октябрь собран из общего журнала: 42 позиции. Проверьте и отправьте ПТО.')">Собрать КС-2 из журнала</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Акт</th><th>Объект</th><th>Период</th><th class="r">Сумма</th><th>Статус</th><th>Что мешает</th></tr></thead><tbody>${ACTS.map(a=>`<tr><td class="mono">${a.n}</td><td>${OB(a.obj).sh}</td><td>${a.per}</td><td class="r mono">${fmt(a.sum)}</td><td><span class="tag ${AST[a.st][1]}">${AST[a.st][0]}</span></td><td class="mini ${a.st==='sign'?'neg':''}">${a.note}</td></tr>`).join('')}</tbody></table></div>`;

SC.roles=()=>{const A=[['Все объекты, пульт, прогноз',{OW:2,PM:1}],['Свой объект: объём работ, задачи, приоритеты',{OW:2,PM:2,SU:1,FR:1}],['Журналы и дневной отчёт',{OW:1,PM:2,SU:2,FR:2}],['Фото и разбор ИИ',{OW:1,PM:2,SU:2,FR:2}],['Люди и табель',{OW:1,PM:2,SU:2,FR:2,BH:1}],['Спецтехника',{OW:1,PM:2,SU:2}],['Заявки на материалы',{OW:2,PM:2,SU:2,FR:2,SN:2,BH:2}],['Деньги и акты',{OW:2,PM:1,BH:2}],['ИИ-ассистент',{OW:2,PM:2,SU:2}]];const R=Object.entries(ROLES);
 return `<div class="hd"><div><h2>Роли и права</h2><p>Шесть должностей с доступом, как вы назвали. Руководитель проекта видит только свой объект; основатель — все три. Подсобники и переменный состав в систему не входят.</p></div></div>
 <div class="tw"><table class="t mx"><thead><tr><th>Раздел</th>${R.map(([k,v])=>`<th class="c">${esc(v.av)}<span>${esc(k)}</span></th>`).join('')}</tr></thead><tbody>${A.map(a=>`<tr><td>${a[0]}</td>${R.map(([k,v])=>`<td class="c">${a[1][v.p]===2?'●':a[1][v.p]===1?'○':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 <p class="mini">● — меняет · ○ — только смотрит · — — не видит. Права настраиваются без программиста.</p>
 <div class="g3">${R.map(([k,v])=>`<div class="pan"><h3>${esc(k)}</h3><p class="mini">${esc(v.n)} · ${esc(v.note)}</p></div>`).join('')}</div>`};

const TRG=[['Стадия объекта закрыта галочкой','Объект переходит на следующую стадию, чек-лист новой стадии — руководителю проекта и начальнику участка'],['Задаче поставлен приоритет «Срочно»','Уведомление бригадиру и начальнику участка; связанные заявки поднимаются наверх у снабженца и бухгалтера'],['Заявка на материал выше 10 млн ₸','Уходит на согласование основателю'],['Заявка оплачена','Снабженец и прораб получают дату доставки'],['Материал принят на площадке','Прорабу — запись во входной контроль'],['ИИ нашёл нарушение ТБ на фото','Уведомление инженеру по ТБ и начальнику участка, задача с фото'],['Материала осталось меньше чем на 7 дней','Предупреждение снабженцу и руководителю проекта'],['Задача просрочена','Исполнителю и руководителю проекта; в сводку основателю'],['Конец месяца','Черновик КС-2 из общего журнала — ПТО и бухгалтеру'],['19:00 каждый день','Сводка ИИ основателю: план/факт, люди, проблемы']];
SC.triggers=()=>`<div class="hd"><div><h2>Триггеры и согласования</h2><p>Система не работает сама за людей — она реагирует на события: поставили галочку, закрыли этап — объект или задача сами уходят нужным людям на рассмотрение.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>№</th><th>Когда</th><th>Что происходит</th><th>Вкл.</th></tr></thead><tbody>${TRG.map((t,i)=>`<tr><td class="mono">${i+1}</td><td><b>${t[0]}</b></td><td>${t[1]}</td><td><span class="sw on" onclick="this.classList.toggle('on')"></span></td></tr>`).join('')}</tbody></table></div>
 <p class="mini">Правила добавляются и меняются на этапе шлифовки вместе с вами.</p>`;

SC.launch=()=>`<div class="hd"><div><h2>Запуск и стоимость</h2><p>Стандартный пакет разработки: своя система, один раз, без абонентской платы. Работает в браузере — с телефона и компьютера, без App Store и Play Market. Стоит на вашем сервере, все ключи — у вас.</p></div></div>
 <div class="pk1"><div><small>Стандартный пакет разработки</small><b>2 500 000 ₸</b><span>всё, что в демо, плюс пункты вашего ТЗ; запас 10–15 % часов на доработки при шлифовке</span></div><div><small>Срок</small><b>4–6 недель</b><span>первая выкатка — через 3 недели</span></div></div>
 <div class="pay3"><div><small>Старт · 10 %</small><b>250 000 ₸</b><span>предоплата, начинаем работу</span></div><div><small>Ядро · 45 %</small><b>1 125 000 ₸</b><span>после приёмки ядра</span></div><div><small>Сдача · 45 %</small><b>1 125 000 ₸</b><span>после шлифовки и передачи ключей</span></div></div>
 <div class="g2"><div class="pan"><h3>Ядро — первые 3 недели</h3>${['Объекты в проектном канбане, карточка объекта, стадии','Объём работ из проекта → задачи, приоритеты','Журналы, дневной отчёт прораба','Заявки на материалы с согласованием','Роли и права, вход с телефона'].map(x=>`<div class="li"><i>✓</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Шлифовка — до сдачи</h3>${['ИИ: разбор журналов и печатные формы, фото, ассистент, прогноз','Люди, табель, спецтехника, материалы на объекте','Деньги по объектам, акты КС-2 / КС-3','Триггеры, сводка основателю','Ваши правки — «этап тысячи мелочей»'].map(x=>`<div class="li n"><i>→</i><span>${x}</span></div>`).join('')}</div></div>
 <div class="g2"><div class="pan"><h3>Ваши расходы потом</h3><div class="kv"><span>Сервер в облаке</span><b>≈ 10 000 ₸ в месяц</b></div><div class="kv"><span>ИИ-сервис</span><b>напрямую, по факту использования</b></div><div class="kv"><span>Поддержка</span><b>20 $ в час · копим, не выставляем за полчаса</b></div></div>
 <div class="pan"><h3>Следующий шаг</h3><p class="mini" style="font-size:12.4px">Вы присылаете техническое задание — сверяем с демо и включаем пункты, которые сегодня не проговорили. Показываете КП основателю, 10 % — и начинаем.</p></div></div>
 ${said('«По деньгам никаких проблем нет — самое главное, чтобы получилось».')}`;

const CARD={};
CARD.newobj=()=>['Новый объект','Выиграли тендер — заводим объект',`<div class="form"><label>Объект<input id="no_n" value="Школа на 300 мест, с. Шаульдер"></label><label>Регион<input id="no_r" value="Туркестанская обл."></label><label>Заказчик<input id="no_c" value="ГУ «Отдел строительства района»"></label><label>Сумма договора, ₸<input id="no_s" value="620000000"></label></div><button class="bt p" onclick="newObj()">Создать</button>`];
function newObj(){const v=i=>document.getElementById(i).value.trim();const id='O'+(OBJS.length+1);OBJS.push({id,n:v('no_n'),sh:v('no_n').split(',')[0],reg:v('no_r'),cust:v('no_c'),st:'tender',plan:0,fact:0,people:0,core:0,mach:0,sum:+v('no_s')||0,got:0,spent:0,start:'—',end:'—',pm:'не назначен',su:'—',fr:'—',risk:'Нет'});closeM();go('objects');toast('Объект создан в стадии «Тендер выигран». Назначьте руководителя проекта и загрузите проект.')}
CARD.newtask=()=>['Новая задача','ПС «Шолак» — встанет в конец списка, приоритет меняется стрелками',`<div class="form"><label>Что сделать<input id="nt_t" value="Кабельные лотки — ячейки 7–8"></label><label>Раздел<select id="nt_s">${SCOPE.map(s=>`<option>${s.sec}</option>`).join('')}</select></label><label>Кто<input id="nt_w" value="Бригада Серика"></label><label>Срок<input id="nt_d" value="22.10"></label><label>Приоритет<select id="nt_p"><option value="norm">Обычный</option><option value="high">Высокий</option><option value="hot">Срочно</option></select></label></div><button class="bt p" onclick="newTask()">Создать</button>`];
function newTask(){const v=i=>document.getElementById(i).value.trim();const id='T-'+(130+TASKS.length);const t={id,t:v('nt_t'),sec:v('nt_s'),who:v('nt_w'),due:v('nt_d'),st:'new',p:v('nt_p'),done:0,why:''};if(t.p==='hot')TASKS.unshift(t);else TASKS.push(t);closeM();tF='open';go('tasks');toast(`${id} создана${t.p==='hot'?' и поставлена первой — срочно':''}. Бригадир получил уведомление.`)}
CARD.scopeai=()=>['Загрузка проекта','ИИ читает ведомость объёмов работ',`<div class="upl"><b>РП_ПС220_том3_ВОР.pdf</b><span>148 страниц · 6,4 МБ</span></div>${ai('ИИ нашёл',`<div class="kv"><span>Разделов</span><b>11</b></div><div class="kv"><span>Позиций объёма</span><b>214</b></div><div class="kv"><span>Не распознано — проверить вручную</span><b class="neg">3 строки</b></div><p class="mini">Строки с непонятными единицами помечены — руководитель проекта проверяет и подтверждает. Без подтверждения в задачи не уходят.</p>`)}<button class="bt p" onclick="closeM();toast('214 позиций добавлены в объём работ. 3 строки ждут проверки руководителя проекта.')">Подтвердить</button>`];
CARD.scopeadd=()=>['Строка объёма вручную','',`<div class="form"><label>Работа<input value="Освещение ОРУ, прожекторные мачты"></label><label>Раздел<select>${SCOPE.map(s=>`<option>${s.sec}</option>`).join('')}</select></label><label>Ед.<input value="шт"></label><label>Количество<input value="4"></label></div><button class="bt p" onclick="closeM();toast('Строка добавлена в объём работ.')">Добавить</button>`];
CARD.jadd=()=>['Запись в журнал','Можно надиктовать — ИИ разложит по графам',`<div class="form"><label>Журнал<select>${JOURN.map(j=>`<option>${j.n}</option>`).join('')}</select></label><label>Дата<input value="${TODAY}"></label><label>Работа<input value="Монтаж кабельных лотков, ячейка 5"></label><label>Объём<input value="64 м"></label></div><button class="bt p" onclick="OZR.unshift(['07.10','Монтаж кабельных лотков, ячейка 5','64 м','бригада Серика','—',ROLES[role].n.split(' ')[0]]);closeM();render();toast('Запись внесена, подписана электронно.')">Записать</button>`];
CARD.jprint=()=>['Общий журнал работ · к печати','ПС 220/10 кВ при ПГУ · 01–07.10.2026',`<div class="prt"><div class="prt-h"><b>ОБЩИЙ ЖУРНАЛ РАБОТ</b><span>Раздел 3. Сведения о выполнении работ</span></div><table><thead><tr><th>Дата</th><th>Наименование работ, объём</th><th>Исполнитель</th><th>Подпись</th></tr></thead><tbody>${OZR.map(r=>`<tr><td>${r[0]}.2026</td><td>${r[1]} — ${r[2]}</td><td>${r[3]}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table><p>Ответственный производитель работ: Нурлан ________ &nbsp; Технадзор: ________</p></div><div class="btns l"><button class="bt p" onclick="toast('PDF для печати сформирован — формат А4, графы как в бумажном журнале.')">Скачать PDF</button><button class="bt" onclick="toast('Отправлено технадзору на почту.')">Отправить технадзору</button></div>`];
CARD.newreq=()=>['Заявка на материал','С телефона прораба',`<div class="form"><label>Объект<select id="nr_o">${OBJS.map(o=>`<option value="${o.id}">${o.sh}</option>`).join('')}</select></label><label>Что<input id="nr_g" value="Хомуты кабельные 300 мм"></label><label>Сколько<input id="nr_q" value="2 000 шт"></label><label>Ориентир, ₸<input id="nr_s" value="180000"></label></div><button class="bt p" onclick="newReq()">Отправить снабженцу</button>`];
function newReq(){const v=i=>document.getElementById(i).value.trim();const id='ЗМ-'+(215+REQS.length-6);REQS.unshift({id,obj:v('nr_o'),who:ROLES[role].n.split(' ')[0],g:v('nr_g'),q:v('nr_q'),sum:+v('nr_s')||0,st:'new',d:'07.10',sup:'—',note:''});closeM();go('supply');toast(`${id} отправлена снабженцу.`)}
CARD.mreq=()=>['Заявка на технику','',`<div class="form"><label>Техника<input value="Автовышка 28 м"></label><label>С какого числа<input value="14.10"></label><label>Дней<input value="6"></label><label>Под задачу<input value="T-126 молниеотводы"></label></div><button class="bt p" onclick="closeM();toast('Заявка отправлена снабженцу. Руководитель проекта получил копию.')">Отправить</button>`];
function card(k,id){const f=CARD[k];if(!f)return;let r;try{r=f(id)}catch(e){toast('Карточка не найдена');return}openM(r[0],r[1],r[2])}
function act(m){toast(m||'В рабочей системе здесь откроется форма.')}
function searchDemo(v){if(!v)return;toast('Поиск по объектам, задачам, журналам и заявкам: «'+esc(v)+'».')}

function renderRoles(){const r=document.getElementById('roles');if(r)r.innerHTML=Object.entries(ROLES).map(([k,v])=>`<div class="role" onclick="enter('${esc(k)}')"><div class="rav">${esc(v.av)}</div><div><b>${esc(k)}</b><span>${esc(v.n)} · ${esc(v.note)}</span></div></div>`).join('');
 const s=document.getElementById('rsel');if(s)s.innerHTML=Object.keys(ROLES).map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('');}
const allowed=k=>ROLES[role].s.indexOf(k)>=0;
function enter(k){role=ROLES[k]?k:'Основатель';document.getElementById('gate').classList.add('hidden');document.getElementById('app').classList.remove('hidden');const s=document.getElementById('rsel');if(s)s.value=role;document.getElementById('me').textContent=ROLES[role].av;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Вы вошли как «${esc(role)}» · ${esc(ROLES[role].n)}.`)}
function switchRole(k){role=k;document.getElementById('me').textContent=ROLES[role].av;const s=document.getElementById('rsel');if(s)s.value=role;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Роль: ${esc(role)}. ${esc(ROLES[role].note)}.`)}
function buildRail(){const on=SECOF[cur];document.getElementById('rail').innerHTML=SEC.filter(s=>s.sub.some(x=>allowed(x[0]))).map(s=>`<a class="ri ${s.k===on?'on':''}" onclick="go('${s.sub.filter(x=>allowed(x[0]))[0][0]}')"><i><svg viewBox="0 0 24 24">${s.ic}</svg></i><span>${s.n}</span></a>`).join('')}
function buildSub(){const s=SEC.find(x=>x.k===SECOF[cur]);document.getElementById('sub').innerHTML=`<h4>${s.n}</h4>`+s.sub.filter(x=>allowed(x[0])).map(x=>`<a class="${x[0]===cur?'on':''}" onclick="go('${x[0]}')">${esc(x[1])}</a>`).join('')}
function build(){buildRail();buildSub();render()}
function render(){const f=SC[cur]||SC.today;document.getElementById('ttl').textContent=SUBN[cur]||'Контур';document.getElementById('content').innerHTML=`<div class="screen">${f()}</div>`;buildSub();buildRail();
 const a=document.getElementById('addBtn');if(a)a.style.display=allowed('tasks')?'':'none';try{history.replaceState(null,'','?s='+cur)}catch(e){}}
function go(k){if(!allowed(k)){toast('Этой роли раздел недоступен — так работают права. Переключите роль справа вверху.');return}cur=k;build();const c=document.querySelector('.content');if(c)c.scrollTop=0}
function openM(t,s,b){document.getElementById('mt').innerHTML=t;document.getElementById('ms').innerHTML=s;document.getElementById('mbody').innerHTML=b;document.getElementById('mbg').classList.add('show');document.querySelector('.modal').scrollTop=0}
function closeM(){document.getElementById('mbg').classList.remove('show')}
let tt=null;function toast(m){const t=document.getElementById('toast');t.innerHTML=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),6400)}
function applyTheme(){document.body.classList.toggle('dark',theme==='dark')}
function toggleTheme(){theme=theme==='dark'?'light':'dark';applyTheme();toast(theme==='dark'?'Тёмная тема.':'Светлая тема.')}
const TOUR=[
 ['today','1 · Пульт основателя: три объекта, план и факт, люди и техника, что ждёт решения, сводка ИИ.'],
 ['objects','2 · Объекты в проектном канбане: закрыли стадию галочкой — объект сам пошёл дальше.'],
 ['object','3 · Карточка объекта: стадии, команда, объём по разделам, документы, лента событий.'],
 ['scope','4 · Объём работ из проекта: ИИ читает ведомость объёмов, из строки — задача.'],
 ['tasks','5 · Задачи и приоритеты: стрелками — что делать первым.'],
 ['daily','6 · Дневной отчёт прораба: надиктовал — ИИ разложил по журналам.'],
 ['journals','7 · Журналы работ вместо бумаги, проверка ИИ, форма к печати.'],
 ['photos','8 · Фото с площадки: ИИ проверяет работу и технику безопасности.'],
 ['forecast','9 · Прогноз ИИ: материалы, люди, спецтехника, срок сдачи.'],
 ['assist','10 · ИИ-ассистент: вопрос своими словами — ответ по данным объекта.'],
 ['crew','11 · Люди: постоянный состав и переменный под объём.'],
 ['machines','12 · Спецтехника: часы, простой, что понадобится.'],
 ['supply','13 · Заявки на материалы: прораб → снабженец → основатель → бухгалтер → площадка.'],
 ['money','14 · Деньги по объектам и акты КС-2 / КС-3.'],
 ['roles','15 · Шесть ролей с доступом.'],
 ['launch','16 · Стоимость: 2,5 млн, 4–6 недель, 10 / 45 / 45.']
];
let ti=-1,tRun=false;
function tour(){if(tRun){stopTour();return}tRun=true;ti=-1;document.getElementById('tourBtn').textContent='■';step()}
function step(){if(!tRun)return;ti++;if(ti>=TOUR.length){stopTour();toast('Сценарий закончен. Всё кликается.');return}const [k,m]=TOUR[ti];if(!allowed(k)){step();return}cur=k;build();toast(m);setTimeout(step,ti===0?6500:7200)}
function stopTour(){tRun=false;ti=-1;const b=document.getElementById('tourBtn');if(b)b.textContent='▶'}
(function(){renderRoles();applyTheme();const s=document.getElementById('rsel');if(s)s.addEventListener('change',e=>switchRole(e.target.value));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeM();stopTour()}});
 let q='';try{q=new URLSearchParams(location.search).get('s')||''}catch(e){}
 if(q&&SECOF[q]){const r=Object.keys(ROLES).find(k=>ROLES[k].s.indexOf(q)>=0);if(r){cur=q;enter(r)}}})();
