
const SC={};
const stg=k=>{const s=STN(k);return `<span class="stg" style="--sc:${s.c}">${s.n}</span>`};
const myDeals=()=>role==='Менеджер'?DEALS.filter(d=>d.m==='NS'):DEALS;
SC.today=()=>{const D=DEALS.filter(d=>d.st!=='real');const sum=D.reduce((a,d)=>a+dealSum(d),0);
 return `<div class="hd"><div><h2>Пульт · 5 октября</h2><p>Заявки, сделки, звонки и маркетплейс — одним экраном. Всё, что сейчас в amoCRM, плюс то, чего там не хватает: равномерное распределение, документы без лимита памяти, каталог фирм.</p></div></div>
 <div class="wid">
  <div class="clk" onclick="go('distrib')"><small>Заявок сегодня</small><b>17</b><span>6 · 6 · 5 — поровну</span></div>
  <div class="clk" onclick="go('funnel')"><small>Сделок в работе</small><b>${D.length}</b><span>на ${mln(sum)}</span></div>
  <div class="clk" onclick="go('calls')"><small>Звонков сегодня</small><b>${CALLS.reduce((a,c)=>a+c.calls,0)}</b><span>${CALLS.reduce((a,c)=>a+c.min,0)} минут на линии</span></div>
  <div class="clk" onclick="go('market')"><small>На маркетплейсе</small><b class="a">${FIRMS.filter(f=>f.st==='pub').length}</b><span>фирм · ${FIRMS.reduce((a,f)=>a+f.views,0)} просмотров</span></div>
  <div class="clk" onclick="go('files')"><small>Документов</small><b>41 ГБ</b><span>без лимита памяти</span></div>
 </div>
 <div class="g21"><div class="pan"><h3>Воронка «Отдел продаж»</h3><div class="fl">${ST.map(s=>{const n=DEALS.filter(d=>d.st===s.k).length;return `<div onclick="go('funnel')" style="--sc:${s.c}"><b>${n}</b><span>${s.n}</span></div>`}).join('')}</div>
  <h3 style="margin-top:16px">Требует внимания</h3>
  <div class="rf bad" onclick="openDeal('Д-2329')"><i></i><div><b>Д-2329 · новая заявка без ответа 22 минуты</b><span>Дамир · срок взять в работу — 15 минут, заявка уйдёт следующему менеджеру через 3 минуты</span></div></div>
  <div class="rf" onclick="openDeal('Д-2318')"><i></i><div><b>Д-2318 · тендер 1 ноября — лицензия II категории</b><span>Нурсултан · возражение «дорого» · 8 касаний</span></div></div>
  <div class="rf" onclick="go('sellers')"><i></i><div><b>Новое предложение продать фирму · ТОО «Строй Лидер Астана»</b><span>СМР II категория · просят 7,5 млн · нужна проверка документов</span></div></div>
  <div class="rf" onclick="go('calls')"><i></i><div><b>Дамир: 5 пропущенных звонков</b><span>перезвонить до 17:00 — задачи созданы</span></div></div></div>
  <div class="pan"><h3>Менеджеры сегодня</h3>${CALLS.map(c=>`<div class="mg"><b>${MGR[c.m]}</b><span>${LEADS_TODAY[c.m]} заявок · ${c.calls} звонков · ${c.min} мин · ${c.touch} касаний</span><div class="bar"><i style="width:${pct(c.min,200)}%"></i></div></div>`).join('')}</div></div>
 ${said('«Есть недовольство: бывают технические сбои, память заканчивается — просят купить пакет, он ещё дороже стоит».','Платон: своя система на вашем сервере — память и количество сотрудников не ограничены искусственно.')}`};

SC.funnel=()=>{const L=myDeals();return `<div class="hd"><div><h2>Воронка «Отдел продаж»${role==='Менеджер'?' · мои':''}</h2><p>Этапы как у вас в amoCRM: новая заявка → взято в работу → квалификация → принятие решения → согласование → точки касания → счёт → договор → реализация. На карточке — услуга, город, сумма и число касаний.</p></div><div class="btns"><button class="bt p" onclick="card('newlead')">+ Заявка</button></div></div>
 <div class="kb">${ST.map(s=>{const X=L.filter(d=>d.st===s.k);return `<div class="kc" style="--sc:${s.c}"><div class="kh"><b>${s.n}</b><span>${X.length}</span></div>${X.map(d=>`<div class="kd ${d.st==='new'&&d.id==='Д-2329'?'alarm':''}" onclick="openDeal('${d.id}')"><div class="kt"><b>${d.id}</b><span class="src">${d.src}</span></div><div class="kr">${esc(d.co!=='—'?d.co:d.ct)}</div><div class="km">${esc(SV(d.sv).n)}${d.firm?' · '+esc(FI(d.firm).n):''}</div><div class="kf"><span>${MGR[d.m]} · ${d.city}</span><b class="mono">${mln(dealSum(d))}</b></div></div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 <div class="note"><b>Постоянные клиенты</b><p>Повторный клиент больше не заходит как «новая заявка»: система узнаёт его по телефону или БИН и создаёт сделку сразу у его менеджера, с историей прошлых услуг. Отдельный экран — «Постоянные клиенты».</p></div>`};

function openDeal(id){if(!allowed('deal')){toast('Карточка сделки этой роли недоступна.');return}curDeal=id;go('deal')}
SC.deal=()=>{const d=DL(curDeal)||DEALS[0];const s=SV(d.sv);const f=d.firm?FI(d.firm):null;const si=STI(d.st);
 return `<div class="hd"><div><div class="crumb"><a onclick="go('funnel')">Воронка</a> / ${d.id}</div><h2>${d.id} · ${esc(d.co!=='—'?d.co:d.ct)}</h2><p>${esc(s.n)} · ${d.city} · источник: ${d.src} · менеджер ${MGR[d.m]}</p></div><div class="btns">${d.st!=='real'?`<button class="bt p" onclick="nextSt('${d.id}')">→ ${ST[si+1].n}</button>`:''}<button class="bt" onclick="go('kp')">КП и договор</button></div></div>
 <div class="stp">${ST.map((x,i)=>`<div class="${i<si?'ok':i===si?'on':''}" style="--sc:${x.c}"><i>${i<si?'✓':i+1}</i><span>${x.n}</span></div>`).join('')}</div>
 <div class="g3">
  <div class="pan"><h3>Клиент</h3><div class="kv"><span>Компания</span><b>${esc(d.co)}</b></div><div class="kv"><span>Контакт</span><b>${esc(d.ct)}</b></div><div class="kv"><span>Телефон</span><b class="mono">+7 7** *** ${d.id.slice(-2)} 14</b></div><div class="kv"><span>Город</span><b>${d.city}</b></div><div class="kv"><span>Касаний</span><b>${d.touch}</b></div>${d.note?`<div class="pin">${esc(d.note)}</div>`:''}</div>
  <div class="pan"><h3>Услуга и цена</h3><div class="kv"><span>Услуга</span><b>${esc(s.n)}</b></div>${f?`<div class="kv"><span>Фирма</span><b class="lk" onclick="curFirm='${f.id}';go('firm')">${esc(f.n)}</b></div><div class="kv"><span>Цена фирмы</span><b class="mono">${fmt(f.price)}</b></div><div class="kv"><span>Сопровождение 6 %</span><b class="mono">${fmt(f.price*.06)}</b></div>`:`<div class="kv"><span>Сопровождение</span><b class="mono">${fmt(s.pr)}</b></div><div class="kv"><span>Госпошлина</span><b class="mono">${fmt(s.duty)}</b></div><div class="kv"><span>Срок</span><b>${s.days}</b></div>`}<div class="kv"><span>Итого</span><b class="mono pos">${fmt(dealSum(d))}</b></div><button class="bt sm" onclick="go('prices')">Пересчитать в калькуляторе</button></div>
  <div class="pan"><h3>Документы клиента</h3>${['Устав и свидетельство.pdf · 4,2 МБ','Справка о госрегистрации.pdf · 0,8 МБ','Дипломы ИТР — 6 файлов · 38 МБ','Трудовые договоры ИТР.zip · 112 МБ','Сканы техники и базы.zip · 640 МБ'].map(x=>`<div class="fd"><i></i><span>${x}</span></div>`).join('')}<button class="bt sm" onclick="toast('Файлы загружены — лимита памяти нет.')">+ Файлы</button></div>
 </div>
 <div class="g2"><div class="pan"><h3>Мессенджер</h3><div class="chat">${(CHATS[d.id]||CHATS.def).map(m=>`<div class="msg ${m[0]}"><small>${m[1]}</small>${esc(m[2])}</div>`).join('')}</div><button class="bt sm" onclick="curDeal='${d.id}';go('chat')">Открыть переписку →</button></div>
 <div class="pan"><h3>Звонки и касания</h3>${[['исх.','05.10 11:42','4:18','обсудили подвиды СМР, отправили КП'],['вход.','03.10 15:06','2:51','уточнил сроки'],['исх.','01.10 10:20','6:02','квалификация: тендер, бюджет'],['исх.','30.09 17:10','—','не дозвонились']].map(c=>`<div class="cl"><span class="tag">${c[0]}</span><b>${c[1]}</b><span>${c[2]}</span><em>${c[3]}</em>${c[2]!=='—'?`<a class="lk" onclick="toast('Запись разговора воспроизводится.')">запись</a>`:''}</div>`).join('')}
  <h3 style="margin-top:12px">Возражение</h3><div class="pin">«Дорого, у конкурентов 700» → ответ из базы возражений: что входит (ИТР, техника, база), гарантия получения, срок до тендера.</div></div></div>`};
function nextSt(id){const d=DL(id);d.st=ST[STI(d.st)+1].k;d.touch++;render();toast(`${d.id} → «${STN(d.st).n}».`+(d.st==='inv'?' Счёт сформирован из прайса.':d.st==='dog'?' Договор собран из сделки — отправьте на подпись.':d.st==='real'?' Юристу ушла задача на подачу документов.':''))}

SC.distrib=()=>{const A=Object.keys(MGR);return `<div class="hd"><div><h2>Распределение заявок</h2><p>Заявки с сайта, маркетплейса, мессенджера и звонков раздаются по правилам — без перекоса. Не взял в работу за 15 минут — заявка уходит следующему. Кто в отпуске или на больничном — пропускается.</p></div></div>
 <div class="g2"><div class="pan"><h3>Правила</h3>
  <div class="srow"><span class="nm"><b>Режим</b><br><span class="mini">${DIST.mode==='even'?'поровну — у кого меньше заявок за день':'по очереди'}</span></span><span class="seg"><a class="${DIST.mode==='even'?'on':''}" onclick="DIST.mode='even';render()">поровну</a><a class="${DIST.mode==='rr'?'on':''}" onclick="DIST.mode='rr';render()">по очереди</a></span></div>
  <div class="srow"><span class="nm"><b>Учитывать специализацию</b><br><span class="mini">СМР — Нурсултан и Алия, медицина и образование — Дамир; если специалист загружен — любому</span></span><span class="sw ${DIST.spec?'on':''}" onclick="DIST.spec=DIST.spec?0:1;render()"></span></div>
  <div class="srow"><span class="nm"><b>Взять в работу за</b> ${DIST.sla} мин<br><span class="mini">иначе заявка переходит следующему, РОП получает уведомление</span></span></div>
  <div class="srow"><span class="nm"><b>Не больше</b> ${DIST.limit} новых заявок в день на менеджера</span></div>
  <h3 style="margin-top:14px">Кто сегодня принимает</h3>${A.map(k=>`<div class="srow"><span class="nm">${MGR[k]}</span><span class="sw ${DIST.away[k]?'':'on'}" onclick="DIST.away['${k}']=DIST.away['${k}']?0:1;render();toast(DIST.away['${k}']?'${MGR[k]} не получает новые заявки.':'${MGR[k]} снова в распределении.')"></span></div>`).join('')}</div>
 <div class="pan"><h3>Сегодня</h3>${A.map(k=>`<div class="hb"><span>${MGR[k]}${DIST.away[k]?' · не принимает':''}</span><i style="width:${LEADS_TODAY[k]*14}%"></i><b class="mono">${LEADS_TODAY[k]}</b></div>`).join('')}
  <h3 style="margin-top:14px">Журнал</h3>${[['16:02','Д-2330 · сайт · Караганда','Алия','у неё меньше всех за день'],['15:48','Д-2329 · Instagram','Дамир','турлицензия — специализация'],['15:31','Д-2328 · маркетплейс','Нурсултан','Нурсултан ведёт продавца этой фирмы'],['15:10','Д-2326 · звонок','Дамир → Нурсултан','не взял за 15 минут']].map(r=>`<div class="lg"><span class="mono">${r[0]}</span><b>${r[1]}</b><span>→ ${r[2]}</span><em>${r[3]}</em></div>`).join('')}
  <button class="bt p" style="margin-top:10px" onclick="testLead()">Пришла новая заявка</button></div></div>
 ${said('«Распределение неравномерно идёт: одному менеджеру больше заявок падает — на это жалуются».','Платон: этот функционал пропишем полностью — как распределять.')}`};
function testLead(){const A=Object.keys(MGR).filter(k=>!DIST.away[k]);if(!A.length){toast('Никто не принимает заявки.');return}const k=A.sort((a,b)=>LEADS_TODAY[a]-LEADS_TODAY[b])[0];LEADS_TODAY[k]++;const id='Д-'+(2332+DEALS.length-12);DEALS.unshift({id,co:'—',ct:'Новый клиент',city:'Астана',sv:'S1',firm:null,m:k,st:'new',touch:0,src:'Сайт',note:''});render();toast(`${id} с сайта → ${MGR[k]}: у него меньше всех заявок за день. Пуш на телефон отправлен.`)}

SC.sellers=()=>`<div class="hd"><div><h2>Продают компанию</h2><p>Отдельная воронка для тех, кто сам предлагает продать свою фирму: документы, проверка юристом, согласование цены — и одной кнопкой на маркетплейс и сайт.</p></div><div class="btns"><button class="bt p" onclick="card('sell')">+ Предложение</button></div></div>
 <div class="kb s6">${SST.map(([k,n])=>{const X=SELL.filter(p=>p.st===k);return `<div class="kc" style="--sc:#7a2e3b"><div class="kh"><b>${n}</b><span>${X.length}</span></div>${X.map(p=>`<div class="kd" onclick="sellNext('${p.id}')"><div class="kt"><b>${p.id}</b><span class="src">${p.d}</span></div><div class="kr">${esc(p.n)}</div><div class="km">${esc(p.lic)} · ${p.city}</div><div class="kf"><span>${esc(p.who)}</span><b class="mono">${mln(p.ask)}</b></div></div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 <div class="g2"><div class="note"><b>Проверка юристом</b><p>Чек-лист: учредительные документы, налоговая задолженность, судебные дела, действующие лицензии и подвиды, ИТР и техника, госконтракты. Пока юрист не закрыл — на маркетплейс не попадёт.</p></div><div class="note"><b>Клик по карточке</b><p>двигает её на следующий этап — так в демо видно, как фирма доходит до маркетплейса.</p></div></div>
 ${said('«Нам часто поступают предложения от клиентов: они хотят свои компании продать — с ними тоже работаем».')}`;
function sellNext(id){const p=SELL.find(x=>x.id===id);const i=SST.findIndex(x=>x[0]===p.st);if(i>=SST.length-2){toast('Фирма уже на маркетплейсе или продана.');return}p.st=SST[i+1][0];if(p.st==='pub'&&!FIRMS.some(f=>f.n===p.n))FIRMS.unshift({id:'F-'+(FIRMS.length+1),n:p.n,city:p.city,year:2018,lic:p.lic,nds:1,turn:'по документам',debt:'нет',price:p.ask,st:'pub',seller:p.who,views:0});render();toast(p.st==='pub'?`${p.n} опубликована на маркетплейсе и на сайте.`:`${p.id} → «${SST[i+1][1]}».`)}

SC.repeat=()=>`<div class="hd"><div><h2>Постоянные клиенты</h2><p>Клиент, который уже получал у вас лицензию, не теряется среди новых заявок. Система узнаёт его по телефону или БИН, показывает историю и подсказывает, что ему предложить: расширение подвидов, продление, повышение категории.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Город</th><th>Что получал</th><th>Последняя услуга</th><th>Что предложить</th><th>Менеджер</th></tr></thead><tbody>${[['ТОО «Шанырак Строй»','Астана','СМР III → II категория','12.10.2026 · в работе','СМР I категория через год','Нурсултан'],['ТОО «Сапа Мед»','Астана','Медицинская лицензия','2025','Расширение видов помощи','Дамир'],['ТОО «Алматы Монтаж Сервис»','Алматы','СМР II, 2 расширения','03.2026','Подвиды «электромонтаж»','Алия'],['ТОО «Орда Проект»','Астана','Проектная III','11.2025','Повышение до II категории','Нурсултан'],['ТОО «Кокше Курылыс»','Кокшетау','Покупка готовой фирмы','06.2026','Расширение подвидов СМР','Алия']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td class="mono">${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Постоянные клиенты тоже у нас есть — пока не делали, чтобы они заново поступали: они к нам поступают как новая заявка снова».')}`;
