
/* ===== Каталог и цены ===== */
let mkCity='Все',mkLic='Все';
SC.market=()=>{const L=FIRMS.filter(f=>f.st!=='sold'&&(mkCity==='Все'||f.city===mkCity)&&(mkLic==='Все'||f.lic.includes(mkLic)));
 return `<div class="hd"><div><h2>Маркетплейс готовых фирм</h2><p>Тот же каталог, что у вас на сайте: город, лицензия, год, НДС, оборот, цена. Фирма из воронки «Продают компанию» публикуется одной кнопкой; заявка с сайта по фирме падает сразу в сделку с этой фирмой.</p></div><div class="btns"><select class="rsel" onchange="mkCity=this.value;render()">${['Все'].concat(CITIES).map(c=>`<option ${c===mkCity?'selected':''}>${c}</option>`).join('')}</select><select class="rsel" onchange="mkLic=this.value;render()">${['Все','СМР I','СМР II','Проектная','Медицинская','Туристическая'].map(c=>`<option ${c===mkLic?'selected':''}>${c}</option>`).join('')}</select></div></div>
 <div class="mk">${L.map(f=>`<div class="fc ${f.st}" onclick="curFirm='${f.id}';go('firm')"><div class="fh"><span class="mono">${f.id}</span>${f.st==='check'?'<span class="tag w">проверка</span>':f.st==='deal'?'<span class="tag a">в сделке</span>':'<span class="tag g">на сайте</span>'}</div><b>${esc(f.n)}</b><span>${f.city} · с ${f.year} г. · ${f.nds?'с НДС':'без НДС'}</span><em>${esc(f.lic)}</em><div class="fp"><strong>${tg(f.price)}</strong><small>${f.views} просмотров</small></div></div>`).join('')||'<p class="mini">Ничего не найдено.</p>'}</div>
 ${said('«Создали маркетплейс для компании… кто хочет купить, зайдёт в каталог, выберет город, какую компанию хочет с лицензией — и сразу может написать либо позвонить».')}`};
SC.firm=()=>{const f=FI(curFirm)||FIRMS[0];const D=DEALS.filter(d=>d.firm===f.id);
 return `<div class="hd"><div><div class="crumb"><a onclick="go('market')">Маркетплейс</a> / ${f.id}</div><h2>${esc(f.n)}</h2><p>${f.city} · зарегистрирована в ${f.year} г. · продавец ${esc(f.seller)}</p></div><div class="btns"><button class="bt p" onclick="toast('Ссылка на фирму отправлена клиенту в мессенджер.')">Отправить клиенту</button></div></div>
 <div class="g3"><div class="pan"><h3>Фирма</h3>${[['Лицензия',esc(f.lic)],['НДС',f.nds?'плательщик':'нет'],['Оборот',esc(f.turn)],['Налоговая задолженность',esc(f.debt)],['Судебные дела','нет'],['ИТР в штате','4 человека, дипломы приложены'],['Цена продавца',tg(f.price)],['Ваше сопровождение · 6 %',tg(f.price*.06)]].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Проверка юристом</h3><div class="chk">${['Учредительные документы','Налоговая задолженность — справка','Судебные дела — проверка по ИИН/БИН','Лицензия и подвиды в реестре','ИТР и техника','Госконтракты и отзывы заказчиков'].map((x,i)=>`<div class="ci"><span class="bx ${f.st==='check'&&i>2?'':'on'}">${f.st==='check'&&i>2?'':'✓'}</span><span class="nm">${x}</span><span class="who">Асем</span></div>`).join('')}</div></div>
 <div class="pan"><h3>Интерес покупателей</h3><div class="kv"><span>Просмотров на сайте</span><b>${f.views}</b></div><div class="kv"><span>Заявок</span><b>${D.length+(f.views>200?3:1)}</b></div>${D.map(d=>`<div class="kv clk" onclick="openDeal('${d.id}')"><span>${d.id} · ${esc(d.co!=='—'?d.co:d.ct)}</span><b>${STN(d.st).n}</b></div>`).join('')}<h3 style="margin-top:12px">Документы</h3>${['Устав.pdf','Выписка из реестра лицензий.pdf','Финотчётность 2023–2025.zip · 84 МБ','Госконтракты.zip · 210 МБ'].map(x=>`<div class="fd"><i></i><span>${x}</span></div>`).join('')}</div></div>`};

const CALC={sv:'S2',city:'Астана',extra:0,urgent:0,itr:0,disc:0};
function setC(k,v){CALC[k]=isNaN(+v)?v:+v;render()}
function calcTot(){const s=SV(CALC.sv);let base=s.pr||0;const ex=CALC.extra*60000,ur=CALC.urgent?Math.round(base*.25):0,itr=CALC.itr*120000;const sub=base+ex+ur+itr;const disc=Math.round(sub*CALC.disc/100);return {s,base,ex,ur,itr,disc,duty:s.duty,tot:sub-disc+s.duty}}
SC.prices=()=>{const T=calcTot();return `<div class="hd"><div><h2>Прайс и калькулятор</h2><p>Ваши прайсы и таблицы — внутри CRM. Менеджер выбирает услугу, город и опции — цена, госпошлина и срок считаются сами и сразу идут в КП, счёт и договор.</p></div><div class="btns"><button class="bt p" onclick="go('kp');toast('КП собрано из расчёта.')">Сформировать КП →</button></div></div>
 <div class="cg"><div class="pan"><div class="cform">
  <label>Услуга<select onchange="setC('sv',this.value)">${SERV.filter(s=>s.pr).map(s=>`<option value="${s.id}" ${s.id===CALC.sv?'selected':''}>${esc(s.n)}</option>`).join('')}</select></label>
  <label>Город<select onchange="setC('city',this.value)">${CITIES.map(c=>`<option ${c===CALC.city?'selected':''}>${c}</option>`).join('')}</select></label>
  <label>Доп. подвиды СМР, шт<input type="number" value="${CALC.extra}" onchange="setC('extra',this.value)"></label>
  <label>Подбор ИТР, человек<input type="number" value="${CALC.itr}" onchange="setC('itr',this.value)"></label>
  <label>Срочно, +25 %<select onchange="setC('urgent',this.value)"><option value="0" ${!CALC.urgent?'selected':''}>нет</option><option value="1" ${CALC.urgent?'selected':''}>да</option></select></label>
  <label>Скидка, %<input type="number" value="${CALC.disc}" onchange="setC('disc',this.value)"></label>
 </div></div>
 <div class="pan"><h3>Итог</h3><div class="wf"><div><span>${esc(T.s.n)}</span><b>${fmt(T.base)}</b></div>${T.ex?`<div><span>Подвиды × ${CALC.extra}</span><b>${fmt(T.ex)}</b></div>`:''}${T.itr?`<div><span>Подбор ИТР × ${CALC.itr}</span><b>${fmt(T.itr)}</b></div>`:''}${T.ur?`<div><span>Срочность</span><b>${fmt(T.ur)}</b></div>`:''}${T.disc?`<div><span>Скидка ${CALC.disc} %</span><b class="neg">− ${fmt(T.disc)}</b></div>`:''}<div><span>Госпошлина</span><b>${fmt(T.duty)}</b></div><div class="tot"><span>Клиенту</span><b>${fmt(T.tot)}</b></div></div><p class="mini">Срок: ${T.s.days}${CALC.urgent?' — сокращаем на треть':''}.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Прайс</th><th>Направление</th><th class="r">Сопровождение</th><th class="r">Госпошлина</th><th>Срок</th></tr></thead><tbody>${SERV.map(s=>`<tr><td><b>${esc(s.n)}</b></td><td>${s.g}</td><td class="r mono">${s.pr?fmt(s.pr):'6 % от цены фирмы'}</td><td class="r mono">${s.duty?fmt(s.duty):'—'}</td><td>${s.days}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Хотелось бы в эту CRM добавить наши прайсы… таблицы тоже добавлять, чтобы удобно было».','Платон: прайсы и калькуляторы внутри сделки входят в стандартный пакет.')}`};
SC.kp=()=>{const T=calcTot();const d=DL(curDeal)||DEALS[0];return `<div class="hd"><div><h2>КП и договор</h2><p>КП собирается из калькулятора, счёт и договор — из сделки: реквизиты клиента, услуга, сумма, сроки. Отправка в мессенджер одной кнопкой; подпись ЭЦП по ссылке.</p></div></div>
 <div class="g2"><div class="pan"><h3>КП · ${d.id}</h3><div class="doc"><div class="dh"><div class="dlg">РЕЕСТР<small>ЛИЦЕНЗИРОВАНИЕ · ГОТОВЫЕ ФИРМЫ</small></div><div style="text-align:right;font-size:10px">КП № ${d.id}<br>05.10.2026</div></div><h4>Коммерческое предложение</h4><p style="font-size:11px">${esc(d.co!=='—'?d.co:d.ct)} · ${CALC.city}</p><div class="drow"><span>Услуга</span><span>${esc(T.s.n)}</span><span class="r">${fmt(T.base)}</span></div>${T.ex?`<div class="drow"><span>Подвиды</span><span>${CALC.extra} шт</span><span class="r">${fmt(T.ex)}</span></div>`:''}<div class="drow"><span>Госпошлина</span><span>по закону</span><span class="r">${fmt(T.duty)}</span></div><div class="dsum"><span>Итого</span><span>${tg(T.tot)}</span></div><div class="dfoot"><span>Срок — ${T.s.days}. Оплата: 50 % при подписании, 50 % при получении лицензии.</span></div></div><div class="btns l" style="margin-top:10px"><button class="bt p" onclick="toast('КП отправлено клиенту в мессенджер из карточки.')">Отправить в мессенджер</button></div></div>
 <div class="pan"><h3>Договор и счёт</h3>${[['Договор оказания услуг — из шаблона','ok'],['Реквизиты клиента подставлены по БИН','ok'],['Счёт на 50 % предоплаты','ok'],['Подпись клиента ЭЦП по ссылке','wait'],['Акт после получения лицензии','wait']].map(x=>`<div class="li ${x[1]==='ok'?'':'w'}"><i>${x[1]==='ok'?'✓':'…'}</i><span>${x[0]}</span></div>`).join('')}<div class="btns l" style="margin-top:10px"><button class="bt p" onclick="toast('Договор отправлен на подпись ЭЦП, сделка → «Договор».')">Отправить на подпись</button></div></div></div>`};

/* ===== Связь ===== */
const CHATS={
 'Д-2318':[['in','Ерлан · 10:12','Добрый день, по II категории — сколько по срокам? Тендер 1 ноября.'],['out','Нурсултан · 10:20','Ерлан, 20–30 рабочих дней. Чтобы успеть, подаём до 9 октября — нужны дипломы ИТР.'],['in','Ерлан · 10:31','У конкурентов 700 тысяч, у вас 900. Почему?'],['out','Нурсултан · 10:44','В нашу цену входят подбор ИТР и проверка базы — без этого откажут. Отправил КП с расчётом.']],
 'Д-2329':[['in','Сабина · 15:48','Здравствуйте! Нужна туристическая лицензия, сколько стоит?']],
 def:[['sys','авто','Заявка принята. Менеджер свяжется в течение 15 минут.'],['in','клиент','Добрый день, нужна консультация']]};
SC.chat=()=>{const d=DL(curDeal)||DEALS[0];const T=Object.keys(CHATS).filter(k=>k!=='def');
 return `<div class="hd"><div><h2>Мессенджер</h2><p>Номер подключается через провайдера, который сейчас у вас вместо заблокированного WhatsApp — или любого другого с API. Вся переписка в карточке сделки, руководитель видит, кто и когда ответил.</p></div></div>
 <div class="g12"><div class="pan"><h3>Чаты</h3>${T.map(k=>{const L=CHATS[k],x=DL(k),last=L[L.length-1];return `<div class="ch ${k===d.id?'on':''}" onclick="curDeal='${k}';render()"><b>${esc(x.ct)} · ${k}</b><span>${esc(last[2]).slice(0,58)}</span>${last[0]==='in'?'<em>ждёт ответа</em>':''}</div>`}).join('')}</div>
 <div class="pan"><h3>${esc(d.ct)} · ${d.id} · ${MGR[d.m]}</h3><div class="chat">${(CHATS[d.id]||CHATS.def).map(m=>`<div class="msg ${m[0]}"><small>${m[1]}</small>${esc(m[2])}</div>`).join('')}</div><div class="wain"><input id="ch_t" value="Добрый день! Отправляю КП по вашей заявке."><button class="bt p" onclick="chSend('${d.id}')">Отправить</button></div></div></div>
 ${said('«WhatsApp нас заблокировал — они же неофициально с Метой работают… нужно узнать, сможем ли проинтегрироваться».','Платон: перенесём и проинтегрируемся.')}`};
function chSend(id){const el=document.getElementById('ch_t');if(!el)return;CHATS[id]=(CHATS[id]||CHATS.def.slice()).concat([['out',ROLES[role].n+' · '+NOW,el.value]]);render();toast('Сообщение отправлено и сохранено в сделке.')}
SC.calls=()=>`<div class="hd"><div><h2>Звонки</h2><p>Телефония в карточке: звонок из CRM в один клик, входящий открывает карточку клиента, записи разговоров в сделке. Сколько звонков, сколько минут на линии, сколько касаний — по каждому менеджеру. Sipuni или новый оператор — любой с API.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Менеджер</th><th class="r">Звонков</th><th class="r">Исходящих</th><th class="r">Пропущено</th><th class="r">Минут на линии</th><th class="r">Средний</th><th class="r">Касаний</th></tr></thead><tbody>${CALLS.map(c=>`<tr><td><b>${MGR[c.m]}</b></td><td class="r mono">${c.calls}</td><td class="r mono">${c.out}</td><td class="r mono ${c.miss>3?'neg':''}">${c.miss}</td><td class="r mono">${c.min}</td><td class="r mono">${(c.min/c.calls).toFixed(1).replace('.',',')} мин</td><td class="r mono">${c.touch}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2"><div class="pan"><h3>Пропущенные</h3>${[['15:52','+7 701 *** 44 21','Дамир','новый номер → заявка создана'],['15:20','+7 777 *** 08 93','Дамир','ТОО «Сапа Мед» → задача перезвонить'],['14:05','+7 705 *** 61 30','Нурсултан','перезвонил 14:09']].map(r=>`<div class="lg"><span class="mono">${r[0]}</span><b>${r[1]}</b><span>${r[2]}</span><em>${r[3]}</em></div>`).join('')}</div>
 <div class="pan"><h3>Сейчас</h3><div class="live"><i></i><div><b>Нурсултан на линии · 3:12</b><span>ТОО «Гранд Проект» · Д-2324 · карточка открыта автоматически</span></div></div><p class="mini">Связь — через вашего оператора; если сейчас меняете Sipuni на другого, подключим нового.</p></div></div>
 ${said('«Аналитику часто смотрим: звонки, сколько на линии проводят менеджеры, сколько касаний делают».')}`;

/* ===== Документы ===== */
SC.files=()=>`<div class="hd"><div><h2>Хранилище документов</h2><p>Тяжёлые документы — дипломы ИТР, архивы техники, госконтракты — лежат в сделке и в карточке фирмы. Никаких пакетов памяти: место на вашем сервере, расширяется за час.</p></div></div>
 <div class="wid"><div><small>Занято</small><b>41 ГБ</b><span>из 200 ГБ на сервере</span></div><div><small>Файлов</small><b>18 640</b><span>в 2 310 сделках</span></div><div><small>Самый большой</small><b>640 МБ</b><span>сканы техники.zip</span></div><div><small>Стоимость места</small><b class="g">≈ 5 $</b><span>в месяц за +100 ГБ</span></div><div><small>Удалять старое</small><b>не нужно</b><span>всё хранится</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Папка</th><th class="r">Файлов</th><th class="r">Размер</th><th>Кто видит</th></tr></thead><tbody>${[['Сделки · лицензирование','12 480','26,4 ГБ','менеджер сделки, РОП, юрист'],['Фирмы на продажу','3 210','11,2 ГБ','юрист, руководитель; менеджеру — после публикации'],['Шаблоны договоров и КП','64','0,1 ГБ','все'],['Архив из amoCRM','2 886','3,3 ГБ','руководитель']].map(r=>`<tr><td><b>${r[0]}</b></td><td class="r mono">${r[1]}</td><td class="r mono">${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Файлы отправляют — у нас же документы в основном, тяжёлые документы — они сохраняются, приходится удалять их».','Платон: до 10 ГБ сервер бесплатный, дальше — около 5 долларов; ограничения у них искусственные.')}`;

SC.analytics=()=>`<div class="hd"><div><h2>Аналитика отдела</h2><p>Конверсия по этапам, источники, города и услуги, звонки и касания по менеджерам — те же отчёты, что вы смотрите в amoCRM, плюс маркетплейс.</p></div></div>
 <div class="wid"><div><small>Заявок в сентябре</small><b>412</b><span>+14 % к августу</span></div><div><small>Сделок закрыто</small><b class="a">38</b><span>на 41,6 млн ₸</span></div><div><small>Конверсия</small><b>9,2 %</b><span>заявка → реализация</span></div><div><small>Средний чек</small><b>1,09 млн</b><span>лицензирование</span></div><div><small>С маркетплейса</small><b class="g">61</b><span>заявка за месяц</span></div></div>
 <div class="g2"><div class="pan"><h3>Воронка · сентябрь</h3>${[['Новая заявка',412],['Взято в работу',398],['Квалификация',214],['Принятие решения',122],['Согласование',88],['Точки касания',71],['Счёт',52],['Договор',44],['Реализация',38]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${pct(x[1],412)}%"></i><b class="mono">${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Источники</h3>${[['Сайт',168],['Маркетплейс',61],['Звонок',74],['Мессенджер',58],['Instagram',31],['Рекомендация',20]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${pct(x[1],168)}%"></i><b class="mono">${x[1]}</b></div>`).join('')}<h3 style="margin-top:14px">Услуги</h3>${[['СМР II категория',14],['СМР III категория',9],['Готовые фирмы',6],['Проектная',4],['Медицинская',3],['Прочее',2]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${pct(x[1],14)}%;background:var(--acc)"></i><b class="mono">${x[1]}</b></div>`).join('')}</div></div>`;
