import {test} from 'node:test';import assert from 'node:assert/strict';
import {fileBatch} from '../app/stroy/dwg/file-batch.mjs';
function setup(){const revisions=new Map(),files=new Map(),calls=[];let n=0,current=null,quota=false,fail='',batch;const store={async save(file,state,meta){if(quota)throw Error('quota');const revision={...meta,state,id:String(++n),sourceId:String(n)};revisions.set(revision.id,revision);files.set(revision.sourceId,file);return revision;},async revision(id){return revisions.get(id);},async source(id){return files.get(id);}};batch=fileBatch({store,busy:()=>false,changed:()=>{},status:s=>calls.push(s),saveCurrent:async()=>current?store.save(current,{ops:['edited']},{name:current.name,dirty:true}):null,release:()=>{current=null;calls.push('release');},open:async(file,rev)=>{calls.push(file.name);if(file.name===fail)return false;current=file;return true;}});return {batch,calls,get current(){return current;},quota:()=>quota=true,fail:name=>fail=name};}
test('batch keeps lightweight revision pointers and opens only one file',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'},{name:'b.dwg'}]);assert.equal(s.current.name,'a.dwg');assert.equal(s.calls.filter(x=>x==='b.dwg').length,0);assert.ok(s.batch.rows().every(r=>!r.file&&!r.state&&!r.doc));await s.batch.activate(s.batch.rows()[1].id);assert.equal(s.current.name,'b.dwg');assert.equal(s.batch.rows()[0].dirty,true);await s.batch.activate(s.batch.rows()[0].id);assert.equal(s.current.name,'a.dwg');});
test('save failure prevents release and switching',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'},{name:'b.dwg'}]);const old=s.batch.active();s.quota();assert.equal(await s.batch.activate(s.batch.rows()[1].id),false);assert.equal(s.current.name,'a.dwg');assert.equal(s.batch.active(),old);});
test('failed opening restores previous persisted drawing',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'},{name:'b.dwg'}]);s.fail('b.dwg');assert.equal(await s.batch.activate(s.batch.rows()[1].id),false);assert.equal(s.current.name,'a.dwg');assert.equal(s.batch.rows()[1].error,true);});
test('adding invalid files and removing inactive entry preserve active work',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'},{name:'b.dwg'},{name:'x.png'}]);assert.equal(s.batch.rows().length,2);await s.batch.remove(s.batch.rows()[1].id);assert.equal(s.current.name,'a.dwg');assert.equal(s.batch.rows().length,1);});
test('concurrent activation is serialized and inactive files are not read',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'},{name:'b.dwg'},{name:'c.dwg'}]);const ids=s.batch.rows().map(r=>r.id);await Promise.all([s.batch.activate(ids[1]),s.batch.activate(ids[2])]);assert.equal(s.current.name,'b.dwg');assert.equal(s.calls.filter(x=>x==='c.dwg').length,0);});
test('closing the last active tab releases the transition lock',async()=>{const s=setup();await s.batch.add([{name:'a.dwg'}]);await s.batch.remove(s.batch.active());assert.equal(s.batch.rows().length,0);assert.equal(s.batch.active(),null);assert.equal(s.batch.locked(),false);});
test('oversized files are refused before storage or decoding',async()=>{const s=setup();await s.batch.add([{name:'huge.dwg',size:129*1024*1024}]);assert.equal(s.batch.rows().length,0);assert.equal(s.current,null);});
