import test from 'node:test';import assert from 'node:assert/strict';
import {fromRecords,get,num} from '../app/stroy/dwg/cad.mjs';
import {dimensionDefinition,dimensionAssociated,planDimensionEdit,planDimensionMove,applyDimensionPlan} from '../app/stroy/dwg/dimension-edit.mjs';
import {captureView,restoreView} from '../app/stroy/dwg/view-history.mjs';
import {replayRecovery} from '../app/stroy/dwg/recovery.mjs';
const rec=(id,type,pairs)=>({id,type,pairs:[[0,type],...pairs].map(([c,v])=>[c,String(v)])});
function fixture(){return fromRecords([rec('s','SECTION',[[2,'BLOCKS']]),rec('b','BLOCK',[[2,'D']]),rec('line','LINE',[[5,'B'],[10,100],[20,0],[11,100],[21,950]]),rec('text','MTEXT',[[5,'C'],[10,120],[20,475],[40,20],[1,'950']]),rec('eb','ENDBLK',[]),rec('es','ENDSEC',[]),rec('s2','SECTION',[[2,'ENTITIES']]),rec('dim','DIMENSION',[[5,'A'],[2,'D'],[70,0],[50,90],[13,0],[23,0],[14,0],[24,950],[10,100],[20,950],[11,120],[21,475],[42,950]]),rec('es2','ENDSEC',[])]);}
test('dimension stretch updates native definition and cache without resizing font',()=>{const doc=fixture(),r=doc.entities[0],plan=planDimensionEdit(doc,r,{length:1200,offset:-200});assert.equal(dimensionDefinition(r).length,950);applyDimensionPlan(plan);const f=dimensionDefinition(r);assert.ok(Math.abs(f.length-1200)<1e-8);assert.ok(Math.abs(f.offset+200)<1e-8);assert.equal(num(r,42),1200);assert.equal(get(r,1),'');const text=doc.records.find(r=>r.id==='text');assert.equal(get(text,1),'1200');assert.equal(num(text,40),20);assert.equal(r.type,'DIMENSION');assert.equal(doc.records.find(r=>r.id==='line').type,'LINE');});
test('invalid and shared dimension cache edits reject before mutation',()=>{const doc=fixture(),r=doc.entities[0],before=JSON.stringify(doc.records);assert.throws(()=>planDimensionEdit(doc,r,{length:-1,offset:0}));assert.equal(JSON.stringify(doc.records),before);doc.records.push(rec('other','DIMENSION',[[2,'D']]));assert.throws(()=>planDimensionEdit(doc,r,{length:1200,offset:0}),/несколькими/);});
test('device endpoint follows length and sideways movement without moving the dimension line',()=>{const doc=fixture(),r=doc.entities[0],f=dimensionDefinition(r);applyDimensionPlan(planDimensionEdit(doc,r,{length:1050,offset:f.offset-20,endNormal:40}));const next=dimensionDefinition(r);assert.ok(Math.abs(next.b[0]+40)<1e-8);assert.ok(Math.abs(next.b[1]-1050)<1e-8);assert.ok(Math.abs(next.q[0]-f.q[0])<1e-8);assert.ok(Math.abs(next.length-1050)<1e-8);});
test('CAD-associated endpoint cannot silently detach from its dependency',()=>{const doc=fixture(),r=doc.entities[0];r.dimensionEndLocked=true;assert.throws(()=>planDimensionEdit(doc,r,{length:1200,offset:0}),/AutoCAD/);});
test('whole dimension move preserves measurement, label and sizes',()=>{const doc=fixture(),r=doc.entities[0],text=doc.records.find(r=>r.id==='text');applyDimensionPlan(planDimensionMove(doc,r,[25,-30]));assert.deepEqual(dimensionDefinition(r).a,[25,-30]);assert.deepEqual(dimensionDefinition(r).b,[25,920]);assert.equal(dimensionDefinition(r).length,950);assert.equal(num(r,42),950);assert.equal(get(text,1),'950');assert.equal(num(text,40),20);assert.equal(num(text,10),145);assert.equal(num(text,20),445);});
test('whole dimension move refuses dependencies, shared cache and invalid deltas',()=>{const doc=fixture(),r=doc.entities[0];assert.throws(()=>planDimensionMove(doc,r,[NaN,0]));r.dimensionEndLocked=true;assert.throws(()=>planDimensionMove(doc,r,[1,2]),/AutoCAD/);r.dimensionEndLocked=false;doc.records.push(rec('other','DIMENSION',[[2,'D']]));assert.throws(()=>planDimensionMove(doc,r,[1,2]),/несколькими/);});
test('confirmed disassociation is undoable and does not bypass shared-cache checks',()=>{const doc=fixture(),r=doc.entities[0];r.dimensionMoveLocked=r.dimensionEndLocked=true;doc.nativeOps=[];const plan=planDimensionMove(doc,r,[25,30],{detach:true}),before=captureView(doc,{},plan.patches.map(p=>p.record));assert.equal(dimensionAssociated(doc,r),true);applyDimensionPlan(plan);doc.nativeOps.push({handle:'A',dimensionMove:[25,30],detachDimension:true});assert.equal(dimensionAssociated(doc,r),false);assert.doesNotThrow(()=>planDimensionEdit(doc,r,{length:1100,offset:0}));restoreView(before);assert.equal(dimensionAssociated(doc,r),true);assert.deepEqual(dimensionDefinition(r).a,[0,0]);doc.records.push(rec('other','DIMENSION',[[2,'D']]));assert.throws(()=>planDimensionMove(doc,r,[1,2],{detach:true}),/несколькими/);});
test('recovery replays confirmed detach, later move and length change in order',()=>{const doc=fixture(),r=doc.entities[0];r.dimensionEndLocked=r.dimensionMoveLocked=true;const ops=[{handle:'A',dimensionMove:[25,30],detachDimension:true},{handle:'A',dimensionMove:[10,0]},{handle:'A',dimension:{length:1100,offset:-100}}];replayRecovery(doc,{ops,added:[],project:null});assert.deepEqual(dimensionDefinition(r).a,[35,30]);assert.ok(Math.abs(dimensionDefinition(r).length-1100)<1e-8);assert.equal(dimensionAssociated(doc,r),false);});
