import assert from 'node:assert/strict';
import {withProjectPayoutRows,payoutTotals,defaultPlan,migratePlan,movePlanRow,remapPlanRows,weekStart,weeksFrom,WEEK,planCalculator,planningIncome} from '../crm/worker/financial-model.js';
import {handleFinancialPlanning,PLAN_COLLECTION} from '../crm/worker/financial-planning.js';
const boundary=Date.parse('2026-10-08T14:00:00+05:00');
assert.equal(weekStart(boundary),boundary);assert.equal(weekStart(boundary-1),boundary-WEEK);
let p=defaultPlan(boundary);p.start=boundary;
p.rows.push({id:'seller1',name:'Продавец 1',kind:'expense',unit:'₸',parentId:'sales'},{id:'seller2',name:'Продавец 2',kind:'expense',unit:'₸',parentId:'sales'});
p.cells={seller1:{[boundary]:'100'},seller2:{[boundary]:'50'},advertising:{[boundary]:'20'}};
const value=(plan,id,c=1)=>planCalculator(plan,[1000],[])(plan.rows.findIndex(r=>r.id===id),c);
assert.equal(value(p,'promotion'),100);assert.equal(value(p,'tax'),20);assert.equal(value(p,'sales'),150);assert.equal(value(p,'profit'),710);
p.cells.promotion={[boundary]:'999',benchmark:'99'};p.cells.tax={[boundary]:'999'};assert.equal(value(p,'tax'),20);assert.equal(value(p,'promotion'),100);
p.rows.push({id:'formula',name:'Контроль',kind:'formula',unit:'₸'});p.cells.formula={[boundary]:'=SUM(R2:R4)+R10'};const before=value(p,'formula');
const moved=movePlanRow(p,'sales',-1);assert.equal(value(moved,'profit'),710);assert.equal(value(moved,'formula'),before);assert.equal(moved.rows[moved.rows.findIndex(r=>r.id==='sales')+1].id,'seller1');
const childMoved=movePlanRow(moved,'seller2',-1);assert.equal(value(childMoved,'formula'),before);assert.equal(childMoved.rows[childMoved.rows.findIndex(r=>r.id==='sales')+1].id,'seller2');
const old={revision:4,start:boundary,cells:{advertising:{[boundary]:'=R1*5%'},custom:{[boundary]:'=R2'}},rows:[{id:'income',kind:'income',name:'Доход',unit:'₸'},{id:'paid',kind:'paid'},{id:'planned',kind:'planned'},{id:'advertising',kind:'expense',name:'Реклама',unit:'₸'},{id:'promotion',kind:'expense'},{id:'tax',kind:'tax'},{id:'profit',kind:'profit',name:'Прибыль',unit:'₸'},{id:'forecast',kind:'forecast'},{id:'role',kind:'payoutPaid'},{id:'custom',kind:'formula',name:'Расчёт',unit:'₸'}]};
const migrated=migratePlan(old);assert.equal(migrated.revision,4);assert.ok(!migrated.rows.some(r=>['paid','planned','forecast','payoutPaid'].includes(r.kind)));assert.equal(value(migrated,'advertising'),50);assert.equal(value(migrated,'profit'),830);assert.equal(migrated.cells.custom[boundary],'=#REF!');assert.deepEqual(migratePlan(migrated),migrated);assert.equal(migrated.legacyRows.length,10);
p=withProjectPayoutRows(p);
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
let stored=null,reads=0;const deps={HttpError,get:async()=>stored,save:async(_,next,revision)=>{if((stored?.revision||0)!==revision)return false;stored=structuredClone(next);return true;},income:async()=>{reads++;return [1000];},payouts:async()=>[]};
const root={email:'uurraa@gmail.com'},viewer={email:'viewer@test.kz'},editor={email:'editor@test.kz'},admin={email:'admin@test.kz',isRoot:true,user:{isSuperAdmin:true}};
const call=(actor,method='GET',path='/financial-planning',body)=>handleFinancialPlanning(new Request('https://test'+path,{method,...(body?{body:JSON.stringify(body)}:{})}),{},actor,deps);
await assert.rejects(()=>call(admin),e=>e.status===403);assert.equal(reads,0);
await call(root,'PUT','/financial-planning/access',{revision:0,viewers:[viewer.email,editor.email],editors:[editor.email]});
assert.equal((await call(viewer)).editable,false);assert.deepEqual((await call(viewer)).plan.viewers,[]);
await assert.rejects(()=>call(viewer,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells}),e=>e.status===403);
await call(editor,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells});assert.equal(stored.rows.find(r=>r.id==='seller1').parentId,'sales');
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells}),e=>e.status===409);
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:2,rows:p.rows.map(r=>r.id==='tax'?{...r,rate:3}:r),cells:p.cells}),e=>e.status===400);
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:2,rows:p.rows.map(r=>r.id==='seller1'?{...r,parentId:'income'}:r),cells:p.cells}),e=>e.status===400);
await call(root,'PUT','/financial-planning/access',{revision:2,viewers:[],editors:[]});await assert.rejects(()=>call(viewer),e=>e.status===403);
console.log('Planning v2: migration, fixed percentages, sales rollup, profit, hierarchy, formula-safe reorder, ACL and conflict tests passed.');
const {setPlanRule,effectiveRule}=await import('../crm/worker/financial-model.js');
let recurring=defaultPlan(boundary);recurring.start=boundary-2*WEEK;
recurring.cells.advertising={[boundary-WEEK]:'77'};
recurring=setPlanRule(recurring,'advertising',boundary,{mode:'amount',value:'100'});
recurring=setPlanRule(recurring,'advertising',boundary+3*WEEK,{mode:'percent',value:'5'});
const incomes=Array.from({length:52},()=>1000),check=(plan,id,c)=>planCalculator(plan,incomes,[])(plan.rows.findIndex(r=>r.id===id),c);
assert.equal(check(recurring,'advertising',1),0);assert.equal(check(recurring,'advertising',2),77);
for(const c of [3,4,5])assert.equal(check(recurring,'advertising',c),100);
assert.equal(check(recurring,'advertising',6),50);assert.equal(check(recurring,'advertising',52),50);
recurring=setPlanRule(recurring,'advertising',boundary+WEEK,{mode:'amount',value:'200'});
assert.equal(check(recurring,'advertising',3),100);assert.equal(check(recurring,'advertising',4),200);assert.equal(check(recurring,'advertising',6),50);
recurring=setPlanRule(recurring,'advertising',boundary+4*WEEK,{mode:'amount',value:'0'});assert.equal(check(recurring,'advertising',7),0);
recurring=setPlanRule(recurring,'promotion',boundary+WEEK,{mode:'percent',value:'12'});assert.equal(check(recurring,'promotion',3),100);assert.equal(check(recurring,'promotion',4),120);
recurring=setPlanRule(recurring,'servers',boundary,{mode:'formula',value:'=SUM(R2:R4)'});
const ruleBefore=check(recurring,'servers',4),ruleMoved=movePlanRow(recurring,'advertising',1);assert.equal(check(ruleMoved,'servers',4),ruleBefore);
const get=await call(root);let apiPlan=get.plan;
apiPlan=setPlanRule(apiPlan,'advertising',apiPlan.start+WEEK,{mode:'percent',value:'5'});
await call(root,'PUT',undefined,{revision:apiPlan.revision,rows:apiPlan.rows,cells:apiPlan.cells,rules:apiPlan.rules});assert.equal((await call(root)).plan.rules.advertising[apiPlan.start+WEEK].value,'5');
await assert.rejects(()=>call(root,'PUT',undefined,{revision:stored.revision,rows:apiPlan.rows,cells:apiPlan.cells,rules:{income:{[apiPlan.start]:{mode:'amount',value:'500'}}}}),e=>e.status===400);
await assert.rejects(()=>call(root,'PUT',undefined,{revision:stored.revision,rows:apiPlan.rows,cells:apiPlan.cells,rules:{advertising:{[apiPlan.start]:{mode:'percent',value:'101'}}}}),e=>e.status===400);
await assert.rejects(()=>call(root,'PUT',undefined,{revision:stored.revision,rows:apiPlan.rows,cells:apiPlan.cells}),e=>e.status===409);
console.log('Forward rules: preserve past, future boundary, inserted change, zero stop, percentage override, formulas on reorder, persistence and API validation passed.');
let manual=defaultPlan(boundary);manual.start=boundary;
manual.rows.push({id:'seller',name:'Seller',kind:'expense',unit:'₸',parentId:'sales'});
manual.cells.seller={[boundary]:'100'};
manual=setPlanRule(manual,'sales',boundary,{mode:'amount',value:'200'});
assert.equal(value(manual,'sales'),300);assert.equal(value(manual,'profit'),580);
manual=setPlanRule(manual,'sales',boundary,{mode:'percent',value:'5'});
assert.equal(value(manual,'sales'),150);assert.equal(value(manual,'profit'),730);
const manualApi=await call(root);manualApi.plan=setPlanRule(manualApi.plan,'sales',manualApi.plan.start,{mode:'amount',value:'200'});
await call(root,'PUT',undefined,{revision:manualApi.plan.revision,rows:manualApi.plan.rows,cells:manualApi.plan.cells,rules:manualApi.plan.rules});
assert.equal((await call(root)).plan.rules.sales[manualApi.plan.start].value,'200');
console.log('Manual group amount/percentage adds children, deducts once and persists through API.');

let grouped=withProjectPayoutRows(defaultPlan(boundary));grouped.start=boundary;
grouped=setPlanRule(grouped,'sales',boundary,{mode:'amount',value:'20'});
grouped.rows.push({id:'s',name:'Seller',kind:'expense',unit:'₸',parentId:'sales'});grouped.cells.s={[boundary]:'30'};
const totals=payoutTotals([{role:'Продажи',status:'paid',amount:100,date:'2026-10-09'},{role:'Агент',status:'paid',amount:50,date:'2026-10-09'},{role:'Дизайнер',status:'planned',amount:70,date:'2026-10-09'},{role:'Программист',status:'paid',amount:999,date:'2026-10-09',deleted:true}],weeksFrom(boundary));
const gv=id=>planCalculator(grouped,[1000],totals)(grouped.rows.findIndex(r=>r.id===id),1);
assert.equal(gv('sales'),150);assert.equal(gv('payout_agents'),50);assert.equal(gv('payout_designers'),0);assert.equal(gv('profit'),680);assert.equal(totals[0].byRole['Дизайнер'].planned,70);
assert.deepEqual(withProjectPayoutRows(grouped),grouped);
console.log('Project roles: paid plus manual plus children, planned separate, deleted ignored, profit once.');
