import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {defaultPlan,weekStart,weeksFrom,WEEK,payoutTotals,formulaValue,planCalculator} from '../crm/worker/financial-model.js';
import {handleFinancialPlanning,PLAN_COLLECTION} from '../crm/worker/financial-planning.js';
import {PAYOUT_COLLECTION} from '../crm/worker/project-payouts.js';
const boundary=Date.parse('2026-10-08T14:00:00+05:00');
assert.equal(weekStart(boundary),boundary);assert.equal(weekStart(boundary-1),boundary-WEEK);
const weeks=weeksFrom(boundary,2), entries=[{date:'2026-10-08',amount:50,status:'paid'},{date:'2026-10-09',amount:100,status:'paid'},{date:'2026-10-10',amount:200,status:'planned'},{date:'2026-10-11',amount:999,status:'paid',deleted:true}];
assert.deepEqual(payoutTotals(entries,weeks)[0],{paid:100,planned:200,byRole:{'Прочие выплаты':{paid:100,planned:200}}});
assert.equal(formulaValue('=SUM(R1:R3)*3%',ref=>+ref.slice(1)*100),18);
assert.equal(formulaValue('=-(20+5)/5',()=>0),-5);
for(const bad of ['=alert(1)','=1/0','=globalThis','=SUM(R1:C2)'])assert.throws(()=>formulaValue(bad,()=>0));
let plan=defaultPlan(boundary);plan.start=boundary;plan.cells={tax:{benchmark:'3'},advertising:{[boundary]:'=R1*10%'},promotion:{[boundary]:'50'}};
let calc=planCalculator(plan,[1000],[{paid:100,planned:200}]);assert.equal(calc(5,1),30);assert.equal(calc(6,1),720);assert.equal(calc(7,1),520);
plan.cells.advertising[boundary]='=R4';assert.throws(()=>planCalculator(plan,[1000],[])(3,1),/Циклическая/);plan.cells.advertising[boundary]='=C1*10%';assert.equal(planCalculator(plan,[1000],[])(3,1),100);
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
let stored=null,reads=0;
const deps={HttpError,get:async()=>stored,save:async(_,next,revision)=>{if((stored?.revision||0)!==revision)return false;stored=structuredClone(next);return true;},income:async()=>{reads++;return [1000];},payouts:async()=>entries};
const root={isRoot:true,email:'uurraa@gmail.com'},viewer={email:'viewer@test.kz'},editor={email:'editor@test.kz'},admin={email:'admin@test.kz',user:{isSuperAdmin:true}};
const call=(actor,method='GET',path='/financial-planning',body)=>handleFinancialPlanning(new Request('https://test'+path,{method,...(body?{body:JSON.stringify(body)}:{})}),{},actor,deps);
assert.equal((await call(admin,'GET','/financial-planning/access')).allowed,false);
await assert.rejects(()=>call(admin),e=>e.status===403);assert.equal(reads,0);
await call(root,'PUT','/financial-planning/access',{revision:0,viewers:[viewer.email,editor.email],editors:[editor.email]});
assert.equal((await call(viewer)).editable,false);assert.deepEqual((await call(viewer)).plan.viewers,[]);
await assert.rejects(()=>call(viewer,'PUT',undefined,{revision:1,...plan}),e=>e.status===409||e.status===403);
await call(editor,'PUT',undefined,{revision:1,rows:plan.rows,cells:plan.cells});assert.equal(stored.revision,2);
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:1,rows:plan.rows,cells:plan.cells}),e=>e.status===409);
await assert.rejects(()=>call(editor,'PUT','/financial-planning/access',{revision:2,viewers:[],editors:[]}),e=>e.status===403);
await assert.rejects(()=>call(root,'PUT',undefined,{revision:2,rows:plan.rows.filter(r=>r.kind!=='income'),cells:{}}),e=>e.status===400);
await call(root,'PUT','/financial-planning/access',{revision:2,viewers:[],editors:[]});await assert.rejects(()=>call(viewer),e=>e.status===403);
const source=readFileSync(new URL('../crm/worker/worker.js',import.meta.url),'utf8');
const ctx=vm.createContext({PLAN_COLLECTION,PAYOUT_COLLECTION,HttpError,readRequestBodyAsJson:r=>r.json(),normalizeCollectionList:x=>x,normalizeCollectionName:x=>x,isObject:x=>!!x,DEFAULT_STORE_PULL_LIMIT:1000,MAX_STORE_OPS:100});
for(const name of ['handleStorePull','handleStorePush']){const start=source.indexOf('async function '+name+'(');vm.runInContext(source.slice(start,source.indexOf('\n}',start)+2),ctx);}
await assert.rejects(()=>ctx.handleStorePull(new Request('https://test',{method:'POST',body:JSON.stringify({collections:[PLAN_COLLECTION]})}),{},root),e=>e.status===403);
await assert.rejects(()=>ctx.handleStorePush(new Request('https://test',{method:'POST',body:JSON.stringify({ops:[{type:'upsert',collection:PLAN_COLLECTION,item:{id:'plan'}}]})}),{},root),e=>e.status===403);
console.log('Financial planning: boundaries, receipts/payouts, taxes, profit, formulas/cycles, strict ACL, revocation, conflict, generic-store isolation passed.');
const {planningIncome,appendPayoutArticles}=await import('../crm/worker/financial-model.js');
const finance={rate:475,money:{a:{deal:1000,cur:'KZT',pays:[{sum:100,at:boundary-1},{sum:200,at:boundary},{sum:50,d:'2026-10-08'}]},b:{cur:'USD',pays:[{sum:10,at:boundary+1000}]}},chartOverrides:{'2026-10-22':{cash:777}}};
const sandbox=vm.createContext({console,URL,Date,Response,Request,TextEncoder,TextDecoder});
vm.runInContext(source.replace(/^import[\s\S]*?;\n/gm,'').replace('export default','const workerExport='),sandbox);
const portal=sandbox.projectFinanceChartSeries(sandbox.normalizeProjectFinance(finance),8,'week',weeks).map(w=>w.cash);
assert.deepEqual(planningIncome(finance,weeks),Array.from(portal));assert.deepEqual(Array.from(portal),[4950,777]);
const withArticles=appendPayoutArticles(defaultPlan(),[{role:'Программист',amount:100,status:'paid'}]);assert.equal(withArticles.rows.length,10);assert.equal(appendPayoutArticles(withArticles,[{role:'Программист'}]).rows.length,10);
await assert.rejects(()=>call({...admin,isRoot:true}),e=>e.status===403);
console.log('Production cash parity (USD, Thursday boundary, overrides), payout articles and superadmin allowlist enforcement passed.');
