import assert from 'node:assert/strict';
import {defaultPlan,migratePlan,movePlanRow,remapPlanRows,weekStart,weeksFrom,WEEK,planCalculator,planningIncome} from '../crm/worker/financial-model.js';
import {handleFinancialPlanning,PLAN_COLLECTION} from '../crm/worker/financial-planning.js';
const boundary=Date.parse('2026-10-08T14:00:00+05:00');
assert.equal(weekStart(boundary),boundary);assert.equal(weekStart(boundary-1),boundary-WEEK);
let p=defaultPlan(boundary);p.start=boundary;
p.rows.push({id:'seller1',name:'Продавец 1',kind:'expense',unit:'₸',parentId:'sales'},{id:'seller2',name:'Продавец 2',kind:'expense',unit:'₸',parentId:'sales'});
p.cells={seller1:{[boundary]:'100'},seller2:{[boundary]:'50'},advertising:{[boundary]:'20'}};
const value=(plan,id,c=1)=>planCalculator(plan,[1000],[])(plan.rows.findIndex(r=>r.id===id),c);
assert.equal(value(p,'promotion'),100);assert.equal(value(p,'tax'),20);assert.equal(value(p,'sales'),150);assert.equal(value(p,'profit'),710);
p.cells.promotion={[boundary]:'999',benchmark:'99'};p.cells.tax={[boundary]:'999'};assert.equal(value(p,'tax'),20);assert.equal(value(p,'promotion'),100);
p.rows.push({id:'formula',name:'Контроль',kind:'formula',unit:'₸'});p.cells.formula={[boundary]:'=SUM(R2:R4)+R10'};const before=value(p,'formula');
const moved=movePlanRow(p,'sales',-1);assert.equal(value(moved,'profit'),710);assert.equal(value(moved,'formula'),before);assert.equal(moved.rows[moved.rows.findIndex(r=>r.id==='sales')+1].id,'seller1');
const childMoved=movePlanRow(moved,'seller2',-1);assert.equal(value(childMoved,'formula'),before);assert.equal(childMoved.rows[childMoved.rows.findIndex(r=>r.id==='sales')+1].id,'seller2');
const old={revision:4,start:boundary,cells:{advertising:{[boundary]:'=R1*5%'},custom:{[boundary]:'=R2'}},rows:[{id:'income',kind:'income',name:'Доход',unit:'₸'},{id:'paid',kind:'paid'},{id:'planned',kind:'planned'},{id:'advertising',kind:'expense',name:'Реклама',unit:'₸'},{id:'promotion',kind:'expense'},{id:'tax',kind:'tax'},{id:'profit',kind:'profit',name:'Прибыль',unit:'₸'},{id:'forecast',kind:'forecast'},{id:'role',kind:'payoutPaid'},{id:'custom',kind:'formula',name:'Расчёт',unit:'₸'}]};
const migrated=migratePlan(old);assert.equal(migrated.revision,4);assert.ok(!migrated.rows.some(r=>['paid','planned','forecast','payoutPaid'].includes(r.kind)));assert.equal(value(migrated,'advertising'),50);assert.equal(value(migrated,'profit'),830);assert.equal(migrated.cells.custom[boundary],'=#REF!');assert.deepEqual(migratePlan(migrated),migrated);assert.equal(migrated.legacyRows.length,10);
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
let stored=null,reads=0;const deps={HttpError,get:async()=>stored,save:async(_,next,revision)=>{if((stored?.revision||0)!==revision)return false;stored=structuredClone(next);return true;},income:async()=>{reads++;return [1000];},payouts:async()=>{throw Error('Payout ledger must not be read');}};
const root={email:'uurraa@gmail.com'},viewer={email:'viewer@test.kz'},editor={email:'editor@test.kz'},admin={email:'admin@test.kz',isRoot:true,user:{isSuperAdmin:true}};
const call=(actor,method='GET',path='/financial-planning',body)=>handleFinancialPlanning(new Request('https://test'+path,{method,...(body?{body:JSON.stringify(body)}:{})}),{},actor,deps);
await assert.rejects(()=>call(admin),e=>e.status===403);assert.equal(reads,0);
await call(root,'PUT','/financial-planning/access',{revision:0,viewers:[viewer.email,editor.email],editors:[editor.email]});
assert.equal((await call(viewer)).editable,false);assert.deepEqual((await call(viewer)).plan.viewers,[]);
await assert.rejects(()=>call(viewer,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells}),e=>e.status===403);
await call(editor,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells});assert.equal(stored.rows.find(r=>r.id==='seller1').parentId,'sales');
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:1,rows:p.rows,cells:p.cells}),e=>e.status===409);
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:2,rows:p.rows.map(r=>r.id==='tax'?{...r,rate:3}:r),cells:p.cells}),e=>e.status===400);
await assert.rejects(()=>call(editor,'PUT',undefined,{revision:2,rows:p.rows.map(r=>r.id==='seller1'?{...r,parentId:'income'}:r),cells:p.cells}),e=>e.status===400);
await call(root,'PUT','/financial-planning/access',{revision:2,viewers:[],editors:[]});await assert.rejects(()=>call(viewer),e=>e.status===403);
console.log('Planning v2: migration, fixed percentages, no payout reads, sales rollup, profit, hierarchy, formula-safe reorder, ACL and conflict tests passed.');
