/* Explicit, reviewable grouping of PDF contours into a movable device. */
(function(){
'use strict';
const button=document.createElement('button');button.type='button';button.className='tool';button.id='pdfDeviceTool';button.dataset.tool='device';button.textContent='Прибор';button.title='Обведите прибор целиком, затем проверьте детали';$('toolbar').append(button);
const overlay=document.createElementNS(SVGNS,'g');overlay.id='pdfDevicePreview';svg.append(overlay);
let pending=null,drag=null,allColors=true;
function scene(){const s=S._pdfScene;return s&&s.src===S.standalonePdf&&s.pn===S.pageNum&&!S.linkedLkDocId?s.scene:null;}
const dark=color=>{if(!/^#[\da-f]{6}$/i.test(color||''))return false;return Math.max(...hex2rgb(color))<100;};
const inside=(b,r)=>b[0]>=r.x-.05&&b[1]>=r.y-.05&&b[2]<=r.x+r.w+.05&&b[3]<=r.y+r.h+.05;
function candidates(r){const sc=scene();if(!sc)return [];const sx=S.W/sc.width,sy=S.H/sc.height,taken=new Set(cur().flatMap(o=>o._pdfIds||[])),out=[];
 for(const raw of sc.objects){if(taken.has(raw.id)||!allColors&&!dark(raw.style.stroke||raw.style.fill))continue;const b=raw.box.map((v,i)=>v*(i%2?sy:sx));if(inside(b,r))out.push({raw,box:b,active:true});}
 for(const o of cur()){if(o._lkDeleted||!o._pdfIds?.length||o._pdfDevice||!allColors&&!dark(o.color))continue;const b=bbox(o),a=[b.x,b.y,b.x+b.w,b.y+b.h];if(inside(a,r))out.push({object:o,box:a,active:true});}return out;
}
function reset(){pending=null;drag=null;overlay.replaceChildren();}
function preview(){overlay.replaceChildren();if(!pending)return;for(const c of pending.items){const p=document.createElementNS(SVGNS,'path');if(c.raw){const sc=scene();p.setAttribute('d',c.raw.d);p.setAttribute('transform',`scale(${S.W/sc.width} ${S.H/sc.height})`);p.setAttribute('stroke-width',Math.max(c.raw.style.width,5/S.scale/(S.W/sc.width)));}else{p.setAttribute('d',linePath(c.object.pts));p.setAttribute('stroke-width',Math.max(c.object.width,5/S.scale));}p.setAttribute('fill','none');p.setAttribute('stroke',c.active?'#db871f':'#aab3bd');p.style.cursor='pointer';p.addEventListener('pointerdown',e=>{e.stopPropagation();e.preventDefault();c.active=!c.active;preview();renderOpt();});overlay.append(p);}const r=document.createElementNS(SVGNS,'rect');for(const key of ['x','y','width','height'])r.setAttribute(key,pending.rect[{width:'w',height:'h'}[key]||key]);r.setAttribute('fill','none');r.setAttribute('stroke','#db871f');r.setAttribute('stroke-width',1/S.scale);r.setAttribute('stroke-dasharray',`${5/S.scale} ${4/S.scale}`);r.style.pointerEvents='none';overlay.append(r);}
function groupItems(items){const sc=scene();if(!sc||!items?.length)return [];pushHistory();const grp='device-'+Date.now()+'-'+S.seq,sx=S.W/sc.width,sy=S.H/sc.height,ids=[];
 for(const c of items){let o=c.object;if(!o){const raw=c.raw,pts=raw.p.map(p=>({x:p[0]*sx,y:p[1]*sy}));o=addObj({type:'line',src:'pdf',cat:'other',color:raw.style.stroke||raw.style.fill,width:Math.max(.01,raw.style.width*sx),pts,nocalc:true,_fill:!!raw.style.fill,_lkSource:true,_pdfIds:[raw.id],_pdfD:raw.d,_pdfStyle:raw.style,_pdfSx:sx,_pdfSy:sy,_pdfLayer:raw.layer,_pdfOriginalPts:pts.map(p=>({...p})),ea:{kind:'free',h:0},eb:{kind:'free',h:0}});}o.grp=grp;o._pdfDevice=true;o.nocalc=true;ids.push(o.id);}
 redrawAll();selectObj(ids[0]);renderSide();lkQueueDrawingSave();return ids;
}
function apply(){const items=pending?.items.filter(c=>c.active);reset();setTool('select');const ids=groupItems(items);if(ids.length)toast('Прибор собран: перетащите его целиком');
}
button.onclick=()=>{if(!scene()){toast('Дождитесь подготовки объектов PDF');return;}reset();hideGuide();closeMobileDrawers();setTool('device');};
const oldOpt=renderOpt;renderOpt=function(){oldOpt();button.hidden=!S.standalonePdf||!!S.linkedLkDocId;if(S.tool==='select'&&S.selected&&getObj(S.selected)?._pdfDevice){const bar=$('optbar');bar.replaceChildren();const tip=document.createElement('span');tip.className='tip';tip.textContent='Прибор выбран целиком · перетащите на новое место';bar.append(tip);for(const [text,action] of [['Дубликат',()=>dup()],['Удалить',()=>delSel()]]){const b=document.createElement('button');b.className='mini';b.textContent=text;b.onclick=action;bar.append(b);}return;}if(S.tool!=='device')return;const bar=$('optbar');bar.replaceChildren();const tip=document.createElement('span');tip.className='tip';tip.textContent=pending?'Нажмите лишние детали, чтобы исключить. Выбрано: '+pending.items.filter(c=>c.active).length:'Обведите прибор целиком. Пересекающие рамку стены и кабели не включаются.';const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=allColors;checkbox.onchange=()=>{allColors=checkbox.checked;if(pending){pending.items=candidates(pending.rect);preview();}renderOpt();};label.append(checkbox,' Все цвета');bar.append(tip,label);if(pending){const ok=document.createElement('button');ok.className='mini';ok.id='pdfDeviceApply';ok.textContent='Выбрать прибор';ok.disabled=!pending.items.some(c=>c.active);ok.onclick=apply;bar.append(ok);}const cancel=document.createElement('button');cancel.className='mini';cancel.textContent='Отмена';cancel.onclick=()=>{reset();setTool('select');};bar.append(cancel);};
window.addEventListener('pointerdown',e=>{if(S.tool!=='device'||!scene()||!vp.contains(e.target)||e.target.closest('#pdfDevicePreview path'))return;if(e.pointerType==='touch'&&!e.isPrimary){reset();return;}if(e.button!==0||!inBase(e.clientX,e.clientY))return;e.stopPropagation();const src=S.standalonePdf,pn=S.pageNum,a=toImg(e.clientX,e.clientY);reset();drag=true;pointerDrag(e,ev=>{if(!drag||S.pageNum!==pn||S.standalonePdf!==src)return;const b=toImg(ev.clientX,ev.clientY);pending={rect:{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)},items:[]};preview();},ev=>{if(ev.type==='pointercancel'||!drag||S.pageNum!==pn||src!==S.standalonePdf){reset();return;}drag=null;if(pending){pending.items=candidates(pending.rect);preview();renderOpt();}});},true);
const members=o=>cur().filter(x=>x._pdfDevice&&x.grp===o.grp&&!x._lkDeleted).map(x=>x.id);
const oldCluster=selCluster;selCluster=function(o){return o?._pdfDevice?members(o):oldCluster(o);};
const oldMove=moveCluster;moveCluster=function(o){return o?._pdfDevice?members(o):oldMove(o);};
const oldBind=bindObj;bindObj=function(el,o){if(o._pdfDevice){el.addEventListener('pointerdown',()=>{if(S.tool==='select'&&isCoarsePointer())selectObj(o.id);});el.addEventListener('dblclick',e=>e.stopImmediatePropagation());}return oldBind(el,o);};
const oldDup=dup;dup=function(){const before=new Set(cur().map(o=>o.id));oldDup();const groups=new Map();for(const o of cur())if(!before.has(o.id)&&o._pdfDevice){if(!groups.has(o.grp))groups.set(o.grp,'device-copy-'+o.id);o.grp=groups.get(o.grp);}if(S.selected)selectObj(S.selected);};
for(const name of ['goPage','closeStandalonePdf']){const old=window[name];window[name]=function(...args){reset();return old.apply(this,args);};}
window.PdfDevices={group:groupItems,list(items){const seen=new Set();return items.filter(o=>{if(o._lkDeleted)return false;if(!o._pdfDevice)return true;if(seen.has(o.grp))return false;seen.add(o.grp);return true;});}};
const oldRedraw=redrawAll;redrawAll=function(){oldRedraw();$('objN').textContent=PdfDevices.list(cur()||[]).length;};
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.tool==='device'){reset();setTool('select');}});
})();
