/* Explicit, reviewable grouping of PDF contours into a movable device. */
(function(){
'use strict';
const button=document.createElement('button');button.type='button';button.className='tool';button.id='pdfDeviceTool';button.dataset.tool='device';button.textContent='Прибор';button.title='Обведите прибор целиком — он сразу готов к перемещению';$('toolbar').append(button);
const overlay=document.createElementNS(SVGNS,'g');overlay.id='pdfDevicePreview';svg.append(overlay);
let pending=null,drag=null,allColors=true;
function scene(){const s=S._pdfScene;return s&&s.src===S.standalonePdf&&s.pn===S.pageNum&&!S.linkedLkDocId?s.scene:null;}
const dark=color=>{if(!/^#[\da-f]{6}$/i.test(color||''))return false;return Math.max(...hex2rgb(color))<100;};
const inside=(b,r)=>b[0]>=r.x-.05&&b[1]>=r.y-.05&&b[2]<=r.x+r.w+.05&&b[3]<=r.y+r.h+.05;
function candidates(r){const sc=scene();if(!sc)return [];const sx=S.W/sc.width,sy=S.H/sc.height,taken=new Set(cur().flatMap(o=>o._pdfIds||[])),out=[];
 for(const raw of sc.objects){if(taken.has(raw.id)||!allColors&&!dark(raw.style.stroke||raw.style.fill))continue;const b=raw.box.map((v,i)=>v*(i%2?sy:sx));if(inside(b,r))out.push({raw,box:b,active:true});}
 for(const o of cur()){if(o._lkDeleted||!o._pdfIds?.length||o._pdfDevice||!allColors&&!dark(o.color))continue;const b=bbox(o),a=[b.x,b.y,b.x+b.w,b.y+b.h];if(inside(a,r))out.push({object:o,box:a,active:true});}return out;
}
function reset(){pending=null;drag=null;overlay.replaceChildren();}
function preview(){overlay.replaceChildren();if(!pending)return;for(const c of pending.items){const p=document.createElementNS(SVGNS,'path');if(c.raw){const sc=scene();p.setAttribute('d',c.raw.d);p.setAttribute('transform',`scale(${S.W/sc.width} ${S.H/sc.height})`);p.setAttribute('stroke-width',Math.max(c.raw.style.width,5/S.scale/(S.W/sc.width)));}else{p.setAttribute('d',linePath(c.object.pts));p.setAttribute('stroke-width',Math.max(c.object.width,5/S.scale));}p.setAttribute('fill','none');p.setAttribute('stroke',c.active?'#db871f':'#aab3bd');p.style.cursor='pointer';p.addEventListener('pointerdown',e=>{e.stopPropagation();e.preventDefault();c.active=!c.active;preview();renderOpt();});overlay.append(p);}const r=document.createElementNS(SVGNS,'rect');for(const key of ['x','y','width','height'])r.setAttribute(key,pending.rect[{width:'w',height:'h'}[key]||key]);r.setAttribute('fill','none');r.setAttribute('stroke','#db871f');r.setAttribute('stroke-width',1/S.scale);r.setAttribute('stroke-dasharray',`${5/S.scale} ${4/S.scale}`);r.style.pointerEvents='none';overlay.append(r);}
function groupItems(items){const sc=scene();if(!sc||!items?.length)return [];pushHistory();const grp='device-'+Date.now()+'-'+S.seq,sx=S.W/sc.width,sy=S.H/sc.height,ids=[];
 for(const c of items){let o=c.object;if(!o){const raw=c.raw,pts=raw.p.map(p=>({x:p[0]*sx,y:p[1]*sy}));o=addObj({type:'line',src:'pdf',cat:'other',color:raw.style.stroke||raw.style.fill,width:Math.max(.01,raw.style.width*sx),pts,nocalc:true,_fill:!!raw.style.fill,_lkSource:true,_pdfIds:[raw.id],_pdfD:raw.d,_pdfStyle:raw.style,_pdfSx:sx,_pdfSy:sy,_pdfLayer:raw.layer,_pdfOriginalPts:pts.map(p=>({...p})),ea:{kind:'free',h:0},eb:{kind:'free',h:0}});}o.grp=grp;o._pdfDevice=true;o.nocalc=true;ids.push(o.id);}
 redrawAll();selectObj(ids[0]);renderSide();lkQueueDrawingSave();return ids;
}
function apply(){const items=pending?.items.filter(c=>c.active);reset();setTool('select');const ids=groupItems(items);if(ids.length)toast('Прибор собран: перетащите его целиком');
}
button.onclick=()=>{if(!scene()){toast('Дождитесь подготовки объектов PDF');return;}reset();hideGuide();closeMobileDrawers();setTool('device');};
const oldOpt=renderOpt;renderOpt=function(){oldOpt();button.hidden=!S.standalonePdf||!!S.linkedLkDocId;if(S.tool==='select'&&S.selected&&getObj(S.selected)?._pdfDevice){const bar=$('optbar');bar.replaceChildren();const tip=document.createElement('span');tip.className='tip';tip.textContent='Прибор';bar.append(tip);for(const [text,action] of [['↶ 90°',()=>transformSelected(-Math.PI/2,1,1)],['↷ 90°',()=>transformSelected(Math.PI/2,1,1)],['Отразить ↔',()=>transformSelected(0,-1,1)],['Отразить ↕',()=>transformSelected(0,1,-1)],['Дубликат',()=>dup()],['Удалить',()=>delSel()]]){const b=document.createElement('button');b.className='mini';b.textContent=text;b.onclick=action;bar.append(b);}return;}if(S.tool!=='device')return;const bar=$('optbar');bar.replaceChildren();const tip=document.createElement('span');tip.className='tip';tip.textContent=pending?'Нажмите лишние детали, чтобы исключить. Выбрано: '+pending.items.filter(c=>c.active).length:'Обведите прибор и отпустите мышь — затем перетаскивайте. Пересекающие рамку линии не включаются.';const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=allColors;checkbox.onchange=()=>{allColors=checkbox.checked;if(pending){pending.items=candidates(pending.rect);preview();}renderOpt();};label.append(checkbox,' Все цвета');bar.append(tip,label);if(pending){const ok=document.createElement('button');ok.className='mini';ok.id='pdfDeviceApply';ok.textContent='Выбрать прибор';ok.disabled=!pending.items.some(c=>c.active);ok.onclick=apply;bar.append(ok);}const cancel=document.createElement('button');cancel.className='mini';cancel.textContent='Отмена';cancel.onclick=()=>{reset();setTool('select');};bar.append(cancel);};
window.addEventListener('pointerdown',e=>{if(S.tool!=='device'||!scene()||!vp.contains(e.target)||e.target.closest('#pdfDevicePreview path'))return;if(e.pointerType==='touch'&&!e.isPrimary){reset();return;}if(e.button!==0||!inBase(e.clientX,e.clientY))return;e.stopPropagation();const src=S.standalonePdf,pn=S.pageNum,a=toImg(e.clientX,e.clientY);reset();drag=true;pointerDrag(e,ev=>{if(!drag||S.pageNum!==pn||S.standalonePdf!==src)return;const b=toImg(ev.clientX,ev.clientY);pending={rect:{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)},items:[]};preview();},ev=>{if(ev.type==='pointercancel'||!drag||S.pageNum!==pn||src!==S.standalonePdf){reset();return;}drag=null;if(pending){pending.items=candidates(pending.rect);if(pending.items.length)apply();else{reset();renderOpt();toast('В рамке нет целых объектов. Обведите прибор немного шире.');}}});},true);
const members=o=>cur().filter(x=>x._pdfDevice&&x.grp===o.grp&&!x._lkDeleted).map(x=>x.id);
const oldCluster=selCluster;selCluster=function(o){return o?._pdfDevice?members(o):oldCluster(o);};
const oldMove=moveCluster;moveCluster=function(o){return o?._pdfDevice?members(o):oldMove(o);};
const oldBind=bindObj;bindObj=function(el,o){if(o._pdfDevice){el.addEventListener('pointerdown',()=>{if(S.tool==='select'&&isCoarsePointer())selectObj(o.id);});el.addEventListener('dblclick',e=>e.stopImmediatePropagation());}return oldBind(el,o);};
function multiply(a,b){return[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];}
function transform(items,center,angle,sx,sy){const co=Math.cos(angle),si=Math.sin(angle),m=[co*sx,si*sx,-si*sy,co*sy,0,0];m[4]=center.x-m[0]*center.x-m[2]*center.y;m[5]=center.y-m[1]*center.x-m[3]*center.y;
 for(const original of items){const o=getObj(original.id);if(!o)continue;const base=(original._pdfMatrix||[1,0,0,1,0,0]).slice(),p=original._pdfOriginalPts?.[0],q=original.pts[0];if(p){base[4]+=q.x-(base[0]*p.x+base[2]*p.y+base[4]);base[5]+=q.y-(base[1]*p.x+base[3]*p.y+base[5]);o._pdfMatrix=multiply(m,base);}o.pts=original.pts.map(p=>({x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]}));o.width=original.width*Math.abs(sx);}
 redrawAll();}
function selectedState(){const o=S.selected&&getObj(S.selected);if(!o?._pdfDevice)return null;const ids=members(o),b=clusterBBox(ids);return{items:ids.map(id=>JSON.parse(JSON.stringify(getObj(id)))),center:{x:b.x+b.w/2,y:b.y+b.h/2},b};}
function transformSelected(angle,sx,sy){const state=selectedState();if(!state)return;pushHistory();transform(state.items,state.center,angle,sx,sy);renderSide();lkQueueDrawingSave();}
const oldSelection=drawSelUI;drawSelUI=function(){oldSelection();const state=selectedState();if(!state)return;const {b,center}=state,c=window.PdfSheetLayout?.active(),zoom=S.scale*(c?PdfSheetLayout.geometry(c,S.W,S.H).scale:1),k=1/Math.max(.001,zoom);
 for(const [role,x,y]of [['nw',b.x,b.y],['ne',b.x+b.w,b.y],['sw',b.x,b.y+b.h],['se',b.x+b.w,b.y+b.h],['rotate',center.x,b.y-30*k]]){const h=document.createElementNS(SVGNS,role==='rotate'?'circle':'rect');const attrs=role==='rotate'?{cx:x,cy:y,r:7*k}:{x:x-5*k,y:y-5*k,width:10*k,height:10*k};for(const [a,v]of Object.entries({...attrs,fill:'white',stroke:'#1284ff','stroke-width':1.5*k,'data-ui':'handle','data-device-handle':role}))h.setAttribute(a,v);h.style.cursor=role==='rotate'?'grab':'nwse-resize';h.style.touchAction='none';gUI.append(h);
 h.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const pn=S.pageNum,data=S.data,start=toImg(e.clientX,e.clientY),v={x:x-center.x,y:y-center.y},length=v.x*v.x+v.y*v.y;let moved=false;const valid=()=>S.pageNum===pn&&S.data===data&&state.items.every(o=>!!getObj(o.id));
 pointerDrag(e,ev=>{if(!valid())return;const p=toImg(ev.clientX,ev.clientY);if(!moved&&Math.hypot(p.x-start.x,p.y-start.y)*zoom<3)return;if(!moved){pushHistory();moved=true;}if(role==='rotate')transform(state.items,center,Math.atan2(p.y-center.y,p.x-center.x)-Math.atan2(start.y-center.y,start.x-center.x),1,1);else{const scale=Math.max(.1,Math.min(10,1+((p.x-start.x)*v.x+(p.y-start.y)*v.y)/Math.max(1,length)));transform(state.items,center,0,scale,scale);}},ev=>{if(!valid())return;if(ev.type==='pointercancel'){state.items.forEach(original=>{const o=getObj(original.id);delete o._pdfMatrix;Object.assign(o,original);});redrawAll();}if(moved){renderSide();lkQueueDrawingSave();}});
 });}
};
const oldDup=dup;dup=function(){const before=new Set(cur().map(o=>o.id));oldDup();const groups=new Map();for(const o of cur())if(!before.has(o.id)&&o._pdfDevice){if(!groups.has(o.grp))groups.set(o.grp,'device-copy-'+o.id);o.grp=groups.get(o.grp);}if(S.selected)selectObj(S.selected);};
for(const name of ['goPage','closeStandalonePdf']){const old=window[name];window[name]=function(...args){reset();return old.apply(this,args);};}
window.PdfDevices={group:groupItems,list(items){const seen=new Set();return items.filter(o=>{if(o._lkDeleted)return false;if(!o._pdfDevice)return true;if(seen.has(o.grp))return false;seen.add(o.grp);return true;});}};
const oldRedraw=redrawAll;redrawAll=function(){oldRedraw();$('objN').textContent=PdfDevices.list(cur()||[]).length;};
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.tool==='device'){reset();setTool('select');}});
})();
