
/* ===== Перевозки ===== */
const myDeals=()=>role==='Логист'?DEALS.filter(d=>d.lg==='DN'):role==='Куратор'?DEALS.filter(d=>d.cur==='AS'):DEALS;
SC.board=()=>{const L=myDeals();
 return `<div class="hd"><div><h2>Доска перевозок${role==='Логист'?' · мои':role==='Куратор'?' · мои клиенты':''}</h2><p>Те же статусы, что сейчас в Битриксе: заявка → договоры → погрузка → в пути → выгрузка → документы → оплата водителю. Карточка не идёт на погрузку без галочки офис-менеджера и не идёт к оплате без документов водителя.</p></div><div class="btns"><button class="bt p" onclick="card('newdeal')">+ Перевозка</button></div></div>
 <div class="kb">${ST.map(s=>{const X=L.filter(d=>d.st===s.k);return `<div class="kc" style="--sc:${s.c}"><div class="kh"><b>${s.n}</b><span>${X.length}</span></div>${X.map(d=>`<div class="kd ${(['load','road'].includes(d.st)&&!d.ok)||(d.st==='unl'&&!drvDocsOk(d))?'alarm':''}" onclick="openDeal('${d.id}')"><div class="kt"><b>${d.id}</b>${d.intl?'<span class="tag a">МЕЖД</span>':''}${!d.ok&&STI(d.st)>=1?'<span class="lock" title="Нет галочки «согласовано»">⊘</span>':''}</div><div class="kr">${route(d)}</div><div class="km">${esc(CL(d.cl).n)} ${fl(CL(d.cl).f)}</div><div class="km">${esc(DR(d.dr).n)} ${fl(DR(d.dr).f)}</div><div class="kf"><span>${STAFF[d.lg]}</span><span>${d.paidC?'<i class="pc g">оплачено</i>':''}</span><b class="mono">${fmt(com(d))}</b></div></div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 ${said('«Карточка не передвигается, пока офис-менеджеру не сдадут подписанный договор с водителем и аналогично с клиентом» · «А если на выгрузку не перешла карточка — бухгалтер не оплачивает».')}`};

function openDeal(id){if(!allowed('deal')){toast('Карточка перевозки этой роли недоступна.');return}curDeal=id;go('deal')}
SC.deal=()=>{const d=DL(curDeal)||DEALS[0];const c=CL(d.cl),r=DR(d.dr);const si=STI(d.st);const C=com(d),V=vat(d);
 const blk=nextBlock(d);
 return `<div class="hd"><div><div class="crumb"><a onclick="go('board')">Доска</a> / ${d.id}</div><h2>${d.id} · ${route(d)}</h2><p>${d.intl?'Международная':'По Казахстану'} · погрузка ${dd(d.load)} · выгрузка ${dd(d.unl)} · логист ${STAFF[d.lg]} · куратор ${STAFF[d.cur]}</p></div>
  <div class="btns">${d.st==='pay'&&!d.paidD&&(role==='Руководитель'||role==='Бухгалтер')?`<button class="bt p" onclick="payDrv('${d.id}')">Оплачено водителю ${fmt(d.d)} ₸</button>`:''}${d.st!=='done'&&d.st!=='pay'?`<button class="bt ${blk?'':'p'}" onclick="nextSt('${d.id}')">→ ${STN(ST[si+1].k).n}</button>`:''}</div></div>
 <div class="stp">${ST.map((s,i)=>`<div class="${i<si?'ok':i===si?'on':''}" style="--sc:${s.c}"><i>${i<si?'✓':i+1}</i><span>${s.n}</span></div>`).join('')}</div>
 ${blk?`<div class="note" style="--tone:var(--bad)"><b>Дальше не двигается: ${blk}</b><p>Так задумано — как у вас в Битриксе, только проще: галочка в этой же карточке, без отдельного согласования.</p></div>`:''}
 <div class="g3">
  <div class="pan"><h3>Клиент</h3><div class="kv"><span>Компания</span><b class="lk" onclick="card('cl','${c.id}')">${esc(c.n)} ${fl(c.f)}</b></div><div class="kv"><span>Телефон</span><b class="mono">${c.ph}</b></div><div class="kv"><span>Оплата</span><b>${c.term?'через '+c.term+' дн. после выгрузки':'предоплата'}</b></div>${c.f!=='ok'?`<div class="pin ${c.f}">${esc(c.note)}</div>`:''}</div>
  <div class="pan"><h3>Водитель</h3><div class="kv"><span>Перевозчик</span><b class="lk" onclick="card('dr','${r.id}')">${esc(r.n)} ${fl(r.f)}</b></div><div class="kv"><span>Машина</span><b>${esc(r.truck)} · <span class="mono">${esc(r.plate)}</span></b></div><div class="kv"><span>Телефон</span><b class="mono">${r.ph}</b></div>${r.f!=='ok'||r.note.length>3?`<div class="pin ${r.f}">${esc(r.note)}</div>`:''}</div>
  <div class="pan"><h3>Деньги</h3><div class="kv"><span>Ставка клиента</span><b class="mono">${fmt(d.c)}</b></div><div class="kv"><span>Ставка водителю</span><b class="mono">${fmt(d.d)}</b></div><div class="kv"><span>Комиссия</span><b class="mono pos">${fmt(C)}</b></div>
   <div class="kv"><span>НДС</span><b><span class="seg"><a class="${d.nds?'on':''}" onclick="setNds('${d.id}',1)">с НДС</a><a class="${d.nds?'':'on'}" onclick="setNds('${d.id}',0)">без НДС</a></span></b></div>
   <div class="kv"><span>Клиент оплатил</span><b>${d.paidC?`<span class="tag g">${dd(d.paidC)}</span>`:`<button class="bt sm" onclick="paidC('${d.id}')">Отметить оплату</button>`}</b></div><div class="kv"><span>Водителю оплачено</span><b>${d.paidD?'<span class="tag g">да</span>':'<span class="tag">нет</span>'}</b></div></div>
 </div>
 <div class="g2">
  <div class="pan"><h3>Договоры-заявки · проверяет офис-менеджер</h3><div class="chk">
   <div class="ci"><span class="bx ${d.cc?'on':''}" onclick="togC('${d.id}','cc')">${d.cc?'✓':''}</span><span class="nm">Договор-заявка с клиентом подписан</span><span class="who">${d.cc?'фото / PDF в карточке':'нет'}</span></div>
   <div class="ci"><span class="bx ${d.cd?'on':''}" onclick="togC('${d.id}','cd')">${d.cd?'✓':''}</span><span class="nm">Договор-заявка с водителем подписан</span><span class="who">${d.cd?'фото бумажного договора':'нет'}</span></div>
   <div class="ci hi"><span class="bx ${d.ok?'on':''}" onclick="setOk('${d.id}')">${d.ok?'✓':''}</span><span class="nm"><b>Согласовано</b> — офис-менеджер проверил, карточку можно двигать</span><span class="who">${d.ok?'Жанна':''}</span></div></div>
   <p class="mini">Водителю электронная подпись не нужна: он подписывает бумагу, логист фотографирует — фото в карточке.</p></div>
  <div class="pan"><h3>Документы по рейсу · ${d.docs.filter(Boolean).length} из 6</h3><div class="chk">${DOCN.map((n,i)=>`<div class="ci"><span class="bx ${d.docs[i]?'on':''}" onclick="togDoc('${d.id}',${i})">${d.docs[i]?'✓':''}</span><span class="nm">${n}${i===0?` <a class="lk" onclick="card('inv','${d.id}')">открыть</a>`:''}</span><span class="who">${i<3?'мы → клиенту':'водитель → нам'}</span></div>`).join('')}</div></div>
 </div>
 <div class="pan"><h3>Ход перевозки</h3><div class="tl">${dealLog(d).map(x=>`<div class="tli ${x[2]||'ok'}"><span class="who">${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>`};
function dealLog(d){const L=[[dd(addDays(d.load,-3))+' · '+STAFF[d.cur],'Заявка от клиента: '+route(d)],[dd(addDays(d.load,-2))+' · '+STAFF[d.lg],'Найдена машина: '+DR(d.dr).n+', '+DR(d.dr).truck]];
 if(d.cc)L.push([dd(addDays(d.load,-2))+' · Жанна','Договор-заявка с клиентом — подписан']);if(d.cd)L.push([dd(addDays(d.load,-1))+' · Жанна','Договор-заявка с водителем — фото бумажного договора']);else if(STI(d.st)>=1)L.push(['сейчас','Договора с водителем нет — карточка ждёт','bad']);
 if(d.paidC)L.push([dd(d.paidC)+' · банк','Клиент оплатил '+tg(d.c)+(d.paidD?'':' — '+tg(d.d)+' из них — деньги водителя')]);
 if(STI(d.st)>=2)L.push([dd(d.load),'Погрузка']);if(STI(d.st)>=3)L.push([dd(addDays(d.load,1)),'В пути — геолокация клиенту отправлена']);if(STI(d.st)>=4)L.push([dd(d.unl),'Выгрузка']);if(STI(d.st)>=5)L.push([dd(addDays(d.unl,1)),'Документы: '+d.docs.filter(Boolean).length+' из 6']);
 if(d.paidD)L.push(['закрыто','Водителю оплачено, комиссия разложена по фондам']);return L.concat(d.log)}
function nextBlock(d){const n=ST[STI(d.st)+1];if(!n)return '';if(n.k==='load'&&!d.ok)return !d.cd?'нет подписанного договора-заявки с водителем':!d.cc?'нет договора-заявки с клиентом':'офис-менеджер ещё не поставил галочку «согласовано»';
 if(n.k==='pay'&&!drvDocsOk(d))return 'нет документов от перевозчика: '+DOCN.filter((x,i)=>i>2&&!d.docs[i]).join(', ');if(STI(d.st)>=1&&STI(d.st)<4&&!d.ok&&n.k!=='load')return 'нет галочки «согласовано» — договоры не сданы';return ''}
function nextSt(id){const d=DL(id);const b=nextBlock(d);if(b){toast('Карточка не двигается: '+b+'.');beep();return}d.st=ST[STI(d.st)+1].k;d.log.push(['сейчас · '+ROLES[role].n,'Статус: '+STN(d.st).n]);render();toast(`${d.id} → «${STN(d.st).n}».`+(d.st==='unl'?' Водителю и бухгалтеру напомнили про документы.':''))}
function payDrv(id){const d=DL(id);d.paidD=true;d.st='done';if(d.paidC){const N=net(d);FUNDS.vat+=vat(d);FUNDS.staff+=N*RULES[0].p/100;FUNDS.tax+=N*RULES[1].p/100;FUNDS.fix+=N*RULES[2].p/100}BANK.open-=d.d;render();toast(`Водителю ${DR(d.dr).n} оплачено ${tg(d.d)}. Комиссия ${tg(com(d))} разложена по фондам.`)}
function paidC(id){const d=DL(id);d.paidC=TODAY;BANK.open+=d.c;render();toast(`Оплата от ${CL(d.cl).n}: ${tg(d.c)}. Из них ${tg(d.d)} — деньги водителя, система держит их отдельно.`)}
function togC(id,k){if(!['Руководитель','Офис-менеджер'].includes(role)){toast('Договоры отмечает офис-менеджер.');return}const d=DL(id);d[k]=!d[k];if(!d.cc||!d.cd)d.ok=false;render()}
function setOk(id){if(!['Руководитель','Офис-менеджер'].includes(role)){toast('Галочку «согласовано» ставит офис-менеджер.');return}const d=DL(id);if(!d.ok&&(!d.cc||!d.cd)){toast('Сначала оба договора-заявки: с клиентом и с водителем.');return}d.ok=!d.ok;render();toast(d.ok?`${d.id} согласовано — карточку можно двигать.`:'Галочка снята.')}
function togDoc(id,i){const d=DL(id);d.docs[i]=d.docs[i]?0:1;render()}
function setNds(id,v){const d=DL(id);d.nds=!!v;render();toast(v?'Счёт и ЭСФ — с НДС 12 %.':'Счёт без НДС.')}

SC.check=()=>{const Q=DEALS.filter(d=>!d.ok&&d.st!=='done');const okd=DEALS.filter(d=>d.ok&&['load','road'].includes(d.st));
 return `<div class="hd"><div><h2>Проверка договоров</h2><p>Очередь офис-менеджера: новые заявки и всё, где не хватает подписанного договора-заявки. Проверила — поставила галочку прямо здесь, без отдельного «согласовать».</p></div></div>
 <div class="wid"><div><small>Ждут проверки</small><b class="w">${Q.length}</b><span>карточек</span></div><div><small>Грузятся без договора</small><b class="r">${Q.filter(d=>['load','road'].includes(d.st)).length}</b><span>красный флаг</span></div><div><small>Согласовано в работе</small><b class="g">${okd.length}</b><span>погрузка и в пути</span></div><div><small>В сентябре</small><b>179</b><span>договоров с водителями</span></div><div><small>Без договора в сентябре</small><b class="g">0</b><span>правило работает</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Рейс</th><th>Статус</th><th>Клиент</th><th>Водитель</th><th>Логист</th><th>С клиентом</th><th>С водителем</th><th>Согласовано</th></tr></thead><tbody>
 ${Q.map(d=>`<tr class="${['load','road'].includes(d.st)?'rowbad':''}"><td><b class="lk" onclick="openDeal('${d.id}')">${d.id}</b><div class="sub">${route(d)} · ${dd(d.load)}</div></td><td>${stg(d.st)}</td><td>${esc(CL(d.cl).n)}</td><td>${esc(DR(d.dr).n)} ${fl(DR(d.dr).f)}</td><td>${STAFF[d.lg]}</td><td><span class="bx ${d.cc?'on':''}" onclick="togC('${d.id}','cc')">${d.cc?'✓':''}</span></td><td><span class="bx ${d.cd?'on':''}" onclick="togC('${d.id}','cd')">${d.cd?'✓':''}</span></td><td><span class="bx big ${d.ok?'on':''}" onclick="setOk('${d.id}')">${d.ok?'✓':''}</span></td></tr>`).join('')}</tbody></table></div>
 <div class="note"><b>Водители и электронная подпись</b><p>Не используем: водитель подписывает бумагу, логист фотографирует, фото прикрепляется к карточке. Клиенты, которым удобно, подписывают договор-заявку по ссылке.</p></div>
 ${said('«Не обязательно ей нажимать „согласовать“ — она просто эти карточки проверяет и в той же карточке ставит галочку „согласовала“» · «Водителю ссылку скидываешь — он: вы что, на меня кредит хотите оформить?»')}`};

SC.docs=()=>{const L=myDeals().filter(d=>STI(d.st)>=4);
 return `<div class="hd"><div><h2>Документы по рейсам</h2><p>На каждый рейс — шесть документов: три мы выставляем клиенту, три получаем от водителя. Пустая клетка — то, что надо сделать или запросить. Клик по клетке — отметить.</p></div><div class="btns"><button class="bt" onclick="act('esfall')">Выписать ЭСФ пачкой</button></div></div>
 <div class="tw"><table class="t dm"><thead><tr><th>Рейс</th><th>Статус</th>${DOCN.map((n,i)=>`<th class="c ${i===3?'bl':''}">${n.replace(' клиенту','').replace(' от перевозчика','')}<span>${i<3?'клиенту':'от водителя'}</span></th>`).join('')}<th>НДС</th></tr></thead><tbody>
 ${L.map(d=>`<tr><td><b class="lk" onclick="openDeal('${d.id}')">${d.id}</b><div class="sub">${esc(CL(d.cl).n)} · ${esc(DR(d.dr).n)}</div></td><td>${stg(d.st)}</td>${d.docs.map((x,i)=>`<td class="c ${i===3?'bl':''}"><span class="dc ${x?'on':''}" onclick="togDoc('${d.id}',${i})">${x?'✓':'—'}</span></td>`).join('')}<td>${d.nds?'<span class="tag">12 %</span>':'<span class="tag a">без</span>'}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2"><div class="note"><b>С НДС или без — переключатель в карточке</b><p>Счёт, АВР и ЭСФ собираются из карточки: клиент, ставка, маршрут, машина. ИП и ТОО, с НДС и без — шаблон подставляется сам, вручную ничего не перебивается.</p></div>
 <div class="note" style="--tone:var(--warn)"><b>Акт сверки</b><p>Раз в месяц по клиенту — из «Кто должен» или из карточки клиента.</p></div></div>
 ${said('«На один маршрут выписываем шесть документов: счёт на оплату, акт сверки, акт выполненных работ и электронный счёт-фактуру для налоговой» · «То с НДС, то без НДС — очень много времени занимает».')}`};

SC.buh=()=>{const pay=DEALS.filter(d=>d.st==='pay'&&!d.paidD);const wait=DEALS.filter(d=>['unl','docs'].includes(d.st)&&!d.paidD);const inv=DEALS.filter(d=>afterUnl(d)&&(!d.docs[0]||!d.docs[1]||!d.docs[2]));
 return `<div class="hd"><div><h2>Кабинет бухгалтера</h2><p>Бухгалтер на аутсорсе открывает один экран вместо пятисот сообщений в WhatsApp: кому платить сегодня, что выставить клиентам, какие документы запросить у водителей. 1С не подключаем — она закрывает у себя, здесь только видит.</p></div></div>
 <div class="g2">
  <div class="pan"><h3>Оплатить водителям сегодня · ${tg(pay.reduce((a,d)=>a+d.d,0))}</h3>${pay.map(d=>`<div class="pr"><div><b class="lk" onclick="openDeal('${d.id}')">${d.id} · ${esc(DR(d.dr).ip)}</b><span>${route(d)} · документы 3 из 3 · ${d.paidC?'клиент оплатил '+dd(d.paidC):'клиент ещё не оплатил'}</span></div><b class="mono">${fmt(d.d)}</b><button class="bt sm p" onclick="payDrv('${d.id}')">Оплачено</button></div>`).join('')||'<p class="mini">Сегодня оплат нет.</p>'}</div>
  <div class="pan"><h3>Ждут документов от водителей</h3>${wait.map(d=>`<div class="pr"><div><b class="lk" onclick="openDeal('${d.id}')">${d.id} · ${esc(DR(d.dr).n)}</b><span>нет: ${DOCN.filter((x,i)=>i>2&&!d.docs[i]).map(x=>x.replace(' от перевозчика','')).join(', ')||'—'}</span></div><button class="bt sm" onclick="act('askdocs','${d.dr}')">Запросить</button></div>`).join('')}</div>
 </div>
 <div class="pan"><h3>Выставить клиентам</h3><div class="tw"><table class="t"><thead><tr><th>Рейс</th><th>Клиент</th><th>НДС</th><th>Счёт</th><th>АВР</th><th>ЭСФ</th><th class="r">Сумма</th></tr></thead><tbody>${inv.map(d=>`<tr><td class="lk" onclick="openDeal('${d.id}')">${d.id}</td><td>${esc(CL(d.cl).n)}</td><td>${d.nds?'с НДС':'без'}</td>${[0,1,2].map(i=>`<td><span class="dc ${d.docs[i]?'on':''}" onclick="togDoc('${d.id}',${i})">${d.docs[i]?'✓':'—'}</span></td>`).join('')}<td class="r mono">${fmt(d.c)}</td></tr>`).join('')}</tbody></table></div></div>
 ${said('«Бухгалтер пусть сам сидит у себя, закрывает — не надо завязывать. Чтоб она этим дашбордом тоже… а то пятьсот переписок, с WhatsApp на WhatsApp».')}`};
