
/* ===== Команда ===== */
const tdue=t=>t.due.slice(8,10)+'.'+t.due.slice(5,7)+' '+t.due.slice(11);
const lateH=t=>Math.max(1,Math.round((new Date(TODAY+'T'+NOW+':00Z')-new Date(t.due.replace(' ','T')+':00Z'))/36e5));
SC.tasks=()=>{const T=role==='Руководитель'?TASKS:TASKS.filter(t=>t.who===ROLES[role].p);const who=[...new Set(T.map(t=>t.who))];
 return `<div class="hd"><div><h2>Задачи и красные флаги</h2><p>Каждая задача — со сроком. Не отработал вовремя — красный флаг, руководителю уведомление, а у сотрудника закрывается его дашборд: свой заработок и цифры он не увидит, пока не напишет, что сделал.</p></div><div class="btns">${role==='Руководитель'?`<button class="bt p" onclick="card('task')">+ Задача</button>`:''}</div></div>
 <div class="wid"><div><small>Открыто</small><b>${T.filter(t=>!t.ok).length}</b><span>задач</span></div><div><small>Просрочено</small><b class="r blink">${T.filter(overdue).length}</b><span>красный флаг</span></div><div><small>Дашборд закрыт</small><b class="r">${[...new Set(T.filter(overdue).map(t=>t.who))].map(k=>STAFF[k]).join(', ')||'—'}</b><span>до отработки</span></div><div><small>Отработано в срок</small><b class="g">87 %</b><span>за сентябрь</span></div><div><small>Утро и вечер</small><b>09:30 · 18:30</b><span>сбор по задачам</span></div></div>
 ${who.map(k=>`<div class="pan"><h3>${STAFF[k]}${T.some(t=>t.who===k&&overdue(t))?' <span class="tag r">дашборд закрыт</span>':''}</h3>${T.filter(t=>t.who===k).map(t=>`<div class="tk ${t.ok?'done':overdue(t)?'over':''}"><i></i><div><b>${esc(t.t)}</b><span>срок ${tdue(t)} · поставил ${STAFF[t.by]}${t.deal?` · <a class="lk" onclick="openDeal('${t.deal}')">${t.deal}</a>`:''}${overdue(t)?` · <em>просрочено ${lateH(t)} ч</em>`:''}${t.res?` · ${esc(t.res)}`:''}</span></div>${t.ok?'<span class="tag g">отработано</span>':`<button class="bt sm ${overdue(t)?'p':''}" onclick="card('done','${t.id}')">Отработал</button>`}</div>`).join('')}</div>`).join('')}
 ${said('«Если он по задаче не даст обратную связь, не отработает — у меня всё это должно ребром стоять, ред флаг» · «Заходит в приложение — дашборд не открывается, блок стоит: невыполненная задача. Отработал — доступ включается».','Привязку к начислению зарплаты продумаем вместе на шлифовке.')}`};
function doneTask(id){const t=TASKS.find(x=>x.id===id);const v=(document.getElementById('dn_r')||{}).value||'';if(v.trim().length<5){toast('Напишите коротко, что сделали — иначе задача не закроется.');return}t.ok=1;t.res=v.trim();closeM();render();toast(`Задача закрыта. Дашборд ${STAFF[t.who]} снова открыт.`)}

const ALERTS=[
 {lv:'bad',t:'Андрей Литвинов на выгрузке (R-1013) — ждёт оплату, документов нет',at:'10:12',go:"openDeal('R-1013')"},
 {lv:'bad',t:'R-1017 грузится без договора-заявки с водителем',at:'09:55',go:"openDeal('R-1017')"},
 {lv:'bad',t:'Задача Данияра просрочена — его дашборд закрыт',at:'09:00',go:"go('tasks')"},
 {lv:'warn',t:'Сегодня оплатить водителям 4 795 000 ₸ — по R-1012 и R-1006 не хватает документов',at:'09:00',go:"go('buh')"},
 {lv:'warn',t:'«Бәйтерек Мебель» не оплатил 2 600 000 ₸ — водителю заплатили своими 20.09',at:'09:00',go:"go('debts')"},
 {lv:'info',t:'Понедельник: план недели и переводы по фондам готовы',at:'08:00',go:"go('funds')"},
 {lv:'ok',t:'«Каспий Агро» оплатил 640 000 ₸ — комиссия разложена по фондам',at:'вчера',go:"go('money')"}
];
const ASET={snd:1,blink:1,push:1,night:1};
SC.alerts=()=>`<div class="hd"><div><h2>Уведомления</h2><p>Не колокольчик, который никто не открывает: важное мигает красным сверху, пищит и приходит пуш на телефон. Пока не отреагировал — горит.</p></div><div class="btns"><button class="bt p" onclick="beep();flash();toast('Так звучит и мигает красное уведомление.')">Проверить звук и мигание</button></div></div>
 <div class="g21"><div class="pan">${ALERTS.map(a=>`<div class="al ${a.lv}" onclick="${a.go}"><i></i><div><b>${esc(a.t)}</b><span>${a.at}</span></div></div>`).join('')}</div>
 <div class="pan"><h3>Как приходит</h3>${[['snd','Звук на компьютере и телефоне'],['blink','Мигает красным в шапке, пока не открыли'],['push','Пуш на телефон — даже если приложение закрыто'],['night','Ночью тоже — у вас звонят и в 2 часа']].map(([k,n])=>`<div class="srow"><span class="nm">${n}</span><span class="sw ${ASET[k]?'on':''}" onclick="ASET['${k}']=ASET['${k}']?0:1;render()"></span></div>`).join('')}
  <h3 style="margin-top:16px">Кому что</h3>${[['Руководителю','все красные, оплаты клиентов, кассовый разрыв'],['Логисту','его рейсы: выгрузка, документы, задачи'],['Куратору','оплаты и просрочки его клиентов'],['Офис-менеджеру','новые заявки без договоров'],['Бухгалтеру','к оплате водителям, документы']].map(x=>`<div class="kv"><span>${x[0]}</span><b class="mini">${x[1]}</b></div>`).join('')}</div></div>
 <div class="note" style="--tone:var(--muted)"><b>Чатов и чат-бота нет — специально</b><p>Клиенты звонят логисту напрямую, ночью — и это правильно для тендерных грузов. Переписку в систему не тянем; звонок фиксируется задачей или заметкой в карточке.</p></div>
 ${said('«Нужны уведомления, чтобы прямо моргали, пикали, горели» · «Чат-бот? Клиент пошлёт — товар на тендер на пятнадцать миллионов едет, а ему робот отвечает».')}`;

SC.my=()=>{const me=role==='Куратор'?'AS':'DN';const T=TASKS.filter(t=>t.who===me&&!t.ok);const od=T.filter(overdue);const k=KPI.find(x=>x.k===me);
 const L=DEALS.filter(d=>(me==='AS'?d.cur:d.lg)===me&&d.st!=='done');
 if(od.length)return `<div class="lockv"><div class="lk-ic">⊘</div><h2>Дашборд закрыт</h2><p>${STAFF[me]}, у вас просрочена задача. Свой заработок, план и цифры вы увидите, как только напишете, что сделали.</p>
  ${od.map(t=>`<div class="tk over"><i></i><div><b>${esc(t.t)}</b><span>срок ${tdue(t)} · просрочено ${lateH(t)} ч · поставил ${STAFF[t.by]}</span></div><button class="bt p" onclick="card('done','${t.id}')">Отработал — написать результат</button></div>`).join('')}
  <p class="mini">Перевозки и карточки при этом работают — закрыт только личный дашборд.</p>${role==='Руководитель'?'<p class="mini">Вы смотрите глазами логиста Данияра.</p>':''}</div>
 <div class="g3 locked">${[['Мой заработок за октябрь','30 % от чистой комиссии по моим рейсам, гарантия и бонус за план'],['План и выполнение','сколько фур и комиссии принёс компании и сколько осталось до 2,1 млн'],['Мои рейсы и задачи','список на сегодня: погрузки, выгрузки, документы, звонки клиентам']].map(x=>`<div class="pan"><h3>${x[0]}</h3><p class="mini">${x[1]}</p><div class="blur">●●● ●●● ₸</div></div>`).join('')}</div>`;
 return `<div class="hd"><div><h2>Мой день · ${STAFF[me]}</h2><p>Свои рейсы, задачи и заработок за месяц — без денег компании.</p></div></div>
 <div class="wid"><div><small>Мои рейсы в работе</small><b>${L.length}</b><span>${L.filter(d=>d.st==='road').length} в пути</span></div><div><small>Фур в октябре</small><b>11</b><span>за 5 дней</span></div><div><small>Принёс комиссии</small><b class="a">${fmt(640000)}</b><span>план ${mln(k?k.plan:2100000)}</span></div><div><small>Мой заработок</small><b class="g">${fmt(171400)}</b><span>30 % от чистой комиссии</span></div><div><small>Задачи</small><b>${T.length}</b><span>открыто</span></div></div>
 <div class="pan"><h3>Мои рейсы</h3>${L.map(d=>`<div class="pr clk" onclick="openDeal('${d.id}')"><div><b>${d.id} · ${route(d)}</b><span>${esc(CL(d.cl).n)} · ${esc(DR(d.dr).n)} · ${dd(d.load)} → ${dd(d.unl)}</span></div>${stg(d.st)}</div>`).join('')}</div>
 <div class="pan"><h3>Мои задачи</h3>${T.map(t=>`<div class="tk"><i></i><div><b>${esc(t.t)}</b><span>срок ${tdue(t)}</span></div><button class="bt sm" onclick="card('done','${t.id}')">Отработал</button></div>`).join('')||'<p class="mini">Всё отработано.</p>'}</div>`};

/* ===== Базы ===== */
let clF='all';
SC.clients=()=>{const L=CLIENTS.filter(c=>clF==='all'||c.f===clF);
 return `<div class="hd"><div><h2>Клиенты</h2><p>Карточка клиента с примечанием — чтобы любой логист понимал, на что готовиться: кто платит с задержкой, кто только по предоплате, кто ждёт геолокацию два раза в день.</p></div><div class="btns"><span class="seg"><a class="${clF==='all'?'on':''}" onclick="clF='all';render()">Все</a><a class="${clF==='warn'?'on':''}" onclick="clF='warn';render()">С пометкой</a><a class="${clF==='bad'?'on':''}" onclick="clF='bad';render()">Красные</a></span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Город</th><th>Куратор</th><th>Оплата</th><th>Примечание</th><th class="r">Рейсов</th><th class="r">Долг</th></tr></thead><tbody>
 ${L.map(c=>{const ds=DEALS.filter(d=>d.cl===c.id);const debt=ds.filter(d=>!d.paidC&&afterUnl(d)).reduce((a,d)=>a+d.c,0);return `<tr class="clk" onclick="card('cl','${c.id}')"><td><b>${esc(c.n)}</b> ${fl(c.f)}</td><td>${esc(c.city)}</td><td>${STAFF[c.cur]}</td><td>${c.term?c.term+' дн.':'предоплата'}</td><td class="mini nt">${esc(c.note)}</td><td class="r mono">${ds.length}</td><td class="r mono ${debt?'neg':''}">${debt?fmt(debt):'—'}</td></tr>`}).join('')}</tbody></table></div>
 ${said('«Чтоб клиентов все данные были, какие-то примечания… неплатёжеспособен или клиент нервный — мы так и пишем прям, чтоб понимать, на что готовиться».')}`};
let drQ='';
SC.drivers=()=>{const L=DRIVERS.filter(d=>!drQ||(d.n+d.ip+d.plate+d.routes).toLowerCase().includes(drQ.toLowerCase()));
 return `<div class="hd"><div><h2>Перевозчики · 1 512</h2><p>Вся база из Битрикса: контакты, ИП и реквизиты, машины, маршруты, сколько рейсов с вами и пометки. Логист ищет машину по направлению — и сразу видит, кому можно доверять.</p></div><div class="btns"><div class="srch in"><i>⌕</i><input placeholder="имя, госномер, направление" value="${esc(drQ)}" onkeydown="if(event.key==='Enter'){drQ=this.value;render()}"></div><button class="bt p" onclick="card('newdr')">+ Перевозчик</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Перевозчик</th><th>ИП / компания</th><th>Машина</th><th>Направления</th><th class="r">Рейсов</th><th>Пометка</th></tr></thead><tbody>
 ${L.map(d=>`<tr class="clk" onclick="card('dr','${d.id}')"><td><b>${esc(d.n)}</b> ${fl(d.f)}<div class="sub mono">${d.ph}</div></td><td>${esc(d.ip)}</td><td>${esc(d.truck)}<div class="sub mono">${esc(d.plate)}</div></td><td>${esc(d.routes)}</td><td class="r mono">${d.trips}</td><td class="mini nt">${d.note==='—'?'':esc(d.note)}</td></tr>`).join('')}
 <tr class="total"><td colspan="6">… ещё 1 500 перевозчиков из Битрикса — поиск по имени, номеру, направлению</td></tr></tbody></table></div>`};

SC.move=()=>`<div class="hd"><div><h2>Переезд с Битрикса</h2><p>Выгружаем из Битрикса всё, что нужно — перевозчиков, клиентов, историю сделок — и загружаем сюда. Дубли склеиваем, телефоны приводим к одному виду. Один-два дня, работа не останавливается.</p></div></div>
 <div class="mvs">${[['1','Выгрузка из Битрикса','контакты, компании, сделки — в Excel','ok'],['2','Сопоставление полей','«Госномер», «ИП», «Направления», пометки','ok'],['3','Проверка дублей','один водитель — одна карточка','on'],['4','Загрузка и сверка','вы смотрите, что всё на месте',''],['5','Битрикс отключаем','после недели параллельной работы','']].map(s=>`<div class="mv ${s[3]}"><i>${s[3]==='ok'?'✓':s[0]}</i><b>${s[1]}</b><span>${s[2]}</span></div>`).join('')}</div>
 <div class="wid"><div><small>Перевозчиков</small><b>1 512</b><span>38 дублей склеено</span></div><div><small>Клиентов</small><b>214</b><span>с реквизитами</span></div><div><small>Сделок за год</small><b>1 890</b><span>история и суммы</span></div><div><small>Битрикс + интегратор</small><b class="r">176 000</b><span>₸ в месяц сейчас</span></div><div><small>Экономия в год</small><b class="g">2,1 млн</b><span>после переезда</span></div></div>
 <div class="pan"><h3>Поля перевозчика: Битрикс → здесь</h3><div class="tw"><table class="t"><thead><tr><th>В Битриксе</th><th>Здесь</th><th>Пример</th></tr></thead><tbody>${[['Имя, Фамилия','Перевозчик','Серик Ахметов'],['Компания','ИП / компания','ИП «Ахметов С.»'],['Телефон рабочий','Телефон','+7 701 *** 41 18'],['UF_GOSNOMER','Госномер','512 ARA 01'],['UF_TRUCK','Машина и кузов','Volvo FH · тент 20 т'],['Комментарий','Пометка','«Надёжный, документы сдаёт сразу»']].map(r=>`<tr><td class="mono">${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div></div>
 ${said('«Я хочу от Битрикса уйти: у меня около полутора тысяч перевозчиков — все их контакты туда перекинуть и все данные фирмы» · «Восемьдесят восемь тысяч Битриксу и ещё восемьдесят восемь — посредникам, а они через раз отвечают».')}`;
