
/* ===== Система ===== */
SC.roles=()=>{const areas=[['Деньги на счёте, «моё / не моё», фонды',['AM']],['Календарь платежей',['AM','GM']],['Кто должен, акты сверки',['AM','AS','GM']],['Аналитика компании',['AM']],['Доска перевозок, карточки',['AM','DN','AS','ZH','GM']],['Галочка «согласовано»',['AM','ZH']],['Оплата водителю',['AM','GM']],['Документы по рейсам',['AM','AS','ZH','GM']],['Свой заработок и план',['AM','DN','AS']],['Базы клиентов и перевозчиков',['AM','DN','AS','ZH']]];const R=Object.entries(ROLES);
 return `<div class="hd"><div><h2>Роли и права</h2><p>Логисты не видят оборот денег и фонды — только свои рейсы и свой заработок. Бухгалтер на аутсорсе видит, кому платить и какие документы нужны. Права меняет руководитель.</p></div></div>
 <div class="tw"><table class="t mx"><thead><tr><th>Что видно</th>${R.map(([k,v])=>`<th class="c">${esc(v.av)}<span>${esc(k)}</span></th>`).join('')}</tr></thead><tbody>
 ${areas.map(a=>`<tr><td>${a[0]}</td>${R.map(([k,v])=>`<td class="c">${a[1].includes(v.p)?'<b class="pos">●</b>':'<span class="mini">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 <div class="g2">${R.map(([k,v])=>`<div class="pan"><h3>${esc(k)} · ${esc(v.n)}</h3><p class="mini">${esc(v.note)}</p><span class="mini">${v.s.length} ${plural(v.s.length,['экран','экрана','экранов'])}</span></div>`).join('')}</div>
 ${said('«Максимально всё в одном поместить, но доступ на определённые функции — чтобы логисты не видели мой оборот денег».')}`};
SC.mobile=()=>`<div class="hd"><div><h2>С телефона</h2><p>Ссылка сохраняется на экран телефона как приложение — из магазина ничего ставить не нужно. Пуш-уведомления приходят, даже когда приложение закрыто.</p></div></div>
 <div class="phones">
  <div class="phone"><div class="pht"><b>Амирбек</b><small>${dd(TODAY)} · ${NOW}</small></div><div class="pb"><div class="pi"><span>На счетах</span><b>${mln(BANK.open)}</b></div><div class="pi"><span>Не моё</span><b class="neg">${mln(notMine())}</b></div><div class="pi"><span>Моё свободно</span><b class="pos">${mln(freeMine())}</b></div><div class="pi"><span>Горит</span><b class="neg">${redFlags().length}</b></div><div class="pbtn" onclick="go('today')">Открыть пульт</div></div></div>
  <div class="phone"><div class="pht"><b>Данияр · логист</b><small>мои рейсы</small></div><div class="pb">${DEALS.filter(d=>d.lg==='DN'&&d.st!=='done').slice(0,4).map(d=>`<div class="pi"><span>${d.id} ${esc(d.from)} → ${esc(d.to)}<small>${STN(d.st).n}</small></span><b>${dd(d.unl)}</b></div>`).join('')}<div class="pbtn" onclick="act('photo')">Фото договора водителя</div></div></div>
  <div class="phone"><div class="pht"><b>Пуш-уведомление</b><small>экран блокировки</small></div><div class="pb"><div class="push"><b>ТРАССА · сейчас</b><span>Литвинов на выгрузке R-1013, ждёт оплату. Документов нет.</span></div><div class="push"><b>ТРАССА · 09:00</b><span>Сегодня водителям ${mln(DEALS.filter(d=>drvPayDay(d)===TODAY).reduce((a,d)=>a+d.d,0))} ₸.</span></div><div class="push"><b>ТРАССА · 08:00</b><span>План недели и переводы по фондам готовы.</span></div></div></div>
 </div>`;
SC.launch=()=>`<div class="hd"><div><h2>Запуск и стоимость</h2><p>Стандартный пакет разработки — 2 000 000 ₸ один раз, без абонентской платы. Ядро — за 2–3 недели, вся система — за 4–6 недель. В пакете заложено около 20 % на доработки, которые появятся, когда начнёте пользоваться.</p></div></div>
 <div class="pay3"><div><small>Старт · 10 %</small><b>200 000 ₸</b><span>собираем вашу первичку: таблицу, Битрикс, документы</span></div><div><small>Ядро · 45 %</small><b>900 000 ₸</b><span>после того, как вы приняли ядро — примерно через месяц</span></div><div><small>Шлифовка и сдача · 45 %</small><b>900 000 ₸</b><span>после приёмки всей системы</span></div></div>
 <div class="g2"><div class="pan"><h3>Ядро — первые 2–3 недели</h3>${['Перевозки вместо Битрикса: статусы, карточка, договоры-заявки, галочка офис-менеджера','Переезд базы: 1 500 перевозчиков, клиенты с пометками','«Мои и не мои деньги» и календарь платежей','Фонды по вашим процентам','Документы по рейсу: с НДС и без'].map(x=>`<div class="li"><i>✓</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Шлифовка — до сдачи</h3>${['Аналитика из вашей таблицы, план компании','Задачи со сроками и блок дашборда','Громкие уведомления и пуш на телефон','KPI логистов, кабинет бухгалтера','Ваши доработки по ходу — в пределах пакета'].map(x=>`<div class="li n"><i>→</i><span>${x}</span></div>`).join('')}</div></div>
 <div class="g2"><div class="pan"><h3>Не делаем — как договорились</h3><div class="li no"><i>—</i><span>Интеграция с 1С — бухгалтер закрывает у себя</span></div><div class="li no"><i>—</i><span>Чат с клиентами и чат-бот — клиенты звонят</span></div><div class="li no"><i>—</i><span>Электронная подпись водителям — фото бумажного договора</span></div></div>
 <div class="pan"><h3>После сдачи</h3><p class="mini">3 месяца сопровождения входят в стоимость. Дальше — доработки по часам, около 20 $ в час. Код и данные — ваши. Битрикс и интегратор (176 000 ₸ в месяц) больше не нужны — за год это 2,1 млн ₸.</p></div></div>
 ${said('«Мне важно понимать, сколько это будет по деньгам, по времени — чтобы не получилось, что сейчас бум-бум, а в конце: и дорого».','Платон: стандартный пакет, 4–6 недель, в районе двух миллионов; 10 % в начале, остальное — по факту: после ядра и после шлифовки.')}`;

/* ===== Карточки ===== */
const CARD={};
CARD.day=day=>{const P=projection()[day];const lbl={in:'Придёт от клиента',out:'Водителю',fix:'Обязательный платёж',paid:'Оплачено',late:'Просрочено клиентом'};
 return [`${dd(day)} · ${dayOf(day)}`,P.bal!==null?`Остаток на конец дня: ${tg(P.bal)}`:'Прошедший день',P.E.length?`<div class="tw"><table class="t"><tbody>${P.E.map(e=>`<tr class="${e.deal?'clk':''}" ${e.deal?`onclick="closeM();openDeal('${e.deal}')"`:''}><td><span class="tag ${e.k==='in'?'g':e.k==='late'?'r':e.k==='paid'?'':'w'}">${lbl[e.k]}</span></td><td>${esc(e.n)}${e.ok?`<div class="sub">${e.ok}</div>`:''}${e.bx?'<div class="sub">уйдёт после переезда</div>':''}</td><td class="r mono">${e.k==='in'||e.k==='late'?'+':'−'} ${fmt(e.s)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="mini">В этот день платежей нет.</p>']};
CARD.fixnew=()=>['Новый платёж в календарь','Обязательный или личный',`<div class="form"><label>Что<input id="fx_n" value="Лизинг тягача"></label><label>Дата<input id="fx_d" type="date" value="2026-10-15" min="2026-10-01" max="2026-10-31"></label><label>Сумма, ₸<input id="fx_s" value="450000"></label><label>Из какого фонда<select id="fx_f"><option value="fix">Обязательные</option><option value="staff">Сотрудники</option><option value="tax">Налоги</option><option value="own">Моя прибыль</option></select></label></div><button class="bt p" onclick="const v=i=>document.getElementById(i).value;FIXED.push({d:v('fx_d'),n:v('fx_n'),s:+v('fx_s')||0,f:v('fx_f')});closeM();render();toast('Платёж добавлен — календарь пересчитан.')">Добавить</button>`];
CARD.cl=id=>{const c=CL(id);const ds=DEALS.filter(d=>d.cl===id);return [esc(c.n),`${esc(c.city)} · куратор ${STAFF[c.cur]} · ${c.term?'оплата через '+c.term+' дн.':'предоплата'}`,`<div class="pin ${c.f}" style="margin-top:0">${esc(c.note)}</div><div class="kv"><span>Телефон</span><b class="mono">${c.ph}</b></div><h4 class="mh4">Рейсы</h4>${ds.map(d=>`<div class="kv clk" onclick="closeM();openDeal('${d.id}')"><span>${d.id} · ${route(d)} · ${dd(d.load)}</span><b>${STN(d.st).n} · ${d.paidC?'оплачено':'<span class="neg">не оплачено</span>'}</b></div>`).join('')}<div class="btns l" style="margin-top:12px"><button class="bt" onclick="closeM();card('sverka','${id}')">Акт сверки</button><button class="bt" onclick="act('remind','${id}')">Напомнить об оплате</button></div>`]};
CARD.sverka=id=>{const c=CL(id);const ds=DEALS.filter(d=>d.cl===id&&afterUnl(d));let bal=0;return ['Акт сверки',`${esc(c.n)} · сентябрь – октябрь 2026`,`<div class="doc"><div class="dh"><div class="dlg">ТРАССА<small>ТРАНСПОРТНАЯ ЭКСПЕДИЦИЯ</small></div><div style="text-align:right;font-size:10px">${dl(TODAY)}</div></div><h4>Акт сверки взаимных расчётов</h4><div class="drow h"><span>Дата</span><span>Документ</span><span class="r">Начислено</span><span class="r">Оплачено</span></div>${ds.map(d=>{bal+=d.c-(d.paidC?d.c:0);return `<div class="drow"><span>${dd(d.unl)}</span><span>АВР · ${d.id} ${esc(d.from)} → ${esc(d.to)}</span><span class="r">${fmt(d.c)}</span><span class="r">${d.paidC?fmt(d.c):'—'}</span></div>`}).join('')}<div class="dsum"><span>Задолженность в пользу ТРАССА</span><span>${tg(bal)}</span></div></div><div class="btns l" style="margin-top:12px"><button class="bt p" onclick="closeM();toast('Акт сверки отправлен клиенту — PDF в WhatsApp куратора.')">Отправить клиенту</button></div>`]};
CARD.dr=id=>{const r=DR(id);const ds=DEALS.filter(d=>d.dr===id);return [esc(r.n),`${esc(r.ip)} · ${esc(r.truck)} · ${esc(r.plate)}`,`${r.note!=='—'?`<div class="pin ${r.f}" style="margin-top:0">${esc(r.note)}</div>`:''}${[['Телефон',r.ph],['Направления',esc(r.routes)],['Рейсов с вами',r.trips],['Реквизиты','ИИН / БИН, банк, счёт — из Битрикса']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<h4 class="mh4">Рейсы</h4>${ds.map(d=>`<div class="kv clk" onclick="closeM();openDeal('${d.id}')"><span>${d.id} · ${route(d)}</span><b>${STN(d.st).n} · ${d.paidD?'оплачено':'не оплачено'}</b></div>`).join('')||'<p class="mini">Сейчас рейсов нет.</p>'}`]};
CARD.newdr=()=>['Новый перевозчик','Попадёт в базу, логисты найдут по направлению',`<div class="form"><label>Имя<input id="nd_n" value="Ерболат Сейткали"></label><label>ИП<input id="nd_ip" value="ИП «Сейткали Е.»"></label><label>Машина<input id="nd_t" value="Volvo FH · тент 20 т"></label><label>Госномер<input id="nd_p" value="771 ESK 01"></label><label>Направления<input id="nd_r" value="Россия ↔ Казахстан"></label><label>Пометка<select id="nd_f"><option value="ok">без пометки</option><option value="warn">с пометкой</option><option value="bad">красная</option></select></label></div><button class="bt p" onclick="const v=i=>document.getElementById(i).value;DRIVERS.unshift({id:'D'+(DRIVERS.length+1),n:v('nd_n'),ip:v('nd_ip'),ph:'+7 7** *** ** **',truck:v('nd_t'),plate:v('nd_p'),routes:v('nd_r'),trips:0,f:v('nd_f'),note:'—'});closeM();render();toast('Перевозчик добавлен.')">Добавить</button>`];
CARD.inv=id=>{const d=DL(id);const c=CL(d.cl);const V=d.nds?Math.round(d.c*12/112):0;return ['Счёт на оплату',`${d.id} · ${esc(c.n)} · ${d.nds?'с НДС':'без НДС'}`,`<div class="doc"><div class="dh"><div class="dlg">ТРАССА<small>ТРАНСПОРТНАЯ ЭКСПЕДИЦИЯ</small></div><div style="text-align:right;font-size:10px">Счёт № ${700+DEALS.indexOf(d)}<br>${dl(TODAY)}</div></div><h4>Счёт на оплату</h4><p style="font-size:11px">Покупатель: ${esc(c.n)}</p><div class="drow h"><span>№</span><span>Услуга</span><span class="r">Кол-во</span><span class="r">Сумма, ₸</span></div><div class="drow"><span>1</span><span>Транспортно-экспедиционные услуги: ${esc(d.from)} → ${esc(d.to)}, ${esc(DR(d.dr).truck)}, ${esc(DR(d.dr).plate)}</span><span class="r">1</span><span class="r">${fmt(d.c)}</span></div><div class="dsum"><span>Итого${d.nds?', в т. ч. НДС 12 %':''}</span><span>${tg(d.c)}${d.nds?' · НДС '+fmt(V):''}</span></div><div class="dfoot"><span>${c.term?'Оплата в течение '+c.term+' дней после выгрузки.':'Предоплата 100 %.'}</span></div></div><div class="btns l" style="margin-top:12px"><button class="bt p" onclick="closeM();DL('${id}').docs[0]=1;render();toast('Счёт отправлен клиенту, отметка в документах рейса.')">Отправить клиенту</button><button class="bt" onclick="setNds('${id}',${d.nds?0:1});card('inv','${id}')">${d.nds?'Без НДС':'С НДС'}</button></div>`]};
CARD.newdeal=()=>['Новая перевозка','Заявка клиента → поиск машины',`<div class="form"><label>Клиент<select id="nw_c">${CLIENTS.map(c=>`<option value="${c.id}">${esc(c.n)}${c.f==='bad'?' — только предоплата':''}</option>`).join('')}</select></label><label>Откуда<input id="nw_f" value="Астана"></label><label>Куда<input id="nw_t" value="Караганда"></label><label>Погрузка<input id="nw_d" type="date" value="2026-10-07"></label><label>Ставка клиента, ₸<input id="nw_cr" value="200000"></label><label>Ставка водителю, ₸<input id="nw_dr" value="165000"></label><label>Водитель<select id="nw_dv">${DRIVERS.map(d=>`<option value="${d.id}">${esc(d.n)}${d.f==='bad'?' — красная пометка':''}</option>`).join('')}</select></label><label>НДС<select id="nw_n"><option value="1">с НДС</option><option value="0">без НДС</option></select></label></div><button class="bt p" onclick="newDeal()">Создать</button>`];
function newDeal(){const v=i=>document.getElementById(i).value;const id='R-'+(1025+DEALS.length-24);const c=v('nw_c');DEALS.unshift({id,cl:c,dr:v('nw_dv'),from:v('nw_f'),to:v('nw_t'),intl:false,c:+v('nw_cr')||0,d:+v('nw_dr')||0,nds:v('nw_n')==='1',lg:role==='Логист'?'DN':'TM',cur:CL(c).cur,st:'new',load:v('nw_d'),unl:addDays(v('nw_d'),1),paidC:null,paidD:false,cc:false,cd:false,ok:false,docs:[0,0,0,0,0,0],log:[]});closeM();curDeal=id;go('deal');toast(`${id} создана. Офис-менеджер видит её в «Проверке договоров».`+(CL(c).f==='bad'?' Клиент с красной пометкой — руководителю ушло уведомление.':''))}
CARD.task=()=>['Новая задача','Со сроком — не отработал вовремя, дашборд закроется',`<div class="form"><label>Кому<select id="tk_w">${['DN','TM','MD','BK','AS','KR','ZH','GM'].map(k=>`<option value="${k}">${STAFF[k]}</option>`).join('')}</select></label><label>Что сделать<input id="tk_t" value="Перезвонить «Темір Снаб» по оплате R-1010"></label><label>Срок<input id="tk_d" value="2026-10-05 16:00"></label></div><button class="bt p" onclick="const v=i=>document.getElementById(i).value;TASKS.unshift({id:'T'+(TASKS.length+1),who:v('tk_w'),t:v('tk_t'),due:v('tk_d'),ok:0,by:'AM'});closeM();render();toast('Задача поставлена — сотруднику пришёл пуш.')">Поставить</button>`];
CARD.done=id=>{const t=TASKS.find(x=>x.id===id);return ['Отработал задачу',esc(t.t),`<div class="form"><label>Что сделано — коротко<input id="dn_r" placeholder="Позвонил, груз в Омске, геолокацию скинул"></label></div><button class="bt p" onclick="doneTask('${id}')">Закрыть задачу</button>`]};
function card(k,id){const f=CARD[k];if(!f)return;let r;try{r=f(id)}catch(e){toast('Карточка не найдена');return}openM(r[0],r[1],r[2])}
function act(k,x){const M={report:'Каждый вечер в 19:00 в WhatsApp: на счёте, моё свободно, кому платили, кто должен, что горит.',remind:'Напоминание об оплате ушло клиенту, куратору — задача перезвонить завтра в 10:00.',remindall:'Напоминания ушли всем просроченным; кураторам — задачи по каждому.',xls:'Выгрузка в Excel — в том же виде, что ваша таблица.',esfall:'ЭСФ по всем рейсам с полными документами — пачкой в ИС ЭСФ.',askdocs:'Водителю позвонить: логисту поставлена задача «запросить документы» до 18:00.',photo:'Камера телефона: фото подписанного договора сразу в карточку рейса.'};toast(M[k]||'Готово.')}
function searchDemo(v){if(!v)return;const q=v.toLowerCase().trim();const d=DEALS.find(x=>(x.id+' '+x.from+' '+x.to).toLowerCase().includes(q));if(d&&allowed('deal')){openDeal(d.id);return}
 const c=CLIENTS.find(x=>x.n.toLowerCase().includes(q));if(c){card('cl',c.id);return}const r=DRIVERS.find(x=>(x.n+x.plate).toLowerCase().includes(q));if(r){card('dr',r.id);return}toast('Не найдено: попробуйте «R-1013», «Москва», «Евразия», «Ким».')}

/* ===== Каркас ===== */
function renderRoles(){const r=document.getElementById('roles');if(r)r.innerHTML=Object.entries(ROLES).map(([k,v])=>`<div class="role" onclick="enter('${esc(k)}')"><div class="rav">${esc(v.av)}</div><div><b>${esc(k)}</b><span>${esc(v.n)} · ${esc(v.note)}</span></div></div>`).join('');
 const s=document.getElementById('rsel');if(s)s.innerHTML=Object.keys(ROLES).map(k=>`<option value="${esc(k)}">${esc(k)}</option>`).join('');}
const allowed=k=>ROLES[role].s.indexOf(k)>=0;
function enter(k){role=ROLES[k]?k:'Руководитель';document.getElementById('gate').classList.add('hidden');document.getElementById('app').classList.remove('hidden');const s=document.getElementById('rsel');if(s)s.value=role;document.getElementById('me').textContent=ROLES[role].av;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Вы вошли как «${esc(role)}» · ${esc(ROLES[role].n)}.`)}
function switchRole(k){role=k;document.getElementById('me').textContent=ROLES[role].av;const s=document.getElementById('rsel');if(s)s.value=role;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Роль: ${esc(role)}. ${esc(ROLES[role].note)}.`)}
function buildRail(){const on=SECOF[cur];document.getElementById('rail').innerHTML=SEC.filter(s=>s.sub.some(x=>allowed(x[0]))).map(s=>`<a class="ri ${s.k===on?'on':''}" onclick="go('${s.sub.filter(x=>allowed(x[0]))[0][0]}')"><i><svg viewBox="0 0 24 24">${s.ic}</svg></i><span>${s.n}</span>${s.k==='team'&&TASKS.some(overdue)?'<b class="cnt">!</b>':''}</a>`).join('')}
function buildSub(){const s=SEC.find(x=>x.k===SECOF[cur]);document.getElementById('sub').innerHTML=`<h4>${s.n}</h4>`+s.sub.filter(x=>allowed(x[0])).map(x=>`<a class="${x[0]===cur?'on':''}" onclick="go('${x[0]}')">${esc(x[1])}</a>`).join('')+(s.k==='own'?`<div class="shint">Логисты и кураторы этого раздела не видят.</div>`:'')}
function buildMbar(){const el=document.getElementById('mbar');if(!el)return;if(!allowed('money')){el.innerHTML='';el.style.display='none';return}el.style.display='';el.innerHTML=`<span class="lb">НА СЧЕТАХ</span><b>${tg(BANK.open)}</b><span class="sp"></span><span>водителям <b class="g1">${mln(heldDrv())}</b></span><span>фонды и НДС <b class="g2">${mln(fundsSum()+heldCom())}</b></span><span class="mine">моё свободно <b>${mln(freeMine())}</b></span>`}
function buildBell(){const b=document.getElementById('bell');if(!b)return;const n=ALERTS.filter(a=>a.lv==='bad').length;b.innerHTML=`<svg viewBox="0 0 24 24"><path d="M6 16V11a6 6 0 0 1 12 0v5l2 2H4z M10 20a2 2 0 0 0 4 0"/></svg><b>${n}</b>`;b.classList.toggle('hot',n>0&&ASET.blink)}
function build(){buildRail();buildSub();render()}
function render(){const f=SC[cur]||SC.today;document.body.dataset.sec=SECOF[cur];document.getElementById('ttl').textContent=SUBN[cur]||'Трасса';document.getElementById('content').innerHTML=`<div class="screen">${f()}</div>`;buildSub();buildRail();buildMbar();buildBell();
 const a=document.getElementById('addBtn');if(a)a.style.display=allowed('board')&&role!=='Бухгалтер'?'':'none';try{history.replaceState(null,'','?s='+cur+(cur==='deal'?'&d='+curDeal:''))}catch(e){}}
function go(k){if(!allowed(k)){toast('Этой роли раздел недоступен — так работают права. Переключите роль справа вверху.');return}cur=k;build();const c=document.querySelector('.content');if(c)c.scrollTop=0}
function openM(t,s,b){document.getElementById('mt').innerHTML=t;document.getElementById('ms').innerHTML=s;document.getElementById('mbody').innerHTML=b;document.getElementById('mbg').classList.add('show');document.querySelector('.modal').scrollTop=0}
function closeM(){document.getElementById('mbg').classList.remove('show')}
let tt=null;function toast(m){const t=document.getElementById('toast');t.innerHTML=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),6400)}
function beep(){if(!ASET.snd)return;try{const A=new(window.AudioContext||window.webkitAudioContext)();[0,.22].forEach(s=>{const o=A.createOscillator(),g=A.createGain();o.frequency.value=880;o.connect(g);g.connect(A.destination);g.gain.setValueAtTime(.15,A.currentTime+s);g.gain.exponentialRampToValueAtTime(.001,A.currentTime+s+.18);o.start(A.currentTime+s);o.stop(A.currentTime+s+.2)})}catch(e){}}
function flash(){document.body.classList.remove('flash');void document.body.offsetWidth;document.body.classList.add('flash')}
function applyTheme(){document.body.classList.toggle('dark',theme==='dark')}
function toggleTheme(){theme=theme==='dark'?'light':'dark';applyTheme();toast(theme==='dark'?'Тёмная тема.':'Светлая тема.')}

const TOUR=[
 ['today','1 · Пульт: сколько на счетах и сколько из этого ваше. Кому платить сегодня, что горит, ближайшие дни.'],
 ['money','2 · Мои и не мои деньги: деньги водителей по оплаченным рейсам, комиссия, НДС, фонды — и только потом ваше свободное.'],
 ['calendar','3 · Календарь платежей: что придёт, что уйдёт, остаток на каждый день. Красный день видно заранее.'],
 ['funds','4 · Фонды по вашим процентам и план недели: сколько и куда перевести в понедельник.'],
 ['debts','5 · Кто должен: по каждому долгу — сколько водителям, сколько ваша комиссия, просрочка, куратор.'],
 ['board','6 · Перевозки вместо Битрикса: те же статусы, карточка не двигается без договоров и документов.'],
 ['deal','7 · Карточка: клиент и водитель с пометками, ставки, с НДС или без, договоры, шесть документов.'],
 ['check','8 · Офис-менеджер: очередь договоров, галочка «согласовано» прямо в строке.'],
 ['docs','9 · Документы по рейсам: что выставить клиенту и что запросить у водителя.'],
 ['tasks','10 · Задачи со сроками: просрочил — красный флаг и закрытый дашборд.'],
 ['my','11 · Так видит логист: пока не отработал задачу — свой заработок не открывается.'],
 ['alerts','12 · Уведомления, которые мигают и пищат, — и пуш на телефон.'],
 ['kpi','13 · KPI логистов: сколько принёс компании и сколько заработал сам.'],
 ['analytics','14 · Аналитика из вашей таблицы: месяцы, клиенты, логисты, международные и внутренние.'],
 ['move','15 · Переезд с Битрикса: 1 500 перевозчиков и клиенты за один-два дня.'],
 ['launch','16 · Стоимость: 2 млн один раз, 10 / 45 / 45, ядро за 2–3 недели.']
];
let ti=-1,tRun=false;
function tour(){if(tRun){stopTour();return}tRun=true;ti=-1;document.getElementById('tourBtn').textContent='■';step()}
function step(){if(!tRun)return;ti++;if(ti>=TOUR.length){stopTour();toast('Сценарий закончен. Всё кликается: карточки, галочки, документы, задачи, фонды.');return}const [k,m]=TOUR[ti];if(!allowed(k)){step();return}cur=k;if(k==='deal')curDeal='R-1017';build();toast(m);setTimeout(step,ti===0?6500:7200)}
function stopTour(){tRun=false;ti=-1;const b=document.getElementById('tourBtn');if(b)b.textContent='▶'}
(function(){renderRoles();applyTheme();const s=document.getElementById('rsel');if(s)s.addEventListener('change',e=>switchRole(e.target.value));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeM();stopTour()}});
 let q='',d='';try{const u=new URLSearchParams(location.search);q=u.get('s')||'';d=u.get('d')||''}catch(e){}if(d&&DL(d))curDeal=d;
 if(q&&SECOF[q]){const r=Object.keys(ROLES).find(k=>ROLES[k].s.indexOf(q)>=0);if(r){cur=q;enter(r)}}})();
