const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map(),listeners={};const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',style:{},showModal(){this.open=true},close(){this.open=false},addEventListener(){}});return elements.get(id)};
const context={console,URL,URLSearchParams,Intl,Date,Number,Math,JSON,Blob,setTimeout:()=>{},history:{replaceState(){}},location:{href:'http://localhost/app/megatex.html',search:''},localStorage:{getItem(){return null},setItem(){}},document:{querySelector:element,addEventListener:(n,f)=>listeners[n]=f},window:{scrollTo(){}},FormData:class{constructor(o){this.v=o.values}get(k){return this.v[k]}has(k){return !!this.v[k]}}};vm.createContext(context);vm.runInContext(fs.readFileSync('app/megatex/demo.js','utf8'),context);const run=s=>vm.runInContext(s,context),click=d=>listeners.click({target:{closest:()=>({dataset:d})},preventDefault(){}});
for(const s of ['overview','projects','estimate','tasks','pto','supply','field','time','finance','effect']){if(s==='effect'){for(const [k,v] of Object.entries({people:8,min:30,rate:3000,loss:0}))element('#roi-'+k).value=v}run(`goto('${s}')`);assert.ok(element('#view').innerHTML.length>500,s)}
assert.equal(run('total()'),5960000);assert.equal(run('rows.reduce((a,r)=>a+r[3]*r[6],0)'),851.8);
run("report(1)");element('#pto-comment').value='Проверено';click({accept:'1'});assert.equal(run('accepted()'),180);const done=run('done()');click({accept:'1'});assert.equal(run('done()'),done,'no double acceptance');
run("action('time-confirm')");assert.equal(run('state.timeApproved'),true);assert.equal(run('hours()*2500'),10000);
run("action('expense-confirm'); action('expense-confirm')");assert.equal(run('state.expense'),true);assert.equal(run("state.events.filter(e=>e.text.includes('18 500')).length"),1);
run("action('purchase'); action('purchase')");assert.equal(run('state.purchase'),true);
listeners.submit({target:{id:'field-form',values:{qty:'120',hours:'4',comment:'Второй участок',proof:'yes'}},preventDefault(){}});assert.equal(run('state.reports.length'),2);assert.equal(run('state.timeApproved'),false);assert.equal(run('accepted()'),180);assert.equal(run('hours()'),8);run("action('time-confirm')");assert.equal(run('state.timeApproved'),true);
listeners.submit({target:{id:'field-form',values:{qty:'10',hours:'1',comment:'Пересечение',proof:'yes'}},preventDefault(){}});run("action('time-confirm')");assert.equal(run('state.timeApproved'),false,'over shift blocked');
run('report(2)');element('#pto-comment').value='';click({reject:'2'});assert.equal(run('state.reports[1].status'),'На проверке');element('#pto-comment').value='Нужна маркировка';click({reject:'2'});assert.equal(run('state.reports[1].status'),'Возвращён');
run("state.reports.push({id:99,qty:2000,hours:1,evidence:'test',status:'На проверке'}); report(99)");click({accept:'99'});assert.equal(run("state.reports.find(r=>r.id===99).status"),'На проверке','over estimate blocked');
run("state.reports.push({id:100,qty:10,hours:1,evidence:'',status:'На проверке'}); report(100)");click({accept:'100'});assert.equal(run("state.reports.find(r=>r.id===100).status"),'На проверке','missing proof blocked');
assert.equal(run("esc('<img src=x onerror=alert(1)>')"),'&lt;img src=x onerror=alert(1)&gt;');
console.log('PASS: 10 sections; arithmetic; report → PTO → estimate; time → cost; overrun guards; duplicate guards; return reason; escaping.');
