import {fromRecords,addEntity,get} from './cad.mjs?v=0.17.66';
import * as projectAPI from './executive-project.mjs?v=0.17.66';
import {routeLength} from './cable-ledger.mjs?v=0.17.66';
import {selectExecutiveRoots} from './executive-selection.mjs?v=0.17.66';
import {executivePlacement} from './executive-placement.mjs?v=0.17.66';
import {cableCurve,nearestCablePoint,cutCable} from './cable-edit.mjs?v=0.17.66';
import {drawingPreset} from './drawing-presets.mjs?v=0.17.66';
import {parseTable,tablePages} from './table-paste.mjs?v=0.17.66';
import {stampLabels} from './stamp-fields.mjs?v=0.17.66';
import {mountStampWorkbench} from './stamp-workbench.mjs?v=0.17.66';
export function mountExecutiveUI(api){
 const panel=document.createElement('section');panel.id='executives';
 panel.innerHTML=`<h2>Исполнительные</h2><button id="exArea">Выделить план рамкой</button><p id="exAreaInfo">Откройте DWG, выберите единицы и выделите план.</p><button id="exCreate" disabled>Создать рядом</button><label>Исполнительная<select id="exSheet"></select></label><label>Заголовок<input id="exTitle" maxlength="1000"></label><label>Поворот плана, °<input id="exAngle" type="number" value="0"></label><details><summary>Редактировать штамп</summary><div id="exStamp"></div></details><button id="exApply">Применить оформление</button><h3>Кабельные трассы</h3><label>Марка<input id="exBrand" value="ВВГнг(А)-LS"></label><label>Сечение<input id="exSection" value="3×2,5"></label><label>Дополнительная длина, м<input id="exExtra" type="number" min="0" value="0" step="any"></label><button id="exRoute">Рисовать трассу</button><button id="exFinish">Завершить трассу</button><label>Трасса<select id="exRouteList"></select></label><button id="exCable">Назначить кабель</button><button id="exLeader">Выноска · 3 точки</button><button id="exRemoveLeader">Удалить выноски</button><button id="exRemoveRoute">Удалить трассу</button><div class="pair"><label>Сдвиг X<input id="exDX" type="number" value="0"></label><label>Сдвиг Y<input id="exDY" type="number" value="0"></label></div><button id="exMoveRoute">Двигать трассу</button><button id="exDevice">Выбрать прибор</button><pre id="exLedger" style="white-space:pre-wrap;font-size:12px"></pre>`;
 document.querySelector('#sidebar').prepend(panel);
 const advanced=document.createElement('div');advanced.innerHTML=`<label>Отдельная выноска<select id="exLeaderList"></select></label><button id="exMoveLeader">Сдвинуть подпись · X/Y выше</button><button id="exDeleteLeader">Удалить выбранную выноску</button><label>Известная длина, м<input id="exKnownMetres" type="number" min="0" step="any" value="1"></label><button id="exCalibrate">Калибровать · 2 точки</button>`;panel.append(advanced);
 const $=id=>document.getElementById(id);
 const showSheet=document.createElement('button');showSheet.id='exShow';showSheet.textContent='Показать исполнительную';$('exSheet').parentElement.after(showSheet);
 const operationError=document.createElement('p');operationError.id='exError';operationError.setAttribute('role','alert');operationError.hidden=true;operationError.style.cssText='color:#ffc38a;overflow-wrap:anywhere';$('exCreate').after(operationError);
 for(const [key,label] of Object.entries(stampLabels)){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.id='exStamp_'+key;i.maxLength=1000;l.append(i);$('exStamp').append(l);}
 let active='',chosen=[],area=null,points=[],mode='',routeId='',selectionSource=null,hoverPoint=null;
 const project=()=>api.getDoc().executiveProject||projectAPI.createExecutiveProject();
 const sheet=()=>project().sheets.find(s=>s.id===active);
 const showCanvas=()=>{if(matchMedia('(max-width:850px)').matches)$('sidebar').classList.remove('open');for(const group of document.querySelectorAll('#executiveToolbar>details'))group.open=false;};
 let acting=false;
 const guard=fn=>async()=>{if(api.busy()||acting)return;acting=true;try{await fn();if(mode)showCanvas();}catch(e){api.status(e.message);}finally{acting=false;}};
 function mutate(fn,geometry=false,afterSnapshot=()=>{}){const next=projectAPI.executiveTransaction(project(),fn);for(const s of next.sheets)projectAPI.executiveEntities(next,s.id);api.snapshot();afterSnapshot();api.getDoc().executiveProject=next;api.changed(geometry?'geometry':'decoration');}
 function refresh(){
  if(selectionSource&&selectionSource!==api.getDoc().sourceFile){chosen=[];area=null;points=[];mode='';selectionSource=null;$('exCreate').disabled=true;operationError.hidden=true;$('exAreaInfo').textContent='Выделите план в текущем DWG.';}
  const p=project(),s=p.sheets.find(s=>s.id===active)||p.sheets[0];active=s?.id||'';
  $('exSheet').replaceChildren(...p.sheets.map(s=>new Option(s.title||s.id,s.id)));$('exSheet').value=active;$('exSheet').disabled=!s;showSheet.disabled=!s;
  $('exTitle').value=s?.title||'';$('exAngle').value=((s?.angle||0)*180/Math.PI).toFixed(3);
  for(const [key,value]of Object.entries(s?.titleStyle||{x:210,y:275,height:5})){const input=$('title_'+key);if(input&&document.activeElement!==input)input.value=value;}
  for(const key of Object.keys(stampLabels))$('exStamp_'+key).value=s?.stamp[key]||'';
  $('exRouteList').replaceChildren(...(s?.routes||[]).map(r=>new Option(`${r.brand||'?'} ${r.section||'?'} · ${((r.paths?r.paths.reduce((n,p)=>n+routeLength(p,r.metresPerUnit),0):routeLength(r.points,r.metresPerUnit))+r.extraMetres).toFixed(2)} м`,r.id)));
  if(!s?.routes.some(r=>r.id===routeId))routeId='';$('exRouteList').value=routeId;
  refreshLeaders();
  const ledger=projectAPI.executiveLedger(p,active);
  $('exLedger').textContent=s?'Этот лист:\n'+ledger.rows.map(r=>`${r.brand} ${r.section}: ${r.length.toFixed(2)} м`).join('\n')+`\nБез выносок: ${ledger.withoutLeaders.length}\nБез марки/сечения: ${ledger.unassigned.length}\nВсего по листу: ${ledger.rows.reduce((n,r)=>n+r.length,0).toFixed(2)} м`:'';
 }
 function refreshLeaders(){const previous=$('exLeaderList').value,r=sheet()?.routes.find(r=>r.id===routeId);$('exLeaderList').replaceChildren(...(r?.leaders||[]).map((l,i)=>new Option('Выноска '+(i+1),l.id)));if(r?.leaders.some(l=>l.id===previous))$('exLeaderList').value=previous;}
 let decorationCache;
 function rebuild(){
  const doc=api.getDoc(),p=doc.executiveProject;if(!p){refresh();return false;}
  const signature=JSON.stringify(p);
  if(decorationCache?.doc===doc&&decorationCache.records===doc.records&&decorationCache.entities===doc.entities&&decorationCache.signature===signature){refresh();return false;}
  const removed=new Set(p.generatedHandles||[]),records=doc.records.filter(r=>!r.id.startsWith('executive-')&&!removed.has(get(r,5)));
  const mini=fromRecords([{id:'section',type:'SECTION',pairs:[[2,'ENTITIES']]},{id:'end',type:'ENDSEC',pairs:[]}]);let i=0;
  for(const key of doc.textStyles.keys())if(key.startsWith('PLLATO_DISPLAY_'))doc.textStyles.delete(key);
  for(const s of p.sheets)for(const item of projectAPI.executiveEntities(p,s.id).items){let pairs;
   const style='PLLATO_DISPLAY_'+(s.font||'times.ttf');doc.textStyles.set(style,{font:s.font||'times.ttf',width:1,oblique:0});
   if(item.type==='LINE')pairs=[[10,item.values[0]],[20,item.values[1]],[11,item.values[2]],[21,item.values[3]]];
   else if(item.type==='TEXT')pairs=[[10,item.values[0]],[20,item.values[1]],[40,item.values[2]],[50,item.values[3]*180/Math.PI],[1,item.text],[7,style]];
   else pairs=[[90,item.points.length/2],[70,item.closed?1:0],...item.points.flatMap((n,j)=>[[j%2?20:10,n]])];
   if(item.align)pairs.push([72,item.align],[11,item.values[0]],[21,item.values[1]]);if(item.color)pairs.push([62,item.color]);if(item.rgb!==undefined)pairs.push([420,item.rgb]);if(item.lineweight!==undefined)pairs.push([370,item.lineweight]);const r=addEntity(mini,item.type,pairs);r.id='executive-'+i++;if(item.routeId)r.routeId=item.routeId;
  }
  const entities=doc.entities.filter(r=>!r.id.startsWith('executive-')&&!removed.has(get(r,5)));
  doc.records=[...records,...mini.entities];doc.entities=[...entities,...mini.entities];decorationCache={doc,records:doc.records,entities:doc.entities,signature};refresh();return true;
 }
 $('exArea').onclick=guard(()=>{if(!api.getDoc().native)throw Error('Исполнительные: откройте исходный DWG');points=[];mode='area';api.setTool('executive');api.status('Зажмите мышь, обведите нужный план рамкой и отпустите — исполнительная создастся автоматически. Включайте объекты целиком.');});
 $('exCreate').onclick=guard(async()=>{
  if(!chosen.length||!area||selectionSource!==api.getDoc().sourceFile)throw Error('Сначала выделите план в текущем DWG');const metres=api.metresPerUnit();if(!metres){$('sidebar').classList.add('open');$('panel').setAttribute('aria-expanded','true');$('units').scrollIntoView({block:'nearest'});$('units').focus();throw Error('Выберите единицы измерения в открытой панели, затем нажмите лист с плюсом ещё раз — область уже выделена.');}
  const p=structuredClone(project()),{unit,origin,centre,position}=executivePlacement(api.shapes(),chosen.map(h=>'dwg-'+h));
  const id=crypto.randomUUID();projectAPI.createExecutive(p,{id,title:'Исполнительная схема '+(p.sheets.length+1),origin,planCentre:position,metresPerUnit:metres,paperUnit:unit});
  operationError.hidden=true;operationError.textContent='';
  const previous=active;active=id;const created=await api.commit(p,{sheetId:id,handles:chosen,centre,position});
  if(!created){active=previous;operationError.textContent=api.lastStatus();operationError.hidden=false;return;}
  chosen=[];area=null;$('exCreate').disabled=true;mode='';$('exAreaInfo').textContent='Исполнительная создана на свободном месте справа от всех чертежей и показана на экране.';
 });
 const createIcon=document.createElement('button');createIcon.id='exCreateIcon';createIcon.innerHTML='<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M13 3H4v18h16V10M14 2v8h8M17 13v6M14 16h6"/></svg>';
 document.querySelector('nav').prepend(createIcon);
 const updateCreateIcon=()=>{const ready=!$('exCreate').disabled;createIcon.disabled=api.busy();createIcon.title=ready?'Создать исполнительную из выделенного плана':'Создать исполнительную · обведите план рамкой';createIcon.setAttribute('aria-label',createIcon.title);createIcon.classList.toggle('ready',ready);};
 createIcon.onclick=()=>{if(api.busy()||acting)return;$('sidebar').classList.remove('open');$('panel').setAttribute('aria-expanded','false');($('exCreate').disabled?$('exArea'):$('exCreate')).click();};
 const createObserver=new MutationObserver(updateCreateIcon);createObserver.observe($('exCreate'),{attributes:true,attributeFilter:['disabled']});createObserver.observe($('busy'),{attributes:true,attributeFilter:['hidden']});updateCreateIcon();
 showSheet.onclick=guard(()=>{api.focus(sheet());showCanvas();});
 function cableFields(){const r=sheet()?.routes.find(r=>r.id===routeId);if(r){$('exBrand').value=r.brand;$('exSection').value=r.section;$('exExtra').value=r.extraMetres;}refreshLeaders();}
 $('exSheet').onchange=()=>{active=$('exSheet').value;refresh();api.focus(sheet());};$('exRouteList').onchange=()=>{routeId=$('exRouteList').value;api.setTool('object');cableFields();};
 $('exMoveLeader').onclick=guard(()=>{const id=$('exLeaderList').value;mutate(p=>projectAPI.moveLeader(p,active,id,[Number($('exDX').value),Number($('exDY').value)]));});
 $('exDeleteLeader').onclick=guard(()=>{const id=$('exLeaderList').value;mutate(p=>projectAPI.removeLeader(p,active,id));});
 $('exCalibrate').onclick=guard(()=>{if(!sheet())throw Error('Создайте исполнительную');const metres=Number($('exKnownMetres').value);if(!Number.isFinite(metres)||metres<=0)throw Error('Укажите известную длину в метрах');mode='calibrate';points=[];api.setTool('executive');api.status('Укажите концы известного отрезка. Метраж этого листа будет пересчитан; геометрия останется на месте.');});
 $('exApply').onclick=guard(async()=>{if(!sheet())throw Error('Создайте исполнительную');const title=$('exTitle').value,angle=Number($('exAngle').value)*Math.PI/180,rotated=Math.abs(angle-sheet().angle)>1e-8,stamp=Object.fromEntries(Object.keys(stampLabels).map(k=>[k,$('exStamp_'+k).value]));if(!Number.isFinite(angle))throw Error('Введите числовой угол');await api.checkpoint('Перед поворотом / оформлением');mutate(p=>{if(rotated)projectAPI.rotateExecutive(p,active,angle);const s=p.sheets.find(s=>s.id===active);s.title=title;s.stamp=stamp;},rotated);if(rotated)api.previewRotation(sheet());});
 $('exRoute').onclick=guard(()=>{if(!sheet())throw Error('Создайте исполнительную');mode='route';points=[];api.setTool('executive');api.status('Укажите точки трассы; затем нажмите «Завершить трассу».');});
 $('exFinish').onclick=guard(()=>{if(mode!=='route'||points.length<2)throw Error('Нужно минимум две точки');const id=crypto.randomUUID(),routePoints=points.map(p=>[...p]);mutate(p=>projectAPI.addRoute(p,active,{id,points:routePoints,brand:$('exBrand').value,section:$('exSection').value,extraMetres:Number($('exExtra').value)}));routeId=id;mode='';points=[];api.setTool('select');refresh();});
 $('exCable').onclick=guard(()=>mutate(p=>projectAPI.setCable(p,active,routeId,{brand:$('exBrand').value,section:$('exSection').value,extraMetres:Number($('exExtra').value)})));
 $('exLeader').onclick=guard(()=>{if(!routeId)throw Error('Выберите трассу');mode='leader';points=[];api.setTool('executive');api.status('Укажите точку привязки, изгиб и положение подписи.');});
 $('exRemoveLeader').onclick=guard(()=>mutate(p=>{const s=p.sheets.find(s=>s.id===active),r=s?.routes.find(r=>r.id===routeId);if(!r)throw Error('Выберите трассу');for(const l of [...r.leaders])projectAPI.removeLeader(p,active,l.id);}));
 $('exRemoveRoute').onclick=guard(()=>mutate(p=>projectAPI.removeRoute(p,active,routeId)));
 $('exMoveRoute').onclick=guard(()=>mutate(p=>projectAPI.moveRoute(p,active,routeId,[Number($('exDX').value),Number($('exDY').value)])));
 $('exDevice').onclick=()=>{if(api.busy())return;api.setTool('device');showCanvas();api.status('Нажмите на любой штрих прибора — выберется весь блок.');};
 function finishArea(a,w){
  if(mode!=='area'||api.busy())return;
  area=[Math.min(a[0],w[0]),Math.min(a[1],w[1]),Math.max(a[0],w[0]),Math.max(a[1],w[1])];
  chosen=selectExecutiveRoots(api.getDoc(),api.shapes(),area);selectionSource=api.getDoc().sourceFile;
  $('exAreaInfo').textContent=`Выбрано объектов: ${chosen.length}. Исходник останется на месте.`;$('exCreate').disabled=!chosen.length;points=[];hoverPoint=null;mode='';api.setTool('select');
  if(chosen.length)$('exCreate').click();else api.status('В рамке нет целых объектов. Если план — один блок, обведите его целиком. Нажмите лист с плюсом и повторите выделение.');
 }
 function tap(w){
  if(mode==='area'){api.status('Зажмите мышь и протяните рамку вокруг плана. Отдельные клики не создают исполнительную.');return;}
  if(mode==='leader'&&!points.length){const r=sheet()?.routes.find(r=>r.id===routeId);w=nearestCablePoint(r?.paths||[r?.points||[]],w)||w;}
  points.push(w);
  if(mode==='calibrate'&&points.length===2){try{mutate(p=>projectAPI.calibrateExecutive(p,active,points[0],points[1],Number($('exKnownMetres').value)));api.status('Масштаб метража обновлён для всех трасс этого листа.');}catch(e){api.status(e.message);}points=[];mode='';api.setTool('select');}
  else if(['route3','broken','straight'].includes(mode)&&points.length>1)api.status('Точек: '+points.length+' · нажмите инструмент повторно, чтобы завершить кабель');
  else if((mode==='route'||mode==='route3')&&points.length>1)api.status('Длина трассы: '+routeLength(cableCurve(points,mode==='route3'),sheet().metresPerUnit).toFixed(3)+' м · точек '+points.length);
  else if(mode==='leader'&&points.length===3){const [anchor,elbow,label]=points;mutate(p=>projectAPI.addLeader(p,active,routeId,{id:crypto.randomUUID(),anchor,elbow,label}));points=[];mode='';api.setTool('select');}
  api.draw();
 }
 function hover(w){hoverPoint=w;if(['route','route3','straight','broken'].includes(mode)&&points.length&&sheet())api.status('Длина трассы: '+routeLength(cableCurve([...points,w],mode==='route3'),sheet().metresPerUnit).toFixed(3)+' м');api.draw();}
 // Действия наверху, параметры — в раскрывающихся группах, без длинной ленты кнопок справа.
 const toolbar=document.createElement('div');toolbar.id='executiveToolbar';toolbar.setAttribute('aria-label','Инструменты исполнительной');
 const groups=[['Лист',['exTitle','exAngle','exApply']],['Кабель',['exBrand','exSection','exExtra','exRoute','exFinish','exRouteList','exCable']],['Выноски',['exLeader','exLeaderList','exMoveLeader','exDeleteLeader','exRemoveLeader']],['Перемещение',['exDX','exDY','exMoveRoute','exDevice','exRemoveRoute']],['Масштаб',['exKnownMetres','exCalibrate']]];
 for(const [title,ids] of groups){const group=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('div');summary.textContent=title;group.append(summary,body);for(const id of ids){const el=$(id);body.append(el.closest('label')||el);}if(title==='Лист'){const stamp=$('exStamp').closest('details');body.insertBefore(stamp,$('exApply'));}toolbar.append(group);}
 document.querySelector('main').before(toolbar);
 const quick=document.createElement('div');quick.className='executiveQuick';toolbar.prepend(quick);
 for(const [label,id] of [['Прибор','exDevice'],['Кабельная трасса','exRoute'],['Выноска','exLeader']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>$(id).click();quick.append(b);}
 const rename=document.createElement('button');rename.id='exRename';rename.textContent='Изменить название';$('exTitle').parentElement.after(rename);rename.onclick=guard(async()=>{if(!sheet())throw Error('Выберите исполнительную');const title=$('exTitle').value;await api.checkpoint('Перед переименованием');mutate(p=>{p.sheets.find(s=>s.id===active).title=title;});api.status('Название изменено и сохраняется локально.');});
 const assign=document.createElement('button');assign.id='exAssignSelection';assign.textContent='Назначить кабель выделенному объекту';$('exCable').after(assign);
function assignSelection(){if(!sheet())throw Error('Выберите исполнительную');const selection=api.selectionPaths(),isNew=selection.ids.length&&selection.ids.every(id=>id.startsWith('new-'));if(selection.shared)throw Error('Общая геометрия повторяющихся блоков: сначала создайте независимую копию прибора.');if(!selection.paths.length)throw Error('Выберите линию, полилинию или кабель');if(!isNew&&!selection.roots.every(id=>sheet().nativeHandles.includes(id.replace('dwg-',''))))throw Error('Выберите объект внутри активной исполнительной');if(project().sheets.some(s=>s.routes.some(r=>r.sourceIds?.some(id=>(selection.allIds||selection.ids).includes(id)))))throw Error('Этот объект уже учтён. Выберите его трассу в списке для изменения кабеля.');if(selection.coincident&&!confirm("Найдены совпадающие копии линий: "+selection.coincident+". Учесть выбранный путь как один кабель, без повторения длины? Если здесь проходят несколько кабелей, отмените и учитывайте их отдельно."))return;const id=crypto.randomUUID();mutate(p=>projectAPI.addRoute(p,active,{id,points:selection.paths[0],...(!isNew?{paths:selection.paths,sourceIds:selection.ids}:{}),brand:$('exBrand').value,section:$('exSection').value,extraMetres:Number($('exExtra').value)}),!!isNew,()=>{if(isNew)api.consumeNewSelection();});routeId=id;refresh();api.status('Кабель назначен. Длина кривых рассчитана по отображаемой геометрии (приближённо).');return id;}
 assign.onclick=guard(assignSelection);
 toolbar.addEventListener('click',e=>{const summary=e.target.closest('summary');if(summary?.parentElement.parentElement===toolbar)for(const group of toolbar.children)if(group!==summary.parentElement)group.open=false;});
 document.addEventListener('pointerdown',e=>{if(!toolbar.contains(e.target))for(const group of toolbar.children)group.open=false;});
 $('exMoveLeader').textContent='Сдвинуть выноску (X/Y в «Перемещение»)';$('exMoveRoute').textContent='Сдвинуть выбранную трассу';$('exApply').textContent='Применить поворот и оформление';
 function selectObject(id,ids){const record=api.getDoc().records.find(r=>r.id===id);for(const s of project().sheets){const r=s.routes.find(r=>r.id===record?.routeId||r.sourceIds?.some(source=>ids.includes(source)));if(r){active=s.id;routeId=r.id;refresh();cableFields();return;}}routeId='';$('exRouteList').value='';}
 function createCable(controls,smooth){if(!sheet())throw Error('Выберите исполнительную');const id=crypto.randomUUID();mutate(p=>projectAPI.addRoute(p,active,{id,points:cableCurve(controls,smooth),controls,smooth,...drawingPreset,extraMetres:0}));routeId=id;refresh();api.status('Кабель создан и включён в ведомость. Можно изменить марку, сечение и поставить выноску.');}
 const selectedRoute=()=>sheet()?.routes.find(r=>r.id===routeId);
 const titleOptions=document.createElement('details');titleOptions.innerHTML='<summary>Положение и размер названия</summary><label>X от левого края, мм<input id="title_x" type="number" min="0" max="420" value="210"></label><label>Y от нижнего края, мм<input id="title_y" type="number" min="0" max="297" value="275"></label><label>Высота текста, мм<input id="title_height" type="number" min="0.2" max="50" step="0.2" value="5"></label><button id="titleApply">Применить название</button>';$('exTitle').parentElement.after(titleOptions);
 $('titleApply').onclick=guard(()=>{const values=Object.fromEntries(['x','y','height'].map(k=>[k,Number($('title_'+k).value)]));if(!Object.values(values).every(Number.isFinite)||values.x<0||values.x>420||values.y<0||values.y>297||values.height<.2||values.height>50)throw Error('Проверьте положение и размер');if(!sheet())throw Error('Выберите исполнительную');const title=$('exTitle').value;mutate(p=>{const s=p.sheets.find(s=>s.id===active);s.title=title;s.titleStyle=values;});});
 for(const id of ['title_x','title_y','title_height'])$(id).addEventListener('change',()=>$('titleApply').click());
 $('title_height').title='Высота заголовка в миллиметрах на листе. Изменение применяется после ввода.';
 const tableOptions=document.createElement('details');tableOptions.innerHTML='<summary>Таблица из Excel</summary><p>Скопируйте любые ячейки из Excel. Столбцы, переносы строк и текст сохранятся; ширина и рамки подбираются автоматически. До 20 столбцов и 1000 строк.</p><textarea id="tablePaste" rows="5" aria-label="Таблица из Excel" placeholder="Вставьте ячейки из Excel"></textarea><label><input id="tableHeader" type="checkbox" checked>Первая строка — заголовок</label><div id="tablePreview" style="overflow:auto;max-height:260px;background:white;color:#111" aria-live="polite"></div><p id="tablePreviewInfo"></p><button id="tableApply" disabled>Вставить таблицу</button><button id="tableReset">Вернуть расчётную ведомость</button>';titleOptions.after(tableOptions);
 function previewTable(){const target=$('tablePreview');target.replaceChildren();$('tableApply').disabled=true;try{const table=parseTable($('tablePaste').value,{header:$('tableHeader').checked}),pages=tablePages(table),el=document.createElement('table');el.style.cssText='border-collapse:collapse;width:100%;font-size:12px';for(const [i,row]of table.cells.slice(0,100).entries()){const tr=el.insertRow();for(const value of row){const cell=document.createElement(i===0&&table.header?'th':'td');cell.textContent=value;cell.style.cssText='border:1px solid #777;padding:5px;white-space:pre-wrap;overflow-wrap:anywhere';if(i===0&&table.header)cell.style.background='#e8eef3';tr.append(cell);}}target.append(el);$('tablePreviewInfo').textContent=`${table.cells.length} строк × ${table.cells[0].length} столбцов · ${pages.length} листов ведомости`+(table.cells.length>100?' · предпросмотр первых 100 строк':'');$('tableApply').disabled=false;}catch(e){$('tablePreviewInfo').textContent=e.message;}}
 $('tablePaste').oninput=previewTable;$('tableHeader').onchange=previewTable;
 $('tableApply').onclick=guard(()=>{if(!sheet())throw Error('Выберите исполнительную');const table=parseTable($('tablePaste').value,{header:$('tableHeader').checked});tablePages(table);mutate(p=>{const s=p.sheets.find(s=>s.id===active);s.table=table;delete s.tableRows;});if(tableDialog.open)tableDialog.close();api.status('Таблица вставлена в нижний левый угол. '+table.cells.length+' строк.');});
 $('tableReset').onclick=guard(()=>{if(!sheet())throw Error('Выберите исполнительную');mutate(p=>{const s=p.sheets.find(s=>s.id===active);delete s.tableRows;delete s.table;});});
 const tableEntry=document.createElement('button');tableEntry.id='exTableEntry';tableEntry.textContent='Вставить из Excel';tableEntry.title='Вставить скопированные ячейки Excel в нижнюю левую таблицу этой исполнительной';tableEntry.hidden=true;tableEntry.style.cssText='position:absolute;z-index:4;font-size:12px;padding:6px 10px;min-height:30px';$('viewport').append(tableEntry);
 const tableDialog=document.createElement('dialog');tableDialog.id='exTableDialog';tableDialog.setAttribute('aria-label','Таблица из Excel');tableDialog.style.cssText='width:min(680px,90vw);max-height:85vh;overflow:auto;background:#142638;color:#eef4fa;border:1px solid #7891a3;border-radius:8px;padding:20px';document.body.append(tableDialog);
 const tableClose=document.createElement('button');tableClose.textContent='Закрыть';tableClose.style.cssText='float:right';tableClose.onclick=()=>tableDialog.close();tableDialog.append(tableClose);
 $('tablePaste').style.cssText='display:block;width:100%;box-sizing:border-box;min-height:110px;resize:vertical;padding:10px;font:14px monospace;background:white;color:#111';$('tableHeader').style.cssText='width:auto;margin:0';$('tableHeader').parentElement.style.cssText='display:flex;align-items:center;gap:8px;margin:12px 0';
 tableDialog.addEventListener('close',()=>{titleOptions.after(tableOptions);tableOptions.open=false;});
 tableEntry.onclick=()=>{if(!sheet()||api.busy())return;showCanvas();tableOptions.open=true;tableDialog.append(tableOptions);tableDialog.showModal();$('tablePaste').focus();};
 // Position only: never rebuild geometry or parse the table on pointer movement.
 let tableAnchorSheet=null,tableHeight=14;
 function paintTableEntry(){const s=sheet(),viewport=$('viewport');if(!s||api.busy()){tableEntry.hidden=true;return;}if(tableAnchorSheet!==s){tableAnchorSheet=s;tableHeight=s.table?tablePages(s.table)[0].height:(Math.min(10,(s.tableRows||projectAPI.executiveLedger(project(),s.id).rows).length)+1)*7;}const [x,y]=api.screen([s.origin[0]+15*s.paperUnit,s.origin[1]+(5+tableHeight)*s.paperUnit]);tableEntry.hidden=x<0||x>viewport.clientWidth-160||y<35||y>viewport.clientHeight;if(!tableEntry.hidden){tableEntry.style.left=x+'px';tableEntry.style.top=Math.max(0,y-34)+'px';}}
 const stampWorkbench=mountStampWorkbench({sheet,project,screen:api.screen,busy:api.busy,edit:(id,stamp)=>{if(!project().sheets.some(s=>s.id===id))throw Error('Исполнительная не найдена');mutate(p=>{p.sheets.find(s=>s.id===id).stamp=stamp;});api.status('Штамп сохранён. Изменения войдут в DWG и PDF.');}});
 return {paintTableEntry:()=>{paintTableEntry();stampWorkbench.paint();},rebuild,tap,project,hover,selectObject,finishArea,startArea:w=>{if(mode==='area'){points=[w];hoverPoint=w;api.draw();}},clearArea:()=>{if(mode==='area'){points=[];hoverPoint=null;api.draw();}},preview:()=>({mode,points,hoverPoint}),cancel:()=>{points=[];hoverPoint=null;mode='';},sheet,route:selectedRoute,
  editLeader:(sheetId,route,leaderId,values)=>mutate(p=>{const s=p.sheets.find(s=>s.id===sheetId),r=s?.routes.find(r=>r.id===route),l=r?.leaders.find(l=>l.id===leaderId);if(!l)throw Error('Выноска не найдена');if(values.remove){r.leaders=r.leaders.filter(l=>l.id!==leaderId);return;}for(const key of ['label','elbow'])if(values[key]){if(!Array.isArray(values[key])||values[key].length!==2||!values[key].every(Number.isFinite))throw Error('Неверная точка');l[key]=[...values[key]];}if(values.textHeight!==undefined){if(!Number.isFinite(values.textHeight)||values.textHeight<.2||values.textHeight>50)throw Error('Высота текста: от 0,2 до 50 мм');l.textHeight=values.textHeight;}for(const key of ['brand','section'])if(values[key]!==undefined){if(typeof values[key]!=='string'||values[key].length>1000)throw Error('Слишком длинное название');r[key]=values[key].trim();}}),
  assignSelection,
  editTitle:(id,values)=>{const s=project().sheets.find(s=>s.id===id);if(!s)throw Error('Исполнительная не найдена');const style={x:210,y:275,height:5,...s.titleStyle,...Object.fromEntries(['x','y','height'].filter(k=>values[k]!==undefined).map(k=>[k,values[k]]))};if(!Object.values(style).every(Number.isFinite)||style.x<0||style.x>420||style.y<0||style.y>297||style.height<.2||style.height>50)throw Error('Размер: 0,2–50 мм; положение — внутри листа');if(values.title!==undefined&&(typeof values.title!=='string'||values.title.length>1000))throw Error('Название: до 1000 символов');active=id;mutate(p=>{const s=p.sheets.find(s=>s.id===id);s.titleStyle=style;if(values.title!==undefined)s.title=values.title;});},
  selectRoute:id=>{routeId=id;refresh();cableFields();},
  beginLeaderAt:(p,elbow,label)=>{if(!selectedRoute()&&!assignSelection())return;const r=selectedRoute();if(!r||!p)throw Error('Выберите кабель');const q=nearestCablePoint(r.paths||[r.points],p);mutate(next=>projectAPI.addLeader(next,active,routeId,{id:crypto.randomUUID(),anchor:q,elbow,label}));mode='';points=[];api.status('Выноска поставлена. Марку и сечение можно изменить рядом с кабелем.');},
  beginCable:(kind='route3')=>{if(!sheet())throw Error('Выберите исполнительную');if(mode===kind){if(points.length<2){api.status('Укажите минимум две точки');return;}createCable(points,kind==='route3');points=[];hoverPoint=null;mode='';api.setTool('object');return;}mode=kind;points=[];api.setTool('executive');api.status('Кликайте точки кабеля. Повторное нажатие этого инструмента завершает линию. Escape — отмена.');},
  cutRoute:(a,b)=>{const r=selectedRoute();if(!r||r.sourceIds)throw Error('Сначала включите редактирование формы');const parts=cutCable(r.points,a,b),ids=parts.map(()=>crypto.randomUUID());mutate(p=>{const s=p.sheets.find(s=>s.id===active);s.routes=s.routes.filter(item=>item.id!==r.id);parts.forEach((points,i)=>{const next={...structuredClone(r),id:ids[i],points,smooth:false,extraMetres:i===0?r.extraMetres:0,...(r.drops?{drops:i===0?structuredClone(r.drops):[]}:{}),leaders:[]};delete next.controls;for(const l of r.leaders){const q=nearestCablePoint([points],l.anchor);if(q&&Math.hypot(q[0]-l.anchor[0],q[1]-l.anchor[1])<1e-6)next.leaders.push(l);}s.routes.push(next);});});routeId=ids[0]||'';refresh();api.status('Часть кабеля удалена. Остатки и ведомость обновлены; отмена доступна.');},
  editRoute:fn=>mutate(p=>{const r=p.sheets.find(s=>s.id===active)?.routes.find(r=>r.id===routeId);if(!r)throw Error('Выберите кабель');fn(r);}),
  duplicateRoute:delta=>{const r=structuredClone(selectedRoute());if(!r||r.sourceIds)throw Error('Выберите нарисованный кабель');r.id=crypto.randomUUID();r.leaders.forEach(l=>l.id=crypto.randomUUID());mutate(p=>{p.sheets.find(s=>s.id===active).routes.push(r);projectAPI.moveRoute(p,active,r.id,delta);});routeId=r.id;refresh();},
  moveRoute:delta=>mutate(p=>projectAPI.moveRoute(p,active,routeId,delta)),removeRoute:()=>mutate(p=>projectAPI.removeRoute(p,active,routeId))};
}
