import {importShx,restoreShx,removeShx,localShx,localShxNames,fontKey} from './local-shx.mjs';
export function shxCatalog({shapes,onChange,status,styles,applyStyle,applyDocument}){
 const button=document.createElement('button');button.id='shxFonts';button.textContent='Шрифты';button.title='Локальные SHX-шрифты этого браузера';document.querySelector('header').append(button);
 const dialog=document.createElement('dialog');dialog.id='shxDialog';dialog.innerHTML='<h2>Шрифты SHX на этом устройстве</h2><p>Добавьте оригинальные файлы .shx. Они сохраняются только в этом браузере и не отправляются на сервер. На другом устройстве загрузите их отдельно. Очистка данных сайта удалит каталог.</p><p>Совпадение по имени файла автоматически подключает шрифт к исходному стилю DWG и векторному PDF. Стили DWG не переименовываются, файлы шрифтов в DWG не встраиваются.</p><label class="button">Загрузить SHX<input id="shxUpload" type="file" accept=".shx" multiple hidden></label><p id="shxStatus" role="status"></p><div id="shxList"></div><h3>Шрифты текущего чертежа</h3><div id="shxRequired"></div><form method="dialog"><button>Закрыть</button></form>';
 document.body.append(dialog);const output=dialog.querySelector('#shxStatus'),list=dialog.querySelector('#shxList'),required=dialog.querySelector('#shxRequired'),input=dialog.querySelector('input');
 const controls=document.createElement('section');controls.innerHTML='<h3>Изменить текстовый стиль DWG</h3><p>Изменятся все надписи этого стиля. Inline-шрифты MTEXT имеют собственное оформление. Выбор сохраняется в DWG; для открытия в другой CAD понадобится тот же SHX.</p><label>Стиль<select id="shxStyle"></select></label><label>Загруженный шрифт<select id="shxChoice"></select></label><button id="shxApply" type="button">Применить к стилю</button>';required.after(controls);
 const styleSelect=controls.querySelector('#shxStyle'),fontSelect=controls.querySelector('#shxChoice'),apply=controls.querySelector('#shxApply');
 const all=document.createElement('button');all.id='shxApplyDocument';all.type='button';all.textContent='Сделать шрифтом всего документа';controls.append(all);
 const note=document.createElement('p');note.textContent='Один выбор меняет все обычные стили, включая Standard для новых надписей. Сохраните DWG — при следующем открытии выбор останется. Исключения: стили Big Font и собственные inline-шрифты MTEXT. Сам SHX остаётся в локальном каталоге устройства.';controls.append(note);
 all.onclick=async()=>{all.disabled=true;apply.disabled=true;try{const count=await applyDocument(fontSelect.value);output.textContent='Шрифт документа изменён: '+count+' стилей. Сохраните DWG, чтобы перенести настройку в файл.';refresh();}catch(e){output.textContent=e.message;}finally{all.disabled=apply.disabled=!styleSelect.options.length||!fontSelect.options.length;}};
 apply.onclick=async()=>{apply.disabled=true;try{await applyStyle(styleSelect.value,fontSelect.value);output.textContent='Стиль изменён. Скачайте DWG для сохранения правки в файл.';refresh();}catch(e){output.textContent=e.message;}finally{apply.disabled=!styleSelect.options.length||!fontSelect.options.length;}};
 dialog.addEventListener('keydown',e=>e.stopPropagation());
 function refresh(){all.disabled=!styles().length||!localShxNames().length;list.replaceChildren();for(const name of localShxNames()){const row=document.createElement('p'),label=document.createElement('span'),remove=document.createElement('button');label.textContent=name+' ';remove.textContent='Убрать с устройства';remove.onclick=async()=>{try{await removeShx(name);onChange();refresh();}catch(e){output.textContent=e.message;}};row.append(label,remove);list.append(row);}
  required.replaceChildren();const found=new Map();for(const s of shapes()){if(s.text===null)continue;const name=fontKey(s.font?.source||'Standard');let v=found.get(name);if(!v)found.set(name,v={count:0,missing:new Set()});v.count++;const font=localShx(name);if(font)for(const c of font.missing(s.text))v.missing.add(c);}
  for(const [name,v] of found){const p=document.createElement('p');p.textContent=name+' — '+v.count+' надписей. '+(localShx(name)?v.missing.size?'Нет символов: '+[...v.missing].join(' ')+'; на экране подстановка, PDF остановится.':'Оригинальный SHX подключён.':/\.shx$/.test(name)?'Не загружен: используется подстановка.':'Не SHX: текущий шрифт редактора.');required.append(p);}
  const current=styleSelect.value;styleSelect.replaceChildren(...styles().map(s=>new Option(s.name+' · '+s.font,s.name)));if([...styleSelect.options].some(o=>o.value===current))styleSelect.value=current;fontSelect.replaceChildren(...localShxNames().map(n=>new Option(n,n)));apply.disabled=!styleSelect.options.length||!fontSelect.options.length;
 }
 button.onclick=()=>{refresh();all.disabled=apply.disabled;dialog.showModal();};
 input.onchange=async()=>{input.disabled=true;const messages=[];for(const file of input.files){output.textContent='Читаю '+file.name+'…';try{await importShx(file);messages.push(file.name+': сохранён локально');}catch(e){messages.push(file.name+': '+e.message);}}input.disabled=false;input.value='';output.textContent=messages.join('. ');onChange();refresh();};
 const ready=restoreShx().then(()=>{onChange();if(dialog.open)refresh();}).catch(()=>status('Локальный каталог SHX недоступен. Проверьте разрешение браузера на хранение данных.'));
 return {ready};
}
