const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={home:'<path d="M3 11 12 4l9 7v9H5v-9"/><path d="M9 20v-6h6v6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',funnel:'<path d="M4 5h16l-6 7v6l-4 2v-8Z"/>',phone:'<path d="M5 4h4l2 5-3 2c2 4 4 6 8 8l2-3 5 2v4c0 1-1 2-2 2C10 23 1 14 2 5c0-1 1-1 3-1Z"/>',return:'<path d="M9 7 4 12l5 5"/><path d="M4 12h9a7 7 0 0 1 7 7"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',branch:'<path d="M5 21V5h10v16M15 10h5v11M8 8h4M8 12h4M8 16h4M18 13h1M18 17h1"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1.1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.9-7.6a5.5 5.5 0 0 0 .9-8.8Z"/>',plan:'<path d="M6 2h12v20H6zM9 7h6M9 11h6M9 15h4"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',box:'<path d="m21 8-9 5-9-5 9-5 9 5Z"/><path d="m3 8 9 5v9M21 8v9l-9 5M7.5 5.5l9 5"/>',wallet:'<path d="M3 6h16v15H3zM19 10h3v7h-3a3 3 0 0 1 0-6Z"/><path d="M5 6V3h11v3"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};
$$('[data-icon]').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24">${icons[el.dataset.icon]||''}</svg>`);

const leads=[
 {id:'marina',name:'Марина С.',relation:'мама пациента',program:'Алкогольная зависимость',source:'Google Ads',owner:'Айгерим',amount:'950 000 ₸',next:'Перезвонить сейчас',age:'42 мин просрочено',stage:'new',tone:'overdue',phone:'+7 701 234 18 06'},
 {id:'saule',name:'Сауле К.',relation:'сестра пациента',program:'Наркотическая зависимость',source:'Звонок',owner:'Руслан',amount:'1 100 000 ₸',next:'Уточнить готовность семьи',age:'Сегодня 10:30',stage:'new',tone:'warm',phone:'+7 707 440 31 90'},
 {id:'dias',name:'Диас М.',relation:'сам пациент',program:'Лудомания',source:'Сайт',owner:'Айгерим',amount:'750 000 ₸',next:'Первичная консультация',age:'Сегодня 12:00',stage:'contact',phone:'+7 747 103 72 18'},
 {id:'alina',name:'Алина Р.',relation:'супруга пациента',program:'Алкогольная зависимость',source:'Рекомендация',owner:'Руслан',amount:'950 000 ₸',next:'Отправить памятку семье',age:'Сегодня 13:30',stage:'contact',tone:'warm',phone:'+7 778 501 09 41'},
 {id:'yerlan',name:'Ерлан Т.',relation:'отец пациента',program:'Наркотическая зависимость',source:'Google Ads',owner:'Айгерим',amount:'1 100 000 ₸',next:'Встреча в центре',age:'30 сен · 11:00',stage:'consult',phone:'+7 701 818 42 11'},
 {id:'madina',name:'Мадина А.',relation:'супруга пациента',program:'Лудомания',source:'Instagram',owner:'Руслан',amount:'750 000 ₸',next:'Согласовать участие врача',age:'1 окт · 15:00',stage:'consult',phone:'+7 700 366 54 08'},
 {id:'arman',name:'Арман Ж.',relation:'брат пациента',program:'Наркотическая зависимость',source:'Звонок',owner:'Айгерим',amount:'1 100 000 ₸',next:'Получить документы',age:'До 18:00',stage:'decision',phone:'+7 705 299 17 62'},
 {id:'gulnaz',name:'Гульназ Б.',relation:'мама пациента',program:'Алкогольная зависимость',source:'Google Ads',owner:'Руслан',amount:'950 000 ₸',next:'Согласовать график оплаты',age:'Сегодня',stage:'decision',tone:'warm',phone:'+7 775 270 61 35'},
 {id:'nikolay',name:'Николай П.',relation:'супруг пациентки',program:'Алкогольная зависимость',source:'Рекомендация',owner:'Айгерим',amount:'950 000 ₸',next:'Оплата первого взноса',age:'Оплата до 30 сен',stage:'docs',phone:'+7 707 170 03 53'},
 {id:'murat',name:'Мурат Н.',relation:'отец пациента',program:'Лудомания',source:'Сайт',owner:'Руслан',amount:'750 000 ₸',next:'Плановое заселение',age:'2 окт · Алатау',stage:'admit',phone:'+7 702 110 77 84'}
];
const patients=[
 {id:'askar',name:'Аскар Н.',branch:'Алатау',day:'12-й день',stage:'Активная программа',curator:'Дана С.',next:'Оценка плана · 13:00',risk:'Семейная встреча не назначена'},
 {id:'timur-p',name:'Тимур О.',branch:'Сайран',day:'4-й день',stage:'Адаптация',curator:'Ермек К.',next:'Первичная оценка · 16:00',risk:'—'},
 {id:'adil',name:'Адиль Р.',branch:'Алатау',day:'37-й день',stage:'Стабилизация',curator:'Дана С.',next:'Группа · 11:30',risk:'—'},
 {id:'ruslan-p',name:'Руслан Д.',branch:'Сайран',day:'68-й день',stage:'Подготовка к выходу',curator:'Алия М.',next:'План 90 дней · завтра',risk:'Проверить проживание после выхода'},
 {id:'kanat',name:'Канат Е.',branch:'Алатау',day:'91-й день',stage:'Постсопровождение',curator:'Ермек К.',next:'Контрольный звонок · 3 окт',risk:'—'}
];
const stages=[['new','Новые','2 обращения'],['contact','Связались','2 обращения'],['consult','Консультация','2 обращения'],['decision','Решение семьи','2 обращения'],['docs','Документы и оплата','1 обращение'],['admit','Заселение','1 обращение']];

function showView(name,push=true){
 $$('.view').forEach(v=>v.classList.toggle('active',v.dataset.page===name));
 $$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));
 const nav=$(`.nav-item[data-view="${name}"]`); $('#crumbTitle').textContent=nav?nav.childNodes[1]?.textContent?.trim()||nav.textContent.trim():'Раздел';
 if(push){const u=new URL(location.href);u.searchParams.set('s',name);history.replaceState({},'',u)}
 closeMobile(); window.scrollTo({top:0,behavior:'smooth'});
}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));

function renderKanban(){
 $('#salesKanban').innerHTML=stages.map(([id,title,count])=>`<section class="kanban-col" data-stage="${id}"><header><b>${title}</b><span>${count}</span></header><div class="kanban-cards">${leads.filter(l=>l.stage===id).map(leadCard).join('')}</div></section>`).join('');
 $$('.lead-card').forEach(card=>{card.draggable=true;card.onclick=()=>openLead(card.dataset.id);card.ondragstart=()=>card.classList.add('is-dragging');card.ondragend=()=>card.classList.remove('is-dragging')});
 $$('.kanban-cards').forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.parentElement.classList.add('drop-highlight')};zone.ondragleave=()=>zone.parentElement.classList.remove('drop-highlight');zone.ondrop=e=>{e.preventDefault();const card=$('.lead-card.is-dragging');if(!card)return;const l=leads.find(x=>x.id===card.dataset.id);l.stage=zone.parentElement.dataset.stage;zone.append(card);zone.parentElement.classList.remove('drop-highlight');toast(`${l.name}: стадия обновлена`)}});
}
function leadCard(l){return `<article class="lead-card ${l.tone||''}" data-id="${l.id}"><b>${l.name}</b><small>${l.relation} · ${l.program}</small><em>${l.next}</em><div class="lead-meta"><span>${l.source}</span><span>${l.age}</span></div></article>`}

function renderTables(){
 $('#clientsTable').innerHTML=table(['Клиент / семья','Запрос','Источник','Ответственный','Следующий шаг','Статус'],leads.map(l=>[`<span class="name-cell"><b>${l.name}</b><small>${l.phone}</small></span>`,l.program,l.source,l.owner,l.next,`<span class="status ${l.tone==='overdue'?'red':''}">${stages.find(s=>s[0]===l.stage)?.[1]}</span>`]),'lead');
 $('#patientsTable').innerHTML=table(['Пациент','Филиал','День программы','Статус','Куратор','Следующий шаг','Сигнал'],patients.map(p=>[`<span class="name-cell"><b>${p.name}</b><small>ID RC-${410+patients.indexOf(p)}</small></span>`,p.branch,p.day,`<span class="status blue">${p.stage}</span>`,p.curator,p.next,p.risk==='—'?'—':`<span class="status amber">${p.risk}</span>`]),'patient');
 $('#paymentsTable').innerHTML=table(['Плательщик','Пациент','Программа','По графику','Получено','Следующая оплата','Статус'],[
 ['Марина С.','Александр С.','90 дней','950 000 ₸','150 000 ₸','300 000 ₸ · сегодня','<span class="status amber">Напомнить</span>'],['Николай П.','Елена П.','90 дней','950 000 ₸','950 000 ₸','—','<span class="status">Оплачено</span>'],['Арман Ж.','Данияр Ж.','120 дней','1 100 000 ₸','550 000 ₸','275 000 ₸ · 3 окт','<span class="status blue">По графику</span>'],['Айгуль Р.','Руслан Р.','90 дней','950 000 ₸','500 000 ₸','225 000 ₸ · просрочено','<span class="status red">Просрочено</span>']
 ]);
 const stock=[['Набор личной гигиены','Гигиена','Алатау','7 шт.','12 шт.','Заказать','red'],['Перчатки нитриловые M','Мед. расходники','Сайран','3 уп.','8 уп.','Заказать','red'],['Средство дезинфицирующее 5 л','Хозяйственные','Алатау','4 кан.','5 кан.','Внимание','amber'],['Бумага A4','Канцелярия','Оба','9 пач.','10 пач.','Внимание','amber'],['Постельный комплект','Быт','Оба','34 шт.','20 шт.','Достаточно',''],['Тест-полоски (учёт)','Мед. расходники','Сайран','12 уп.','10 уп.','Достаточно','']];
 $('#warehouseTable').innerHTML=table(['Позиция','Категория','Филиал','Остаток','Минимум','Состояние'],stock.map(r=>[r[0],r[1],r[2],r[3],r[4],`<span class="status ${r[6]}">${r[5]}</span>`]));
}
function table(headers,rows,type=''){return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr ${type?`data-${type}-row="${type==='lead'?leads[i]?.id:patients[i]?.id}"`:''}>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}

function renderCalls(){
 $('#callQueue').innerHTML=leads.slice(0,8).map((l,i)=>`<div class="call-row ${i<3?'overdue':''}" data-call="${l.id}"><span class="priority">${i+1}</span><div><b>${l.name} · ${l.relation}</b><small>${l.program} · ${l.source} · ${l.phone}</small></div><strong>${l.next}</strong></div>`).join('');
 $$('.call-row').forEach(r=>r.onclick=()=>selectCall(r.dataset.call)); selectCall('marina');
}
function selectCall(id){const l=leads.find(x=>x.id===id)||leads[0];$('#callScript').innerHTML=`<div class="phone-big">☎</div><h2>${l.name}</h2><small>${l.phone} · ${l.relation}</small><div class="script-box"><b>ПОЧЕМУ ЗВОНИМ СЕЙЧАС</b><p>${l.next}. Последний контакт: ${l.age}. Спросить, удалось ли обсудить решение внутри семьи, и предложить понятный следующий шаг.</p></div><div class="script-box"><b>ВАЖНО</b><p>Не давать медицинских обещаний по телефону. При профильных вопросах подключить специалиста центра.</p></div><div class="script-actions"><button class="btn primary" data-action="call-done">Звонок состоялся</button><button class="btn ghost" data-action="no-answer">Нет ответа</button><button class="btn ghost" data-action="book-consult">Консультация</button><button class="btn ghost" data-action="postpone">Перенести</button></div>`;bindActions($('#callScript'))}

function renderReturn(){
 const seg=[['12','Не дозвонились','3 попытки или тишина более 7 дней'],['9','Решили позже','Есть согласованный месяц возврата'],['8','Семья не готова','Нужна повторная семейная консультация'],['8','Вопрос стоимости','Предложить понятный график оплаты']];
 $('#segmentGrid').innerHTML=seg.map(s=>`<button class="segment-card"><b>${s[0]}</b><strong>${s[1]}</strong><span>${s[2]}</span></button>`).join('');
 $('#returnTable').innerHTML=table(['Когда','Клиент','Причина','Последний контакт','Ответственный','Разрешённый канал','Действие'],[
 ['Сегодня 15:30','Ляззат К.','Решили позже','14 сентября','Айгерим','Звонок','<span class="status">Позвонить</span>'],['30 сентября','Ольга В.','Не дозвонились','22 сентября','Руслан','WhatsApp','<span class="status blue">Написать</span>'],['1 октября','Бекзат А.','Семья не готова','18 сентября','Айгерим','Звонок','<span class="status amber">Консультация</span>'],['3 октября','Алия С.','Вопрос стоимости','20 сентября','Руслан','Звонок','<span class="status">График оплаты</span>']
 ]);
}

function renderBranches(){
 $('#branchOverview').innerHTML=[['Алатау','24','18','75%','2','1','Дана С.'],['Сайран','16','13','81%','1','1','Ермек К.']].map(b=>`<article class="branch-block"><header><div><h2>${b[0]}</h2><small>Алматы · руководитель ${b[6]}</small></div><span class="status">Работает</span></header><div class="big-num">${b[2]} <small>/ ${b[1]} мест</small></div><div class="progress"><i style="width:${b[3]}"></i></div><div class="branch-stats"><div><b>${b[4]}</b><small>ожидаются</small></div><div><b>${b[5]}</b><small>выписка</small></div><div><b>${b[3]}</b><small>загрузка</small></div></div></article>`).join('');
 $('#bedMap').innerHTML=[['Алатау · корпус A',6,[2,2,1,2,0,1]],['Алатау · корпус B',6,[2,1,2,2,1,0]],['Сайран · 1 этаж',6,[2,2,2,1,1,0]],['Сайран · 2 этаж',4,[2,2,1,0]]].map((f,fi)=>`<div class="floor"><h3>${f[0]}</h3><div class="rooms">${f[2].map((n,i)=>`<div class="room"><b>Комната ${fi+1}${i+1}</b><div class="beds"><span class="bed ${n>0?'occupied':'free'}"></span><span class="bed ${n>1?'occupied':n===1&&i%2?'planned':'free'}"></span></div></div>`).join('')}</div></div>`).join('');
}

function renderProgram(){
 $('#patientStatus').innerHTML=[['Ожидаются',3],['Адаптация',4],['Активная программа',17],['Стабилизация',6],['К выходу',3],['Постсопровождение',24]].map((s,i)=>`<button class="status-step ${i===2?'active':''}"><b>${s[1]}</b><span>${s[0]}</span></button>`).join('');
 $('#planPanel').innerHTML=`<div class="patient-mini"><span class="avatar">АН</span><div><b>Аскар Н. · 12-й день</b><small>Алатау · куратор Дана С. · доступ ограничен</small></div><button class="link-btn" data-open-patient="askar">Карточка</button></div><div class="plan-steps"><div class="plan-step done"><span>✓</span><div><b>Вводная оценка и согласование плана</b><small>Зафиксировано специалистом</small></div><time>18 сен</time></div><div class="plan-step done"><span>✓</span><div><b>Период адаптации</b><small>Первые 7 дней завершены</small></div><time>25 сен</time></div><div class="plan-step"><span>3</span><div><b>Активная индивидуальная программа</b><small>4 из 12 целей в работе</small></div><time>сейчас</time></div><div class="plan-step"><span>4</span><div><b>Семейная встреча</b><small>Нужно назначить дату</small></div><time>до 3 окт</time></div><div class="plan-step"><span>5</span><div><b>План выхода и 90 дней сопровождения</b><small>Готовится командой</small></div><time>позже</time></div></div>`;
 $('#teamPlan').innerHTML=[['Индивидуальная встреча с куратором','Аскар Н. · Дана','10:30'],['Группа «Ответственность»','8 участников · Дана','11:30'],['Проверить план семейной встречи','Аскар Н. · Айгерим','13:00'],['Обход и фиксация наблюдений','Филиал Сайран · Ермек','16:00'],['Передача смены','Оба филиала','19:30']].map((x,i)=>`<label class="check-item"><input type="checkbox" ${i<1?'checked':''}><span><b>${x[0]}</b><small>${x[1]}</small></span><time>${x[2]}</time></label>`).join('');
}
function renderCalendar(){
 const days=['Пн 29','Вт 30','Ср 1','Чт 2','Пт 3','Сб 4','Вс 5'], hours=['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'];
 let html='<div class="week-grid"><div class="week-head"></div>'+days.map(d=>`<div class="week-head"><b>${d}</b>сентябрь / октябрь</div>`).join('');
 hours.forEach((h,hi)=>{html+=`<div class="hour">${h}</div>`;days.forEach((d,di)=>{let e='';if((hi+di)%6===1)e=`<span class="event ${di%3===1?'blue':di%3===2?'amber':''}">${['Группа','Консультация семьи','Индивидуальная встреча'][di%3]}<br>${di%2?'Сайран':'Алатау'}</span>`;html+=`<div>${e}</div>`})}); html+='</div>';$('#calendar').innerHTML=html;
}
function renderWarehouse(){
 $('#lowStock').innerHTML=`<h2>Нужно заказать</h2>${[['Набор личной гигиены','7 из 12','58%'],['Перчатки нитриловые M','3 из 8','37%'],['Дезинфицирующее средство','4 из 5','80%'],['Бумага A4','9 из 10','90%']].map(x=>`<div class="stock-alert"><b>${x[0]}</b><small>${x[1]} минимального остатка</small><div class="bar"><i style="width:${x[2]}"></i></div><button class="link-btn" data-action="stock-order">В заявку</button></div>`).join('')}`;bindActions($('#lowStock'));
}
function renderAnalytics(){
 const src=[['Google Ads',58,46,'9 заселений'],['Рекомендации',28,22,'5 заселений'],['Органический поиск',18,14,'2 заселения'],['Instagram',12,10,'1 заселение'],['Прочее',10,8,'1 заселение']];
 $('#sourceChart').innerHTML=src.map(x=>`<div class="source-row"><b>${x[0]}</b><div class="bar"><i style="width:${x[2]*2}%"></i></div><strong>${x[1]}</strong><strong>${x[3]}</strong></div>`).join('');
 $('#managerTable').innerHTML=[['Айгерим','64 обращения','11','17,2%'],['Руслан','52 обращения','7','13,5%'],['Общая линия','10 обращений','0','—']].map(x=>`<div class="manager"><span><b>${x[0]}</b><small>${x[1]}</small></span><strong>${x[2]} зас.</strong><strong>${x[3]}</strong></div>`).join('');
 $('#lineChart').innerHTML=[['апр',58,31],['май',64,44],['июн',70,52],['июл',74,61],['авг',78,68],['сен',77,76]].map(x=>`<div class="month-bar"><i style="height:${x[1]}%"></i><i style="height:${x[2]}%"></i><span>${x[0]}</span></div>`).join('');
}
function renderAccess(){
 const rows=[['Роль','Лиды','Мед. часть','Оплаты','Склад','Аналитика'],['Собственник','✓','огранич.','✓','✓','✓'],['Продажи','✓','—','график','—','своя'],['Специалист','контакт','✓','—','—','программа'],['Администратор','заселение','статус','✓','выдача','филиал'],['Кладовщик','—','—','—','✓','склад']];
 $('#accessMatrix').innerHTML=rows.map((r,i)=>`<div class="matrix-row">${r.map((c,j)=>j===0?`<b>${c}</b>`:`<span class="${c==='✓'?'access-yes':c==='—'?'access-no':'access-limited'}">${c}</span>`).join('')}</div>`).join('');
 $('#auditList').innerHTML=[['Айгерим открыла карточку обращения Марины С.','09:42 · отдел продаж'],['Дана обновила этап программы Аскара Н.','09:31 · разрешённая медицинская роль'],['Арман провёл выдачу со склада № W-184','09:12 · филиал Сайран'],['Тимур выгрузил отчёт по рекламе','08:55 · собственник'],['Система закрыла сессию неактивного пользователя','вчера 23:40 · безопасность']].map(x=>`<div class="audit"><b>${x[0]}</b><small>${x[1]}</small></div>`).join('');
}
function renderSignals(){
 $('#signalBoard').innerHTML=[['critical','!','Просроченный звонок Марине','42 минуты · ответственный Айгерим','Позвонить'],['critical','₸','Платёж 225 000 ₸ просрочен','Айгуль Р. · график оплаты','Открыть'],['warning','2','Семейная встреча не назначена','Аскар Н. · до 3 октября','Назначить'],['warning','4','Четыре позиции ниже минимума','Два филиала · склад','Сформировать'],['info','1','Новое заселение без комнаты','Мурат Н. · 2 октября','Разместить'],['info','7','Семь лидов без контакта более 3 часов','Google Ads · сегодняшние','Распределить']].map(x=>`<article class="signal-card ${x[0]}"><span class="signal">${x[1]}</span><div><b>${x[2]}</b><small>${x[3]}</small></div><button>${x[4]}</button></article>`).join('');
}

function openLead(id){const l=leads.find(x=>x.id===id)||leads[0];$('#drawerKicker').textContent='ОБРАЩЕНИЕ · '+l.source.toUpperCase();$('#drawerTitle').textContent=l.name;$('#drawerBody').innerHTML=`<div class="drawer-tabs"><button class="active">Главное</button><button>История</button><button>Задачи</button><button>Документы</button></div><section class="drawer-section"><div class="next-step"><small>РЕКОМЕНДОВАННЫЙ СЛЕДУЮЩИЙ ШАГ</small><b>${l.next}</b><small>Основание: обещанный срок и история контактов. Это не медицинская рекомендация.</small></div></section><section class="drawer-section"><h3>Данные обращения</h3><div class="detail-grid"><div><small>Кто обратился</small><b>${l.relation}</b></div><div><small>Телефон</small><b>${l.phone}</b></div><div><small>Направление</small><b>${l.program}</b></div><div><small>Ориентир программы</small><b>${l.amount}</b></div><div><small>Источник</small><b>${l.source}</b></div><div><small>Ответственный</small><b>${l.owner}</b></div></div></section><section class="drawer-section"><h3>История контактов</h3></section><div class="drawer-timeline"><div class="drawer-event"><b>Создано обращение</b><small>Сегодня 09:08 · ${l.source}</small></div><div class="drawer-event"><b>Первый звонок · 4 мин 18 сек</b><small>Уточнён запрос семьи, согласие на повторный контакт получено</small></div><div class="drawer-event"><b>Отправлена памятка о консультации</b><small>WhatsApp · доставлено</small></div></div><div class="drawer-actions"><button class="btn primary" data-action="call-done">Позвонить</button><button class="btn ghost" data-action="book-consult">Назначить консультацию</button><button class="btn ghost" data-action="return-lead">Вернуть в работу</button></div>`;openDrawer();bindActions($('#drawer'))}
function openPatient(id){const p=patients.find(x=>x.id===id)||patients[0];$('#drawerKicker').textContent='ПАЦИЕНТ · ДОСТУП ПО РОЛИ';$('#drawerTitle').textContent=p.name;$('#drawerBody').innerHTML=`<div class="drawer-tabs"><button class="active">Сводка</button><button>План</button><button>Встречи</button><button>Документы</button></div><section class="drawer-section"><div class="drawer-kpis"><div><small>Этап</small><b>${p.stage}</b></div><div><small>В центре</small><b>${p.day}</b></div><div><small>Филиал</small><b>${p.branch}</b></div></div></section><section class="drawer-section"><h3>Ближайший шаг</h3><div class="next-step"><b>${p.next}</b><small>${p.risk==='—'?'Критических сигналов нет':p.risk}</small></div></section><section class="drawer-section"><h3>Команда и маршрут</h3><div class="detail-grid"><div><small>Куратор</small><b>${p.curator}</b></div><div><small>Специалист</small><b>Ермек К.</b></div><div><small>Семейный консультант</small><b>Айгерим М.</b></div><div><small>План выхода</small><b>В подготовке</b></div></div></section><section class="drawer-section"><h3>Важно о доступе</h3><p style="font-size:10px;color:#677783">Медицинские записи, оценки риска и назначения доступны только уполномоченным специалистам. Менеджеры продаж видят лишь организационный статус: ожидается / заселён / завершил программу.</p></section><div class="drawer-actions"><button class="btn primary" data-action="new-session">Назначить встречу</button><button class="btn ghost" data-action="note">Добавить запись</button></div>`;openDrawer();bindActions($('#drawer'))}
function openDrawer(){$('#drawer').classList.add('open');$('#drawerShade').classList.add('open')}function closeDrawer(){$('#drawer').classList.remove('open');$('#drawerShade').classList.remove('open')}

function openModal(html){$('#modalBody').innerHTML=html;$('#modalShade').classList.add('open');bindActions($('#modalBody'))}function closeModal(){$('#modalShade').classList.remove('open')}
function newLeadModal(){openModal(`<h2>Новое обращение</h2><p>Создаётся в отделе продаж. Медицинские сведения сюда не вносятся.</p><div class="form-grid"><label>Имя обратившегося<input placeholder="Например, Марина"></label><label>Телефон<input placeholder="+7 7__ ___ __ __"></label><label>Кем приходится пациенту<select><option>Родитель</option><option>Супруг / супруга</option><option>Сам пациент</option><option>Другой родственник</option></select></label><label>Источник<select><option>Google Ads</option><option>Входящий звонок</option><option>Сайт</option><option>Рекомендация</option></select></label><label>Направление<select><option>Алкогольная зависимость</option><option>Наркотическая зависимость</option><option>Лудомания</option><option>Нужно уточнить</option></select></label><label>Ответственный<select><option>Айгерим</option><option>Руслан</option></select></label><label class="full">Следующий шаг<textarea>Позвонить и согласовать первичную консультацию</textarea></label></div><button class="btn primary" data-action="save-lead">Создать обращение</button>`)}
function tour(){openModal(`<h2>Как показать демо за 4 минуты</h2><p>Откройте последовательно ключевые экраны — каждый пункт кликабелен.</p><div class="tour-steps"><div class="tour-step"><span>1</span><div><b>Главная</b><small>Вся сеть, два филиала и сигналы собственника.</small></div></div><div class="tour-step"><span>2</span><div><b>Воронка обращений</b><small>Перетащите карточку и откройте Марину.</small></div></div><div class="tour-step"><span>3</span><div><b>Звонки и возврат</b><small>Покажите рекомендацию следующего шага и старую базу.</small></div></div><div class="tour-step"><span>4</span><div><b>Пациенты</b><small>Отдельный защищённый контур и этапы программы.</small></div></div><div class="tour-step"><span>5</span><div><b>Склад и аналитика</b><small>Остатки по филиалам и путь Google Ads → заселение.</small></div></div></div><button class="btn primary" data-action="tour-start">Начать показ</button>`)}
function searchModal(){openModal(`<h2>Быстрый поиск</h2><p>Введите имя, телефон, номер карточки или задачу.</p><label class="search-field" style="max-width:none"><span data-icon="search"></span><input autofocus placeholder="Например, Аскар или +7 701..."></label><div class="tour-steps"><div class="tour-step" data-open-patient="askar"><span>АН</span><div><b>Аскар Н. · пациент</b><small>Алатау · 12-й день · активная программа</small></div></div><div class="tour-step" data-open-lead="marina"><span>МС</span><div><b>Марина С. · обращение</b><small>Google Ads · просрочен звонок</small></div></div></div>`);$$('[data-icon]',$('#modal')).forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24">${icons[el.dataset.icon]}</svg>`);bindDeepLinks($('#modal'))}

function bindActions(root=document){$$('[data-action]',root).forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='new-lead')return newLeadModal();if(a==='save-lead'){closeModal();toast('Обращение создано и назначено Айгерим');return}if(a==='tour-start'){closeModal();showView('dashboard');toast('Шаг 1 из 5 · пульт собственника');return}if(a==='call-done'){toast('Результат звонка сохранён · выберите следующий шаг');return}if(a==='book-consult'){toast('Консультация добавлена в календарь');return}if(a==='return-lead'){toast('Клиент возвращён в основную воронку');return}if(a==='no-answer'){toast('Нет ответа · повторный звонок поставлен на 17:30');return}if(a==='postpone'){toast('Задача перенесена · срок можно изменить в карточке');return}if(a==='stock-order'){toast('Позиция добавлена в заявку снабжению');return}if(a==='inventory'){toast('Открыт черновик инвентаризации филиала «Сайран»');return}if(a==='receipt'){toast('Создан новый документ поступления');return}if(a==='reactivation-plan'){toast('План возврата сформирован: 12 звонков на 7 дней');return}if(a==='new-payment'){toast('Открыт документ оплаты');return}if(a==='new-admission'||a==='new-patient'){toast('Открыт мастер заселения и выбора свободного места');return}if(a==='new-session'){toast('Открыта форма события в расписании');return}if(a==='note'){toast('Запись добавляется в защищённый журнал специалиста');return}if(a==='resolve-all'){toast('6 задач распределены ответственным');return}toast('Действие выполнено в демо-режиме')})}
function bindDeepLinks(root=document){$$('[data-open-lead]',root).forEach(b=>b.onclick=()=>{closeModal();openLead(b.dataset.openLead)});$$('[data-open-patient]',root).forEach(b=>b.onclick=()=>{closeModal();openPatient(b.dataset.openPatient)})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}

function popAt(pop,anchor){const r=anchor.getBoundingClientRect();pop.style.top=`${r.bottom+6}px`;pop.style.left=`${Math.max(8,Math.min(innerWidth-pop.offsetWidth-8,r.left))}px`;pop.classList.toggle('open')}
$('#branchBtn').onclick=()=>popAt($('#branchPop'),$('#branchBtn'));$('#roleBtn').onclick=()=>popAt($('#rolePop'),$('#roleBtn'));
$$('[data-set-branch]').forEach(b=>b.onclick=()=>{$('#branchName').textContent=b.dataset.setBranch;$('#branchPop').classList.remove('open');toast('Фильтр применён: '+b.dataset.setBranch)});
$$('[data-role]').forEach(b=>b.onclick=()=>{const [n,r]=b.dataset.role.split('|');$('#roleName').textContent=n;$('.role-btn small').textContent=r;$('#rolePop').classList.remove('open');toast('Демо переключено на роль: '+r)});
document.addEventListener('click',e=>{if(!e.target.closest('#branchBtn,#branchPop'))$('#branchPop').classList.remove('open');if(!e.target.closest('#roleBtn,#rolePop'))$('#rolePop').classList.remove('open')});
$('#drawerClose').onclick=closeDrawer;$('#drawerShade').onclick=closeDrawer;$('#modalClose').onclick=closeModal;$('#modalShade').onclick=e=>{if(e.target===$('#modalShade'))closeModal()};
$('#tourBtn').onclick=tour;$('#searchBtn').onclick=searchModal;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchModal()}if(e.key==='Escape'){closeDrawer();closeModal()}});
function closeMobile(){$('#sidebar').classList.remove('open');$('#mobileShade').classList.remove('open')}$('#mobileMenu').onclick=()=>{$('#sidebar').classList.add('open');$('#mobileShade').classList.add('open')};$('#sideClose').onclick=closeMobile;$('#mobileShade').onclick=closeMobile;
$$('[data-branch]').forEach(b=>b.onclick=()=>{showView('branches');toast('Открыт филиал «'+b.dataset.branch+'»')});

renderKanban();renderTables();renderCalls();renderReturn();renderBranches();renderProgram();renderCalendar();renderWarehouse();renderAnalytics();renderAccess();renderSignals();bindActions();bindDeepLinks();
$$('[data-lead-row]').forEach(r=>r.onclick=()=>openLead(r.dataset.leadRow));$$('[data-patient-row]').forEach(r=>r.onclick=()=>openPatient(r.dataset.patientRow));
const initial=new URLSearchParams(location.search).get('s')||'dashboard';showView($(`.view[data-page="${initial}"]`)?initial:'dashboard',false);
