import { transcriptText } from './zoom-crm.js';
const BASE='https://pllato-elc-worker.uurraa.workers.dev/api/zoom';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{const d=new Date(v);return Number.isFinite(+d)?new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Almaty',dateStyle:'medium',timeStyle:'short'}).format(d):'Дата не указана';};
export function mountZoomArchive(root,{getToken}) {
  if(!root||root.dataset.mounted)return;
  root.dataset.mounted='true';root.hidden=false;
  const style=document.createElement('style');style.textContent=`
  #zoomArchive{margin:20px 0 28px;padding:22px;border:1px solid var(--border,#d8dde5);border-radius:12px;background:var(--card,#fff);color:var(--text,#172438)}
  #zoomArchive h2{margin:0;font-size:21px}#zoomArchive p{font-size:13px;color:var(--muted,#657284);margin:6px 0 16px}
  #zoomArchive .za-tools,#zoomArchive .za-actions,#zoomArchive .za-pages{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
  #zoomArchive input{flex:1;min-width:180px;padding:10px;border:1px solid #cbd3df;border-radius:6px;background:transparent;color:inherit}
  #zoomArchive button,#zoomArchive a{font:inherit;font-size:12px;padding:8px 11px;border:1px solid #cbd3df;border-radius:6px;background:transparent;color:inherit;cursor:pointer;text-decoration:none}
  #zoomArchive button:disabled{opacity:.5;cursor:default}#zoomArchive .za-primary{background:#173149;color:#fff;border-color:#173149}
  #zoomArchive article{display:grid;grid-template-columns:160px minmax(0,1fr);gap:16px;padding:17px 0;border-bottom:1px solid var(--border,#e4e8ee)}
  #zoomArchive h3{font-size:15px;line-height:1.5;margin:0 0 5px;overflow-wrap:anywhere}#zoomArchive small{display:block;color:var(--muted,#657284);font-size:12px;margin-bottom:9px}
  #zoomArchive .za-pages{justify-content:flex-end;margin-top:14px}#zoomArchive [role=status]{font-size:13px;margin-top:10px}
  .za-dialog{width:min(900px,92vw);max-height:88vh;overflow:auto;padding:24px;border:1px solid #cbd3df;border-radius:10px;color:#172438;background:#fff}.za-dialog::backdrop{background:#11223388}.za-dialog textarea{width:100%;height:50vh;margin:12px 0;font:14px/1.6 system-ui}.za-dialog video,.za-dialog audio{width:100%;max-height:65vh}.za-dialog button{padding:9px 14px;margin:8px 8px 0 0}
  @media(max-width:650px){#zoomArchive article{grid-template-columns:1fr;gap:4px}#zoomArchive{padding:14px}}
  `;document.head.append(style);
  root.innerHTML=`<h2>Встречи Zoom — записи и транскрипты</h2><p>Весь архив встреч в одном месте. Время Алматы (UTC+5). Транскрипт можно скопировать отдельно или вместе с заданием для демо и КП.</p><form class="za-tools"><input aria-label="Поиск встреч Zoom" placeholder="Название, клиент, номер встречи или дата YYYY-MM-DD"><button>Найти</button><button type="button" data-refresh>Обновить</button></form><div role="status" data-status></div><div data-list></div><div class="za-pages"><button data-prev>← Назад</button><span data-page></span><button data-next>Далее →</button></div>`;
  let page=1,query='',meetings=[],sequence=0;
  const status=root.querySelector('[data-status]');
  async function fetchFile(f){const token=await getToken();if(!token)throw new Error('Войдите в портал');const r=await fetch(BASE+'/files/'+encodeURIComponent(f.id),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw new Error('Не удалось прочитать транскрипт');const raw=await r.text();return f.extension.toUpperCase()==='VTT'?transcriptText(raw):raw;}
  function dialog(title){const d=document.createElement('dialog');d.className='za-dialog';const h=document.createElement('h3');h.textContent=title;const content=document.createElement('div'),close=document.createElement('button');close.textContent='Закрыть';close.onclick=()=>d.close();d.append(h,content,close);d.onclose=()=>{d.querySelectorAll('video,audio').forEach(p=>{p.pause();p.removeAttribute('src');p.load();});d.remove();};document.body.append(d);d.showModal();return {d,content};}
  async function showText(text,title){const {content}=dialog(title);const area=document.createElement('textarea');area.readOnly=true;area.value=text;const copy=document.createElement('button');copy.textContent='Копировать';copy.onclick=async()=>{try{await navigator.clipboard.writeText(text);copy.textContent='Скопировано';}catch{area.focus();area.select();}};content.append(copy,area);area.focus();area.select();}
  async function load(){const seq=++sequence;status.textContent='Загружаю архив…';root.querySelector('[data-list]').replaceChildren();try{const token=await getToken();if(!token)throw new Error('Войдите в портал');const r=await fetch(BASE+'/archive?'+new URLSearchParams({q:query,page:String(page)}),{headers:{Authorization:'Bearer '+token},cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Не удалось загрузить архив');if(seq!==sequence)return;meetings=data.meetings;status.textContent=data.total?`Найдено встреч: ${data.total}`:'Встреч с записями пока нет';root.querySelector('[data-page]').textContent=`${page} / ${Math.max(1,Math.ceil(data.total/25))}`;root.querySelector('[data-prev]').disabled=page<=1;root.querySelector('[data-next]').disabled=page*25>=data.total;
      root.querySelector('[data-list]').innerHTML=meetings.map((m,i)=>{const ready=m.files.filter(f=>f.status==='stored');const transcripts=ready.filter(f=>/transcript/i.test(f.kind)&&/^(VTT|TXT)$/i.test(f.extension));return `<article><div><b>${esc(date(m.recording_start))}</b><small>Zoom ${esc(m.meeting_id)}</small></div><div><h3>${esc(m.topic||'Встреча Zoom')}</h3><small>${esc(m.deal_title||'Пока без привязки к сделке')} · ${ready.length} файлов${transcripts.length?' · Транскрипт готов':' · Транскрипта пока нет'}</small><div class="za-actions">${transcripts.length?`<button class="za-primary" data-copy="${i}">Копировать транскрипт</button><button data-read="${i}">Читать</button><button data-brief="${i}">Задание для демо и КП</button>`:''}${ready.filter(f=>/^(MP4|M4A|MP3|WAV)$/i.test(f.extension)).map((f,n)=>`<button data-media="${i}" data-file="${esc(f.id)}">${f.extension.toUpperCase()==='MP4'?'Видео':'Аудио'}${n?' '+(n+1):''}</button>`).join('')}${m.deal_id?`<a href="/team.html#deal/${encodeURIComponent(m.deal_id.replace(/^deal_/,''))}" target="_blank" rel="noopener">Открыть сделку</a>`:''}</div></div></article>`;}).join('');
    }catch(e){if(seq===sequence)status.textContent=e.message;}}
  root.querySelector('form').onsubmit=e=>{e.preventDefault();query=root.querySelector('input').value.trim();page=1;load();};root.querySelector('[data-refresh]').onclick=load;root.querySelector('[data-prev]').onclick=()=>{page--;load();};root.querySelector('[data-next]').onclick=()=>{page++;load();};
  root.querySelector('[data-list]').onclick=async e=>{const b=e.target.closest('button');if(!b)return;b.disabled=true;try{if(b.dataset.media!==undefined){const m=meetings[Number(b.dataset.media)],f=m.files.find(f=>f.id===b.dataset.file);const {content}=dialog(m.topic);const player=document.createElement(f.extension.toUpperCase()==='MP4'?'video':'audio');player.controls=true;player.preload='metadata';player.playsInline=true;const token=await getToken();player.src=BASE+'/files/'+encodeURIComponent(f.id)+'?auth='+encodeURIComponent(token);player.onerror=()=>{status.textContent='Не удалось воспроизвести файл. Обновите архив и попробуйте снова.';};content.append(player);return;}
      const i=Number(b.dataset.copy??b.dataset.read??b.dataset.brief),m=meetings[i];const files=m.files.filter(f=>f.status==='stored'&&/transcript/i.test(f.kind)&&/^(VTT|TXT)$/i.test(f.extension));let text=(await Promise.all(files.map(fetchFile))).join('\n\n');if(b.dataset.brief!==undefined)text=`Подготовь индивидуальное демо и коммерческое предложение по стандартам Pllato из app. Встреча: ${m.topic}. Дата: ${date(m.recording_start)}.\n${m.deal_id?'Сделка: https://pllato.kz/team.html#deal/'+encodeURIComponent(m.deal_id.replace(/^deal_/,''))+'\n':''}Опирайся на запрос клиента ниже. Не выдумывай согласованные цены и сроки; отдельно укажи вопросы, если данных не хватает.\n\nТРАНСКРИПТ ВСТРЕЧИ:\n${text}`;
      if(b.dataset.read!==undefined)await showText(text,m.topic);else{try{await navigator.clipboard.writeText(text);status.textContent=b.dataset.brief!==undefined?'Задание и транскрипт скопированы — вставьте в рабочий чат для подготовки демо и КП.':'Транскрипт скопирован';}catch{await showText(text,'Скопируйте текст');}}
    }catch(error){status.textContent=error.message;}finally{b.disabled=false;}};
  load();
}
