
/* ===== Реквизит ===== */
const bookedOn=(pid,day,skip)=>BOOK.filter(b=>b.p===pid&&b.id!==skip&&b.from<=day&&b.to>=day).reduce((a,b)=>a+b.q,0);
let propDay='2026-10-17';
SC.props=()=>`<div class="hd"><div><h2>Склад реквизита</h2><p>Реквизит не продаётся: он уходит на ваши мероприятия или в аренду и возвращается. Поэтому главное — сколько исправных и сколько свободно на нужную дату. Бронь видят все менеджеры.</p></div>
  <div class="btns"><label class="dsel">Свободно на <input type="date" value="${propDay}" onchange="propDay=this.value;render()"></label><button class="bt p" onclick="card('book')">+ Бронь</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Позиция</th><th>Категория</th><th>Ячейка</th><th class="r">Всего</th><th class="r">Исправно</th><th class="r">В ремонте</th><th class="r">Занято ${dd(propDay)}</th><th class="r">Свободно ${dd(propDay)}</th></tr></thead><tbody>
 ${PROPS.map(p=>{const b=bookedOn(p.id,propDay),f=p.ok-b;return `<tr onclick="card('prop','${p.id}')"><td><b>${esc(p.n)}</b></td><td>${esc(p.cat)}</td><td class="mono">${esc(p.cell)}</td><td class="r">${p.tot}</td><td class="r">${p.ok}</td><td class="r ${p.broken?'warnt':''}">${p.broken||'—'}</td><td class="r">${b||'—'}</td><td class="r"><b class="${f<0?'neg':f===0?'warnt':'pos'}">${f}</b></td></tr>`}).join('')}
 </tbody></table></div>
 ${said('«Один менеджер бронирует определённый объём реквизита на определённую дату… бывает, что пересекаются датой, и один менеджер может не знать, что забронировал другой»')}`;
function bookProp(){const v=id=>document.getElementById(id).value;const p=v('bk_p'),q=+v('bk_q'),fr=v('bk_f'),to=v('bk_t')||fr,ref=v('bk_r');if(!q||q<1){toast('Укажите количество');return}
 const P=RP(p);let worst=P.ok,day=fr;for(let d=fr;d<=to;d=addDays(d,1)){const free=P.ok-bookedOn(p,d);if(free<worst){worst=free;day=d}}
 if(q>worst){document.getElementById('bk_res').innerHTML=`<div class="al r"><b>Нужно ${q} шт, свободно ${Math.max(0,worst)} на ${dd(day)}</b><span>Исправно ${P.ok}, уже забронировано ${bookedOn(p,day)}: ${BOOK.filter(b=>b.p===p&&b.from<=day&&b.to>=day).map(b=>who(b.by)+' — '+b.q+' шт').join(', ')}. Возьмите меньше, другую позицию или договоритесь в чате.</span></div>`;return}
 BOOK.push({id:'B'+(BOOK.length+1),p,q,from:fr,to,ref,by:myKey(),st:ref[0]==='P'?'confirmed':'tentative'});closeM();render();toast(`Забронировано: ${esc(P.n)} — ${q} шт, ${dd(fr)}${to!==fr?'–'+dd(to):''}. Остальные менеджеры видят бронь сразу.`)}
SC.propcal=()=>{
 const days=[];for(let i=0;i<31;i++)days.push(addDays('2026-10-05',i));
 const conf=[];PROPS.forEach(p=>days.forEach(d=>{if(bookedOn(p.id,d)>p.ok)conf.push([p,d])}));
 return `<div class="hd"><div><h2>Брони по датам</h2><p>Каждая клетка — сколько штук занято в этот день. Красная — забронировали больше, чем исправно на складе. Предварительная бронь под сделку сгорает, если сделка не подписана.</p></div><div class="btns"><button class="bt p" onclick="card('book')">+ Бронь</button></div></div>
 ${conf.length?conf.map(c=>`<div class="al r"><b>Конфликт: ${esc(c[0].n)} · ${dd(c[1])}</b><span>Исправно ${c[0].ok}, забронировано ${bookedOn(c[0].id,c[1])}: ${BOOK.filter(b=>b.p===c[0].id&&b.from<=c[1]&&b.to>=c[1]).map(b=>`${who(b.by)} — ${b.q} шт (${refL(b.ref)})`).join('; ')}. <a class="lk" onclick="fixConflict('${c[0].id}','${c[1]}')">Заменить у предварительной брони на стойки-ограждения</a></span></div>`).join(''):'<div class="al g"><b>Конфликтов нет</b><span>Все брони помещаются в исправный остаток.</span></div>'}
 <div class="pan cal"><div class="cg" style="--n:${days.length}"><div class="ch0"></div>${days.map(d=>`<div class="ch ${['сб','вс'].includes(dayOf(d))?'we':''} ${d===TODAY?'td':''}"><b>${d.slice(8)}</b><small>${dayOf(d)}</small></div>`).join('')}
  ${PROPS.map(p=>`<div class="cn"><b>${esc(p.n)}</b><span>исправно ${p.ok}</span></div>${days.map(d=>{const b=bookedOn(p.id,d);return `<div class="cc ${b>p.ok?'bad':b?'on':''}" title="${b} из ${p.ok}">${b||''}</div>`}).join('')}`).join('')}</div></div>`;
};
function fixConflict(pid,day){const b=BOOK.filter(x=>x.p===pid&&x.from<=day&&x.to>=day&&x.st==='tentative').pop();if(!b){toast('Подтверждённые брони меняет только руководитель — напишите в чат.');return}b.p='R7';render();toast(`Бронь ${who(b.by)} переведена на стойки-ограждения — конфликт снят, ${who(b.by)} получил уведомление.`)}
SC.revision=()=>`<div class="hd"><div><h2>Ревизия, выдача, поломки</h2><p>Кладовщик пересчитывает склад с телефона: ввёл факт — система показала расхождение, причину и действие. Было 10 указателей — стало 7, и все брони сразу считают от семи.</p></div><div class="btns"><button class="bt p" onclick="doRev()">Провести ревизию</button></div></div>
 <div class="g21"><div class="pan"><h3>Пересчёт · ${dlong(TODAY)}</h3><div class="tw"><table class="t"><thead><tr><th>Позиция</th><th class="r">По учёту</th><th class="r">Факт</th><th class="r">Разница</th></tr></thead><tbody>
  ${PROPS.map(p=>`<tr><td>${esc(p.n)}<span class="sub">${esc(p.cell)}</span></td><td class="r">${p.ok}</td><td class="r"><input class="qin" id="rv_${p.id}" value="${p.ok}" onchange="revDiff('${p.id}',this.value)"></td><td class="r" id="rd_${p.id}">—</td></tr>`).join('')}
 </tbody></table></div></div>
 <div><div class="pan"><h3>Журнал ревизий и поломок</h3>${REVLOG.map(r=>`<div class="tli bad"><span class="who">${dd(r.d)} · ${who(r.who)}</span><b>${esc(RP(r.p).n)}: ${r.was} → ${r.now}</b><p>${esc(r.why)} · ${esc(r.act)}</p></div>`).join('')}</div>
 <div class="pan"><h3>Выдача и возврат</h3>${ISSUES.map((x,i)=>`<div class="kv"><span>${dd(x.d)} · ${esc(x.kind)} · ${esc(RP(x.p).n)} × ${x.q}<span class="sub">${refL(x.ref)}${x.note?' · '+esc(x.note):''}</span></span><b>${x.st==='done'?'<span class="tag g">проведено</span>':`<button class="bt" onclick="ISSUES[${i}].st='done';render();toast('Выдача проведена: фото состояния и подпись получателя в карточке.')">Выдать</button>`}</b></div>`).join('')}</div></div></div>
 ${said('«Чек, который отвечает за хранение на складе, делает периодические ревизии и понимает, что у него там три указателя сломались… помечают, что у него теперь не десять указателей, а семь»')}`;
function revDiff(id,v){const p=RP(id),n=+v,el=document.getElementById('rd_'+id);if(el)el.innerHTML=n===p.ok?'—':`<b class="${n<p.ok?'neg':'pos'}">${n-p.ok>0?'+':''}${n-p.ok}</b>`}
function doRev(){let c=0;PROPS.forEach(p=>{const i=document.getElementById('rv_'+p.id);if(!i)return;const n=+i.value;if(n!==p.ok&&n>=0){REVLOG.unshift({d:TODAY,who:'SE',p:p.id,was:p.ok,now:n,why:'Ревизия',act:n<p.ok?'в ремонт / списать':'найдено'});p.broken+=Math.max(0,p.ok-n);p.ok=n;c++}});render();toast(c?`Ревизия проведена: изменено позиций — ${c}. Брони пересчитаны от нового остатка.`:'Расхождений нет — ревизия записана.')}

/* ===== Аналитика ===== */
SC.analytics=()=>{
 const zadel=DEALS.filter(d=>['confirmed','contract'].includes(d.st));
 return `<div class="hd"><div><h2>Продажи и конверсия</h2><p>Конверсия по этапам, задел, план-факт, выигрыши и потери по направлениям и форматам отбора. Всё считается из воронки — без ручных сводов в Excel.</p></div><div class="btns"><button class="bt" onclick="act('export')">Выгрузить</button></div></div>
 <div class="g2"><div class="pan"><h3>Конверсия по этапам · III квартал</h3>${FUNNEL.map((f,i)=>`<div class="fr"><span>${f[0]}</span><div class="bar"><i style="--w:${pct(f[1],FUNNEL[0][1])}%"></i></div><b>${f[1]}${i?` · ${pct(f[1],FUNNEL[i-1][1])}%`:''}</b></div>`).join('')}<p class="mini">Из заявки в подписанный договор — ${pct(FUNNEL[6][1],FUNNEL[0][1])}%. Больше всего теряем между защитой и подтверждением.</p></div>
 <div class="pan"><h3>Задел: подтверждено, но не подписано</h3>${zadel.map(d=>`<div class="kv"><span>${dealL(d.id)}<span class="sub">${esc(CL(d.cl).n)} · ${stTag(d.st)}</span></span><b>${tg(d.sum)}</b></div>`).join('')}<div class="kv big"><span>Итого задел</span><b>${tg(zadel.reduce((a,d)=>a+d.sum,0))}</b></div></div></div>
 <div class="pan"><h3>План-факт по месяцам, млн ₸</h3><div class="pf">${PLANFACT.map(m=>`<div class="pfc"><div class="pfb"><i class="p" style="height:${m[1]/90*100}%"></i><i class="f ${m[2]<m[1]?'lo':''}" style="height:${m[2]/90*100}%"></i></div><b>${String(m[2]||'—').replace('.',',')}</b><small>${m[0]} · план ${m[1]}</small></div>`).join('')}</div><div class="legend"><span><i style="background:var(--card3)"></i>план</span><span><i style="background:var(--acc)"></i>факт</span><span><i style="background:var(--warn)"></i>ниже плана</span></div></div>
 <div class="g2"><div class="pan"><h3>Направления</h3><div class="tw"><table class="t"><thead><tr><th>Направление</th><th class="r">Выиграно</th><th class="r">Проиграно</th><th class="r">Win rate</th><th class="r">Выручка</th><th class="r">Маржа</th></tr></thead><tbody>${BYDIR.map(b=>`<tr><td>${dirTag(b.d)}</td><td class="r">${b.won}</td><td class="r">${b.lost}</td><td class="r">${pct(b.won,b.won+b.lost)}%</td><td class="r">${mln(b.rev)}</td><td class="r">${b.mg}%</td></tr>`).join('')}</tbody></table></div></div>
 <div class="pan"><h3>Формат отбора</h3><div class="tw"><table class="t"><thead><tr><th>Формат</th><th class="r">Сделок</th><th class="r">Выиграно</th><th class="r">Конверсия</th></tr></thead><tbody>${BYTEN.map(b=>`<tr><td>${TENDER[b.k]}</td><td class="r">${b.n}</td><td class="r">${b.won}</td><td class="r">${pct(b.won,b.n)}%</td></tr>`).join('')}</tbody></table></div>
  <h3 style="margin-top:12px">Почему проигрываем</h3><div class="kv"><span>Цена</span><b>5</b></div><div class="kv"><span>Перенос или отмена мероприятия</span><b>3</b></div><div class="kv"><span>Выбрали агентство клиента</span><b>1</b></div></div></div>
 ${said('«Нам нужно понимать конверсию, сколько проектов в работе, сколько подтверждены, но не подписаны — хороший задел… план-факт… сколько проектов мы потеряли или реализовали в направлении маркетинг, HR, B2G»')}`;
};
SC.sources=()=>`<div class="hd"><div><h2>Источники и путь клиента</h2><p>Источник записывается в момент заявки: UTM сайта, номер WhatsApp, кнопка 2ГИС, Direct. Дальше система ведёт его до выручки — видно, какой канал приносит деньги, а не просто заявки.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Источник</th><th>Путь клиента</th><th class="r">Заявок</th><th class="r">Сделок</th><th class="r">Конверсия</th><th class="r">Выручка</th><th class="r">Выручка на заявку</th></tr></thead><tbody>
 ${SOURCES.map(s=>`<tr><td><b>${esc(SRC[s.k])}</b></td><td class="mini">${esc(s.path)}</td><td class="r">${s.leads}</td><td class="r">${s.deals}</td><td class="r">${pct(s.deals,s.leads)}%</td><td class="r">${mln(s.rev)}</td><td class="r"><b>${mln(s.rev/s.leads)}</b></td></tr>`).join('')}
 </tbody></table></div>
 <div class="note"><b>Расход на рекламу</b><p>Если вносить бюджет Google Ads и Instagram по месяцам, рядом появится цена заявки и окупаемость канала.</p></div>
 ${said('«Запрос пришёл с сайта. На сайт человек попал через Google-рекламу, или через наш Instagram, или через 2ГИС, или по рекомендации… путь клиента нам тоже важно понимать»')}`;
SC.managers=()=>`<div class="hd"><div><h2>План-факт менеджеров · IV квартал</h2><p>План у каждого менеджера, факт — по подписанным договорам. Рядом — конверсия и средний чек: видно, кому помочь со сделками, а кому — с новыми заявками.</p></div></div>
 ${MGRS.map(m=>`<div class="pan mg"><div class="mgh">${av(m.k)}<div><b>${esc(TEAM[m.k].f)}</b><span>${esc(TEAM[m.k].r)}</span></div><strong>${pct(m.fact,m.plan)}%</strong></div><div class="bar big"><i style="--w:${Math.min(100,pct(m.fact,m.plan))}%"></i></div>
  <div class="mgk"><div><small>План</small><b>${mln(m.plan)}</b></div><div><small>Факт</small><b>${mln(m.fact)}</b></div><div><small>Сделок в работе</small><b>${m.deals}</b></div><div><small>Выиграно</small><b>${m.won}</b></div><div><small>Конверсия</small><b>${m.conv}%</b></div><div><small>Средний чек</small><b>${mln(m.avg)}</b></div></div></div>`).join('')}`;

/* ===== Компания ===== */
SC.kb=()=>`<div class="hd"><div><h2>База знаний и онбординг</h2><p>Всё, что сейчас живёт в головах и чатах: как мы продаём, шаблоны, регламенты реализации и склада. Новичок открывает одну страницу и проходит чек-лист первой недели.</p></div><div class="btns"><button class="bt p" onclick="act('kbnew')">+ Статья</button></div></div>
 <div class="g21"><div class="kbg">${KB.map(s=>`<div class="pan"><h3>${esc(s.s)}</h3>${s.items.map(x=>`<a class="kbi" onclick="act('kbopen')">${esc(x)}</a>`).join('')}</div>`).join('')}</div>
 <div class="pan"><h3>Онбординг новичка · первая неделя</h3><p>Камила, ивент-ассистент · вышла 28.09</p><div class="bar"><i class="g" style="--w:${pct(ONB.filter(o=>o[1]).length,ONB.length)}%"></i></div><p class="mini">${ONB.filter(o=>o[1]).length} из ${ONB.length}</p>
  ${ONB.map((o,i)=>`<div class="tk ${o[1]?'done':''}"><span class="bx ${o[1]?'on':''}" onclick="ONB[${i}][1]=!ONB[${i}][1];render()">${o[1]?'✓':''}</span><div><b>${esc(o[0])}</b></div></div>`).join('')}</div></div>
 ${said('«Онбординг людей, когда джун приходит, и в одном месте собрано всё, что ему нужно знать сразу»')}`;
SC.roles=()=>{
 const areas=[['Входящие и воронка',['IN','DS','AB']],['Сметы и маржа',['IN','DS','AB']],['Креатив',['IN','DS','AB','AS']],['Проекты и задачи',['IN','MK','AS','RT']],['Бюджеты и оплаты',['IN','RT','AG']],['Реквизит',['IN','DS','AB','RT','SE']],['Аналитика',['IN','DS']],['База знаний',['IN','DS','AB','MK','AS','RT','SE','AG']]];
 const R=Object.entries(ROLES);
 return `<div class="hd"><div><h2>Роли и структура</h2><p>У каждого руководителя — свой контур. Руководитель продаж не видит задачи реализации, проджект — переписку отдела продаж, бухгалтерия — только документы и оплаты. Права меняет операционный директор.</p></div></div>
 <div class="org">${[['IN',[]],['DS',['AB','TM']],['MK',[]],['AS',['ZH','OL']],['RT',['EK','KA']],['SE',['DA','NU']],['AG',[]]].map(([h,s],i)=>`<div class="onode ${i===0?'top':''}"><div class="oh">${av(h)}<b>${esc(TEAM[h].f)}</b><span>${esc(TEAM[h].r)}</span></div>${s.map(k=>`<div class="os">${av(k)} ${esc(TEAM[k].f)}<span>${esc(TEAM[k].r)}</span></div>`).join('')}</div>`).join('')}</div>
 <div class="pan"><h3>Кто что видит</h3><div class="tw"><table class="t mx"><thead><tr><th>Раздел</th>${R.map(([k,v])=>`<th class="c">${esc(v.av)}<span>${esc(k)}</span></th>`).join('')}</tr></thead><tbody>
 ${areas.map(a=>`<tr><td>${a[0]}</td>${R.map(([k,v])=>`<td class="c">${a[1].includes(v.p)?'<b class="pos">●</b>':'<span class="mini">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>
 ${said('«Руководителю отдела реализации вовсе не обязательно быть в курсе задач отдела продаж»')}`;
};
SC.mobile=()=>`<div class="hd"><div><h2>Мобильная версия</h2><p>Та же система в браузере телефона, ярлык на рабочий стол. Менеджер отвечает клиенту, проджект ведёт тайминг на площадке, склад выдаёт реквизит с фото.</p></div></div>
 <div class="phones">
  <div class="phone"><div class="pht"><b>Алина · сделки</b><small>сегодня 4 задачи</small></div><div class="pb">${DEALS.filter(d=>d.mgr==='AB'&&!['lost','won'].includes(d.st)).slice(0,4).map(d=>`<div class="pi"><span>${esc(CL(d.cl).n)}<small>${STGOF(d.st).n}</small></span><b>${d.sum?mln(d.sum):'—'}</b></div>`).join('')}<div class="pbtn" onclick="act('wa')">Ответить в WhatsApp</div></div></div>
  <div class="phone"><div class="pht"><b>Руслан · тайминг 18.10</b><small>караван-сарай · сейчас ${ROS[rosNow]?ROS[rosNow].t:'—'}</small></div><div class="pb">${ROS.slice(4,9).map(r=>`<div class="pi"><span>${r.t} · ${esc(r.n.slice(0,34))}…</span><b>${r.done?'✓':''}</b></div>`).join('')}<div class="pbtn" onclick="shiftRos(${rosNow<0?0:rosNow},15)">Сдвинуть на +15 мин</div></div></div>
  <div class="phone"><div class="pht"><b>Серик · склад</b><small>выдача 09.10 · Qazaq Retail</small></div><div class="pb">${ISSUES.filter(x=>x.st==='plan').map(x=>`<div class="pi"><span>${esc(RP(x.p).n)}</span><b>${x.q} шт</b></div>`).join('')}<div class="pi"><span>Фото состояния</span><b>2 из 2</b></div><div class="pbtn" onclick="act('issue')">Выдать Даурену</div></div></div>
 </div>`;
SC.integr=()=>`<div class="hd"><div><h2>Каналы и интеграции</h2><p>Что подключаем в стандартном пакете и что — по желанию. Телефонию оставляем вашу: звонок из карточки и запись разговора в истории.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Канал</th><th>Как работает</th><th>Статус</th></tr></thead><tbody>
 ${[['WhatsApp рабочего номера','Заявки и переписка в карточке, клиентские группы проектов. Провайдер — около 5 000 ₸ в месяц за номер','в пакете'],['Почта','Письма с заявками и вложениями падают во входящие и в карточку сделки','в пакете'],['Ваша телефония','Звонок из карточки, запись разговора и пропущенные — во входящих','в пакете'],['Форма сайта и UTM','Источник и рекламная кампания записываются в сделку','в пакете'],['Instagram Direct','Сообщения во входящих с источником Instagram','в пакете'],['2ГИС','Звонки с кнопки 2ГИС помечаются источником','в пакете'],['ЭЦП НУЦ РК · NCALayer','Подписание договоров и актов, клиент подписывает по ссылке','в пакете'],['Telegram-уведомления','Задачи, брони, отчёт в 09:00 — каждому свой','в пакете'],['Adesk','Передача проектов и оплат по API','по желанию'],['1С бухгалтерии на аутсорсе','Выгрузка счетов и актов для бухгалтера','по желанию']].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td><span class="tag ${x[2]==='в пакете'?'g':'w'}">${x[2]}</span></td></tr>`).join('')}
 </tbody></table></div>`;
SC.migrate=()=>`<div class="hd"><div><h2>Переезд с amoCRM</h2><p>Лицензия amoCRM заканчивается в конце октября. Ядро — входящие, воронка, карточка сделки, сметы, документы — поднимаем за две недели, и продажи переходят сюда до конца лицензии. Остальное шлифуем параллельно.</p></div></div>
 <div class="tl big">${[['01.10','Показ демо','Тест-драйв: всё кликается, роли переключаются',1],['после 10%','Старт','Выгрузка контактов и компаний из amoCRM, ваш файл этапов и аналитики',0],['+2 недели','Ядро в работе','Входящие, воронка с вашими этапами, сделка, сметы, документы — продажи переходят из amoCRM',0],['+3–4 недели','Проекты и реквизит','Портфель, задачи, тайминг, чаты, склад реквизита, бронь и ревизия',0],['+4–6 недель','Аналитика и база знаний','Конверсия, задел, план-факт, источники, LTV, онбординг — приёмка',0]].map(x=>`<div class="tli ${x[3]?'ok':'on'}"><span class="who">${x[0]}</span><b>${x[1]}</b><p>${x[2]}</p></div>`).join('')}</div>
 <div class="g2"><div class="pan"><h3>Что переносим из amoCRM</h3><div class="li"><i>✓</i><span>Контакты и компании с телефонами и почтой</span></div><div class="li"><i>✓</i><span>Открытые сделки — с этапом по вашей новой воронке</span></div><div class="li no"><i>—</i><span>Старые закрытые сделки — по желанию, архивом</span></div></div>
  <div class="pan"><h3>Что нужно от вас</h3><div class="li n"><i>1</i><span>Файл с описанием этапов воронки</span></div><div class="li n"><i>2</i><span>Файл с аналитикой, которую вы уже продумали</span></div><div class="li n"><i>3</i><span>Выгрузка из amoCRM (Excel)</span></div><div class="li n"><i>4</i><span>Шаблоны договора, счёта, акта</span></div></div></div>
 ${said('«Немножко смущает тот момент, что у нас заканчивается лицензия на amo… успеть внедрить свою собственную систему, переехать в неё и отказаться»','Ирина ответила: через две недели подключаетесь с воронкой продаж, остальное — параллельно.')}`;
