
const SC={};
const stg=k=>{const s=STN(k);return `<span class="stg" style="--sc:${s.c}">${s.n}</span>`};
const PREQ=[
 {id:'З-311',who:'Аслан',why:'Сделка С-1190 · не хватает Ø16',g:'G4',q:20,sup:'ТОО «КарМет Трейд»',pr:309000,st:'agree',d:'05.10'},
 {id:'З-310',who:'Склад',why:'Ниже минимума',g:'G10',q:6,sup:'ТОО «ТехноПауэр»',pr:258000,st:'order',d:'04.10'},
 {id:'З-309',who:'Склад',why:'Ниже минимума',g:'G7',q:200,sup:'ТОО «Изол Центр»',pr:7200,st:'way',d:'02.10'},
 {id:'З-308',who:'Айгерим',why:'Сделка С-1186',g:'G9',q:6,sup:'«Shandong Mixer» (Китай)',pr:104000,st:'way',d:'28.09'},
 {id:'З-306',who:'Склад',why:'Ниже минимума',g:'G1',q:2400,sup:'АО «Карцемент»',pr:2100,st:'done',d:'24.09'}
];
const PST=[['new','Новая'],['agree','Согласование директора'],['order','Заказано, ждём счёт'],['way','Оплачено, в пути'],['done','Принято на склад']];
SC.today=()=>{const open=DEALS.filter(d=>d.st!=='done');const inv=DEALS.filter(d=>d.st==='inv').reduce((a,d)=>a+dSum(d),0);
 return `<div class="hd"><div><h2>Пульт исполнительного директора · ${TODAY}</h2><p>Всё в одном месте: продажи, склад, закупки и деньги. Не нужно ходить по сотрудникам и просить скинуть отчёт — открыли с телефона и видите.</p></div><div class="btns"><button class="bt" onclick="toast('Отчёт за день отправлен собственнику.')">Отчёт собственнику</button></div></div>
 <div class="wid">
  <div class="clk" onclick="go('funnel')"><small>Сделок в работе</small><b>${open.length}</b><span>на ${mln(open.reduce((a,d)=>a+dSum(d),0))}</span></div>
  <div class="clk" onclick="go('payments')"><small>Ждём оплату по счетам</small><b class="w">${mln(inv)}</b><span>${DEALS.filter(d=>d.st==='inv').length} счёт</span></div>
  <div class="clk" onclick="go('cash')"><small>Касса сегодня</small><b class="g">${tg(CASHDAY.reduce((a,c)=>a+c.s,0))}</b><span>${CASHDAY.length} поступления</span></div>
  <div class="clk" onclick="go('catalog')"><small>Ниже минимума</small><b class="r">${GOODS.filter(g=>g.q-g.res<g.min).length}</b><span>позиций на складе</span></div>
  <div class="clk" onclick="go('preq')"><small>Закупки</small><b>${PREQ.filter(p=>p.st!=='done').length}</b><span>${PREQ.filter(p=>p.st==='agree').length} ждёт вашего согласия</span></div>
 </div>
 <div class="g3">
  <div class="pan zone"><h3>1 · Менеджеры</h3><p class="mini">звонки и переписка</p>${[['Звонков сегодня','74'],['Минут на линии','268'],['Сообщений клиентам','131'],['Без ответа больше 30 минут','2']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<button class="bt sm" onclick="go('control')">Записи и переписка →</button></div>
  <div class="pan zone"><h3>2 · Бухгалтерия</h3><p class="mini">пришло · продано · оплачено</p>${[['Приход сегодня','2 накладные · 4,7 млн'],['Реализация сегодня','3 накладные · 6,2 млн'],['Оплаты клиентов','5,4 млн'],['Расхождение склад / учёт','нет']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<button class="bt sm" onclick="go('realize')">Приход и реализация →</button></div>
  <div class="pan zone"><h3>3 · Снабжение</h3><p class="mini">заявки и поставщики</p>${[['Заявок в работе',PREQ.filter(p=>p.st!=='done').length],['Ждут согласования',PREQ.filter(p=>p.st==='agree').length],['В пути','2 поставки'],['Переписок с поставщиками','18 за неделю']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<button class="bt sm" onclick="go('preq')">Заявки на закупку →</button></div>
 </div>
 <div class="g2"><div class="pan"><h3>Требует решения</h3>
  <div class="rf bad" onclick="go('preq')"><i></i><div><b>З-311 · закупка арматуры Ø16, 20 т на 6,18 млн</b><span>под сделку С-1190 «Береке Строй» — ждёт вашего согласия</span></div></div>
  <div class="rf" onclick="go('advances')"><i></i><div><b>Аванс на командировку — Ерик, Караганда, 85 000 ₸</b><span>встреча с поставщиком арматуры 07–08.10</span></div></div>
  <div class="rf" onclick="go('control')"><i></i><div><b>Клиент ТОО «Алау Инжиниринг» ждёт ответа 42 минуты</b><span>Айгерим · вопрос по сроку поставки бетономешалок</span></div></div>
  <div class="rf" onclick="go('wagons')"><i></i><div><b>Вагон на Павлодар — подача завтра 09:00</b><span>С-1187 · цемент навалом 60 т</span></div></div></div>
 <div class="pan"><h3>Продажи за неделю</h3>${[['пн',3.1],['вт',4.4],['ср',2.6],['чт',5.2],['пт',6.2]].map(x=>`<div class="hb"><span>${x[0]}</span><i style="width:${x[1]*15}%"></i><b class="mono">${String(x[1]).replace('.',',')} млн</b></div>`).join('')}<p class="mini">Маржа недели — 17,4 %. Лучший менеджер — Аслан, 9,8 млн.</p></div></div>
 ${said('«Чтобы ко мне не бегали сотрудники… я могу зайти в свою CRM и в одном лице увидеть, что мне нужно».')}`};

const CALLS=[
 {m:'AS',calls:31,min:118,msg:52,late:0,rec:[['исх.','11:42','6:10','С-1184 · Нур-Сити Строй — согласовали вагон до Караганды'],['вход.','14:05','2:30','новый клиент — профнастил']]},
 {m:'MR',calls:24,min:86,msg:41,late:1,rec:[['исх.','10:15','4:48','С-1185 · скидка на профнастил от 400 м²'],['исх.','15:30','—','не дозвонился']]},
 {m:'AI',calls:19,min:64,msg:38,late:1,rec:[['вход.','12:20','3:55','С-1186 · Алау Инжиниринг — сравнивают цены']]}
];
SC.control=()=>`<div class="hd"><div><h2>Контроль трёх зон</h2><p>Ваши три критерия: менеджеры — звонки и переписка; бухгалтерия — что пришло и что продано; снабжение — с кем и о чём договаривались. Всё записывается и хранится в карточках.</p></div></div>
 <div class="pan"><h3>1 · Менеджеры — звонки и переписка</h3><div class="tw"><table class="t"><thead><tr><th>Менеджер</th><th class="r">Звонков</th><th class="r">Минут</th><th class="r">Сообщений</th><th class="r">Без ответа &gt;30 мин</th><th>Последние записи</th></tr></thead><tbody>${CALLS.map(c=>`<tr><td><b>${MGR[c.m]}</b></td><td class="r mono">${c.calls}</td><td class="r mono">${c.min}</td><td class="r mono">${c.msg}</td><td class="r mono ${c.late?'neg':''}">${c.late}</td><td>${c.rec.map(r=>`<div class="rec"><span class="tag">${r[0]}</span> ${r[1]} · ${r[2]} · ${esc(r[3])} ${r[2]!=='—'?`<a class="lk" onclick="toast('Запись разговора воспроизводится.')">слушать</a>`:''}</div>`).join('')}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="g2"><div class="pan"><h3>2 · Бухгалтерия — приход и реализация</h3><div class="tw"><table class="t"><thead><tr><th>Документ</th><th>Кто</th><th class="r">Сумма</th><th>Склад</th></tr></thead><tbody>${[['Приход № 412 · АО «Карцемент»','Сауле','5 040 000','принято 2 400 меш'],['Приход № 413 · ТОО «Изол Центр»','Сауле','0','в пути'],['Реализация № 918 · КазДорСтрой','Гаухар','4 245 600','отгружено'],['Реализация № 919 · ЭнергоМонтаж KZ','Гаухар','1 335 000','к отгрузке 06.10']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="r mono">${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div><p class="mini">Остаток на складе меняется сам при проведении прихода и реализации — сверять с отдельной базой не нужно.</p></div>
 <div class="pan"><h3>3 · Снабжение — поставщики</h3>${[['Ерик → «КарМет Трейд»','звонок 5:12 · цена Ø16 309 000 ₸/т, отгрузка 3 дня'],['Ерик → «Shandong Mixer»','переписка · инвойс на 6 бетономешалок, в пути до 12.10'],['Ерик → «ТехноПауэр»','звонок 2:40 · генераторы — счёт завтра']].map(r=>`<div class="kv"><span>${r[0]}</span><b class="mini">${r[1]}</b></div>`).join('')}<button class="bt sm" onclick="go('suppliers')">Все поставщики →</button></div></div>
 ${said('«Три главных критерия: контроль менеджеров — полностью звонки, переписки; контроль бухгалтерии — что пришло, товар продан; контроль снабжения — снабженцы общались, и всё тоже сохранялось».')}`;

SC.reports=()=>`<div class="hd"><div><h2>Отчёты в одной таблице</h2><p>Продажи, маржа, остатки, закупки, касса — одна таблица за выбранный период. Без запросов бухгалтеру и без выгрузок из 1С.</p></div><div class="btns"><button class="bt" onclick="toast('Таблица выгружена в Excel.')">Выгрузить в Excel</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Показатель</th><th class="r">Сегодня</th><th class="r">Неделя</th><th class="r">Сентябрь</th><th class="r">Динамика</th></tr></thead><tbody>${[['Продажи, ₸','6 180 000','21 500 000','84 300 000','+11 %'],['Маржа, ₸','1 070 000','3 740 000','14 600 000','+8 %'],['Маржа, %','17,3','17,4','17,3','—'],['Сделок закрыто','3','14','61','+6'],['Средний чек, ₸','2 060 000','1 535 000','1 382 000','−3 %'],['Закуплено, ₸','5 040 000','12 900 000','61 200 000','+4 %'],['Оплаты клиентов, ₸','5 400 000','19 800 000','80 100 000','+9 %'],['Долг клиентов, ₸','—','—','7 400 000','−12 %'],['Остаток склада, ₸','—','—','58 600 000','+2 %'],['Звонков менеджеров','74','362','1 540','+14 %'],['Касса (наличные), ₸','1 260 000','3 100 000','11 900 000','—']].map(r=>`<tr><td><b>${r[0]}</b></td>${r.slice(1).map((x,i)=>`<td class="r mono ${i===3&&x.startsWith('−')?'neg':i===3&&x.startsWith('+')?'pos':''}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 ${said('«Чтобы всё отчётно было в одной таблице».')}`;

const myD=()=>role==='Менеджер'?DEALS.filter(d=>d.m==='AS'):DEALS;
SC.funnel=()=>`<div class="hd"><div><h2>Сделки · канбан${role==='Менеджер'?' · мои':''}</h2><p>Заявка → подбор и расчёт → КП → счёт → оплачен → отгрузка → закрыта. На карточке — клиент, товары, сумма и маржа. Не хватает товара на складе — карточка подсвечена, снабженцу уходит заявка.</p></div><div class="btns"><button class="bt p" onclick="card('newdeal')">+ Сделка</button></div></div>
 <div class="kb">${ST.map(s=>{const X=myD().filter(d=>d.st===s.k);return `<div class="kc" style="--sc:${s.c}"><div class="kh"><b>${s.n}</b><span>${X.length}</span></div>${X.map(d=>{const lack=d.lines.some(([g,q])=>GD(g).q<q);return `<div class="kd ${lack?'alarm':''}" onclick="openDeal('${d.id}')"><div class="kt"><b>${d.id}</b><span class="src">${d.src}</span></div><div class="kr">${esc(d.cl)}</div><div class="km">${d.lines.map(([g,q])=>esc(GD(g).n.split(',')[0])).join(' · ')}</div><div class="kf"><span>${MGR[d.m]}</span><b class="mono">${mln(dSum(d))}</b></div>${lack?'<div class="lack">не хватает на складе</div>':''}</div>`}).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 ${said('«Вести, конечно, канбан нужен; чтобы запись разговоров была, переписки, чтобы записи были».')}`;

function openDeal(id){if(!allowed('deal')){toast('Карточка сделки этой роли недоступна.');return}curDeal=id;go('deal')}
SC.deal=()=>{const d=DL(curDeal)||DEALS[0];const si=STI(d.st);const S=dSum(d),C=dCost(d);
 return `<div class="hd"><div><div class="crumb"><a onclick="go('funnel')">Сделки</a> / ${d.id}</div><h2>${d.id} · ${esc(d.cl)}</h2><p>контакт ${esc(d.ct)} · источник ${d.src} · менеджер ${MGR[d.m]}</p></div><div class="btns">${d.st!=='done'?`<button class="bt p" onclick="nextSt('${d.id}')">→ ${ST[si+1].n}</button>`:''}<button class="bt" onclick="go('invoice')">Счёт и КП</button></div></div>
 <div class="stp">${ST.map((x,i)=>`<div class="${i<si?'ok':i===si?'on':''}" style="--sc:${x.c}"><i>${i<si?'✓':i+1}</i><span>${x.n}</span></div>`).join('')}</div>
 <div class="pan"><h3>Товары</h3><div class="tw"><table class="t"><thead><tr><th>Товар</th><th class="r">Кол-во</th><th class="r">На складе</th><th class="r">Цена</th><th class="r">Сумма</th></tr></thead><tbody>${d.lines.map(([g,q])=>{const x=GD(g);return `<tr class="${x.q<q?'rowbad':''}"><td>${esc(x.n)}</td><td class="r mono">${fmt(q)} ${x.u}</td><td class="r mono ${x.q<q?'neg':''}">${String(x.q).replace('.',',')}</td><td class="r mono">${fmt(x.sell)}</td><td class="r mono">${fmt(x.sell*q)}</td></tr>`}).join('')}<tr class="total"><td colspan="4">Итого · маржа ${pct(S-C,S)} %</td><td class="r mono">${fmt(S)}</td></tr></tbody></table></div>${d.lines.some(([g,q])=>GD(g).q<q)?`<button class="bt sm p" onclick="go('preq');toast('Заявка на закупку З-311 уже создана по этой сделке.')">Заявка на закупку недостающего</button>`:''}</div>
 <div class="g2"><div class="pan"><h3>Переписка</h3><div class="chat">${[['in',esc(d.ct)+' · 10:02','Добрый день, нужна цена с доставкой.'],['out',MGR[d.m]+' · 10:15','Здравствуйте! Отправил КП, доставка вагоном до станции — 3 дня.'],['in',esc(d.ct)+' · 10:40','Хорошо, выставляйте счёт.']].map(m=>`<div class="msg ${m[0]}"><small>${m[1]}</small>${m[2]}</div>`).join('')}</div></div>
 <div class="pan"><h3>Звонки</h3>${[['исх.','05.10 11:42','6:10','согласовали вагон и сроки'],['вход.','04.10 16:20','3:05','запрос цены'],['исх.','03.10 09:50','—','не дозвонился']].map(c=>`<div class="kv"><span><span class="tag">${c[0]}</span> ${c[1]} · ${c[2]} · ${c[3]}</span>${c[2]!=='—'?`<b class="lk" onclick="toast('Запись разговора воспроизводится.')">слушать</b>`:'<b>—</b>'}</div>`).join('')}${d.note?`<div class="pin">${esc(d.note)}</div>`:''}</div></div>`};
function nextSt(id){const d=DL(id);const n=ST[STI(d.st)+1].k;if(n==='ship'&&!d.paid){toast('Отгрузка только после оплаты: кассир или бухгалтер отметит оплату.');return}d.st=n;if(n==='paid')d.paid=1;render();toast(`${d.id} → «${STN(n).n}».`+(n==='inv'?' Счёт сформирован из товаров сделки.':n==='paid'?' Товар зарезервирован, бухгалтеру по реализации — накладная.':n==='ship'?' Остаток на складе списан.':''))}

SC.invoice=()=>{const d=DL(curDeal)||DEALS[0];const S=dSum(d);return `<div class="hd"><div><h2>Счёт на оплату и КП</h2><p>Менеджер собирает товары в сделке — счёт и коммерческое предложение формируются сами из каталога: цены, остатки, реквизиты клиента. Без 1С.</p></div></div>
 <div class="g2"><div class="pan"><h3>Счёт на оплату · ${d.id}</h3><div class="doc"><div class="dh"><div class="dlg">ОПОРА<small>СТРОЙМАТЕРИАЛЫ И ОБОРУДОВАНИЕ</small></div><div style="text-align:right;font-size:10px">Счёт № ${d.id.slice(2)}<br>${TODAY}</div></div><h4>Счёт на оплату</h4><p style="font-size:11px">Покупатель: ${esc(d.cl)}</p><div class="drow h"><span>№</span><span>Товар</span><span class="r">Кол-во</span><span class="r">Сумма</span></div>${d.lines.map(([g,q],i)=>`<div class="drow"><span>${i+1}</span><span>${esc(GD(g).n)}</span><span class="r">${fmt(q)}</span><span class="r">${fmt(GD(g).sell*q)}</span></div>`).join('')}<div class="dsum"><span>Итого, в т. ч. НДС 12 %</span><span>${tg(S)}</span></div></div><div class="btns l" style="margin-top:10px"><button class="bt p" onclick="toast('Счёт отправлен клиенту в мессенджер, сделка → «Счёт выставлен».')">Отправить клиенту</button><button class="bt" onclick="toast('PDF счёта скачан.')">PDF</button></div></div>
 <div class="pan"><h3>Коммерческое предложение</h3><div class="doc"><div class="dh"><div class="dlg">ОПОРА<small>КП</small></div><div style="text-align:right;font-size:10px">${TODAY}</div></div><h4>${esc(d.cl)}</h4>${d.lines.map(([g,q])=>`<div class="drow"><span>${esc(GD(g).n.split(',')[0])}</span><span class="r">${fmt(q)} ${GD(g).u}</span><span class="r">${fmt(GD(g).sell)} ₸</span></div>`).join('')}<div class="dsum"><span>Итого</span><span>${tg(S)}</span></div><div class="dfoot"><span>Цены действительны 5 дней. Доставка вагоном или самовывоз со склада.</span></div></div><div class="btns l" style="margin-top:10px"><button class="bt p" onclick="toast('КП отправлено клиенту.')">Отправить КП</button></div></div></div>
 ${said('«Все товары там были, менеджеры могли счёт на оплату делать, коммерческое предложение».')}`};
SC.clients=()=>`<div class="hd"><div><h2>Клиенты</h2><p>Клиент — все сделки, счета, оплаты, долг, звонки и переписка в одной карточке. Реквизиты подставляются в счёт и накладную.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Клиент</th><th>Город</th><th>Менеджер</th><th class="r">Сделок</th><th class="r">Оборот за год</th><th class="r">Долг</th></tr></thead><tbody>${[['ТОО «КазДорСтрой»','Астана','Мурат',14,'62 400 000','0'],['ТОО «Нур-Сити Строй»','Караганда','Аслан',6,'21 800 000','2 400 000'],['ТОО «Сарыарка Курылыс»','Павлодар','Аслан',9,'34 100 000','0'],['ТОО «ЭнергоМонтаж KZ»','Астана','Мурат',11,'18 700 000','1 335 000'],['ТОО «Алау Инжиниринг»','Астана','Айгерим',2,'3 900 000','0'],['ИП Мухамеджанов','Косшы','Мурат',1,'—','0']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td class="r mono">${r[3]}</td><td class="r mono">${r[4]}</td><td class="r mono ${r[5]!=='0'?'neg':''}">${r[5]}</td></tr>`).join('')}</tbody></table></div>`;
