
/* ===== Склад ===== */
let gF='Все';
SC.catalog=()=>{const G=['Все',...new Set(GOODS.map(g=>g.g))];const L=GOODS.filter(g=>gF==='Все'||g.g===gF);
 return `<div class="hd"><div><h2>Товары и остатки</h2><p>Как в «Моём складе»: каждый товар, остаток, резерв под оплаченные сделки, свободно, минимальный остаток, закупочная и продажная цена, место хранения. Ниже минимума — подсветка и заявка снабженцу.</p></div><div class="btns"><span class="seg">${G.map(g=>`<a class="${g===gF?'on':''}" onclick="gF='${g}';render()">${g}</a>`).join('')}</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>Группа</th><th>Место</th><th class="r">Остаток</th><th class="r">Резерв</th><th class="r">Свободно</th><th class="r">Мин.</th>${role==='Менеджер'?'':'<th class="r">Закуп</th>'}<th class="r">Продажа</th></tr></thead><tbody>${L.map(g=>{const f=+(g.q-g.res).toFixed(1);return `<tr class="${f<g.min?'rowwarn':''}"><td><b>${esc(g.n)}</b></td><td>${g.g}</td><td>${g.cell}</td><td class="r mono">${String(g.q).replace('.',',')} ${g.u}</td><td class="r mono">${g.res?String(g.res).replace('.',','):'—'}</td><td class="r mono ${f<0?'neg':''}">${String(f).replace('.',',')}</td><td class="r mono">${g.min}</td>${role==='Менеджер'?'':`<td class="r mono">${fmt(g.buy)}</td>`}<td class="r mono">${fmt(g.sell)}</td></tr>`}).join('')}</tbody></table></div>
 ${said('«Мне главное, чтобы были все товары там — это как «Мой склад»».')}`};
const INC=[
 {n:'412',sup:'АО «Карцемент»',d:'05.10',lines:[['G1',2400]],sum:5040000,st:'done'},
 {n:'413',sup:'ТОО «Изол Центр»',d:'ожидается 07.10',lines:[['G7',200]],sum:1440000,st:'way'},
 {n:'414',sup:'«Shandong Mixer» (Китай)',d:'ожидается 12.10',lines:[['G9',6]],sum:624000,st:'way'}
];
SC.income=()=>`<div class="hd"><div><h2>Приход</h2><p>Бухгалтер по приходу заносит накладные поставщиков — товар появляется на складе, закупка закрывается, оплата поставщику уходит в «Оплаты». Одно действие вместо 1С плюс таблица.</p></div><div class="btns"><button class="bt p" onclick="card('income')">+ Приход</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>№</th><th>Поставщик</th><th>Дата</th><th>Товары</th><th class="r">Сумма</th><th>Статус</th><th></th></tr></thead><tbody>${INC.map((x,i)=>`<tr><td class="mono">${x.n}</td><td><b>${esc(x.sup)}</b></td><td>${x.d}</td><td>${x.lines.map(([g,q])=>esc(GD(g).n.split(',')[0])+' · '+fmt(q)+' '+GD(g).u).join('<br>')}</td><td class="r mono">${fmt(x.sum)}</td><td>${x.st==='done'?'<span class="tag g">принято</span>':'<span class="tag w">в пути</span>'}</td><td>${x.st==='done'?'':`<button class="bt sm" onclick="incDone(${i})">Принять на склад</button>`}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Два бухгалтера: один по приходу товара, другой по реализации — чтобы бухгалтер по приходу всё туда закидывал, пополнял».')}`;
function incDone(i){const x=INC[i];x.st='done';x.d=TODAY;x.lines.forEach(([g,q])=>GD(g).q+=q);const p=PREQ.find(p=>p.g===x.lines[0][0]&&p.st==='way');if(p)p.st='done';render();toast(`Приход № ${x.n} принят: остатки обновлены, заявка на закупку закрыта.`)}
SC.realize=()=>{const D=DEALS.filter(d=>['paid','ship','done'].includes(d.st));return `<div class="hd"><div><h2>Реализация</h2><p>Бухгалтер по реализации видит оплаченные сделки: накладная и ЭСФ формируются из сделки, отгрузка списывает товар со склада. Что продано, что оплачено, что отгружено — в одной таблице.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Сделка</th><th>Клиент</th><th class="r">Сумма</th><th>Оплата</th><th>Накладная</th><th>ЭСФ</th><th>Отгрузка</th></tr></thead><tbody>${D.map(d=>`<tr><td class="lk" onclick="openDeal('${d.id}')">${d.id}</td><td>${esc(d.cl)}</td><td class="r mono">${fmt(dSum(d))}</td><td><span class="tag g">оплачено</span></td><td><span class="tag ${d.st==='paid'?'w':'g'}">${d.st==='paid'?'сформировать':'№ 9'+d.id.slice(-2)}</span></td><td><span class="tag ${d.st==='done'?'g':''}">${d.st==='done'?'выписана':'—'}</span></td><td>${d.st==='done'?'отгружено':d.st==='ship'?'06.10 · самовывоз':d.note.includes('вагон')?'вагоном':'ждёт'}</td></tr>`).join('')}</tbody></table></div>
 <div class="note"><b>1С — пока параллельно</b><p>Пока налоговая отчётность в 1С, документы выгружаются туда файлом. Когда будете готовы — рабочую базу 1С отключаете полностью.</p></div>`};
const WAG=[
 {n:'№ 61284531',deal:'С-1187',to:'Павлодар',cargo:'Цемент М500 навал',t:60,st:'apply',d:'подача 06.10 09:00'},
 {n:'№ 61284549',deal:'С-1187',to:'Павлодар',cargo:'Цемент М500 навал',t:60,st:'apply',d:'подача 06.10 09:00'},
 {n:'№ 52910377',deal:'С-1184',to:'Караганда',cargo:'Цемент М400 · арматура · сетка',t:42,st:'plan',d:'после оплаты счёта'},
 {n:'№ 52844120',deal:'С-1181',to:'Шымкент',cargo:'Цемент М400 · арматура Ø12',t:74,st:'sent',d:'отправлен 01.10, прибытие 06.10'}
];
const WST={plan:'Планируется',apply:'Заявка подана · ждём подачу',load:'Погрузка',sent:'Отправлен'};
SC.wagons=()=>`<div class="hd"><div><h2>Отгрузка вагонами</h2><p>Вагон привязан к сделке: груз, тоннаж, станция, дата подачи и погрузки, ЖД-накладная. Менеджер и бухгалтер видят статус, клиент получает номер вагона.</p></div><div class="btns"><button class="bt p" onclick="card('wagon')">+ Вагон</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Вагон</th><th>Сделка</th><th>Станция</th><th>Груз</th><th class="r">Тонн</th><th>Статус</th><th>Когда</th><th></th></tr></thead><tbody>${WAG.map((w,i)=>`<tr><td class="mono"><b>${w.n}</b></td><td class="lk" onclick="openDeal('${w.deal}')">${w.deal}</td><td>${w.to}</td><td>${w.cargo}</td><td class="r mono">${w.t}</td><td><span class="tag ${w.st==='sent'?'g':w.st==='apply'?'w':''}">${WST[w.st]}</span></td><td>${w.d}</td><td>${w.st!=='sent'&&w.st!=='plan'?`<button class="bt sm" onclick="wagNext(${i})">${w.st==='apply'?'Погрузка':'Отправлен'}</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Для загрузки, например, вагонов — менеджеры со складом и бухгалтерией — чтобы всё было в одном месте».')}`;
function wagNext(i){const w=WAG[i];w.st=w.st==='apply'?'load':'sent';w.d=w.st==='load'?'погрузка '+TODAY:'отправлен '+TODAY;render();toast(w.st==='sent'?`Вагон ${w.n} отправлен — клиенту ушёл номер вагона, остаток списан.`:`Вагон ${w.n} на погрузке.`)}

/* ===== Снабжение ===== */
SC.preq=()=>`<div class="hd"><div><h2>Заявки на закупку</h2><p>Бизнес-процесс: заявку создаёт менеджер под сделку или склад, когда товар ниже минимума. Снабженец подбирает поставщика и цену, директор согласует, бухгалтер оплачивает, приход закрывает заявку.</p></div><div class="btns"><button class="bt p" onclick="card('preq')">+ Заявка</button></div></div>
 <div class="kb k5">${PST.map(([k,n])=>{const X=PREQ.filter(p=>p.st===k);return `<div class="kc" style="--sc:#3f5f86"><div class="kh"><b>${n}</b><span>${X.length}</span></div>${X.map(p=>`<div class="kd ${p.st==='agree'?'alarm':''}"><div class="kt"><b>${p.id}</b><span class="src">${p.d}</span></div><div class="kr">${esc(GD(p.g).n.split(',')[0])} · ${fmt(p.q)} ${GD(p.g).u}</div><div class="km">${esc(p.sup)} · ${fmt(p.pr)} ₸ за ${GD(p.g).u}</div><div class="km">${esc(p.who)} · ${esc(p.why)}</div><div class="kf"><span>итого</span><b class="mono">${mln(p.pr*p.q)}</b></div>${p.st==='agree'&&(role==='Исполнительный директор')?`<div class="btns l"><button class="bt sm p" onclick="pqOk('${p.id}')">Согласовать</button><button class="bt sm" onclick="toast('Возвращено снабженцу с комментарием.')">Вернуть</button></div>`:''}</div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 ${said('«Бизнес-процессы, типа заявка на закупку: у нас есть снабженцы, которые закупают оборудование, товары».')}`;
function pqOk(id){const p=PREQ.find(x=>x.id===id);p.st='order';render();toast(`${p.id} согласована — снабженец заказывает у ${p.sup}, бухгалтеру ушёл счёт на оплату.`)}
SC.suppliers=()=>`<div class="hd"><div><h2>Поставщики</h2><p>Карточка поставщика: что берём, по какой цене последние разы, звонки с записями и переписка снабженца. Можно сравнить, у кого дешевле, и проверить, о чём договорились.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Поставщик</th><th>Что берём</th><th>Последняя цена</th><th>Было раньше</th><th>Звонков / сообщений</th><th>Последний контакт</th></tr></thead><tbody>${[['АО «Карцемент»','цемент М400, М500','2 100 ₸/меш','2 050 ₸ (август)','12 / 34','05.10 · приход принят'],['ТОО «КарМет Трейд»','арматура, сетка','309 000 ₸/т Ø16','314 000 ₸ (сентябрь)','8 / 21','05.10 · звонок 5:12'],['ТОО «ТехноПауэр»','генераторы, инверторы','258 000 ₸ генератор','265 000 ₸','5 / 9','04.10 · ждём счёт'],['«Shandong Mixer» (Китай)','бетономешалки','104 000 ₸','118 000 ₸ (местный)','2 / 46','03.10 · инвойс'],['ТОО «Изол Центр»','минвата','7 200 ₸/уп','7 400 ₸','4 / 11','02.10 · в пути']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td class="mono">${r[2]}</td><td class="mono mini">${r[3]}</td><td class="mono">${r[4]}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div>
 <div class="note"><b>Запись разговоров снабженца</b><p>Звонки поставщикам идут через ту же телефонию, что у менеджеров: запись, длительность, к какой заявке относится.</p></div>`;

/* ===== Деньги ===== */
const CASHDAY=[{t:'10:20',who:'ТОО «ЭнергоМонтаж KZ»',deal:'С-1188',s:860000},{t:'12:05',who:'ИП Ахмедов (самовывоз)',deal:'С-1179',s:214000},{t:'15:40',who:'ИП Бекова',deal:'С-1180',s:186000}];
SC.cash=()=>`<div class="hd"><div><h2>Касса</h2><p>Для кассира — самый простой экран: найти счёт, принять деньги, распечатать чек. Сделка сама становится «Оплачена», менеджер и бухгалтер видят это сразу.</p></div></div>
 <div class="cashbox">
  <div class="cb-step"><i>1</i><b>Найдите счёт</b><input id="cs_q" value="С-1184" placeholder="номер счёта или клиент"></div>
  <div class="cb-step"><i>2</i><b>Сумма</b><div class="cb-sum">${tg(dSum(DL('С-1184')))}</div><span>ТОО «Нур-Сити Строй» · счёт С-1184</span></div>
  <div class="cb-btns"><button class="cbb ok" onclick="cashIn()">Принять наличные</button><button class="cbb" onclick="toast('Оплата картой через терминал — чек распечатан.')">Картой</button><button class="cbb" onclick="toast('Чек отправлен на печать.')">Печать чека</button></div>
 </div>
 <div class="pan"><h3>Сегодня в кассе · ${tg(CASHDAY.reduce((a,c)=>a+c.s,0))}</h3>${CASHDAY.map(c=>`<div class="kv"><span>${c.t} · ${esc(c.who)} · ${c.deal}</span><b class="mono">${fmt(c.s)}</b></div>`).join('')}<button class="bt sm" onclick="toast('Смена закрыта, отчёт директору и бухгалтеру.')">Закрыть смену</button></div>
 ${said('«Кассир очень взрослая… с компьютером не очень. Нажми А, нажми Б, нажми Ц».','Платон: максимально простой интерфейс — три кнопки.')}`;
function cashIn(){const d=DL('С-1184');if(d.paid){toast('Этот счёт уже оплачен.');return}d.paid=1;d.st='paid';CASHDAY.push({t:NOW,who:d.cl,deal:d.id,s:dSum(d)});render();toast(`Принято ${tg(dSum(d))}. Сделка С-1184 → «Оплачен», менеджеру Аслану и бухгалтеру — уведомление.`)}
SC.payments=()=>`<div class="hd"><div><h2>Оплаты по счетам</h2><p>Большинство оплат — безналом: выписка банка загружается раз в день, платежи сами находят свои счета. Оплаты поставщикам — из согласованных заявок на закупку.</p></div><div class="btns"><button class="bt p" onclick="toast('Выписка загружена: 6 платежей разнесены по счетам, 1 — вручную.')">Загрузить выписку</button></div></div>
 <div class="g2"><div class="pan"><h3>От клиентов</h3>${[['С-1187 · Сарыарка Курылыс','5 520 000','банк · 04.10'],['С-1188 · ЭнергоМонтаж KZ','860 000','касса · 05.10'],['С-1181 · КазДорСтрой','4 245 600','банк · 01.10'],['С-1184 · Нур-Сити Строй','—','ждём · счёт от 04.10']].map(r=>`<div class="kv"><span>${r[0]}<br><span class="mini">${r[2]}</span></span><b class="mono">${r[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Поставщикам</h3>${[['З-309 · Изол Центр','1 440 000','оплачено 02.10'],['З-308 · Shandong Mixer','624 000','оплачено 28.09'],['З-310 · ТехноПауэр','1 548 000','к оплате после счёта'],['З-311 · КарМет Трейд','6 180 000','после согласования директора']].map(r=>`<div class="kv"><span>${r[0]}<br><span class="mini">${r[2]}</span></span><b class="mono">${r[1]}</b></div>`).join('')}</div></div>`;
const ADV=[{id:'А-27',who:'Ерик',why:'Командировка Караганда, поставщик арматуры, 07–08.10',s:85000,st:'agree'},{id:'А-26',who:'Аслан',why:'Встреча с клиентом в Павлодаре, 02.10',s:46000,st:'report',left:4200},{id:'А-25',who:'Мурат',why:'Бензин, развоз образцов',s:20000,st:'closed'}];
SC.advances=()=>`<div class="hd"><div><h2>Авансы и командировки</h2><p>Сотрудник просит аванс или командировочные в системе — директор согласует одной кнопкой — кассир или бухгалтер выдаёт — сотрудник прикладывает чеки, остаток возвращается. Всё видно, кто сколько взял и отчитался.</p></div><div class="btns"><button class="bt p" onclick="card('adv')">+ Заявка на аванс</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>№</th><th>Кто</th><th>На что</th><th class="r">Сумма</th><th>Статус</th><th></th></tr></thead><tbody>${ADV.map(a=>`<tr><td class="mono">${a.id}</td><td><b>${a.who}</b></td><td>${esc(a.why)}</td><td class="r mono">${fmt(a.s)}</td><td>${a.st==='agree'?'<span class="tag w">ждёт согласования</span>':a.st==='paid'?'<span class="tag i">выдано</span>':a.st==='report'?`<span class="tag w">ждём чеки · остаток ${fmt(a.left)}</span>`:'<span class="tag g">закрыт</span>'}</td><td>${a.st==='agree'&&role==='Исполнительный директор'?`<button class="bt sm p" onclick="advOk('${a.id}')">Согласовать</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«И до получения даже авансов, командировочных — чтобы всё было в одном месте».')}`;
function advOk(id){const a=ADV.find(x=>x.id===id);a.st='paid';render();toast(`${a.id} согласован — кассиру ушла задача выдать ${tg(a.s)}.`)}
