
/* ===== Лента заказов ===== */
let ordF='all',ordMp='all',ordView='board';
const nextBtn=o=>({new:'В резерв',res:'Собран',pack:isPickup(o)?'Выдать':'Курьеру',courier:'Выдан'}[o.st]);
const actBtns=(o,sm)=>`${nextBtn(o)?`<button class="bt ${sm?'sm':''} p" onclick="event.stopPropagation();ordAdv('${o.id}')">${nextBtn(o)}</button>`:''}${o.st==='refuse'?`<button class="bt ${sm?'sm':''} r" onclick="event.stopPropagation();ordBack('${o.id}')">Товар вернулся</button>`:''}${['new','res','pack','courier'].includes(o.st)?`<button class="bt ${sm?'sm':''}" onclick="event.stopPropagation();ordRefuse('${o.id}')">${o.st==='courier'?'Отказ':'Отмена'}</button>`:''}`;
SC.orders=()=>{const O=SO().filter(o=>(ordMp==='all'||o.mp===ordMp));const F=O.filter(o=>ordF==='all'||o.st===ordF);
 return `<div class="hd"><div><h2>Лента заказов</h2><p>Kaspi, Halyk и Forte в одной очереди: номер, дата, клиент, телефон, состав, аптека. Резерв — сразу; товарный чек — при резерве; фискальный — только когда площадка пришлёт «выдан» или клиент забрал в аптеке.</p></div><div class="btns"><div class="seg"><button class="${ordView==='board'?'on':''}" onclick="ordView='board';render()">Доска</button><button class="${ordView==='list'?'on':''}" onclick="ordView='list';render()">Список</button></div></div></div>
 <div class="filt"><button class="${ordMp==='all'?'on':''}" onclick="ordMp='all';render()">Все площадки · ${SO().length}</button>${['kaspi','halyk','forte','wolt'].map(k=>`<button class="${ordMp===k?'on':''}" onclick="ordMp='${k}';render()"><i class="sq" style="background:${MP[k].c}"></i>${MP[k].s} · ${SO().filter(o=>o.mp===k).length}</button>`).join('')}<span class="fsep"></span>${ordView==='list'?`<button class="${ordF==='all'?'on':''}" onclick="ordF='all';render()">Все статусы</button>${OST.map(s=>`<button class="${ordF===s.k?'on':''}" onclick="ordF='${s.k}';render()">${s.n} · ${O.filter(o=>o.st===s.k).length}</button>`).join('')}`:''}</div>
 ${ordView==='board'?`<div class="board">${OST.map(s=>{const L=O.filter(o=>o.st===s.k);return `<div class="bcol ${ordF===s.k?'hl':''}"><div class="bh" style="--c:${s.c}"><b>${s.n}</b><span>${L.length} · ${fmt(L.reduce((a,o)=>a+oSum(o),0))} ₸</span></div>${L.map(o=>`<div class="oc" onclick="openOrd('${o.id}')"><div class="ocb">${mpm(o.mp)}<span class="mono">${esc(o.id)}</span>${stm(o.s)}</div><b>${esc(o.cl)}</b><span>${o.it.map(i=>esc(PR(i[0]).n.split(',')[0])+' × '+i[1]).join('; ')}</span><div class="ocf"><strong>${tg(oSum(o))}</strong><em>${dd(o.d)} ${o.t}</em></div>${o.st==='refuse'?`<div class="ocw">${o.arrived?'Товар привезли — подтвердите':'Везут назад'}</div>`:''}<div class="ocbtn">${actBtns(o,1)}</div></div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>`
 :`<div class="tw"><table class="t"><thead><tr><th>Заказ</th><th>Площадка</th><th>Пришёл</th><th>Клиент</th><th>Состав</th><th>Аптека</th><th class="r">Сумма</th><th>Статус</th><th>Документ</th><th></th></tr></thead><tbody>${F.map(o=>`<tr onclick="openOrd('${o.id}')"><td class="mono">${esc(o.id)}</td><td>${mpm(o.mp)}</td><td class="mono">${dd(o.d)} ${o.t}</td><td>${esc(o.cl)}<span class="sub mono">${esc(o.ph)}</span></td><td>${o.it.map(i=>esc(PR(i[0]).n.split(',')[0])+' × '+i[1]).join('<br>')}</td><td>${stm(o.s)}</td><td class="r mono">${fmt(oSum(o))}</td><td>${ost(o.st)}</td><td class="mono">${o.fc?'<span class="pos">'+o.fc+'</span>':o.tc?o.tc:'—'}</td><td><div class="rbtn">${actBtns(o,1)}</div></td></tr>`).join('')}</tbody></table></div>`}
 <div class="note"><b>Почему чек не пробивается сразу</b><p>Пока заказ у курьера, клиент может отказаться. Раньше чек был уже пробит — приходилось оформлять возврат по чеку. Теперь до выдачи есть только товарный чек, а фискальный создаётся автоматически по статусу «выдан» от площадки.</p></div>`};

/* ===== Карточка заказа ===== */
function openOrd(id){if(!OR(id))return;curOrd=id;if(allowed('order')&&cur!=='order'){go('order')}else if(allowed('order')){render()}else card('ord',id)}
const FLOW=['new','res','pack','courier','done'];
const ordSteps=o=>{const i=o.st==='refuse'||o.st==='back'?3:FLOW.indexOf(o.st);return `<div class="steps">${FLOW.map((k,j)=>`<div class="stp ${j<i||o.st==='done'&&j===i?'done':j===i&&o.st!=='refuse'&&o.st!=='back'?'on':''}"><i>${j+1}</i>${esc(OSTOF(k).n)}</div>`).join('')}${o.st==='refuse'||o.st==='back'?`<div class="stp ${o.st==='refuse'?'on bad':'done'}"><i>↩</i>${esc(OSTOF(o.st).n)}</div>`:''}</div>`};
const ordBody=o=>`${ordSteps(o)}
 <div class="g21"><div><div class="pan"><h3>Состав заказа</h3><div class="tw"><table class="t"><thead><tr><th>Товар</th><th class="r">Кол-во</th><th class="r">Свободно на ${STORES[o.s].s}</th><th class="r">Цена</th><th class="r">Сумма</th><th>НДС</th><th>Маркировка</th></tr></thead><tbody>${o.it.map(i=>{const p=PR(i[0]);return `<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}${p.rx?' <span class="rx">Rx</span>':''}</td><td class="r mono">${i[1]}</td><td class="r mono">${freeQ(p.id,o.s)}</td><td class="r mono">${fmt(p.price)}</td><td class="r mono">${fmt(lineSum(i))}</td><td class="mono">${vatOf(p)}%</td><td>${p.mk?(o.st==='done'?'<span class="pos">выведен из оборота</span>':'в обороте'):'<span class="mini">не нужна</span>'}</td></tr>`}).join('')}<tr class="total"><td>Итого</td><td class="r mono">${oQty(o)}</td><td></td><td></td><td class="r mono">${fmt(oSum(o))}</td><td colspan="2" class="mini">${vatLine(o.it)}</td></tr></tbody></table></div>
  <div class="btns l" style="margin-top:12px">${actBtns(o)}<button class="bt" onclick="card('tch','${o.id}')">Товарный чек</button>${o.fc?`<button class="bt g" onclick="card('chk','${o.fc}')">Фискальный чек ${o.fc}</button>`:''}<button class="bt" onclick="act('wa')">Написать клиенту</button></div></div>
 <div class="pan"><h3>Документы заказа</h3>
  <div class="doclane"><div class="${o.tc?'ok':''}"><small>1 · при резерве</small><b>Товарный чек</b><span class="mono">${o.tc||'появится при резерве'}</span></div><div class="${o.fc?'ok':o.st==='back'?'no':''}"><small>2 · при «выдан»</small><b>Фискальный чек → ОФД</b><span class="mono">${o.fc||(o.st==='back'?'не пробивался — не нужен':'ждёт статуса «выдан»')}</span></div><div class="${o.fc&&o.it.some(i=>PR(i[0]).mk)?'ok':o.st==='back'?'no':''}"><small>3 · вместе с чеком</small><b>ИС МПТ: выбытие кодов</b><span>${o.it.some(i=>PR(i[0]).mk)?(o.fc?'коды выведены из оборота':o.st==='back'?'коды остались в обороте':'после выдачи'):'товар без маркировки'}</span></div></div></div></div>
 <div><div class="pan"><h3>Клиент и доставка</h3>${[['Клиент',esc(o.cl)],['Телефон',`<span class="mono">${esc(o.ph)}</span>`],['Площадка',MP[o.mp].n],['Номер на площадке',`<span class="mono">${esc(o.id)}</span>`],['Пришёл',dl(o.d)+' '+o.t],['Аптека',stName(o.s)+' · '+STORES[o.s].addr],['Доставка',esc(o.dlv)]].concat(o.why?[['Причина отказа',esc(o.why)]]:[]).map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>История</h3><div class="tl">${o.h.slice().reverse().map((x,j)=>`<div class="tli ${j===0?'on':'ok'}"><span class="who">${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}</div></div></div></div>`;
SC.order=()=>{const o=OR(curOrd)||ORDERS[0];const L=SO();
 return `<div class="crumb"><a onclick="go('orders')">Лента заказов</a> / ${esc(MP[o.mp].n)} / ${esc(o.id)}</div>
 <div class="hd"><div><h2>${mpm(o.mp)} Заказ ${esc(o.id)} · ${ost(o.st)}</h2><p>${esc(o.cl)} · ${oQty(o)} шт. · ${tg(oSum(o))} · ${stName(o.s)}. ${esc(OSTOF(o.st).d)}</p></div><div class="btns"><select class="osel" onchange="curOrd=this.value;render()">${L.map(x=>`<option value="${x.id}" ${x.id===o.id?'selected':''}>${x.id} · ${OSTOF(x.st).n}</option>`).join('')}</select></div></div>
 ${ordBody(o)}
 ${said('«Чтобы товар, когда заказ поступил, упаковали, передали в службу доставки, и после того как выдано будет — чтобы у меня автоматически пробивался чек. До этого момента — только товарный чек.»')}`};

/* ===== Отказы и возвраты ===== */
SC.returns=()=>{const R=SO().filter(o=>o.st==='refuse'),B=SO().filter(o=>o.st==='back');
 return `<div class="hd"><div><h2>Отказы и возвраты</h2><p>Отказ от площадки ставит заказ в «везут назад» — товар числится в резерве, на площадках не продаётся. Когда курьер привёз — сотрудник жмёт «Товар вернулся»: резерв снимается, остаток восстанавливается на той аптеке, откуда уходил.</p></div></div>
 <div class="flow3"><div><small>1</small><b>Площадка: отказ</b><span>Kaspi, Halyk или Forte присылают статус сами</span></div><div><small>2</small><b>Товар в пути назад</b><span>резерв держится, чек не пробит</span></div><div><small>3</small><b>«Товар вернулся»</b><span>одна кнопка в аптеке или в телефоне</span></div><div class="ok"><small>4</small><b>Снова в продаже</b><span>остаток +N на нужной аптеке и на всех площадках</span></div></div>
 <div class="pan"><h3>Ждут приёмки · ${R.length}</h3>${R.length?`<div class="tw"><table class="t"><thead><tr><th>Заказ</th><th>Площадка</th><th>Клиент</th><th>Товар</th><th>Аптека</th><th>Причина</th><th>Где товар</th><th></th></tr></thead><tbody>${R.map(o=>`<tr onclick="openOrd('${o.id}')"><td class="mono">${esc(o.id)}</td><td>${mpm(o.mp)}</td><td>${esc(o.cl)}</td><td>${o.it.map(i=>esc(PR(i[0]).n.split(',')[0])+' × '+i[1]).join('<br>')}</td><td>${stm(o.s)}</td><td>${esc(o.why||'—')}</td><td>${o.arrived?'<b class="warnt">привезли в аптеку</b>':'у курьера'}</td><td><button class="bt sm r" onclick="event.stopPropagation();ordBack('${o.id}')">Товар вернулся</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="mini">Все возвраты приняты.</p>'}</div>
 <div class="g2"><div class="pan"><h3>Принятые возвраты</h3>${B.map(o=>`<div class="kv" style="cursor:pointer" onclick="openOrd('${o.id}')"><span>${mpm(o.mp)} <span class="mono">${esc(o.id)}</span> · ${esc(o.why||'')}</span><b>${tg(oSum(o))}</b></div>`).join('')||'<p class="mini">Пока нет.</p>'}</div>
 <div class="pan"><h3>Сентябрь</h3>${[['Отказов с площадок',38],['Возвратов по фискальному чеку','0'],['Раньше — возвратов по чеку в месяц','≈ 30–40'],['Средний срок возврата товара','1,6 дня']].map(x=>`<div class="kv"><span>${x[0]}</span><b class="mono">${x[1]}</b></div>`).join('')}<p class="mini" style="margin-top:8px">Если клиент вернул товар уже после выдачи — это обычный возврат по чеку, система оформит его по ОФД и вернёт коды в оборот.</p></div></div>
 ${said('«Возврат — как мы получим от курьерской службы, и мы у себя подтвердили, что товар мы получили, — убрать резерв и перекинуть на склад.»')}`};

/* ===== Чеки и ОФД ===== */
let chkTab='f';
SC.checks=()=>{const C=CHECKS.filter(c=>inStore(c.s)),T=TCHECKS.filter(t=>inStore(t.s));
 const z=s=>{const L=CHECKS.filter(c=>c.s===s);const v={};L.forEach(c=>{const r=vatSplit(c.it);Object.keys(r).forEach(k=>v[k]=(v[k]||0)+r[k])});return [L.length,L.reduce((a,c)=>a+cSum(c),0),v]};
 return `<div class="hd"><div><h2>Чеки и ОФД</h2><p>Два вида документов. Товарный чек — внутренний, печатается при резерве и кладётся в пакет. Фискальный — уходит в ОФД только при фактической выдаче или продаже в аптеке, с разбивкой НДС 5% и 16%.</p></div><div class="btns"><button class="bt" onclick="act('z')">Z-отчёт смены</button></div></div>
 <div class="g2">${SK.filter(inStore).map(s=>{const [n,sm,v]=z(s);return `<div class="pan zr"><h3>${stName(s)} · ${STORES[s].kkm}</h3>${[['Чеков за смену',n],['Сумма',tg(sm)]].concat(Object.keys(v).sort((a,b)=>a-b).map(k=>['в т. ч. НДС '+k+'%',tg(vatSum(v[k],+k))])).map(x=>`<div class="kv"><span>${x[0]}</span><b class="mono">${x[1]}</b></div>`).join('')}</div>`}).join('')}</div>
 <div class="tabs"><a class="tab ${chkTab==='f'?'on':''}" onclick="chkTab='f';render()">Фискальные чеки · ${C.length}</a><a class="tab ${chkTab==='t'?'on':''}" onclick="chkTab='t';render()">Товарные чеки · ${T.length}</a></div>
 ${chkTab==='f'?`<div class="tw"><table class="t"><thead><tr><th>Чек</th><th>Время</th><th>Аптека</th><th>Источник</th><th>Заказ</th><th class="r">Сумма</th><th>НДС</th><th>Оплата</th><th>ОФД</th><th>Клиенту</th></tr></thead><tbody>${C.map(c=>`<tr onclick="card('chk','${c.no}')"><td class="mono">${c.no}</td><td class="mono">${c.t}</td><td>${stm(c.s)}</td><td>${mpm(c.src)}</td><td>${c.ord?ordL(c.ord):'<span class="mini">в аптеке</span>'}</td><td class="r mono">${fmt(cSum(c))}</td><td class="mini">${vatLine(c.it)}</td><td>${esc(c.pay)}</td><td>${c.ofd==='ok'?'<span class="pos">принят</span>':'<span class="warnt">отправляется</span>'}</td><td>${c.wa?'<span class="pos">WhatsApp ✓</span>':'<span class="mini">—</span>'}</td></tr>`).join('')}</tbody></table></div>`
 :`<div class="tw"><table class="t"><thead><tr><th>Товарный чек</th><th>Заказ</th><th>Аптека</th><th>Статус заказа</th><th>Что дальше</th></tr></thead><tbody>${T.map(t=>`<tr onclick="openOrd('${t.ord}')"><td class="mono">${t.no}</td><td class="mono">${t.ord}</td><td>${stm(t.s)}</td><td>${ost(t.st)}</td><td class="mini">${t.st==='done'?'закрыт фискальным чеком':t.st==='back'?'аннулирован: возврат, фискальный не нужен':'ждёт выдачи'}</td></tr>`).join('')}</tbody></table></div>`}
 ${said('«После того как выдано будет клиенту — пробивался фискальный чек. До этого момента — только товарный чек.»')}`};

/* ===== Продажа в аптеке ===== */
let CART=[],posStore='A1',posFound='';
function posStoreNow(){return ROLES[role].st||(store==='all'?posStore:store)}
function findBc(code){const q=String(code).trim().toLowerCase();for(const p of PRODUCTS){const b=p.bc.find(x=>x[0].toLowerCase()===q);if(b)return [p,b]}return null}
function posScan(code){const r=findBc(code);if(!r){toast('Код не найден. Можно добавить его к нужному товару — у товара может быть сколько угодно штрихкодов и артикулов.');return}const [p,b]=r;posFound=`${esc(p.n)} — найден по коду <span class="mono">${esc(b[0])}</span> (${esc(b[1])})`;const e=CART.find(c=>c[0]===p.id&&c[2]!=='u');if(e)e[1]++;else CART.push([p.id,1]);render()}
function posUnit(i){const c=CART[i],p=PR(c[0]);if(!p.u){toast('Этот товар не делится — продаётся только целой упаковкой.');return}c[2]=c[2]==='u'?undefined:'u';render()}
function posPay(how){if(!CART.length){toast('Корзина пустая — отсканируйте товар.');return}const s=posStoreNow();let opened=[];
 CART.forEach(c=>{const p=PR(c[0]);if(c[2]==='u'){let need=c[1];while(p.op[s]<need){p.st[s][0]--;fefoTake(p.id,s,1);p.op[s]+=p.u[1];opened.push(p.n.split(',')[0])}p.op[s]-=need}else{p.st[s][0]-=c[1];fefoTake(p.id,s,c[1])}});
 const no=`ФЧ-${s[1]}-0${fcN[s]++}`;CHECKS.unshift({no,s,t:NOW,src:'shop',it:CART.map(c=>c.slice()),pay:how,ofd:'ok'});const sm=CART.reduce((a,c)=>a+lineSum(c),0),vl=vatLine(CART);CART=[];posFound='';render();
 toast(`Чек <b>${no}</b> на ${tg(sm)} ушёл в ОФД (${vl}).${opened.length?' Вскрыта упаковка: '+esc(opened.join(', '))+' — остаток пересчитан в блистеры.':''}`)}
SC.pos=()=>{const s=posStoreNow();const sm=CART.reduce((a,c)=>a+lineSum(c),0);
 return `<div class="hd"><div><h2>Продажа в аптеке · ${stName(s)}</h2><p>Сканер читает любой из штрихкодов товара — заводской, старой упаковки, артикул поставщика. Можно продать целую упаковку или один блистер: упаковка вскрывается автоматически, остаток считается в блистерах.</p></div>${ROLES[role].st||store!=='all'?'':`<div class="btns"><div class="seg">${SK.map(k=>`<button class="${posStore===k?'on':''}" onclick="posStore='${k}';render()">${STORES[k].s}</button>`).join('')}</div></div>`}</div>
 <div class="g12"><div class="pan"><h3>Сканер</h3><div class="scan"><input id="bcin" placeholder="штрихкод или артикул" onkeydown="if(event.key==='Enter'){posScan(this.value);this.value=''}"><button class="bt p" onclick="const i=document.getElementById('bcin');posScan(i.value);i.value=''">Найти</button></div>
  <p class="mini" style="margin:10px 0 6px">Попробуйте коды одного и того же парацетамола:</p><div class="codes">${PR('P01').bc.slice(0,4).map(b=>`<button onclick="posScan('${b[0]}')"><span class="mono">${b[0]}</span><small>${esc(b[1])}</small></button>`).join('')}<button onclick="posScan('3582910065312')"><span class="mono">3582910065312</span><small>Магний B6</small></button><button onclick="posScan('VM-OM3-90')"><span class="mono">VM-OM3-90</span><small>Омега-3 · БАД</small></button></div>
  ${posFound?`<div class="note" style="--tone:var(--ok)"><b>Найдено</b><p>${posFound}</p></div>`:''}</div>
 <div class="pan"><h3>Чек</h3>${CART.length?`<div class="tw"><table class="t"><thead><tr><th>Товар</th><th>Единица</th><th class="r">Кол-во</th><th class="r">Цена</th><th class="r">Сумма</th><th>НДС</th><th></th></tr></thead><tbody>${CART.map((c,i)=>{const p=PR(c[0]);return `<tr><td>${esc(p.n)}${p.mk?' <span class="mkm">DataMatrix</span>':''}</td><td>${p.u?`<div class="seg sm"><button class="${c[2]!=='u'?'on':''}" onclick="if(CART[${i}][2]==='u')posUnit(${i})">упаковка</button><button class="${c[2]==='u'?'on':''}" onclick="if(CART[${i}][2]!=='u')posUnit(${i})">${p.u[0]}</button></div>`:'<span class="mini">упаковка</span>'}</td><td class="r"><input class="qin" value="${c[1]}" onchange="CART[${i}][1]=Math.max(1,+this.value||1);render()"></td><td class="r mono">${fmt(c[2]==='u'?p.u[2]:p.price)}</td><td class="r mono">${fmt(lineSum(c))}</td><td class="mono">${vatOf(p)}%</td><td><a class="lk" onclick="CART.splice(${i},1);render()">убрать</a></td></tr>`}).join('')}<tr class="total"><td colspan="4">Итого · ${vatLine(CART)}</td><td class="r mono">${fmt(sm)}</td><td colspan="2"></td></tr></tbody></table></div>
  <div class="btns l" style="margin-top:12px">${['Наличные','Карта','Kaspi QR'].map(h=>`<button class="bt p" onclick="posPay('${h}')">${h}</button>`).join('')}<button class="bt" onclick="CART=[];posFound='';render()">Очистить</button></div>`:'<p class="mini">Отсканируйте товар или нажмите один из кодов слева.</p>'}
  <div class="opn"><small>Вскрытые упаковки на ${STORES[s].s}</small>${PRODUCTS.filter(p=>p.u&&p.op[s]).map(p=>`<span>${esc(p.n.split(',')[0])} <b class="mono">${p.op[s]} ${esc(p.u[0])}</b></span>`).join('')||'<span>—</span>'}</div></div></div>
 ${said('«Отдельно название товара плюс штрихкод… возможность этому товару добавить несколько артикулов — не один, а сразу пять, шесть, сколько получится.»')}`};

/* ===== WhatsApp и Telegram ===== */
let curChat='W1';
SC.chats=()=>{const c=CHATS.find(x=>x.id===curChat)||CHATS[0];c.un=0;
 return `<div class="hd"><div><h2>WhatsApp и Telegram</h2><p>Переписка с поставщиками и клиентами — в системе, рядом с заказом или накладной. Шаблоны «заказ собран», «передан курьеру», «напоминание о продлении договора» отправляются в один клик. Телефония не нужна — как вы сказали.</p></div></div>
 <div class="chw"><div class="chl">${CHATS.map(x=>`<div class="chi ${x.id===c.id?'on':''}" onclick="curChat='${x.id}';render()"><i class="chn ${x.ch}">${x.ch==='wa'?'WA':'TG'}</i><div><b>${esc(x.n)}</b><span>${esc(x.sub)}</span></div>${x.un?`<em>${x.un}</em>`:''}</div>`).join('')}</div>
 <div class="chm"><div class="chh"><b>${esc(c.n)}</b><span>${c.ch==='wa'?'WhatsApp':'Telegram'} · ${esc(c.sub)}</span></div><div class="chat">${c.ms.map(m=>`<div class="msg ${m[0]}">${esc(m[1])}<small>${esc(m[2])}</small></div>`).join('')}</div>
  <div class="chs"><input id="chin" placeholder="Сообщение…" onkeydown="if(event.key==='Enter')chatSend()"><button class="bt p" onclick="chatSend()">Отправить</button></div>
  <div class="tpls">${['Ваш заказ собран и ждёт курьера','Заказ передан курьеру, ожидайте сегодня','Пришлите, пожалуйста, скан накладной в PDF','Договор истекает — нужен ДС о продлении'].map(t=>`<button onclick="document.getElementById('chin').value='${t}'">${t}</button>`).join('')}</div></div></div>`};
function chatSend(){const i=document.getElementById('chin');if(!i||!i.value.trim())return;const c=CHATS.find(x=>x.id===curChat);c.ms.push(['out',i.value.trim(),NOW]);render();toast(`Отправлено в ${c.ch==='wa'?'WhatsApp':'Telegram'}.`)}

/* ===== Своя доставка ===== */
function courierGo(id){const o=OR(id);if(!o||o.st!=='pack')return;ordAdv(id)}
function courierDone(id){const o=OR(id);if(!o||o.st!=='courier')return;issue(o,'Своя доставка: доставлен клиенту');tcSync();render();toast(`Доставлено: ${esc(o.addr)}. Статус «выдан» ушёл в Kaspi, <b>фискальный чек ${o.fc}</b> пробит, ссылка на чек — клиенту в WhatsApp.`)}
let curOwn=null;
SC.courier=()=>{const O=ORDERS.filter(o=>o.own&&(role==='Курьер'?o.st==='courier'||o.st==='done':inStore(o.s)));const act=O.filter(o=>o.st!=='done'&&o.st!=='back');
 const pin=(o,i)=>`<g class="pin ${o.st}" onclick="curOwn='${o.id}';render()"><circle cx="${o.xy[0]}" cy="${o.xy[1]}" r="3.4"/><text x="${o.xy[0]}" y="${o.xy[1]+1.3}">${i+1}</text></g>`;
 return `<div class="hd"><div><h2>Своя доставка и курьеры</h2><p>Часть заказов Kaspi вы отвозите сами, а не курьер Kaspi. Такие заказы сразу попадают курьеру в телефон: адреса на карте, порядок объезда курьер выбирает сам — без автоматического маршрута. На точке — «Доставлен»: статус уходит в Kaspi, фискальный чек пробивается сам.</p></div></div>
 <div class="g21"><div class="pan"><h3>Карта · сегодня</h3><svg class="cmap" viewBox="0 0 100 70"><path class="riv" d="M0 44 C18 38 30 50 46 46 S78 34 100 40"/><path class="rd" d="M8 0V70M38 0V70M70 0V70M92 0V70M0 14H100M0 30H100M0 62H100"/><path class="rd2" d="M0 52 L100 8"/>
  <g class="shop"><rect x="${17}" y="${64}" width="6" height="5" rx="1"/><text x="20" y="62">№1</text></g><g class="shop"><rect x="${80}" y="${48}" width="6" height="5" rx="1"/><text x="83" y="46">№2</text></g>
  ${act.map(pin).join('')}</svg>
  <div class="legend"><span><i style="background:#5b7a2a"></i>собран — ждёт курьера</span><span><i style="background:#b7791f"></i>у курьера</span><span><i style="background:#2b7a3d"></i>доставлен</span></div></div>
 <div class="phone"><div class="pht"><b>Серик · мои доставки</b><small>${O.filter(o=>o.st==='courier').length} в пути · маршрут выбираю сам</small></div><div class="pb">${O.filter(o=>o.st==='courier').map(o=>`<div class="pi"><span>${esc(o.addr)}<small>${esc(o.cl)} · ${esc(o.ph)} · ${tg(oSum(o))} · оплачен на Kaspi</small></span><b><a class="lk" onclick="courierDone('${o.id}')">Доставлен</a></b></div>`).join('')||'<p class="mini">Нет заказов в пути.</p>'}<div class="pbtn" onclick="act('map2gis')">Открыть адреса в 2ГИС / Яндекс Картах</div></div></div></div>
 <div class="tw"><table class="t"><thead><tr><th>#</th><th>Заказ</th><th>Аптека</th><th>Адрес</th><th>Клиент</th><th class="r">Сумма</th><th>Статус</th><th>Курьер</th><th></th></tr></thead><tbody>${O.map((o,i)=>`<tr class="${curOwn===o.id?'sel':''}" onclick="openOrd('${o.id}')"><td class="mono">${act.indexOf(o)>=0?act.indexOf(o)+1:'·'}</td><td class="mono">${esc(o.id)}</td><td>${stm(o.s)}</td><td>${esc(o.addr)}</td><td>${esc(o.cl)}<span class="sub mono">${esc(o.ph)}</span></td><td class="r mono">${fmt(oSum(o))}</td><td>${ost(o.st)}</td><td>${o.courier?STAFF[o.courier]:'—'}</td><td onclick="event.stopPropagation()">${o.st==='pack'?`<button class="bt sm p" onclick="courierGo('${o.id}')">Передать Серику</button>`:o.st==='courier'?`<button class="bt sm g" onclick="courierDone('${o.id}')">Доставлен</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«С Kaspi упали заказы, и мы этот заказ должны сами отвозить… чтобы курьеры заходили, смотрели адреса, как в карточке у Яндекса, — и сам примерно настроил маршрут, чтобы не автоматом.»')}`};
