
/* ===== Площадки: витрины и остатки ===== */
const mpPrice=(p,k)=>k==='kaspi'?((DUMP.find(d=>d.p===p.id)||{}).our||p.price):p.price;
SC.market=()=>{const L=PRODUCTS.filter(p=>p.mpl.length||p.nkt!=='ok');
 return `<div class="hd"><div><h2>Витрины площадок и остатки</h2><p>Каждые несколько минут система отправляет на Kaspi, Halyk и Forte цену и <b>свободный</b> остаток по каждой аптеке — уже за вычетом резерва. Продать то, что лежит в чужом заказе, нельзя.</p></div><div class="btns"><button class="bt" onclick="act('sync')">Обновить сейчас</button></div></div>
 <div class="g4">${['kaspi','halyk','forte','wolt'].map(k=>{const i=INT(k);const pub=PRODUCTS.filter(p=>p.mpl.includes(k));return `<div class="pan mpp" style="--c:${MP[k].c}"><h3>${esc(MP[k].n)}</h3>${[['Связь',`<i class="dot ${i.st}"></i>${esc(i.ago)} назад`],['Товаров на витрине',pub.length],['Заказов сегодня',ORDERS.filter(o=>o.mp===k&&o.d===TODAY).length],['Точки выдачи',k==='kaspi'?'PP1 — №1, PP2 — №2':'обе аптеки'],['Не опубликовано (нет НКТ)',PRODUCTS.filter(p=>p.nkt!=='ok'&&p.mpl.includes(k)).length]].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}${i.msg?`<div class="note" style="--tone:var(--warn)"><p>${esc(i.msg)}</p></div>`:''}</div>`}).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>НКТ</th><th class="r">Свободно №1</th><th class="r">Свободно №2</th>${['kaspi','halyk','forte','wolt'].map(k=>`<th class="r">${MP[k].s}</th>`).join('')}</tr></thead><tbody>${L.map(p=>`<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}</td><td>${p.nkt==='ok'?'<span class="pos">есть</span>':p.nkt==='wait'?'<span class="warnt">модерация</span>':'<span class="neg">нет</span>'}</td>${SK.map(s=>`<td class="r mono ${freeQ(p.id,s)<p.min?'warnt':''}">${freeQ(p.id,s)}</td>`).join('')}${['kaspi','halyk','forte','wolt'].map(k=>`<td class="r mono">${p.mpl.includes(k)?(k==='wolt'?'<span class="mini">вручную</span>':p.nkt==='ok'?fmt(mpPrice(p,k)):'<span class="warnt">ждёт НКТ</span>'):'<span class="mini">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 ${said('«В данный момент у меня подключено — передаю только остатки и цены, и в каком магазине есть товар в наличии. Ещё мне хотелось бы более автоматизировать.»','Остатки и цены остаются, к ним добавляются заказы, резерв, статусы «выдан» и «отказ».')}`};

/* ===== Демпинг Kaspi ===== */
SC.dumping=()=>`<div class="hd"><div><h2>Цены и демпинг на Kaspi</h2><p>Робот каждые 15 минут смотрит минимальную цену конкурентов по каждой карточке и снижает вашу цену на шаг — но никогда не ниже порога. Порог считается от себестоимости партии, чтобы не продавать в минус.</p></div><div class="btns"><button class="bt" onclick="act('floor')">Порог: себестоимость + 15%</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th class="r">Наша цена</th><th class="r">Мин. у конкурентов</th><th class="r">Место</th><th class="r">Продавцов</th><th class="r">Порог</th><th class="r">Шаг</th><th class="r">Маржа на пороге</th><th>Робот</th></tr></thead><tbody>${DUMP.map((d,i)=>{const p=PR(d.p);return `<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}</td><td class="r mono"><b>${fmt(d.our)}</b></td><td class="r mono ${d.comp<d.our?'neg':'pos'}">${fmt(d.comp)}</td><td class="r mono">${d.pos}</td><td class="r mono">${d.sellers}</td><td class="r mono">${fmt(d.floor)}</td><td class="r mono">${d.step}</td><td class="r mono">${pct(d.floor-p.cost,d.floor)}%</td><td onclick="event.stopPropagation()"><span class="sw ${d.auto?'on':''}" onclick="DUMP[${i}].auto=!DUMP[${i}].auto;render();toast(DUMP[${i}].auto?'Робот включён для этой карточки.':'Робот выключен — цена не меняется.')"></span></td></tr>`}).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Журнал робота · сегодня</h3>${DLOG.map(l=>`<div class="kv"><span><span class="mono">${l[0]}</span> · ${esc(l[1])} — ${esc(l[3])}</span><b class="mono">${esc(l[2])}</b></div>`).join('')}<button class="bt" style="margin-top:10px" onclick="dumpRun()">Проверить сейчас</button></div>
 <div class="pan"><h3>Правила</h3>${[['Проверка','каждые 15 минут, 08:00–23:00'],['Если конкурент дешевле','минус шаг, не ниже порога'],['Если мы одни на 1-м месте','поднять до конкурента минус шаг'],['Если упёрлись в порог','уведомление менеджеру'],['Halyk и Forte','цена = цена аптеки, без робота']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>`;
function dumpRun(){let n=0;DUMP.forEach(d=>{if(!d.auto)return;if(d.comp<d.our&&d.our-d.step>=d.floor){const was=d.our;d.our=Math.max(d.floor,d.comp-d.step);DLOG.unshift([NOW,PR(d.p).n.split(',')[0],fmt(was)+' → '+fmt(d.our),'конкурент '+fmt(d.comp)]);d.pos=1;n++}});render();toast(n?`Цены обновлены по ${n} ${plural(n,['карточке','карточкам','карточкам'])} — в пределах порогов.`:'Всё уже на лучших позициях в пределах порогов.')}

/* ===== Остатки двух аптек ===== */
let stF='all',stQ='';
SC.stock=()=>{const S=SK.filter(inStore);let L=PRODUCTS.filter(p=>!stQ||p.n.toLowerCase().includes(stQ.toLowerCase())||p.bc.some(b=>b[0].toLowerCase().includes(stQ.toLowerCase())));
 if(stF==='low')L=L.filter(p=>S.some(s=>freeQ(p.id,s)<p.min));if(stF==='mk')L=L.filter(p=>p.mk);if(stF==='res')L=L.filter(p=>S.some(s=>reserved(p.id,s)));
 return `<div class="hd"><div><h2>Остатки ${store==='all'?'двух аптек':stName(store)}</h2><p>На полке = свободно + резерв. Резерв — товар, который лежит в заказах площадок до выдачи или возврата. Вскрытые упаковки считаются отдельно, в блистерах или пакетиках.</p></div><div class="btns"><button class="bt" onclick="go('moves')">Перемещение</button><button class="bt p" onclick="go('inventory')">Инвентаризация</button></div></div>
 <div class="filt"><input class="fin" placeholder="название или любой штрихкод" value="${esc(stQ)}" onkeydown="if(event.key==='Enter'){stQ=this.value;render()}">${[['all','Все'],['low','Ниже минимума'],['res','В резерве'],['mk','С маркировкой']].map(f=>`<button class="${stF===f[0]?'on':''}" onclick="stF='${f[0]}';render()">${f[1]}</button>`).join('')}</div>
 <div class="tw"><table class="t stk"><thead><tr><th rowspan="2">Товар</th><th rowspan="2">Группа</th>${S.map(s=>`<th colspan="4" class="c gs">${stName(s)}</th>`).join('')}<th rowspan="2" class="r">Мин.</th></tr><tr>${S.map(()=>`<th class="r">Полка</th><th class="r">Резерв</th><th class="r">Свободно</th><th class="r">Вскрыто</th>`).join('')}</tr></thead><tbody>${L.map(p=>`<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}${p.rx?' <span class="rx">Rx</span>':''}</td><td>${catm(p.cat)}</td>${S.map(s=>{const f=freeQ(p.id,s),r=reserved(p.id,s);return `<td class="r mono gs">${onHand(p.id,s)}</td><td class="r mono">${r?'<b class="acc">'+r+'</b>':'·'}</td><td class="r mono ${f<p.min?(f<=p.min/3?'neg':'warnt'):''}"><b>${f}</b></td><td class="r mono">${p.u&&p.op[s]?p.op[s]+' '+uAb(p):'·'}</td>`}).join('')}<td class="r mono">${p.min}</td></tr>`).join('')}</tbody></table></div>
 <div class="note"><b>Склад = две аптеки</b><p>Каждая аптека — отдельный склад со своими остатками, кассой и точкой выдачи на площадках. Перемещение между ними — документом, с партиями и кодами маркировки.</p></div>`};

/* ===== Партии и сроки ===== */
SC.batches=()=>{const L=BATCHES.filter(b=>inStore(b.s)&&b.q>0).sort((a,b)=>a.exp<b.exp?-1:1);
 return `<div class="hd"><div><h2>Партии и сроки годности</h2><p>Каждый приход — своя партия: серия, срок, поставщик, закупочная цена. При продаже первой списывается партия с ближайшим сроком. Себестоимость и маржа считаются по партии.</p></div></div>
 <div class="wid"><div><small>Партий в остатке</small><b>${L.length}</b></div><div><small>Срок до 60 дней</small><b class="r">${L.filter(b=>daysBetween(TODAY,b.exp)<=60).length}</b><span>${tg(L.filter(b=>daysBetween(TODAY,b.exp)<=60).reduce((a,b)=>a+b.q*b.cost,0))} по закупке</span></div><div><small>Срок 60–120 дней</small><b class="w">${L.filter(b=>{const d=daysBetween(TODAY,b.exp);return d>60&&d<=120}).length}</b></div><div><small>Склад по закупке</small><b class="a">${mln(L.reduce((a,b)=>a+b.q*b.cost,0))}</b></div><div><small>Просрочено</small><b class="g">0</b><span>просроченное не продаётся</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>Аптека</th><th>Серия</th><th>Годен до</th><th class="r">Осталось дней</th><th class="r">Кол-во</th><th>Поставщик</th><th class="r">Закупка</th><th></th></tr></thead><tbody>${L.map(b=>{const d=daysBetween(TODAY,b.exp);return `<tr onclick="card('pr','${b.p}')"><td>${esc(PR(b.p).n)}</td><td>${stm(b.s)}</td><td class="mono">${b.no}</td><td class="mono">${dl(b.exp)}</td><td class="r mono ${d<=60?'neg':d<=120?'warnt':''}"><b>${d}</b></td><td class="r mono">${b.q}</td><td>${esc(SU(b.sup).n.replace(/ТОО |ИП /,''))}</td><td class="r mono">${fmt(b.cost)}</td><td>${d<=60?`<a class="lk" onclick="event.stopPropagation();act('expiry')">действие</a>`:''}</td></tr>`}).join('')}</tbody></table></div>`};

/* ===== Приход и накладные ===== */
let curIn='IN-0933';
SC.income=()=>{const L=INCOMES.filter(i=>inStore(i.s));const i=INCOMES.find(x=>x.id===curIn)||L[0];const su=SU(i.sup);
 return `<div class="hd"><div><h2>Приход товара и накладные</h2><p>Поставщик привёз товар — фармацевт сканирует коды, система сверяет с электронной накладной, партии и сроки встают на склад нужной аптеки, к документу прикрепляется скан накладной в PDF. Накладные поставщиков из <b>Провизора</b> приходят сами — строки, серии и сроки уже заполнены, остаётся отсканировать коды и провести.</p></div><div class="btns"><button class="bt p" onclick="act('newin')">+ Приход</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Приход</th><th>Дата</th><th>Поставщик</th><th>Откуда</th><th>Накладная</th><th>Аптека</th><th class="r">Сумма</th><th>Оплата</th><th>Скан PDF</th><th>Коды ИС МПТ</th><th>Статус</th></tr></thead><tbody>${L.map(x=>`<tr class="${x.id===i.id?'sel':''}" onclick="curIn='${x.id}';render()"><td class="mono">${x.id}</td><td class="mono">${dd(x.d)}</td><td>${esc(SU(x.sup).n)}</td><td>${x.via?'<span class="pos">'+x.via+'</span>':'<span class="mini">вручную</span>'}</td><td class="mono">${x.inv}</td><td>${stm(x.s)}</td><td class="r mono">${fmt(inSum(x))}</td><td>${esc(PAYT[SU(x.sup).pay].n)}</td><td>${x.pdf?'<span class="pos">есть</span>':'<span class="neg">нет</span>'}</td><td class="mono">${x.codes[1]?x.codes[0]+' / '+x.codes[1]:'не нужны'}</td><td>${x.st==='done'?'<span class="pos">проведён</span>':'<span class="warnt">черновик</span>'}</td></tr>`).join('')}</tbody></table></div>
 <div class="g21" style="margin-top:12px"><div class="pan"><h3>${i.id} · накладная ${i.inv} от ${dl(i.d)}</h3><p>${esc(su.n)} → ${stName(i.s)} · ${esc(PAYT[su.pay].n)}${i.pay?' · '+esc(i.pay):''}</p>
  <div class="tw"><table class="t"><thead><tr><th>Товар</th><th class="r">Кол-во</th><th>Серия</th><th>Годен до</th><th class="r">Цена</th><th class="r">Сумма</th><th>НДС</th></tr></thead><tbody>${i.lines.map(l=>`<tr onclick="card('pr','${l[0]}')"><td>${esc(PR(l[0]).n)}</td><td class="r mono">${l[1]}</td><td class="mono">${l[2]}</td><td class="mono">${dl(l[3])}</td><td class="r mono">${fmt(l[4])}</td><td class="r mono">${fmt(lineSumIn(l))}</td><td class="mono">${vatOf(PR(l[0]))}%</td></tr>`).join('')}<tr class="total"><td>Итого</td><td class="r mono">${i.lines.reduce((a,l)=>a+l[1],0)}</td><td colspan="3"></td><td class="r mono">${fmt(inSum(i))}</td><td></td></tr></tbody></table></div>
  ${i.err?`<div class="note" style="--tone:var(--bad)"><b>Маркировка</b><p>${esc(i.err)}</p></div>`:''}
  ${i.st==='draft'?`<div class="btns l" style="margin-top:12px"><button class="bt ${i.pdf?'':'w'}" onclick="inPdf('${i.id}')">${i.pdf?'PDF прикреплён ✓':'Прикрепить скан PDF'}</button><button class="bt ${i.codes[0]>=i.codes[1]?'':'v'}" onclick="inCodes('${i.id}')">${i.codes[0]>=i.codes[1]?'Коды приняты ✓':'Сканировать коды · '+i.codes[0]+' / '+i.codes[1]}</button><button class="bt p" onclick="inPost('${i.id}')">Провести приход</button></div>`:''}</div>
 <div class="pan"><h3>Файлы документа</h3>${[['Электронная накладная',i.inv+' · из ИС МПТ / от поставщика',true],['Скан накладной с подписью','PDF, '+(i.pdf?'1,2 МБ':'не прикреплён'),i.pdf],['Счёт на оплату',su.pay==='pre'?'СФ поставщика · оплачен':'не нужен',su.pay==='pre'],['Договор',(CONTRACTS.find(c=>c.sup===i.sup)||{}).no||'—',true]].map(f=>`<div class="file ${f[2]?'':'no'}"><i>PDF</i><div><b>${f[0]}</b><span>${esc(f[1])}</span></div></div>`).join('')}
  ${said('«Когда приход товара будет у нас на склад, поставщик отправил товар, мы приходуем все эти товары — и возможность прикрепить к этому файл: PDF, отсканированный документ этой накладной.»')}</div></div>`};
function inPdf(id){const i=INCOMES.find(x=>x.id===id);i.pdf=true;render();toast('Скан накладной прикреплён к приходу — найдётся из архива документов и из карточки поставщика.')}
function inCodes(id){const i=INCOMES.find(x=>x.id===id);i.codes[0]=i.codes[1];render();toast('Коды DataMatrix отсканированы и приняты в ИС МПТ — товар числится за аптекой.')}
function inPost(id){const i=INCOMES.find(x=>x.id===id);if(!i.pdf||i.codes[0]<i.codes[1]){toast('Сначала прикрепите скан PDF и примите коды маркировки — без этого приход не проводится.');return}i.st='done';i.lines.forEach(l=>{PR(l[0]).st[i.s][0]+=l[1];BATCHES.push({p:l[0],s:i.s,no:l[2],exp:l[3],q:l[1],sup:i.sup,cost:l[4]})});const su=SU(i.sup);if(su.pay==='post')su.debt+=inSum(i);render();toast(`Приход проведён: ${i.lines.length} позиций на ${stName(i.s)}, партии и сроки на складе, остаток на площадках обновится через минуту.${su.pay==='post'?' Долг поставщику вырос на '+tg(inSum(i))+' — срок оплаты '+dl(addDays(TODAY,30))+'.':''}`)}

/* ===== Перемещения ===== */
SC.moves=()=>`<div class="hd"><div><h2>Перемещения между аптеками</h2><p>Если на одной аптеке закончилось, а на другой лежит — перемещение документом: что, сколько, какая партия. В пути товар не продаётся ни там, ни там; при приёмке встаёт на остаток.</p></div></div>
 <div class="g12"><div class="pan"><h3>Новое перемещение</h3><div class="form one"><label>Откуда<select id="mv_f">${SK.map(s=>`<option value="${s}">${stName(s)}</option>`).join('')}</select></label><label>Товар<select id="mv_p">${PRODUCTS.map(p=>`<option value="${p.id}">${esc(p.n)}</option>`).join('')}</select></label><label>Количество, уп.<input id="mv_q" value="5"></label></div><button class="bt p" onclick="mvNew()">Отправить</button></div>
 <div class="pan"><h3>Документы</h3><div class="tw"><table class="t"><thead><tr><th>№</th><th>Дата</th><th>Маршрут</th><th>Что</th><th>Зачем</th><th>Статус</th><th></th></tr></thead><tbody>${MOVES.map(m=>`<tr><td class="mono">${m.id}</td><td class="mono">${dd(m.d)}</td><td>${STORES[m.from].s} → ${STORES[m.to].s}</td><td>${m.lines.map(l=>esc(PR(l[0]).n.split(',')[0])+' × '+l[1]).join('<br>')}</td><td class="mini">${esc(m.why)}</td><td>${m.st==='done'?'<span class="pos">принято</span>':'<span class="warnt">в пути</span>'}</td><td>${m.st==='way'?`<button class="bt sm p" onclick="mvAccept('${m.id}')">Принять</button>`:''}</td></tr>`).join('')}</tbody></table></div></div></div>`;
function mvNew(){const f=document.getElementById('mv_f').value,p=document.getElementById('mv_p').value,q=Math.max(1,+document.getElementById('mv_q').value||1);const t=f==='A1'?'A2':'A1';if(freeQ(p,f)<q){toast(`На ${stName(f)} свободно только ${freeQ(p,f)} — остальное в резерве под заказы.`);return}PR(p).st[f][0]-=q;fefoTake(p,f,q);MOVES.unshift({id:'ПМ-0'+(42+MOVES.length-3),from:f,to:t,d:TODAY,st:'way',lines:[[p,q]],who:ROLES[role].p,why:'Создано вручную'});render();toast(`Перемещение отправлено: ${esc(PR(p).n)} × ${q}, ${STORES[f].s} → ${STORES[t].s}. В пути товар не продаётся.`)}
function mvAccept(id){const m=MOVES.find(x=>x.id===id);if(m.st!=='way')return;m.st='done';m.lines.forEach(l=>{PR(l[0]).st[m.to][0]+=l[1];const b=BATCHES.find(x=>x.p===l[0]&&x.s===m.to);if(b)b.q+=l[1];else BATCHES.push({p:l[0],s:m.to,no:'—',exp:addDays(TODAY,365),q:l[1],sup:'S1',cost:PR(l[0]).cost})});render();toast(`Перемещение ${m.id} принято на ${stName(m.to)} — остаток обновлён, на площадках тоже.`)}

/* ===== Инвентаризация ===== */
SC.inventory=()=>{const o=INVS.find(x=>x.st==='open');const L=PRODUCTS.filter(p=>p.cat==='bad'||['P07','P10'].includes(p.id));
 return `<div class="hd"><div><h2>Инвентаризация</h2><p>Полная или по полке. Фармацевт вводит факт или сканирует — система показывает разницу с учётом резерва и вскрытых упаковок. Недостача и излишки проводятся актом, история хранится.</p></div></div>
 ${o?`<div class="pan"><h3>${o.id} · ${stName(o.s)} · ${esc(o.zone)} · идёт сейчас</h3><div class="tw"><table class="t"><thead><tr><th>Товар</th><th class="r">По учёту</th><th class="r">В т. ч. резерв</th><th class="r">Факт</th><th class="r">Разница</th></tr></thead><tbody>${L.map(p=>`<tr><td>${esc(p.n)}</td><td class="r mono">${onHand(p.id,o.s)}</td><td class="r mono">${reserved(p.id,o.s)||'·'}</td><td class="r"><input class="qin" id="iv_${p.id}" value="${p.id==='P08'?onHand(p.id,o.s)-1:onHand(p.id,o.s)}" oninput="ivDiff()"></td><td class="r mono" id="ivd_${p.id}">${p.id==='P08'?'<b class="neg">−1</b>':'0'}</td></tr>`).join('')}</tbody></table></div>
  <div class="btns l" style="margin-top:12px"><button class="bt p" onclick="ivPost()">Провести акт</button><span class="mini">Резерв считается: товар в пакете заказа — это не недостача.</span></div></div>`:'<div class="pan"><p class="mini">Открытых инвентаризаций нет.</p></div>'}
 <div class="pan"><h3>Проведённые</h3>${INVS.filter(x=>x.st==='done').map(x=>`<div class="kv"><span><span class="mono">${x.id}</span> · ${dl(x.d)} · ${stName(x.s)} · ${esc(x.zone)}</span><b>${x.diff.map(d=>esc(PR(d[0]).n.split(',')[0])+' '+(d[1]>0?'+':'')+d[1]).join('; ')||'без расхождений'}</b></div>`).join('')}</div>`};
function ivDiff(){const o=INVS.find(x=>x.st==='open');PRODUCTS.forEach(p=>{const i=document.getElementById('iv_'+p.id);if(!i)return;const d=(+i.value||0)-onHand(p.id,o.s);document.getElementById('ivd_'+p.id).innerHTML=d?`<b class="${d<0?'neg':'pos'}">${d>0?'+':''}${d}</b>`:'0'})}
function ivPost(){const o=INVS.find(x=>x.st==='open');const D=[];PRODUCTS.forEach(p=>{const i=document.getElementById('iv_'+p.id);if(!i)return;const d=(+i.value||0)-onHand(p.id,o.s);if(d){D.push([p.id,d,d<0?'недостача':'излишек']);p.st[o.s][0]+=d}});o.diff=D;o.st='done';render();toast(D.length?`Акт ${o.id} проведён: ${D.length} ${plural(D.length,['расхождение','расхождения','расхождений'])}, остатки исправлены.`:'Акт проведён без расхождений.')}
