
/* ===== Номенклатура ===== */
let catF='all';
SC.catalog=()=>{const L=PRODUCTS.filter(p=>catF==='all'||p.cat===catF);
 return `<div class="hd"><div><h2>Номенклатура</h2><p>Карточка товара: название, производитель, группа, фасовка, минимальный остаток и <b>сколько угодно штрихкодов и артикулов</b> — заводской, старой упаковки, артикулы каждого поставщика, SKU площадок. Сканер найдёт товар по любому из них.</p></div><div class="btns"><button class="bt" onclick="act('import')">Импорт из Excel / текущей программы</button><button class="bt p" onclick="card('newpr')">+ Новый товар</button></div></div>
 <div class="filt"><button class="${catF==='all'?'on':''}" onclick="catF='all';render()">Все · ${PRODUCTS.length}</button>${Object.keys(CATS).map(k=>`<button class="${catF===k?'on':''}" onclick="catF='${k}';render()">${CATS[k].n} · ${PRODUCTS.filter(p=>p.cat===k).length}</button>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>Группа</th><th>Фасовка / деление</th><th class="r">Кодов</th><th>НДС</th><th>НКТ</th><th>Маркировка</th><th class="r">Закупка</th><th class="r">Цена</th><th class="r">Маржа</th><th>Площадки</th></tr></thead><tbody>${L.map(p=>`<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}${p.rx?' <span class="rx">Rx</span>':''}<span class="sub">${esc(p.mf)}</span></td><td>${catm(p.cat)}</td><td>${p.u?`1 уп. = ${p.u[1]} ${p.u[0]==='блистер'?'бл.':p.u[0]==='пакетик'?'пак.':'шт.'} · ${fmt(p.u[2])} ₸`:'<span class="mini">не делится</span>'}</td><td class="r mono"><b>${p.bc.length}</b></td><td class="mono">${vatOf(p)}%</td><td>${p.nkt==='ok'?'<span class="pos">есть</span>':p.nkt==='wait'?'<span class="warnt">модерация</span>':'<span class="neg">нет</span>'}</td><td>${p.mk?'<span class="mkm">DataMatrix</span>':'<span class="mini">—</span>'}</td><td class="r mono">${fmt(p.cost)}</td><td class="r mono">${fmt(p.price)}</td><td class="r mono">${pct(p.price-p.cost,p.price)}%</td><td>${p.mpl.map(mpm).join(' ')||'<span class="mini">—</span>'}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Отдельно название товара плюс штрихкод… возможность этому товару добавить несколько артикулов — не один, а сразу пять, шесть, сколько получится.»','Парацетамол в демо — 6 кодов: заводской, старая упаковка, два артикула поставщиков, Kaspi и Halyk.')}`};
function addBc(id){const v=document.getElementById('nbc').value.trim(),w=document.getElementById('nbw').value;if(!v){toast('Введите код.');return}const f=findBc(v);if(f){toast(`Этот код уже привязан к «${esc(f[0].n)}» — двойных кодов система не допустит.`);return}PR(id).bc.push([v,w]);card('pr',id);render();toast('Код добавлен — сканер и поиск уже находят товар по нему.')}

/* ===== Разукомплектация ===== */
let unLog=[['30.09 18:05','A1','P01','1 уп. → 2 блистера','Асель'],['30.09 12:40','A2','P16','1 уп. → 10 пакетиков','Динара'],['29.09 20:15','A1','P07','1 уп. → 5 блистеров','Асель']];
SC.unpack=()=>{const L=PRODUCTS.filter(p=>p.u);const S=SK.filter(inStore);
 return `<div class="hd"><div><h2>Разукомплектация</h2><p>В коробке два блистера по десять таблеток — клиенту нужен один. Фармацевт продаёт блистер, система сама вскрывает упаковку: на полке становится на 1 упаковку меньше и +2 блистера. Партия, срок и себестоимость переходят на блистеры.</p></div></div>
 <div class="unf"><div><small>было</small><b>1 упаковка</b><span>Парацетамол №20 · 290 ₸</span></div><i>→</i><div><small>вскрыли</small><b>2 блистера × 10</b><span>по 160 ₸ за блистер</span></div><i>→</i><div class="ok"><small>продали один</small><b>1 блистер на полке</b><span>остаток: упаковки + 1 бл.</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>Деление</th><th class="r">Цена уп.</th><th class="r">Цена ед.</th><th class="r">Маржа ед.</th>${S.map(s=>`<th class="r">${STORES[s].s}: уп. / вскрыто</th>`).join('')}<th></th></tr></thead><tbody>${L.map(p=>`<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}</td><td>1 уп. = ${p.u[1]} ${uPl(p,p.u[1])}</td><td class="r mono">${fmt(p.price)}</td><td class="r mono">${fmt(p.u[2])}</td><td class="r mono">${pct(p.u[2]-p.cost/p.u[1],p.u[2])}%</td>${S.map(s=>`<td class="r mono">${onHand(p.id,s)} / ${p.op[s]||'·'}</td>`).join('')}<td onclick="event.stopPropagation()">${S.map(s=>`<button class="bt sm" onclick="unpack('${p.id}','${s}')">Вскрыть на ${STORES[s].s}</button>`).join(' ')}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Журнал вскрытий</h3>${unLog.map(l=>`<div class="kv"><span><span class="mono">${l[0]}</span> · ${STORES[l[1]].s} · ${esc(PR(l[2]).n.split(',')[0])} · ${esc(l[4])}</span><b>${esc(l[3])}</b></div>`).join('')}</div>
 <div class="pan"><h3>Маркировка при делении</h3><p class="mini">Код DataMatrix стоит на упаковке. При вскрытии система отмечает упаковку в ИС МПТ по правилам частичной продажи — точный порядок для лекарств и БАДов сверим с регламентом при подключении, чтобы аптека не получила расхождение.</p></div></div>
 ${said('«В упаковке два блистера по десять штук, полная коробка не нужна, нужен только один блистер — возможно сделать разукомплектацию?»')}`};
function unpack(id,s){const p=PR(id);if(freeQ(id,s)<1){toast('Свободных упаковок нет — всё в резерве.');return}p.st[s][0]--;fefoTake(id,s,1);p.op[s]+=p.u[1];unLog.unshift([dd(TODAY)+' '+NOW,s,id,`1 уп. → ${p.u[1]} ${p.u[0]==='блистер'?plural(p.u[1],['блистер','блистера','блистеров']):p.u[0]==='пакетик'?plural(p.u[1],['пакетик','пакетика','пакетиков']):'шт.'}`,STAFF[ROLES[role].p]]);render();toast(`Вскрыта упаковка «${esc(p.n.split(',')[0])}» на ${STORES[s].s}: −1 уп., +${p.u[1]} ${esc(p.u[0])}. Продаются по ${tg(p.u[2])}.`)}

/* ===== Ставки НДС ===== */
SC.vat=()=>{const ex=[['P01',2],['P09',1],['P13',1]];const r27=items=>{const r={};items.forEach(i=>{const p=PR(i[0]),v=vatOn(p.cat,'2027-01-01');r[v]=(r[v]||0)+lineSum(i)});return r};
 return `<div class="hd"><div><h2>Ставки НДС</h2><p>Ставка задаётся группе товаров и привязана к дате. Лекарства — 5% в 2026 году и 10% с 1 января 2027; остальное — 16%. Новая ставка включится сама в нужный день, в чеке НДС разбивается по ставкам.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Группа</th><th class="r">Товаров</th><th>2026</th><th>С 01.01.2027</th><th>Комментарий</th></tr></thead><tbody>${VAT.map(v=>`<tr><td><b>${esc(v.n)}</b></td><td class="r mono">${PRODUCTS.filter(p=>p.cat===v.k).length}</td><td class="mono"><b>${vatOn(v.k,'2026-06-01')}%</b></td><td class="mono"><b class="${vatOn(v.k,'2027-01-01')!==vatOn(v.k,'2026-06-01')?'warnt':''}">${vatOn(v.k,'2027-01-01')}%</b></td><td class="mini">${esc(v.note)}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Пример чека сегодня</h3>${ex.map(i=>`<div class="kv"><span>${esc(PR(i[0]).n)} × ${i[1]} · НДС ${vatOf(PR(i[0]))}%</span><b class="mono">${fmt(lineSum(i))}</b></div>`).join('')}<div class="kv big"><span>Итого</span><b>${tg(ex.reduce((a,i)=>a+lineSum(i),0))}</b></div>${Object.entries(vatSplit(ex)).map(([k,v])=>`<div class="kv"><span>в т. ч. НДС ${k}%</span><b class="mono">${fmt(vatSum(v,+k))}</b></div>`).join('')}</div>
 <div class="pan"><h3>Тот же чек с 1 января 2027</h3>${ex.map(i=>`<div class="kv"><span>${esc(PR(i[0]).n)} × ${i[1]} · НДС ${vatOn(PR(i[0]).cat,'2027-01-01')}%</span><b class="mono">${fmt(lineSum(i))}</b></div>`).join('')}<div class="kv big"><span>Итого</span><b>${tg(ex.reduce((a,i)=>a+lineSum(i),0))}</b></div>${Object.entries(r27(ex)).map(([k,v])=>`<div class="kv"><span>в т. ч. НДС ${k}%</span><b class="mono">${fmt(vatSum(v,+k))}</b></div>`).join('')}<p class="mini" style="margin-top:8px">Цена не меняется сама — система покажет, как изменится маржа, а вы решите: оставить цену или поднять. Ставки по каждой группе подтверждает ваш бухгалтер.</p></div></div>
 ${said('«Обычные товары — НДС шестнадцать процентов, а лекарственные средства облагаются пятипроцентным в этом году, после — десять процентов.»')}`};

/* ===== НКТ ===== */
SC.nkt=()=>{const L=PRODUCTS.slice().sort((a,b)=>(a.nkt==='ok')-(b.nkt==='ok'));
 return `<div class="hd"><div><h2>Национальный каталог товаров</h2><p>Каждая карточка сверяется с НКТ по GTIN: наименование, производитель, форма выпуска. Пока карточки нет — товар не публикуется на площадках и не принимается по маркировке. Статусы подтягиваются автоматически.</p></div><div class="btns"><button class="bt" onclick="act('nktsync')">Сверить всё с НКТ</button></div></div>
 <div class="wid"><div><small>Есть в НКТ</small><b class="g">${PRODUCTS.filter(p=>p.nkt==='ok').length}</b></div><div><small>На модерации</small><b class="w">${PRODUCTS.filter(p=>p.nkt==='wait').length}</b></div><div><small>Нет карточки</small><b class="r">${PRODUCTS.filter(p=>p.nkt==='no').length}</b></div><div><small>Блокирует площадки</small><b>${PRODUCTS.filter(p=>p.nkt!=='ok'&&p.mpl.length).length}</b></div><div><small>Последняя сверка</small><b class="mono" style="font-size:18px">13:20</b></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Товар</th><th>GTIN</th><th>Группа</th><th>Статус НКТ</th><th>Что блокирует</th><th></th></tr></thead><tbody>${L.map(p=>`<tr onclick="card('pr','${p.id}')"><td>${esc(p.n)}</td><td class="mono">${p.gtin||'—'}</td><td>${catm(p.cat)}</td><td>${p.nkt==='ok'?'<span class="pos">карточка есть</span>':p.nkt==='wait'?'<span class="warnt">на модерации</span>':'<span class="neg">нет карточки</span>'}</td><td class="mini">${p.nkt==='ok'?'—':(p.mpl.length?'публикация на '+p.mpl.map(k=>MP[k].s).join(', '):'продажа на площадках')+(p.mk?', приёмка кодов':'')}</td><td onclick="event.stopPropagation()">${p.nkt==='no'?`<button class="bt sm p" onclick="PR('${p.id}').nkt='wait';render();toast('Заявка на карточку отправлена в НКТ. Статус придёт автоматически.')">Создать карточку</button>`:p.nkt==='wait'?`<button class="bt sm" onclick="PR('${p.id}').nkt='ok';render();toast('НКТ: карточка одобрена — товар опубликуется на площадках при следующей синхронизации.')">Проверить статус</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Национальный каталог товаров — немаловажно, по законодательству нужно, чтобы НКТ было подключено.»')}`};

/* ===== Маркировка ИС МПТ ===== */
let MKLOG=[
 ['14:02','A1','Выбытие · продажа','ФЧ-1-018824 · Парацетамол, 1 блистер','ok'],
 ['13:58','A2','Выбытие · продажа','ФЧ-2-007417 · Диосмектит, 2 пакетика','wait'],
 ['12:30','A1','Выбытие · заказ выдан','614497203 · Ибупрофен, Аскорбиновая кислота','ok'],
 ['11:15','A2','Выбытие · заказ выдан','HM-240871 · Омега-3 × 2','ok'],
 ['10:20','A2','Перемещение','ПМ-041 · Нафазолин × 8 → аптека №1','ok'],
 ['30.09 17:10','A2','Приёмка','ВМ-Н-2207 «Витамакс» · 19 из 20 кодов','err'],
 ['30.09 10:20','A2','Возврат в оборот','614493317 — отказ до выдачи, коды не выбывали','ok'],
 ['30.09 09:05','A1','Приёмка','ФЛ-58213 «Фармлайн» · 44 из 44','ok']
];
SC.marking=()=>`<div class="hd"><div><h2>Маркировка · ИС МПТ</h2><p>Лекарства и с 1 сентября БАДы — с кодом DataMatrix. Приёмка кодов от поставщика, выбытие при выдаче заказа или продаже в аптеке, перемещения между аптеками. Отказ до выдачи кодов не трогает — они не выбывали.</p></div><div class="btns"><button class="bt" onclick="card('int','ismp')">Подключение</button></div></div>
 <div class="wid"><div><small>Кодов на балансе №1</small><b>${fmt(PRODUCTS.filter(p=>p.mk).reduce((a,p)=>a+onHand(p.id,'A1'),0))}</b></div><div><small>Кодов на балансе №2</small><b>${fmt(PRODUCTS.filter(p=>p.mk).reduce((a,p)=>a+onHand(p.id,'A2'),0))}</b></div><div><small>Выбыло сегодня</small><b class="g">${MKLOG.filter(l=>l[0].indexOf('.')<0&&l[2].indexOf('Выбытие')===0).length}</b></div><div><small>Ошибки</small><b class="r">${MKLOG.filter(l=>l[4]==='err').length}</b><span>разбираются с поставщиком</span></div><div><small>БАДы с маркировкой</small><b class="w">${PRODUCTS.filter(p=>p.cat==='bad'&&p.mk).length}</b><span>с 01.09.2026</span></div></div>
 <div class="g21"><div class="pan"><h3>События</h3><div class="tw"><table class="t"><thead><tr><th>Время</th><th>Аптека</th><th>Операция</th><th>Документ</th><th>ИС МПТ</th></tr></thead><tbody>${MKLOG.filter(l=>inStore(l[1])).map(l=>`<tr><td class="mono">${l[0]}</td><td>${stm(l[1])}</td><td>${esc(l[2])}</td><td>${esc(l[3])}</td><td>${l[4]==='ok'?'<span class="pos">принято</span>':l[4]==='wait'?'<span class="warnt">отправляется</span>':'<span class="neg">ошибка</span>'}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="pan"><h3>Когда что уходит в ИС МПТ</h3>${[['Приход от поставщика','приёмка кодов по накладной'],['Резерв под заказ','ничего — код в обороте'],['Заказ выдан','выбытие вместе с фискальным чеком'],['Отказ до выдачи','ничего — код не выбывал'],['Возврат после выдачи','возврат в оборот по чеку возврата'],['Перемещение №1 ↔ №2','смена места хранения'],['Вскрытие упаковки','по правилам частичной продажи']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>
 ${said('«Интеграция ИС МПТ — маркировка лекарственных средств… Первого сентября ввели БАДы тоже — маркировку.»')}`;
