
/* ===== Поставщики и оплаты ===== */
let PAYS=[
 {id:'PY1',sup:'S1',what:'Счёт СФ-9944 · предоплата под отгрузку 02.10',sum:486000,due:'2026-10-01',st:'open'},
 {id:'PY2',sup:'S3',what:'Консигнация: отчёт о продажах 15–30.09',sum:312000,due:'2026-10-03',st:'open'},
 {id:'PY3',sup:'S2',what:'Накладная МС-Н-54870 от 05.09 · отсрочка 30 дней',sum:640000,due:'2026-10-05',st:'open'},
 {id:'PY4',sup:'S5',what:'Консигнация: продано за сентябрь',sum:94000,due:'2026-10-05',st:'open'},
 {id:'PY5',sup:'S2',what:'Накладная МС-Н-55012 от 18.09 · отсрочка 30 дней',sum:600000,due:'2026-10-18',st:'open'},
 {id:'PY6',sup:'S4',what:'Счёт ДФ-СФ-3370 · предоплата',sum:210000,due:'2026-09-24',st:'paid'}
];
SC.suppliers=()=>`<div class="hd"><div><h2>Поставщики и оплаты</h2><p>У каждого поставщика свой порядок: предоплата по счёту, отсрочка или консигнация. Система ведёт, что и когда платить: счёт к оплате, срок отсрочки по накладной, по консигнации — только за проданное.</p></div></div>
 <div class="sups">${SUPPLIERS.map(s=>`<div class="sup" style="--c:${PAYT[s.pay].c}" onclick="card('sup','${s.id}')"><small>${esc(PAYT[s.pay].n)}</small><b>${esc(s.n)}</b><span>${esc(s.term)}</span><div class="kv"><span>${s.pay==='cons'?'К оплате за проданное':s.pay==='post'?'Долг по отсрочке':'Счёт к оплате'}</span><b class="mono">${fmt(s.pay==='pre'?s.pend:s.debt)}</b></div>${s.cons?`<div class="kv"><span>На реализации у нас</span><b class="mono">${fmt(s.cons)}</b></div>`:''}<div class="kv"><span>Доля закупок</span><b class="mono">${s.share}%</b></div></div>`).join('')}</div>
 <div class="pan"><h3>Календарь оплат</h3><div class="tw"><table class="t"><thead><tr><th>Срок</th><th>Поставщик</th><th>Основание</th><th>Тип</th><th class="r">Сумма</th><th></th></tr></thead><tbody>${PAYS.slice().sort((a,b)=>a.due<b.due?-1:1).map(p=>{const d=daysBetween(TODAY,p.due);return `<tr onclick="card('sup','${p.sup}')"><td class="mono ${p.st==='open'&&d<=0?'neg':p.st==='open'&&d<=3?'warnt':''}">${dl(p.due)}${p.st==='open'?(d<0?' · просрочено':d===0?' · сегодня':' · через '+d+' дн.'):''}</td><td>${esc(SU(p.sup).n)}</td><td>${esc(p.what)}</td><td>${esc(PAYT[SU(p.sup).pay].n)}</td><td class="r mono">${fmt(p.sum)}</td><td onclick="event.stopPropagation()">${p.st==='paid'?'<span class="pos">оплачено</span>':`<button class="bt sm p" onclick="payDo('${p.id}')">Оплачено</button>`}</td></tr>`}).join('')}</tbody></table></div></div>
 ${said('«Кто-то сначала отправляет счёт на оплату, после этого мы оплачиваем, и нам отправляют товары. Есть консигнация — сначала товар отправляют, и потом оплачиваем.»')}`;
function payDo(id){const p=PAYS.find(x=>x.id===id);p.st='paid';const s=SU(p.sup);if(s.pay==='pre')s.pend=Math.max(0,s.pend-p.sum);else s.debt=Math.max(0,s.debt-p.sum);render();toast(`Оплата ${tg(p.sum)} отмечена — ${esc(s.n)}. ${s.pay==='pre'?'Поставщик получит уведомление в WhatsApp, ждём отгрузку.':'Долг уменьшен.'}`)}

/* ===== Договоры ===== */
SC.contracts=()=>`<div class="hd"><div><h2>Договоры с поставщиками</h2><p>Номер, дата, до какого числа действует, PDF договора и все дополнительные соглашения к нему. За 30 дней до окончания — напоминание руководителю и закупщику.</p></div><div class="btns"><button class="bt p" onclick="card('newctr')">+ Договор</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Поставщик</th><th>Договор</th><th>Заключён</th><th>Действует до</th><th class="r">Осталось</th><th>Предмет</th><th>PDF</th><th class="r">Доп. соглашений</th></tr></thead><tbody>${CONTRACTS.map(c=>{const d=daysBetween(TODAY,c.to);return `<tr onclick="card('ctr','${c.id}')"><td>${esc(SU(c.sup).n)}</td><td class="mono"><b>${esc(c.no)}</b></td><td class="mono">${dl(c.d)}</td><td class="mono">${dl(c.to)}</td><td class="r mono ${d<=30?'neg':d<=90?'warnt':''}">${d} дн.</td><td class="mini">${esc(c.subj)}</td><td>${c.pdf?'<span class="pos">есть</span>':'<span class="neg">прикрепить</span>'}</td><td class="r mono">${c.add.length}</td></tr>`}).join('')}</tbody></table></div>
 ${said('«Ведём все данные договора — номер договора, когда заключён и до какого числа, и возможность прикрепить электронный вариант, PDF… и дополнительные документы, если будут доп. соглашения.»')}`;

/* ===== Архив документов ===== */
let docF='all';
const DOCS=()=>{const D=[];CONTRACTS.forEach(c=>{if(c.pdf)D.push(['ctr',c.d,'Договор '+c.no,c.sup,c.pdf,`card('ctr','${c.id}')`]);c.add.forEach(a=>D.push(['ds',a[1],a[0]+' к договору '+c.no+' · '+a[2],c.sup,a[3],`card('ctr','${c.id}')`]))});
 INCOMES.forEach(i=>D.push(['inv',i.d,'Накладная '+i.inv+' · '+i.id,i.sup,i.pdf?'Скан_'+i.inv+'.pdf':'',`curIn='${i.id}';go('income')`]));
 PAYS.filter(p=>SU(p.sup).pay==='pre').forEach(p=>D.push(['bill',p.due,p.what,p.sup,'Счёт.pdf',`card('sup','${p.sup}')`]));
 D.push(['act','2026-09-30','Акт сверки на 30.09','S2','Акт_сверки_МС_30-09.pdf',`card('sup','S2')`],['act','2026-09-30','Отчёт о продажах консигнации 15–30.09','S3','Отчёт_ВМ_30-09.pdf',`card('sup','S3')`]);
 return D.sort((a,b)=>a[1]<b[1]?1:-1)};
const DOCT={ctr:'Договоры',ds:'Доп. соглашения',inv:'Накладные',bill:'Счета',act:'Акты и отчёты'};
SC.docs=()=>{const A=DOCS(),L=A.filter(d=>docF==='all'||d[0]===docF);
 return `<div class="hd"><div><h2>Архив документов</h2><p>Всё, что прикреплено к поставщикам, договорам и приходам, — в одном месте с поиском. Через год нужный договор или скан накладной находится за секунды, а не в папке на компьютере.</p></div></div>
 <div class="folders">${Object.keys(DOCT).map(k=>`<div class="folder ${docF===k?'on':''}" onclick="docF=docF==='${k}'?'all':'${k}';render()"><i>${A.filter(d=>d[0]===k).length}</i><b>${DOCT[k]}</b><span>${A.filter(d=>d[0]===k&&!d[4]).length?A.filter(d=>d[0]===k&&!d[4]).length+' без файла':'все с файлами'}</span></div>`).join('')}<div class="folder" onclick="act('b2b')"><i>B2B</i><b>Продажа юрлицам</b><span>редко · счёт и накладная из системы</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Дата</th><th>Тип</th><th>Документ</th><th>Поставщик</th><th>Файл</th></tr></thead><tbody>${L.map(d=>`<tr onclick="${d[5]}"><td class="mono">${dl(d[1])}</td><td>${DOCT[d[0]]}</td><td>${esc(d[2])}</td><td>${esc(SU(d[3]).n)}</td><td>${d[4]?`<span class="pdf">PDF</span> <span class="mini">${esc(d[4])}</span>`:'<span class="neg">не прикреплён</span>'}</td></tr>`).join('')}</tbody></table></div>`};

/* ===== Интеграции ===== */
SC.integr=()=>`<div class="hd"><div><h2>Интеграции</h2><p>Девять подключений — главное в системе. Делаем их там, где у стороннего сервиса есть API: у Kaspi, Halyk и Forte он есть, Провизор проверяем на старте, Wolt пока не даёт. Статус каждого виден в верхней строке на любом экране. Если площадка не ответила — система повторит запрос и сообщит, данные не теряются.</p></div></div>
 <div class="imap"><div class="ic l">${INTEG.filter(i=>['kaspi','halyk','forte','wolt'].includes(i.k)).map(i=>`<div class="inode" onclick="card('int','${i.k}')"><i class="dot ${i.st}"></i><b>${esc(i.full)}</b><span>${esc(i.sh)}</span></div>`).join('')}</div>
  <div class="icore"><b>BIPHARM</b><span>две аптеки · один учёт</span></div>
  <div class="ic r">${INTEG.filter(i=>['prov','ofd','ismp','nkt','wa'].includes(i.k)).map(i=>`<div class="inode" onclick="card('int','${i.k}')"><i class="dot ${i.st}"></i><b>${esc(i.full)}</b><span>${esc(i.sh)}</span></div>`).join('')}</div></div>
 <div class="tw"><table class="t"><thead><tr><th>Подключение</th><th>Что передаётся</th><th>Связь</th><th>Что нужно от вас</th></tr></thead><tbody>${INTEG.map(i=>`<tr onclick="card('int','${i.k}')"><td><i class="dot ${i.st}"></i><b>${esc(i.full)}</b></td><td class="mini">${esc(i.what)}</td><td class="mono">${esc(i.ago)}${i.msg?`<span class="sub">${esc(i.msg)}</span>`:''}</td><td class="mini">${esc(i.need)}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Мне главное, чтобы с интеграциями работали… Маркетплейсы и Национальный каталог товаров, и ИС МПТ — сайт маркировки лекарственных средств.»')}`;

/* ===== Роли ===== */
SC.roles=()=>{const areas=[['Заказы площадок: резерв, сборка, выдача',['ER','AS','DK','NR','ZN']],['Своя доставка: адреса и «доставлен»',['ER','AS','DK','NR','KR']],['Касса и фискальные чеки',['ER','AS','DK','GS']],['Остатки и приход своей аптеки',['ER','AS','DK','BL']],['Остатки обеих аптек — изменение',['ER','BL']],['Цены и демпинг на площадках',['ER','ZN']],['Закупочные цены и маржа',['ER','BL','GS']],['Поставщики, договоры, оплаты',['ER','BL','GS']],['Аналитика по выручке',['ER','ZN','GS']]];const R=Object.entries(ROLES);
 return `<div class="hd"><div><h2>Роли и права</h2><p>Фармацевт видит и меняет только свою аптеку; сборщик — очередь заказов в телефоне; менеджер площадок — цены и витрины, без закупочных цен; бухгалтер — чеки, НДС и оплаты. Руководитель видит всё и меняет права сам.</p></div></div>
 <div class="tw"><table class="t mx"><thead><tr><th>Что можно</th>${R.map(([k,v])=>`<th class="c">${esc(v.av)}<span>${esc(k)}</span></th>`).join('')}</tr></thead><tbody>${areas.map(a=>`<tr><td>${a[0]}</td>${R.map(([k,v])=>`<td class="c">${a[1].includes(v.p)?'<b class="pos">●</b>':'<span class="mini">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px">${R.map(([k,v])=>`<div class="pan"><h3>${esc(k)} · ${esc(v.n)}</h3><p>${esc(v.note)}</p><span class="mini">${v.s.length} ${plural(v.s.length,['экран','экрана','экранов'])}${v.st?' · только '+stName(v.st):''}</span></div>`).join('')}</div>`};

/* ===== Телефон ===== */
SC.mobile=()=>{const Q=ORDERS.filter(o=>['new','res','pack'].includes(o.st)&&o.s==='A1'),R=ORDERS.filter(o=>o.st==='refuse');
 return `<div class="hd"><div><h2>Телефон</h2><p>Ссылка открывается в браузере и сохраняется на экран как приложение. Сборщик собирает заказы и сканирует коды камерой, фармацевт принимает возвраты, руководитель видит день — откуда угодно.</p></div></div>
 <div class="phones">
  <div class="phone"><div class="pht"><b>Сборка · аптека №1</b><small>${Q.length} ${plural(Q.length,['заказ','заказа','заказов'])} в очереди</small></div><div class="pb">${Q.map(o=>`<div class="pi" onclick="openOrd('${o.id}')"><span>${MP[o.mp].s} ${esc(o.id)}<small>${esc(OSTOF(o.st).n)} · ${oQty(o)} шт.</small></span><b>${nextBtn(o)||''}</b></div>`).join('')}<div class="pbtn" onclick="act('scan')">Сканировать DataMatrix</div></div></div>
  <div class="phone"><div class="pht"><b>Возвраты от курьеров</b><small>${R.length} ждут приёмки</small></div><div class="pb">${R.map(o=>`<div class="pi"><span>${esc(o.id)}<small>${o.it.map(i=>esc(PR(i[0]).n.split(',')[0])+' × '+i[1]).join(', ')}</small></span><b>${STORES[o.s].s}</b></div>`).join('')||'<p class="mini">Нет</p>'}${R.length?`<div class="pbtn" onclick="ordBack('${R[0].id}')">Товар вернулся</div>`:''}</div></div>
  <div class="phone"><div class="pht"><b>Ерлан · день</b><small>${dl(TODAY)}, ${NOW}</small></div><div class="pb">${[['Выручка по чекам',tg(CHECKS.reduce((a,c)=>a+cSum(c),0))],['Новых заказов',ORDERS.filter(o=>o.st==='new').length],['В доставке',ORDERS.filter(o=>o.st==='courier').length],['Отказов в пути',R.length],['Оплатить сегодня',tg(PAYS.filter(p=>p.st==='open'&&p.due<=TODAY).reduce((a,p)=>a+p.sum,0))]].map(x=>`<div class="pi"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<div class="pbtn" onclick="go('today')">Открыть пульт</div></div></div>
  <div class="phone"><div class="pht"><b>Серик · курьер</b><small>своя доставка</small></div><div class="pb">${ORDERS.filter(o=>o.own&&o.st!=='back').map(o=>`<div class="pi"><span>${esc(o.addr)}<small>${esc(OSTOF(o.st).n)} · ${tg(oSum(o))}</small></span><b>${o.st==='courier'?'в пути':o.st==='done'?'✓':'ждёт'}</b></div>`).join('')}<div class="pbtn" onclick="go('courier')">Карта доставок</div></div></div>
 </div>`};

/* ===== Автоматизация ===== */
let AUTO=[
 ['Заказ пришёл с площадки','резерв на аптеке, где есть товар, и товарный чек — без ручного ввода',true,''],
 ['Заказ собран','своя доставка — заказ у курьера на карте; доставка площадки — ждём курьера',true,''],
 ['Площадка прислала «выдан» или курьер нажал «доставлен»','фискальный чек в ОФД, выбытие кодов в ИС МПТ, списание партии',true,''],
 ['Фискальный чек пробит','ссылка на чек — клиенту в WhatsApp',true,'если ОФД отдаёт ссылку на чек — проверяем на старте'],
 ['Отказ от площадки','«везут назад», резерв держится до приёмки',true,''],
 ['Накладная поставщика в Провизоре','черновик прихода на нужной аптеке с сериями и сроками',true,'при наличии API Провизора'],
 ['Остаток ниже минимума','задача закупщику и черновик заявки поставщику',true,''],
 ['Конкурент на Kaspi дешевле','робот демпинга в пределах порога',true,''],
 ['Заказ из Wolt','в ленту заказов с резервом',false,'включится, когда Wolt даст API']
];
function autoT(i){AUTO[i][2]=!AUTO[i][2];render();toast(AUTO[i][2]?'Правило включено.':'Правило выключено — этот шаг сотрудник делает вручную.')}
SC.auto=()=>`<div class="hd"><div><h2>Автоматизация</h2><p>Всё, что повторяется одинаково, система делает сама. Сотруднику остаётся то, что нельзя автоматизировать физически: собрать заказ, отсканировать DataMatrix маркированного товара, принять возврат и провести приход.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Когда</th><th>Что делает система</th><th>Условие</th><th>Вкл.</th></tr></thead><tbody>${AUTO.map((a,i)=>`<tr><td><b>${esc(a[0])}</b></td><td>${esc(a[1])}</td><td class="mini">${esc(a[3])||'—'}</td><td onclick="event.stopPropagation()"><span class="sw ${a[2]?'on':''}" onclick="autoT(${i})"></span></td></tr>`).join('')}</tbody></table></div>
 <div class="g3" style="margin-top:12px"><div class="pan"><h3>Остаётся сотруднику</h3>${['Собрать заказ и нажать «Собран»','Отсканировать код маркировки у маркированного товара','Принять возврат от курьера — «Товар вернулся»','Отсканировать коды и провести приход из Провизора'].map(x=>`<div class="li b"><i>·</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Резервные копии</h3>${[['На сервере','каждую ночь, хранятся 30 дней'],['На вашем компьютере','выгрузка полной копии кнопкой в настройках'],['Если сервер сломается','восстановление из последней копии']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<p class="mini" style="margin-top:6px">Формат выгрузки на компьютер уточняем со специалистами на старте.</p></div>
 <div class="pan"><h3>Расходы в месяц</h3>${[['WhatsApp через казахстанского провайдера','≈ 5 000 ₸'],['Сервер (до 100 ГБ)','0–10 000 ₸'],['Абонентская плата за систему','нет']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<p class="mini" style="margin-top:6px">Для сравнения: WhatsApp через интеграции Битрикс24 — около 36 000 ₸ за номер в месяц.</p></div></div>
 ${said('«Заказ упал — чтобы автоматом отработалось, а с нашей стороны только подтверждать; маркированный товар — маркировку.» · «Чек чтобы автоматически на WhatsApp клиента отправлялся — получится?»')}`;

/* ===== Запуск и стоимость ===== */
SC.launch=()=>`<div class="hd"><div><h2>Запуск и стоимость</h2><p>Стандартный пакет — 1 500 000 ₸, один раз, без абонентской платы. Предоплата — только 10%; остальное — после того, как вы приняли работу. Ядро — за две недели, затем шлифовка вместе с вами в Zoom и общей группе.</p></div></div>
 <div class="pay3"><div><small>Старт · 10%</small><b>150 000 ₸</b><span>данные, доступы, интеграции, ядро</span></div><div><small>Приёмка ядра · 45%</small><b>675 000 ₸</b><span>после того, как вы приняли ядро</span></div><div><small>После шлифовки · 45%</small><b>675 000 ₸</b><span>пользуетесь, правим, добавляем — потом остаток</span></div></div>
 <div class="g2"><div class="pan"><h3>Ядро — первые 2 недели</h3>${['Номенклатура: штрихкоды и артикулы, группы, НДС 5% / 16%','Две аптеки: остатки, резерв, партии и сроки','Заказы: новый → резерв → собран → у курьера → выдан / отказ','Товарный чек при резерве, возврат одной кнопкой','Перенос товаров и остатков из текущей программы'].map(x=>`<div class="li"><i>✓</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Шлифовка — вместе с вами</h3>${['Kaspi, Halyk, Forte; Wolt — когда даст API','Провизор: накладные поставщиков в приход','ОФД: чек по «выдан» и ссылка клиенту в WhatsApp','НКТ и ИС МПТ, разукомплектация, демпинг Kaspi','Своя доставка: курьер с картой; поставщики, договоры, аналитика'].map(x=>`<div class="li n"><i>→</i><span>${x}</span></div>`).join('')}<p class="mini" style="margin-top:6px">В пакете остаётся около 15% запаса — на то, что захотите добавить по ходу.</p></div></div>
 <div class="g2"><div class="pan"><h3>Интеграции — при наличии API</h3>${[['Kaspi, Halyk, Forte','API есть'],['Провизор','проверяем на старте'],['Wolt','пока не даёт API — подключим, когда откроют'],['НКТ, ИС МПТ, ОФД','по вашим доступам и ЭЦП'],['WhatsApp','через казахстанского провайдера']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<p class="mini" style="margin-top:6px">Если сторонний сервис не даёт API, это не наша недоработка: предложим обмен файлами или ручной режим в той же системе.</p></div>
 <div class="pan"><h3>После запуска</h3>${[['Сопровождение после передачи','несколько месяцев, наши ошибки — бесплатно'],['Доработки потом','20 $ в час, оценка заранее'],['WhatsApp','≈ 5 000 ₸ в месяц'],['Сервер','0–10 000 ₸ в месяц'],['Договор','с подписью ЭЦП — вы в Астане, мы в Алматы']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>
 ${said('«Десять процентов — допустим, двести тысяч — оплачиваю, вы приступаете, все данные, все интеграции настраиваете. Передаёте — я оплачиваю сорок пять. Пользуюсь, что-то подкорректировать… после этого остаток.»','Так и есть: 150 000 ₸ на старт, 675 000 ₸ после ядра, 675 000 ₸ после шлифовки.')}`;
