
/* ===== Карточки ===== */
const CARD={};
CARD.pr=id=>{const p=PR(id);const B=BATCHES.filter(b=>b.p===id&&b.q>0).sort((a,b)=>a.exp<b.exp?-1:1);
 return [esc(p.n),`${CATS[p.cat].n} · ${esc(p.mf)} · НДС ${vatOf(p)}%${p.rx?' · по рецепту':''}`,`<div class="g2"><div class="pan"><h3>Штрихкоды и артикулы · ${p.bc.length}</h3><p>Сканер и поиск находят товар по любому из них.</p>${p.bc.map(b=>`<div class="kv"><span>${esc(b[1])}</span><b class="mono">${esc(b[0])}</b></div>`).join('')}
  <div class="addbc"><input id="nbc" placeholder="новый код или артикул"><select id="nbw"><option>Артикул поставщика</option><option>Штрихкод производителя</option><option>Kaspi SKU</option><option>Halyk SKU</option><option>Forte SKU</option><option>Внутренний</option></select><button class="bt p" onclick="addBc('${id}')">Добавить</button></div></div>
 <div class="pan"><h3>Остатки</h3><div class="tw"><table class="t"><thead><tr><th>Аптека</th><th class="r">Полка</th><th class="r">Резерв</th><th class="r">Свободно</th><th class="r">Вскрыто</th></tr></thead><tbody>${SK.map(s=>`<tr><td>${stName(s)}</td><td class="r mono">${onHand(id,s)}</td><td class="r mono">${reserved(id,s)||'·'}</td><td class="r mono"><b>${freeQ(id,s)}</b></td><td class="r mono">${p.u&&p.op[s]?p.op[s]+' '+uAb(p):'·'}</td></tr>`).join('')}</tbody></table></div><div class="kv"><span>Минимальный остаток</span><b>${p.min} уп. на аптеку</b></div>
  ${[['Деление',p.u?`1 уп. = ${p.u[1]} ${uPl(p,p.u[1])} · ${tg(p.u[2])} за единицу`:'не делится'],['Закупка / цена',`${tg(p.cost)} / ${tg(p.price)} · маржа ${pct(p.price-p.cost,p.price)}%`],['НКТ',p.nkt==='ok'?'карточка есть · GTIN '+p.gtin:p.nkt==='wait'?'на модерации':'нет карточки'],['Маркировка',p.mk?'DataMatrix, ИС МПТ':'не требуется'],['Площадки',p.mpl.map(k=>MP[k].s+' '+fmt(mpPrice(p,k))).join(' · ')||'не выставлен']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div>
 <div class="pan"><h3>Партии</h3><div class="tw"><table class="t"><thead><tr><th>Аптека</th><th>Серия</th><th>Годен до</th><th class="r">Кол-во</th><th>Поставщик</th><th class="r">Закупка</th></tr></thead><tbody>${B.map(b=>`<tr><td>${stm(b.s)}</td><td class="mono">${b.no}</td><td class="mono">${dl(b.exp)}</td><td class="r mono">${b.q}</td><td>${esc(SU(b.sup).n)}</td><td class="r mono">${fmt(b.cost)}</td></tr>`).join('')}</tbody></table></div></div>`]};
CARD.ord=id=>{const o=OR(id);return [`${MP[o.mp].s} · заказ ${esc(o.id)}`,`${esc(o.cl)} · ${stName(o.s)} · ${OSTOF(o.st).n}`,ordBody(o)]};
CARD.tch=id=>{const o=OR(id);if(!o.tc)return ['Товарный чек','Появится при постановке в резерв','<p class="mini">Заказ ещё новый — нажмите «В резерв».</p>'];
 return ['Товарный чек '+o.tc,`Заказ ${o.id} · не фискальный документ`,`<div class="doc rc"><div class="dh"><div class="dlg">BIPHARM<small>${esc(stName(o.s)).toUpperCase()} · ${esc(STORES[o.s].addr)}</small></div><div style="text-align:right;font-size:10px">${o.tc}<br>${dl(o.d)}</div></div><h4>Товарный чек</h4><p style="font-size:11px">${MP[o.mp].n}, заказ ${o.id} · ${esc(o.cl)}</p><div class="drow h"><span>№</span><span>Товар</span><span class="r">Кол-во</span><span class="r">Сумма</span></div>${o.it.map((i,j)=>`<div class="drow"><span>${j+1}</span><span>${esc(PR(i[0]).n)}</span><span class="r">${i[1]}</span><span class="r">${fmt(lineSum(i))}</span></div>`).join('')}<div class="dsum"><span>Итого</span><span>${tg(oSum(o))}</span></div><div class="dfoot"><span>Не является фискальным документом. Фискальный чек будет пробит при выдаче заказа.</span><span>Собрал: ________</span></div></div>`]};
const fakeCode=(p,n)=>'01'+(p.gtin||'0000000000000').padStart(14,'0')+'21'+(p.id+n+'XQ7'+n*31).slice(0,10);
CARD.chk=no=>{const c=CHECKS.find(x=>x.no===no);if(!c)return ['Чек','—','<p class="mini">Чек не найден.</p>'];const v=vatSplit(c.it);
 return ['Фискальный чек '+c.no,`${stName(c.s)} · ${c.t} · ${c.ord?MP[c.src].s+' заказ '+c.ord:'продажа в аптеке'}`,`<div class="doc rc"><div class="dh"><div class="dlg">BIPHARM<small>${esc(stName(c.s)).toUpperCase()} · ${STORES[c.s].kkm}</small></div><div style="text-align:right;font-size:10px">${c.no}<br>${dl(TODAY)} ${c.t}</div></div><h4>Кассовый чек · продажа</h4>${c.it.map((i,j)=>{const p=PR(i[0]);return `<div class="drow"><span>${j+1}</span><span>${esc(p.n)}${i[2]==='u'?' — '+esc(p.u[0]):''}<br><small>НДС ${vatOf(p)}%${p.mk?' · код '+fakeCode(p,j):''}</small></span><span class="r">${i[1]}</span><span class="r">${fmt(lineSum(i))}</span></div>`}).join('')}<div class="dsum"><span>Итого</span><span>${tg(cSum(c))}</span></div>${Object.keys(v).sort((a,b)=>a-b).map(k=>`<div class="drow"><span></span><span>в т. ч. НДС ${k}%</span><span></span><span class="r">${fmt(vatSum(v[k],+k))}</span></div>`).join('')}<div class="dfoot"><span>Оплата: ${esc(c.pay)}<br>ОФД: ${c.ofd==='ok'?'чек принят':'отправляется'}</span><span>Фискальный признак 3${c.no.replace(/\D/g,'').slice(-7)}</span></div></div>`]};
CARD.int=k=>{const i=INT(k);const LOG={kaspi:[['14:18','Получено заказов: 2'],['14:15','Цены отправлены: 7 карточек'],['14:10','Остатки PP1 / PP2 отправлены'],['12:30','Статус «выдан»: 614497203 → чек']],halyk:[['14:16','Получен заказ HM-240917'],['14:00','Остатки и цены отправлены'],['11:15','Статус «выдан»: HM-240871 → чек']],forte:[['13:54','Ответ 12 с — повтор'],['13:02','Получен заказ FM-0031842'],['10:20','Передан курьеру: FM-0031807']],nkt:[['13:20','Сверка: 18 карточек, 2 на модерации'],['09:00','Ежедневная сверка']],ismp:[['14:02','Выбытие ФЧ-1-018824 — принято'],['13:58','Выбытие ФЧ-2-007417 — отправляется'],['30.09 17:10','Приёмка ВМ-Н-2207: 1 код не найден']],ofd:[['14:02','ФЧ-1-018824 принят'],['13:58','ФЧ-2-007417 отправляется'],['13:41','ФЧ-2-007416 принят']],wa:[['14:18','Ответ клиенту HM-240917'],['13:10','Счёт от «Фармлайн»'],['12:31','Ссылка на чек ФЧ-1-018822 — клиенту']],wolt:[['вчера','Запрос API у Wolt отправлен'],['вчера','Заказы Wolt вносятся вручную в ленту']],prov:[['14:05','Получена накладная ФЛ-58377 → черновик прихода IN-0933'],['30.09 09:00','Накладная ФЛ-58213 → приход IN-0931 проведён']]}[k]||[];
 return [esc(i.full),`Связь: ${esc(i.ago)} назад`,`<div class="g2"><div class="pan"><h3>Что передаётся</h3><p>${esc(i.what)}</p>${i.msg?`<div class="note" style="--tone:var(--${i.st==='err'?'bad':'warn'})"><b>Сейчас</b><p>${esc(i.msg)}</p></div>`:''}<div class="note"><b>Что нужно от вас</b><p>${esc(i.need)}</p></div></div><div class="pan"><h3>Журнал</h3>${LOG.map(l=>`<div class="kv"><span>${esc(l[1])}</span><b class="mono">${l[0]}</b></div>`).join('')}</div></div>`]};
CARD.ctr=id=>{const c=CONTRACTS.find(x=>x.id===id);const d=daysBetween(TODAY,c.to);
 return ['Договор '+esc(c.no),esc(SU(c.sup).n),`<div class="g2"><div class="pan"><h3>Реквизиты договора</h3>${[['Номер',esc(c.no)],['Заключён',dl(c.d)],['Действует до',dl(c.to)+' · осталось '+d+' дн.'],['Предмет',esc(c.subj)],['Порядок оплаты',PAYT[SU(c.sup).pay].n]].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
  <div class="file ${c.pdf?'':'no'}" style="margin-top:10px"><i>PDF</i><div><b>${c.pdf?esc(c.pdf):'Файл не прикреплён'}</b><span>${c.pdf?'электронная копия договора':'нажмите, чтобы прикрепить скан'}</span></div></div>${c.pdf?'':`<button class="bt w" style="margin-top:8px" onclick="CONTRACTS.find(x=>x.id==='${id}').pdf='Договор_${c.no.replace(/\//g,'-')}.pdf';card('ctr','${id}');render();toast('PDF договора прикреплён.')">Прикрепить PDF</button>`}</div>
 <div class="pan"><h3>Дополнительные соглашения · ${c.add.length}</h3>${c.add.map(a=>`<div class="file"><i>PDF</i><div><b>${esc(a[0])} от ${dl(a[1])}</b><span>${esc(a[2])}</span></div></div>`).join('')||'<p class="mini">Пока нет.</p>'}
  <div class="form one" style="margin-top:10px"><label>Новое ДС — о чём<input id="ds_t" value="Продление срока действия до 31.12.2027"></label></div><button class="bt p" onclick="addDs('${id}')">+ Доп. соглашение с PDF</button></div></div>`]};
function addDs(id){const c=CONTRACTS.find(x=>x.id===id);const t=document.getElementById('ds_t').value||'Доп. соглашение';const n='ДС-'+(c.add.length+1);c.add.push([n,TODAY,t,n+'_'+c.no.replace(/\//g,'-')+'.pdf']);if(/продлен/i.test(t))c.to='2027-12-31';card('ctr',id);render();toast(`${n} добавлено к договору ${esc(c.no)}${/продлен/i.test(t)?' — срок действия обновлён до 31.12.2027':''}.`)}
CARD.sup=id=>{const s=SU(id);const C=CONTRACTS.filter(c=>c.sup===id),I=INCOMES.filter(i=>i.sup===id),P=PAYS.filter(p=>p.sup===id);
 return [esc(s.n),`${PAYT[s.pay].n} · менеджер ${esc(s.mgr)}`,`<div class="g2"><div class="pan"><h3>Условия</h3>${[['Порядок',esc(s.term)],[s.pay==='pre'?'Счёт к оплате':'Долг',tg(s.pay==='pre'?s.pend:s.debt)]].concat(s.cons?[['Товар на консигнации',tg(s.cons)]]:[]).concat(C.map(c=>['Договор',`<a class="lk" onclick="card('ctr','${c.id}')">${esc(c.no)}</a> до ${dl(c.to)}`])).map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Оплаты</h3>${P.map(p=>`<div class="kv"><span>${dl(p.due)} · ${esc(p.what)}</span><b class="mono ${p.st==='paid'?'pos':''}">${fmt(p.sum)}</b></div>`).join('')||'<p class="mini">Нет.</p>'}</div></div>
 <div class="pan"><h3>Приходы</h3>${I.map(i=>`<div class="kv" style="cursor:pointer" onclick="closeM();curIn='${i.id}';go('income')"><span><span class="mono">${i.id}</span> · накладная ${esc(i.inv)} · ${dl(i.d)} · ${stName(i.s)} ${i.pdf?'· PDF':''}</span><b class="mono">${fmt(inSum(i))}</b></div>`).join('')||'<p class="mini">Нет.</p>'}</div>`]};
CARD.newpr=()=>['Новый товар','Название, группа, коды, деление',`<div class="form"><label>Название<input id="np_n" value="Ацетилцистеин 200 мг, порошок №20"></label><label>Группа (ставка НДС подставится)<select id="np_c">${Object.keys(CATS).map(k=>`<option value="${k}">${CATS[k].n} · ${vatOn(k,TODAY)}%</option>`).join('')}</select></label><label>Штрихкоды и артикулы — через запятую<input id="np_b" value="4870204512005, FL-51200, MS-ACC200-20"></label><label>Деление<select id="np_u"><option value="">не делится</option><option value="пакетик|20">20 пакетиков</option><option value="блистер|2">2 блистера</option></select></label><label>Закупка, ₸<input id="np_cost" value="620"></label><label>Цена, ₸<input id="np_p" value="1090"></label><label>Минимальный остаток<input id="np_min" value="5"></label><label>Маркировка<select id="np_mk"><option value="1">DataMatrix</option><option value="">не нужна</option></select></label></div><button class="bt p" onclick="newPr()">Создать и сверить с НКТ</button>`];
function newPr(){const v=i=>document.getElementById(i).value;const bc=v('np_b').split(',').map(x=>x.trim()).filter(Boolean);const dup=bc.find(b=>findBc(b));if(dup){toast(`Код ${esc(dup)} уже есть у другого товара.`);return}const u=v('np_u')?[v('np_u').split('|')[0],+v('np_u').split('|')[1],Math.ceil((+v('np_p')||0)/(+v('np_u').split('|')[1])*1.1/10)*10]:null;
 const id='P'+(PRODUCTS.length+1);PRODUCTS.push({id,n:v('np_n'),mf:'—',cat:v('np_c'),mk:!!v('np_mk'),nkt:'wait',gtin:bc[0]&&/^\d{13}$/.test(bc[0])?'0'+bc[0]:'',cost:+v('np_cost')||0,price:+v('np_p')||0,u,bc:bc.map((b,i)=>[b,i===0?'Штрихкод производителя':'Артикул поставщика']),st:{A1:[0,0],A2:[0,0]},op:{A1:0,A2:0},min:+v('np_min')||1,mpl:[]});closeM();catF='all';render();toast(`Товар создан с ${bc.length} ${plural(bc.length,['кодом','кодами','кодами'])}. Запрос в НКТ отправлен, НДС ${vatOn(v('np_c'),TODAY)}%.`)}
CARD.newctr=()=>['Новый договор','Поставщик, номер, сроки, PDF',`<div class="form"><label>Поставщик<select id="nc_s">${SUPPLIERS.map(s=>`<option value="${s.id}">${esc(s.n)}</option>`).join('')}</select></label><label>Номер<input id="nc_n" value="ВМ-К-27"></label><label>Дата<input id="nc_d" value="01.10.2026"></label><label>Действует до<input id="nc_t" value="30.09.2027"></label><label>Предмет<input id="nc_p" value="Консигнация БАДов, новая редакция"></label><label>Файл<select id="nc_f"><option>Скан договора.pdf</option><option>Прикрепить позже</option></select></label></div><button class="bt p" onclick="newCtr()">Сохранить</button>`];
function newCtr(){const v=i=>document.getElementById(i).value;const iso=s=>{const m=s.split('.');return m.length===3?m[2]+'-'+m[1]+'-'+m[0]:TODAY};CONTRACTS.unshift({id:'C'+(CONTRACTS.length+1),sup:v('nc_s'),no:v('nc_n'),d:iso(v('nc_d')),to:iso(v('nc_t')),pdf:v('nc_f').indexOf('позже')<0?'Договор_'+v('nc_n')+'.pdf':'',subj:v('nc_p'),add:[]});closeM();render();toast('Договор сохранён. Напоминание придёт за 30 дней до окончания.')}
function card(k,id){const f=CARD[k];if(!f)return;let r;try{r=f(id)}catch(e){toast('Карточка не найдена');return}openM(r[0],r[1],r[2])}
function act(k){const M={map2gis:'Адреса открываются в 2ГИС или Яндекс Картах — порядок объезда курьер выбирает сам.',report:'Каждый вечер в 21:00 в WhatsApp: выручка по аптекам и площадкам, заказы, отказы, что оплатить завтра.',wa:'Сообщение отправлено клиенту в WhatsApp.',z:'Z-отчёт закрыт в онлайн-кассе, итоги смены сохранены.',sync:'Цены и свободные остатки отправлены на Kaspi, Halyk и Forte.',floor:'Порог для каждой карточки: себестоимость последней партии + 15%. Можно задать вручную.',expiry:'Варианты: вернуть поставщику по договору, переместить в другую аптеку, выставить скидку на Kaspi.',newin:'Новый приход: поставщик, аптека, номер накладной — строки заполнятся из электронной накладной, коды — сканером.',import:'Загрузка из Excel или выгрузки текущей программы: названия, коды, группы, остатки по аптекам.',nktsync:'Сверка с НКТ запущена — статусы обновятся в течение нескольких минут.',scan:'Камера телефона читает DataMatrix — код сверяется с заказом.',b2b:'Продажа юрлицу: счёт на оплату и накладная формируются из системы, отгрузка списывает остаток. Используется редко — как вы сказали.'};toast(M[k]||'Готово.')}
function searchDemo(v){if(!v)return;const q=v.toLowerCase().trim();const o=ORDERS.find(x=>(x.id+' '+x.cl+' '+x.ph).toLowerCase().includes(q));if(o){openOrd(o.id);return}const b=findBc(q);if(b){card('pr',b[0].id);return}const p=PRODUCTS.find(x=>x.n.toLowerCase().includes(q));if(p){card('pr',p.id);return}const s=SUPPLIERS.find(x=>x.n.toLowerCase().includes(q));if(s){card('sup',s.id);return}toast('Ничего не нашлось. Ищите по номеру заказа, клиенту, телефону, штрихкоду, артикулу или поставщику.')}

/* ===== Каркас: рейка слева, строка интеграций сверху, экраны вкладками ===== */
const ICON={day:'<path d="M3 12h4l2.5-6 4 12 2.5-6h5"/>',ord:'<path d="M3 7.5l9-4 9 4v9l-9 4-9-4z"/><path d="M3 7.5l9 4 9-4M12 11.5v9"/>',mp:'<path d="M4 9l1.2-5h13.6L20 9"/><path d="M4 9v11h16V9M4 9h16M9.5 20v-6h5v6"/>',wh:'<path d="M4 3v18M20 3v18M4 8.5h16M4 14h16M4 20h16"/><path d="M7 5.5h3M13 11h4M8 17h5"/>',cat:'<rect x="2.5" y="8.5" width="19" height="7" rx="3.5" transform="rotate(-45 12 12)"/><path d="M9.5 9.5l5 5"/>',sup:'<path d="M2 6h11v10H2zM13 9.5h4.5L21 13v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="17" cy="18" r="2"/>',sys:'<circle cx="12" cy="12" r="3.2"/><path d="M12 2.5v3M12 18.5v3M2.5 12h3M18.5 12h3M5.3 5.3l2.1 2.1M16.6 16.6l2.1 2.1M5.3 18.7l2.1-2.1M16.6 7.4l2.1-2.1"/>'};
function renderRoles(){const r=document.getElementById('roles');if(r)r.innerHTML=Object.entries(ROLES).map(([k,v])=>`<div class="role" onclick="enter('${esc(k)}')"><div class="rav">${esc(v.av)}</div><div><b>${esc(k)}</b><span>${esc(v.n)} · ${esc(v.note)}</span></div></div>`).join('');
 const s=document.getElementById('rsel');if(s)s.innerHTML=Object.keys(ROLES).map(k=>`<option>${esc(k)}</option>`).join('')}
const allowed=k=>ROLES[role].s.indexOf(k)>=0;
function enter(k){role=ROLES[k]?k:'Руководитель';store=ROLES[role].st||'all';document.getElementById('gate').classList.add('hidden');document.getElementById('app').classList.remove('hidden');const s=document.getElementById('rsel');if(s)s.value=role;document.getElementById('me').textContent=ROLES[role].av;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Вы вошли как «${esc(role)}» · ${esc(ROLES[role].n)}.`)}
function switchRole(k){role=k;store=ROLES[role].st||'all';document.getElementById('me').textContent=ROLES[role].av;const s=document.getElementById('rsel');if(s)s.value=role;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Роль: ${esc(role)}. ${esc(ROLES[role].note)}.`)}
function buildRail(){const on=SECOF[cur];const nw=ORDERS.filter(o=>o.st==='new'&&inStore(o.s)).length+ORDERS.filter(o=>o.st==='refuse'&&o.arrived&&inStore(o.s)).length;
 document.getElementById('rail').innerHTML=SEC.filter(s=>s.sub.some(x=>allowed(x[0]))).map(s=>`<a class="ri ${s.k===on?'on':''}" onclick="go('${s.sub.filter(x=>allowed(x[0]))[0][0]}')"><svg viewBox="0 0 24 24">${ICON[s.k]}</svg><span>${s.n}</span>${s.k==='ord'&&nw?`<em>${nw}</em>`:''}</a>`).join('')}
function buildSub(){const s=SEC.find(x=>x.k===SECOF[cur]);document.getElementById('sub').innerHTML=s.sub.filter(x=>allowed(x[0])).map(x=>`<a class="${x[0]===cur?'on':''}" onclick="go('${x[0]}')">${esc(x[1])}</a>`).join('');const c=document.getElementById('crumb');if(c)c.textContent=s.n}
function buildSync(){const el=document.getElementById('sync');if(!el)return;const lock=ROLES[role].st;
 el.innerHTML=`<div class="sy-l">${INTEG.map(i=>`<a class="sy" onclick="card('int','${i.k}')" title="${esc(i.full)}"><i class="dot ${i.st}"></i>${esc(i.n)}<small>${esc(i.ago)}</small></a>`).join('')}</div><div class="sy-r"><span class="sy-t">${dd(TODAY)} · ${NOW}</span><div class="stsw">${(lock?[lock]:['all','A1','A2']).map(s=>`<button class="${store===s?'on':''}" onclick="setStore('${s}')">${s==='all'?'Обе аптеки':STORES[s].n}</button>`).join('')}</div></div>`}
function build(){buildSync();buildRail();buildSub();render()}
function render(){const f=SC[cur]||SC.today;document.getElementById('ttl').textContent=SUBN[cur]||'BIPHARM';document.getElementById('content').innerHTML=`<div class="screen">${f()}</div>`;buildSub();buildRail();
 const a=document.getElementById('addBtn');if(a)a.style.display=allowed('pos')?'':'none';try{history.replaceState(null,'','?s='+cur+(cur==='order'?'&o='+curOrd:''))}catch(e){}}
function go(k){if(!allowed(k)){toast('Этой роли раздел недоступен — так работают права. Переключите роль справа вверху.');return}cur=k;build();const c=document.querySelector('.content');if(c)c.scrollTop=0}
function openM(t,s,b){document.getElementById('mt').innerHTML=t;document.getElementById('ms').innerHTML=s;document.getElementById('mbody').innerHTML=b;document.getElementById('mbg').classList.add('show');document.querySelector('.modal').scrollTop=0}
function closeM(){document.getElementById('mbg').classList.remove('show')}
let tt=null;function toast(m){const t=document.getElementById('toast');t.innerHTML=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),6400)}
function applyTheme(){document.body.classList.toggle('dark',theme==='dark')}
function toggleTheme(){theme=theme==='dark'?'light':'dark';applyTheme();toast(theme==='dark'?'Тёмная тема.':'Светлая тема.')}

const TOUR=[
 ['today','1 · Пульт дня: заказы по шагам, что требует действия, выручка по фискальным чекам. Сверху — связь с Kaspi, Halyk, Forte, НКТ, ИС МПТ и ОФД.'],
 ['orders','2 · Все заказы площадок в одной ленте: номер, клиент, телефон, состав, аптека. Вводить вручную больше ничего не нужно.'],
 ['order','3 · Заказ: «В резерв» — товар уходит из свободного остатка, печатается товарный чек. Фискального пока нет.'],
 ['returns','4 · Отказ: товар везут назад, резерв держится. «Товар вернулся» — резерв снят, остаток восстановлен, чек возвращать не нужно.'],
 ['checks','5 · Фискальный чек — только при «выдан» или продаже в аптеке, НДС разбит на 5% и 16%.'],
 ['pos','6 · Продажа в аптеке: сканер найдёт товар по любому из кодов, можно продать один блистер.'],
 ['courier','6а · Своя доставка: заказы Kaspi, которые вы везёте сами, — у курьера на карте, маршрут он выбирает сам.'],
 ['market','7 · На площадки уходит свободный остаток каждой аптеки — за вычетом резерва.'],
 ['dumping','8 · Демпинг Kaspi: робот снижает цену на шаг, но не ниже порога от себестоимости.'],
 ['stock','9 · Остатки двух аптек: полка, резерв, свободно, вскрытые упаковки, минимум.'],
 ['batches','10 · Партии и сроки годности: первым продаётся ближайший срок.'],
 ['income','11 · Приход: строки накладной, серии и сроки, коды маркировки и скан накладной в PDF.'],
 ['catalog','12 · Номенклатура: у товара сколько угодно штрихкодов и артикулов.'],
 ['unpack','13 · Разукомплектация: коробка → блистеры, партия и срок переходят.'],
 ['vat','14 · НДС по группам: лекарства 5% и с 2027 года 10%, остальное 16%.'],
 ['nkt','15 · НКТ: без карточки товар не публикуется — система показывает, что заблокировано.'],
 ['marking','16 · ИС МПТ: приёмка кодов, выбытие при выдаче, БАДы с 1 сентября.'],
 ['suppliers','17 · Поставщики: предоплата, отсрочка, консигнация — календарь оплат.'],
 ['contracts','18 · Договоры: номер, срок, PDF и доп. соглашения, напоминание за 30 дней.'],
 ['integr','19 · Девять интеграций — делаем там, где у сервиса есть API.'],
 ['auto','19а · Автоматизация: сотруднику остаются сборка и скан маркировки, остальное — система.'],
 ['launch','20 · Стоимость: 1,5 млн один раз, 10 / 45 / 45, ядро за 2 недели.']
];
let ti=-1,tRun=false;
function tour(){if(tRun){stopTour();return}tRun=true;ti=-1;document.getElementById('tourBtn').textContent='■';step()}
function step(){if(!tRun)return;ti++;if(ti>=TOUR.length){stopTour();toast('Сценарий закончен. Всё кликается: заказы, резерв, выдача, возвраты, чеки, приход, договоры.');return}const [k,m]=TOUR[ti];if(!allowed(k)){step();return}cur=k;if(k==='order')curOrd='614502871';build();toast(m);setTimeout(step,ti===0?6500:7200)}
function stopTour(){tRun=false;ti=-1;const b=document.getElementById('tourBtn');if(b)b.textContent='▶'}
(function(){renderRoles();applyTheme();const s=document.getElementById('rsel');if(s)s.addEventListener('change',e=>switchRole(e.target.value));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeM();stopTour()}});
 let q='',o='';try{const u=new URLSearchParams(location.search);q=u.get('s')||'';o=u.get('o')||''}catch(e){}if(o&&OR(o))curOrd=o;
 if(q&&SECOF[q]){const r=Object.keys(ROLES).find(k=>ROLES[k].s.indexOf(q)>=0);if(r){cur=q;enter(r)}}})();
