
const SC={};
const tagSt=k=>{const m={new:'i',wait:'w',part:'w',paid:'g',docs:'g',fly:'i',done:'',refund:'r'};return `<span class="tag ${m[k]||''}">${OSN(k)}</span>`};
const fTag=f=>`<span class="tag ${FST[f.st][1]}">${FST[f.st][0]}${f.newT?' · '+f.newT:''}</span>`;
/* графики */
function lineChart(pts,{h=150,lbl=[]}={}){const w=600,mx=Math.max(...pts)*1.1,step=w/(pts.length-1),P=pts.map((v,i)=>[i*step,h-v/mx*h]);const d=P.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');
 return `<svg class="lc" viewBox="0 -10 ${w} ${h+12}" preserveAspectRatio="none"><path d="${d} L ${w} ${h} L 0 ${h} Z" class="la"/><path d="${d}" class="ll"/>${P.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" class="lp"/>`).join('')}</svg><div class="lcl">${lbl.map(l=>`<span>${l}</span>`).join('')}</div>`}
function bars(rows){const mx=Math.max(...rows.map(r=>r[1]));return rows.map(r=>`<div class="hb"><span>${r[0]}</span><i style="width:${r[1]/mx*100}%"></i><b>${r[2]||fmt(r[1])}</b></div>`).join('')}
let dPer='week';
const SALES={day:[0.4,0.9,1.6,2.1,2.8,3.4,4.2,4.9,5.6,6.1,6.8,7.4],week:[18.2,22.6,19.4,27.8,31.2,24.6,29.4],month:[61,74,82,96,88,104,118,126,97,112,131,142]};
const SLBL={day:['09:00','','','12:00','','','15:00','','','18:00','','21:00'],week:['пн','вт','ср','чт','пт','сб','вс'],month:['ноя','дек','янв','фев','мар','апр','май','июн','июл','авг','сен','окт']};
SC.dash=()=>{const tot={day:7.4,week:173.2,month:1331}[dPer];const ordN={day:14,week:96,month:742}[dPer];
 return `<div class="hd"><div><h2>Пульт · ${TODAY}</h2><p>Пользователи приложения, заказы и продажи за день, неделю, месяц — с графиками. Ниже — ближайшие рейсы и что требует внимания.</p></div><div class="seg">${[['day','День'],['week','Неделя'],['month','Месяц']].map(x=>`<a class="${dPer===x[0]?'on':''}" onclick="dPer='${x[0]}';render()">${x[1]}</a>`).join('')}</div></div>
 <div class="wid">
  <div class="clk" onclick="go('tourists')"><small>Пользователей приложения</small><b>18 942</b><span>+412 за неделю · 63% с включёнными push</span></div>
  <div class="clk" onclick="go('orders')"><small>Заказов за ${dPer==='day'?'день':dPer==='week'?'неделю':'месяц'}</small><b class="a">${ordN}</b><span>${dPer==='day'?'+3 к вчера':dPer==='week'?'+12% к прошлой':'+9% к сентябрю'}</span></div>
  <div class="clk" onclick="go('finance')"><small>Продажи</small><b class="g">${{day:'7,4 млн',week:'173 млн',month:'1,33 млрд'}[dPer]} ₸</b><span>средний чек 1,18 млн</span></div>
  <div class="clk" onclick="go('finance')"><small>Долги туристов</small><b class="w">${mln(ORDERS.reduce((a,o)=>a+(o.st==='refund'?0:o.sum-o.paid),0))}</b><span>${ORDERS.filter(o=>o.st!=='refund'&&o.sum>o.paid).length} заказа · ближайший вылет завтра</span></div>
  <div class="clk" onclick="go('flights')"><small>Рейсы на неделе</small><b>${FLIGHTS.length}</b><span>${FLIGHTS.filter(f=>f.st!=='ok').length} с изменениями</span></div>
 </div>
 <div class="g2 g21"><div class="pan"><h3>Продажи, млн ₸ · ${dPer==='day'?'сегодня по часам':dPer==='week'?'эта неделя':'12 месяцев'}</h3>${lineChart(SALES[dPer],{lbl:SLBL[dPer]})}</div>
 <div class="pan"><h3>Направления · заказы за месяц</h3>${bars([['Анталья',268],['Шарм-эль-Шейх',176],['Дубай',121],['Нячанг',98],['Пхукет',79]])}<h3 style="margin-top:14px">Источники заказов</h3>${bars([['Приложение',338,'46%'],['Instagram',176,'24%'],['Сайт',139,'19%'],['Повторные',89,'11%']])}</div></div>
 <div class="g2"><div class="pan"><h3>Ближайшие рейсы</h3><div class="tw"><table class="t"><thead><tr><th>Рейс</th><th>Дата</th><th>Туристов</th><th>Статус</th></tr></thead><tbody>${FLIGHTS.slice(0,4).map(f=>`<tr class="clk" onclick="go('flights')"><td><b>${f.id}</b> ${f.from} → ${f.to}</td><td class="mono">${f.d} ${f.t}</td><td class="mono">${f.tour}</td><td>${fTag(f)}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="pan"><h3>Требует внимания</h3>
  <div class="rf bad" onclick="go('flights')"><i></i><div><b>ST455 Шарм-эль-Шейх перенесён на 13:30</b><span>push отправлен 201 туристу · открыли 164</span></div></div>
  <div class="rf bad" onclick="applySaved(1)"><i></i><div><b>3 заказа не оплачены, вылет меньше чем через 7 дней</b><span>долг 2,84 млн · напоминание об оплате уходит автоматически</span></div></div>
  <div class="rf" onclick="applySaved(2)"><i></i><div><b>4 заказа без авиабилетов в документах</b><span>вылеты 11–15.10</span></div></div>
  <div class="rf" onclick="go('auto')"><i></i><div><b>Регистрация на SL809 откроется 12.10</b><span>push «Регистрация открыта» уйдёт автоматически 131 туристу</span></div></div></div></div>
 ${said('Дашборд с основной аналитикой: количество пользователей, количество заказов, продажи за день/неделю/месяц, графики и статистика.')}`};

/* Заказы */
let F={q:'',st:'',fl:'',dir:'',air:'',m:'',when:'',unpaid:0,nodocs:0,moved:0,mine:0},SEL=new Set(),savedOn=-1;
function applySaved(i){const s=SAVED[i];F={q:'',st:'',fl:'',dir:'',air:'',m:'',when:'',unpaid:0,nodocs:0,moved:0,mine:0,...s.f};savedOn=i;go('orders')}
function fOrders(){return ORDERS.filter(o=>{const f=FL(o.fl);const t=(o.id+' '+o.pax.map(p=>p[0]).join(' ')+' '+o.hotel+' '+o.ph).toLowerCase();
 if(F.q&&!t.includes(F.q.toLowerCase()))return false;if(F.st&&o.st!==F.st)return false;if(F.fl&&o.fl!==F.fl)return false;if(F.dir&&f.to!==F.dir)return false;if(F.air&&f.air!==F.air)return false;if(F.m&&o.m!==F.m)return false;
 if(F.when==='tomorrow'&&f.d!=='11.10')return false;if(F.unpaid&&!(o.paid<o.sum&&o.st!=='refund'))return false;if(F.nodocs&&!(o.st!=='refund'&&(!o.docs.ticket||!o.docs.vouch)))return false;if(F.moved&&f.st==='ok')return false;if(F.mine&&o.m!=='DN')return false;return true})}
const sel=(id,opts,v,ph)=>`<select onchange="F.${id}=this.value;savedOn=-1;render()"><option value="">${ph}</option>${opts.map(o=>`<option value="${o[0]}" ${v===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>`;
SC.orders=()=>{const L=fOrders();
 return `<div class="hd"><div><h2>Заказы</h2><p>Фильтры по статусу, рейсу, направлению, авиакомпании и менеджеру. Частые подборки сохраняются одним кликом. Выделили заказы — отправили push, напоминание об оплате или выгрузили в Excel.</p></div><div class="btns"><button class="bt" onclick="exportXls('orders')">⇩ Excel</button><button class="bt p" onclick="card('neword')">+ Заказ</button></div></div>
 <div class="saved">${SAVED.map((s,i)=>`<a class="${savedOn===i?'on':''}" onclick="applySaved(${i})">★ ${esc(s.n)}<em>${(()=>{const b=F,bo=savedOn;F={q:'',st:'',fl:'',dir:'',air:'',m:'',when:'',unpaid:0,nodocs:0,moved:0,mine:0,...s.f};const n=fOrders().length;F=b;savedOn=bo;return n})()}</em></a>`).join('')}<a class="add" onclick="saveFilter()">+ Сохранить текущий фильтр</a></div>
 <div class="flt"><input placeholder="Поиск: номер, турист, телефон, отель" value="${esc(F.q)}" onchange="F.q=this.value;savedOn=-1;render()">${sel('st',OST,F.st,'Все статусы')}${sel('fl',FLIGHTS.map(f=>[f.id,f.id+' '+f.to]),F.fl,'Все рейсы')}${sel('dir',DIR.map(d=>[d,d]),F.dir,'Все направления')}${sel('air',Object.entries(AIR),F.air,'Все авиакомпании')}${sel('m',Object.entries(MGR),F.m,'Все менеджеры')}<a class="lk" onclick="F={q:'',st:'',fl:'',dir:'',air:'',m:'',when:'',unpaid:0,nodocs:0,moved:0,mine:0};savedOn=-1;render()">Сбросить</a></div>
 ${SEL.size?`<div class="bulk"><b>Выбрано: ${SEL.size}</b><button class="bt sm p" onclick="bulkPush()">Отправить push</button><button class="bt sm" onclick="toast('Напоминание об оплате отправлено ${SEL.size} заказам: push + WhatsApp.')">Напомнить об оплате</button><button class="bt sm" onclick="exportXls('sel')">⇩ Excel</button><a class="lk" onclick="SEL.clear();render()">снять выделение</a></div>`:''}
 <div class="tw"><table class="t ord"><thead><tr><th><input type="checkbox" onchange="if(this.checked)fOrders().forEach(o=>SEL.add(o.id));else SEL.clear();render()" ${L.length&&L.every(o=>SEL.has(o.id))?'checked':''}></th><th>Заказ</th><th>Туристы</th><th>Рейс</th><th>Отель</th><th class="r">Сумма</th><th class="r">Долг</th><th>Документы</th><th>Статус</th><th>Менеджер</th></tr></thead><tbody>${L.map(o=>{const f=FL(o.fl);const d=o.st==='refund'?0:o.sum-o.paid;return `<tr class="clk ${SEL.has(o.id)?'sel':''}"><td onclick="event.stopPropagation()"><input type="checkbox" ${SEL.has(o.id)?'checked':''} onchange="this.checked?SEL.add('${o.id}'):SEL.delete('${o.id}');render()"></td><td onclick="openOrd('${o.id}')"><b>${o.id}</b><div class="sub">${o.created} · ${o.src}${o.app?' · в приложении':''}</div></td><td onclick="openOrd('${o.id}')">${esc(o.pax[0][0])}${o.pax.length>1?` +${o.pax.length-1}`:''}</td><td onclick="openOrd('${o.id}')"><b>${o.fl}</b> ${f.to}<div class="sub">${f.d} ${f.newT||f.t} ${f.st!=='ok'?`<span class="neg">${FST[f.st][0].toLowerCase()}</span>`:''}</div></td><td onclick="openOrd('${o.id}')" class="mini">${esc(o.hotel)}</td><td class="r mono" onclick="openOrd('${o.id}')">${fmt(o.sum)}</td><td class="r mono ${d?'neg':''}" onclick="openOrd('${o.id}')">${d?fmt(d):'—'}</td><td onclick="openOrd('${o.id}')">${docDots(o)}</td><td onclick="openOrd('${o.id}')">${tagSt(o.st)}</td><td onclick="openOrd('${o.id}')">${MGR[o.m]}</td></tr>`}).join('')||'<tr><td colspan="10" class="mini">Ничего не найдено</td></tr>'}</tbody></table></div>
 <p class="mini">Показано ${L.length} из ${ORDERS.length} · в рабочей системе — все заказы с постраничной загрузкой.</p>
 ${said('Добавить возможность сохранять часто используемые фильтры и быстрые подборки заказов. Выгружать отчёты в Excel.')}`};
const docDots=o=>`<span class="dd">${[['vouch','В'],['ticket','Б'],['ins','С'],['visa','Ви']].map(([k,l])=>`<i class="${o.docs[k]?'on':''}" title="${{vouch:'Ваучер',ticket:'Авиабилет',ins:'Страховка',visa:'Виза'}[k]}">${l}</i>`).join('')}</span>`;
function saveFilter(){const n=prompt('Название подборки','Мои фильтры '+(SAVED.length+1));if(!n)return;SAVED.push({n,f:{...F}});savedOn=SAVED.length-1;render();toast(`Подборка «${esc(n)}» сохранена — видна вам; руководитель может сделать её общей.`)}
function bulkPush(){PUSH.ids=[...SEL];PUSH.mode='orders';go('push');toast(`Получатели — туристы из ${SEL.size} выбранных заказов.`)}
function openOrd(id){curOrd=id;go('order')}

SC.order=()=>{const o=OR(curOrd),f=FL(o.fl),h=HIST[o.id]||[['10.10 10:00','Система','Заказ создан','—',o.created]],cm=COMMENTS[o.id]||[];const d=o.st==='refund'?0:o.sum-o.paid;
 return `<div class="hd"><div><div class="mini"><a class="lk" onclick="go('orders')">Заказы</a> / ${o.id}</div><h2>${o.id} · ${f.to}, ${o.nights} ночей</h2><p>${esc(o.hotel)} · ${o.pax.length} туриста · менеджер ${MGR[o.m]} · создан ${o.created} · ${o.src}</p></div><div class="btns"><button class="bt" onclick="PUSH.ids=['${o.id}'];PUSH.mode='orders';go('push')">Push туристам</button><button class="bt p" onclick="card('pay','${o.id}')">+ Оплата</button></div></div>
 <div class="ostp">${OST.slice(0,7).map((s,i)=>{const ci=OST.findIndex(x=>x[0]===o.st);return `<div class="${o.st==='refund'?'':i<ci?'ok':i===ci?'on':''}"><i>${i<ci&&o.st!=='refund'?'✓':i+1}</i>${s[1]}</div>`}).join('')}</div>
 <div class="g3">
  <div class="pan"><h3>Перелёт</h3><div class="kv"><span>Туда</span><b>${o.fl} · ${f.from} → ${f.to}</b></div><div class="kv"><span>Вылет</span><b>${f.d} ${f.newT?`<s>${f.t}</s> ${f.newT}`:f.t}</b></div><div class="kv"><span>Авиакомпания</span><b>${AIR[f.air]}</b></div><div class="kv"><span>Обратно</span><b>${o.back}</b></div><div class="kv"><span>Регистрация</span><b>${f.reg}</b></div>${f.st!=='ok'?`<div class="pin">${FST[f.st][0]}: новое время ${f.newT}. Туристам отправлен push.</div>`:''}</div>
  <div class="pan"><h3>Туристы</h3>${o.pax.map(p=>`<div class="kv"><span>${esc(p[0])}<em class="mini"> · ${p[1]}</em></span><b class="mono">${p[2]}</b></div>`).join('')}<div class="kv"><span>Телефон</span><b class="mono">${o.ph}</b></div><div class="kv"><span>Приложение</span><b>${o.app?'установлено · push включены':'<span class="neg">не установлено — SMS / WhatsApp</span>'}</b></div></div>
  <div class="pan"><h3>Деньги</h3><div class="kv"><span>Стоимость</span><b class="mono">${tg(o.sum)}</b></div><div class="kv"><span>Оплачено</span><b class="mono pos">${tg(o.paid)}</b></div><div class="kv"><span>Долг</span><b class="mono ${d?'neg':''}">${tg(d)}</b></div>${o.refund?`<div class="kv"><span>Возврат</span><b class="mono neg">${tg(o.refund)}</b></div>`:''}<div class="kv"><span>Оплатить до</span><b>${d?'за 7 дней до вылета · авто-напоминание':'—'}</b></div></div>
 </div>
 <div class="g2">
  <div class="pan"><h3>Документы</h3>${[['vouch','Ваучер на отель','PDF'],['ticket','Авиабилеты','PDF'],['ins','Страховка','PDF'],['visa','Виза / разрешение','PDF'],['contract','Договор с туристом','подписан ЭЦП']].map(([k,n,t])=>{const has=k==='contract'||o.docs[k];return `<div class="doc ${has?'':'no'}"><i>${has?'PDF':'—'}</i><span><b>${n}</b><em>${has?t+' · отправлен в приложение':'не загружен'}</em></span>${has?'<a class="lk" onclick="toast(\'Документ открыт.\')">Открыть</a>':`<a class="lk" onclick="OR('${o.id}').docs['${k}']=1;render();toast('Документ загружен — туристу ушёл push «Документы готовы».')">Загрузить</a>`}</div>`}).join('')}</div>
  <div class="pan"><h3>Комментарии</h3><div class="cms">${cm.map(c=>`<div class="cm"><small>${c[0]} · ${c[1]}</small>${esc(c[2])}</div>`).join('')||'<p class="mini">Комментариев пока нет.</p>'}</div><div class="qin"><input id="cmin" placeholder="Комментарий для коллег, @упоминание…" onkeydown="if(event.key==='Enter')addCm()"><button class="bt p" onclick="addCm()">Добавить</button></div></div>
 </div>
 <div class="pan"><h3>История изменений заказа</h3><div class="tw"><table class="t"><thead><tr><th>Когда</th><th>Кто</th><th>Что</th><th>Было</th><th>Стало</th></tr></thead><tbody>${h.map(x=>`<tr><td class="mono">${x[0]}</td><td><b>${x[1]}</b></td><td>${x[2]}</td><td class="mini">${esc(x[3])}</td><td>${esc(x[4])}</td></tr>`).join('')}</tbody></table></div></div>
 ${said('Сделать более информативную карточку заказа, где будут все документы, комментарии и история изменений. Историю — кто, когда и какие изменения внёс.')}`};
function addCm(){const v=document.getElementById('cmin');if(!v||!v.value.trim())return;(COMMENTS[curOrd]=COMMENTS[curOrd]||[]).push([ROLES[role].n,TODAY.slice(0,5)+' '+NOW,v.value.trim()]);(HIST[curOrd]=HIST[curOrd]||[]).unshift([TODAY.slice(0,5)+' '+NOW,ROLES[role].n,'Комментарий','—',v.value.trim().slice(0,60)]);render()}

SC.tourists=()=>`<div class="hd"><div><h2>Туристы и приложение</h2><p>База туристов: кто установил приложение, включены ли push, сколько поездок. Отсюда же — сегменты для рассылок.</p></div></div>
 <div class="wid"><div><small>Туристов в базе</small><b>31 406</b><span>за всё время</span></div><div><small>Установили приложение</small><b class="a">18 942</b><span>60%</span></div><div><small>Push включены</small><b class="g">11 930</b><span>63% установивших</span></div><div><small>Повторные</small><b>27%</b><span>2+ поездки</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Турист</th><th>Телефон</th><th>Поездок</th><th>Последний заказ</th><th>Приложение</th><th>Push</th></tr></thead><tbody>${ORDERS.flatMap(o=>o.pax.filter(p=>p[1]==='взр.').slice(0,1).map(p=>[p[0],o.ph,o.id==='Z-24166'?4:o.id==='Z-24187'?2:1,o.id+' · '+FL(o.fl).to,o.app,o.app&&o.id!=='Z-24203'])).map(r=>`<tr><td><b>${esc(r[0])}</b></td><td class="mono">${r[1]}</td><td class="mono">${r[2]}</td><td>${r[3]}</td><td>${r[4]?'<span class="tag g">установлено</span>':'<span class="tag">нет</span>'}</td><td>${r[5]?'вкл':'—'}</td></tr>`).join('')}</tbody></table></div>`;
