
SC.flights=()=>`<div class="hd"><div><h2>Рейсы</h2><p>Все рейсы с туристами: загрузка, регистрация, статус. Перенос или задержка вводится один раз — время обновляется во всех заказах, и туристам рейса уходит push.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Рейс</th><th>Авиакомпания</th><th>Маршрут</th><th>Вылет</th><th>Места</th><th>Туристов</th><th>Регистрация</th><th>Статус</th><th></th></tr></thead><tbody>${FLIGHTS.map(f=>`<tr class="${f.st==='moved'?'rowwarn':f.st==='delay'?'rowbad':''}"><td><b>${f.id}</b></td><td>${AIR[f.air]}</td><td>${f.from} → ${f.to}</td><td class="mono">${f.d} ${f.newT?`<s>${f.t}</s> <b>${f.newT}</b>`:f.t}</td><td><div class="pbr"><i style="width:${f.sold/f.seats*100}%"></i></div><span class="mini">${f.sold} / ${f.seats}</span></td><td class="mono">${f.tour}</td><td class="mini">${f.reg}</td><td>${fTag(f)}</td><td><button class="bt sm" onclick="card('move','${f.id}')">Перенос / задержка</button></td></tr>`).join('')}</tbody></table></div>
 ${said('Массовая отправка Push-уведомлений туристам с фильтрацией по рейсу… например, при переносе рейса или изменении времени вылета.')}`;
function moveDo(id){const f=FL(id),t=document.getElementById('mv_t').value.trim(),k=document.getElementById('mv_k').value;if(!t){toast('Укажите новое время');return}const old=f.newT||f.t;f.newT=t;f.st=k;(HIST['Z-24187']=HIST['Z-24187']||[]);AUDIT.unshift([TODAY.slice(0,5)+' '+NOW,ROLES[role].n,role,'Рейсы',`Изменил время вылета ${id}`,`${old} → ${t}`,'Chrome · Mac']);closeM();
 if(document.getElementById('mv_p').checked){PUSH.f={fl:id,dir:'',air:'',date:'',pay:''};PUSH.mode='filter';PUSH.title=k==='delay'?'Задержка рейса '+id:'Перенос рейса '+id;PUSH.text=`Внимание! Рейс ${id} ${f.from} → ${f.to} ${f.d}: новое время вылета ${t}. Трансфер в аэропорт сдвинут автоматически. Вопросы — в чат в приложении.`;go('push');toast(`Время ${id} обновлено во всех заказах. Push подготовлен — проверьте текст и отправьте.`)}else{render();toast(`Время ${id} обновлено во всех заказах.`)}}

SC.tours=()=>`<div class="hd"><div><h2>Направления и туры</h2><p>Направления, отели и блоки мест на рейсах — откуда менеджер собирает заказ, а туристы в приложении видят предложения.</p></div></div>
 <div class="g3">${[['Анталья','Турция','268 заказов в месяц','Lara Palace 5★ · Side Garden 4★ · Alanya Sun 4★','от 498 000 ₸'],['Шарм-эль-Шейх','Египет','176 заказов','Coral Bay Resort 5★ · Reef Oasis 4★','от 452 000 ₸'],['Дубай','ОАЭ','121 заказ','Marina View 4★ · Palm Club 5★','от 612 000 ₸'],['Нячанг','Вьетнам','98 заказов','Sea Pearl 4★ · Nha Trang Bay 5★','от 589 000 ₸'],['Пхукет','Таиланд','79 заказов','Kata Beach 5★ · Patong Hill 4★','от 701 000 ₸']].map(d=>`<div class="pan dest"><h3>${d[0]} <span class="mini">${d[1]}</span></h3><div class="kv"><span>Спрос</span><b>${d[2]}</b></div><p class="mini">${d[3]}</p><b class="pr">${d[4]}</b></div>`).join('')}</div>`;

/* Массовые push */
let PUSH={mode:'filter',f:{fl:'',dir:'',air:'',date:'',pay:''},ids:[],title:'Осенние скидки −10%',text:'Только до 20 октября: −10% на туры в Анталью и Шарм-эль-Шейх при оплате в приложении.',when:'now'};
let PSENT=[['10.10 13:33','Арман','Перенос рейса ST455','рейс ST455',201,198,164],['10.10 10:05','Ая','Осенние скидки −10%','все с push',11930,11702,3011],['09.10 18:00','Авто','Напоминание о вылете','рейс SL801 · завтра',176,174,149],['09.10 12:00','Авто','Напоминание об оплате','долг · вылет < 7 дней',12,12,10]];
function pushRecipients(){if(PUSH.mode==='orders')return ORDERS.filter(o=>PUSH.ids.includes(o.id)).reduce((a,o)=>a+o.pax.length,0);
 let n=0;FLIGHTS.forEach(f=>{if(PUSH.f.fl&&f.id!==PUSH.f.fl)return;if(PUSH.f.dir&&f.to!==PUSH.f.dir)return;if(PUSH.f.air&&f.air!==PUSH.f.air)return;if(PUSH.f.date&&f.d!==PUSH.f.date)return;n+=f.tour});if(PUSH.f.pay==='debt')n=Math.round(n*.08);if(!PUSH.f.fl&&!PUSH.f.dir&&!PUSH.f.air&&!PUSH.f.date&&!PUSH.f.pay)n=11930;return n}
const psel=(k,opts,ph)=>`<label>${ph}<select onchange="PUSH.f.${k}=this.value;PUSH.mode='filter';render()"><option value="">Все</option>${opts.map(o=>`<option value="${o[0]}" ${PUSH.f[k]===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></label>`;
SC.push=()=>{const n=pushRecipients();
 return `<div class="hd"><div><h2>Массовые push-уведомления</h2><p>Выбираете туристов фильтрами — по рейсу, дате, направлению, авиакомпании, оплате — или из выделенных заказов. Видно, сколько человек получит, как выглядит уведомление на телефоне, сколько доставлено и открыто.</p></div></div>
 <div class="pushw"><div class="pan"><h3>1. Кому</h3>${PUSH.mode==='orders'?`<div class="pin">Туристы из выбранных заказов: ${PUSH.ids.join(', ')} <a class="lk" onclick="PUSH.mode='filter';render()">выбрать фильтрами</a></div>`:`<div class="form">${psel('fl',FLIGHTS.map(f=>[f.id,f.id+' · '+f.to+' · '+f.d]),'Рейс')}${psel('date',[...new Set(FLIGHTS.map(f=>f.d))].map(d=>[d,d]),'Дата вылета')}${psel('dir',DIR.map(d=>[d,d]),'Направление')}${psel('air',Object.entries(AIR),'Авиакомпания')}${psel('pay',[['debt','Есть долг по оплате'],['paid','Оплачено полностью']],'Оплата')}</div>`}
  <div class="rcp"><b>${fmt(n)}</b><span>получателей с включёнными push · остальным — SMS / WhatsApp</span></div>
  <h3>2. Сообщение</h3><div class="form one"><label>Заголовок<input value="${esc(PUSH.title)}" oninput="PUSH.title=this.value;pv()"></label><label>Текст<textarea rows="4" oninput="PUSH.text=this.value;pv()">${esc(PUSH.text)}</textarea></label><label>Что откроется по нажатию<select><option>Карточка заказа в приложении</option><option>Информация о рейсе</option><option>Чат с менеджером</option><option>Акция</option></select></label></div>
  <div class="tpls"><span class="mini">Шаблоны:</span>${[['Перенос рейса','Внимание! Время вылета вашего рейса изменилось. Новое время — в приложении.'],['Регистрация открыта','Онлайн-регистрация на ваш рейс открыта. Зарегистрируйтесь в приложении, чтобы выбрать места.'],['Документы готовы','Ваш ваучер, билеты и страховка готовы — они уже в приложении.'],['Напоминание об оплате','Остаток по туру нужно оплатить до вылета. Оплатить можно в приложении через Kaspi.']].map(t=>`<a onclick="PUSH.title=${JSON.stringify(t[0]).replace(/"/g,'&quot;')};PUSH.text=${JSON.stringify(t[1]).replace(/"/g,'&quot;')};render()">${t[0]}</a>`).join('')}</div>
  <h3>3. Когда</h3><div class="seg">${[['now','Сейчас'],['plan','Запланировать']].map(x=>`<a class="${PUSH.when===x[0]?'on':''}" onclick="PUSH.when='${x[0]}';render()">${x[1]}</a>`).join('')}</div>${PUSH.when==='plan'?'<input class="inp" value="11.10.2026 09:00">':''}
  <div class="btns l" style="margin-top:14px"><button class="bt p" onclick="pushSend(${n})">Отправить ${fmt(n)} туристам</button><button class="bt" onclick="toast('Тестовое уведомление отправлено на ваш телефон.')">Тест себе</button></div></div>
 <div class="phonew"><div class="phone"><div class="ph-top"><span>14:20</span><span>●●● ▮</span></div><div class="ph-lock"><b>14:20</b><span>суббота, 10 октября</span></div><div class="ntf" id="pvn"><div class="ntf-h"><i>К</i><b>Компас Тур</b><span>сейчас</span></div><b class="ntf-t">${esc(PUSH.title)}</b><p>${esc(PUSH.text)}</p></div></div><p class="mini" style="text-align:center">Так туристы увидят уведомление</p></div></div>
 <div class="pan"><h3>Отправленные рассылки</h3><div class="tw"><table class="t"><thead><tr><th>Когда</th><th>Кто</th><th>Рассылка</th><th>Кому</th><th class="r">Отправлено</th><th class="r">Доставлено</th><th class="r">Открыли</th></tr></thead><tbody>${PSENT.map(r=>`<tr><td class="mono">${r[0]}</td><td>${r[1]}</td><td><b>${esc(r[2])}</b></td><td class="mini">${esc(r[3])}</td><td class="r mono">${fmt(r[4])}</td><td class="r mono">${fmt(r[5])}</td><td class="r mono">${fmt(r[6])} · ${Math.round(r[6]/r[5]*100)}%</td></tr>`).join('')}</tbody></table></div></div>
 ${said('Массовая отправка Push-уведомлений туристам с фильтрацией по рейсу, дате, направлению или авиакомпании.')}`};
function pv(){const n=document.getElementById('pvn');if(n){n.querySelector('.ntf-t').textContent=PUSH.title;n.querySelector('p').textContent=PUSH.text}}
function pushSend(n){PSENT.unshift([TODAY.slice(0,5)+' '+NOW,ROLES[role].n,PUSH.title,PUSH.mode==='orders'?'выбранные заказы':Object.entries(PUSH.f).filter(x=>x[1]).map(x=>x[1]).join(' · ')||'все с push',n,Math.round(n*.985),0]);AUDIT.unshift([TODAY.slice(0,5)+' '+NOW,ROLES[role].n,role,'Push',`Массовый push «${PUSH.title}»`,n+' получателей','Chrome · Mac']);SEL.clear();render();toast(`${PUSH.when==='now'?'Отправлено':'Запланировано'}: ${fmt(n)} туристам. Статистика доставки и открытий — в таблице ниже.`)}

/* Автоуведомления */
let AUTO=[['Регистрация открыта','за 24 ч до вылета (по данным авиакомпании)','push · WhatsApp',1,'«Онлайн-регистрация на рейс {рейс} открыта»'],['Напоминание об оплате','за 10, 7 и 3 дня до вылета, если есть долг','push · WhatsApp · SMS',1,'«Остаток {долг} ₸ нужно оплатить до {дата}»'],['Документы готовы','когда менеджер загрузил ваучер / билеты / страховку','push',1,'«Ваши документы уже в приложении»'],['Напоминание о вылете','за 24 часа и за 4 часа','push · SMS',1,'«Вылет {рейс} завтра в {время}, будьте в аэропорту за 3 часа»'],['Перенос или задержка рейса','при изменении времени в разделе «Рейсы»','push · SMS',1,'«Новое время вылета {время}»'],['Трансфер','за 12 часов до трансфера','push',1,'«Трансфер из отеля в {время}, гид {имя}»'],['Обратный вылет','за 24 часа до обратного рейса','push',1,'«Вылет домой {дата} {время}»'],['Отзыв о поездке','на следующий день после возвращения','push',0,'«Оцените поездку — 1 минута»'],['День рождения','в день рождения туриста','push',0,'«Скидка −5% на следующий тур»']];
SC.auto=()=>`<div class="hd"><div><h2>Автоматические уведомления</h2><p>Система сама пишет туристам в нужный момент: регистрация, оплата, документы, вылет. Включаете правило, правите текст — дальше работает без менеджера.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Уведомление</th><th>Когда</th><th>Каналы</th><th>Текст</th><th>Вкл.</th></tr></thead><tbody>${AUTO.map((a,i)=>`<tr><td><b>${a[0]}</b></td><td class="mini">${a[1]}</td><td class="mini">${a[2]}</td><td class="mini">${esc(a[4])}</td><td><span class="sw ${a[3]?'on':''}" onclick="AUTO[${i}][3]=AUTO[${i}][3]?0:1;this.classList.toggle('on');toast(AUTO[${i}][3]?'Включено':'Выключено')"></span></td></tr>`).join('')}</tbody></table></div>
 <div class="g2"><div class="pan"><h3>Сегодня уйдёт автоматически</h3>${[['13:30','Регистрация открыта','ST455 · 201 турист'],['18:00','Напоминание о вылете','SL801, ST455 · 377 туристов'],['20:00','Напоминание об оплате','3 заказа с долгом']].map(x=>`<div class="kv"><span class="mono">${x[0]}</span><span>${x[1]}</span><b>${x[2]}</b></div>`).join('')}</div>
 <div class="pan"><h3>Если нет приложения</h3><p class="mini">Туристам без приложения или с выключенными push то же сообщение уходит в WhatsApp или SMS — через провайдера с API. В карточке заказа видно, что и когда отправлено.</p></div></div>
 ${said('Автоматические уведомления туристам (об открытии регистрации, напоминание об оплате, отправка документов, напоминание о вылете).')}`;

/* Финансы */
SC.finance=()=>{const debtT=ORDERS.filter(o=>o.st!=='refund'&&o.paid<o.sum);
 return `<div class="hd"><div><h2>Финансы</h2><p>Выручка, возвраты и задолженности: туристы — нам, мы — туроператорам и авиакомпаниям. По месяцам, направлениям и менеджерам.</p></div><div class="btns"><button class="bt" onclick="exportXls('finance')">⇩ Excel</button></div></div>
 <div class="wid"><div><small>Выручка · октябрь</small><b class="g">142 млн</b><span>+8,5% к сентябрю</span></div><div><small>Маржа</small><b>18,6 млн</b><span>13,1% от выручки</span></div><div><small>Возвраты · октябрь</small><b class="r">4,8 млн</b><span>9 заказов · 3,4%</span></div><div><small>Долги туристов</small><b class="w">${mln(debtT.reduce((a,o)=>a+o.sum-o.paid,0))}</b><span>${debtT.length} заказа</span></div><div><small>Долг партнёрам</small><b>38,4 млн</b><span>оплатить до 15.10</span></div></div>
 <div class="g2 g21"><div class="pan"><h3>Выручка и возвраты, млн ₸</h3>${lineChart(SALES.month,{lbl:SLBL.month})}<div class="lg2"><i class="c1"></i>выручка · возвраты в октябре 3,4% — в таблице справа внизу</div></div>
 <div class="pan"><h3>Выручка по менеджерам · октябрь</h3>${bars([['Дана',48.2,'48,2 млн'],['Тимур',36.9,'36,9 млн'],['Асель',31.4,'31,4 млн'],['Ерлан',25.5,'25,5 млн']])}</div></div>
 <div class="g2"><div class="pan"><h3>Долги туристов</h3><div class="tw"><table class="t"><thead><tr><th>Заказ</th><th>Вылет</th><th class="r">Долг</th><th>Напоминание</th></tr></thead><tbody>${debtT.map(o=>`<tr class="clk" onclick="openOrd('${o.id}')"><td><b>${o.id}</b> ${esc(o.pax[0][0])}</td><td class="mono">${FL(o.fl).d}</td><td class="r mono neg">${fmt(o.sum-o.paid)}</td><td class="mini">авто · за 7 и 3 дня</td></tr>`).join('')}</tbody></table></div></div>
 <div class="pan"><h3>Возвраты</h3><div class="tw"><table class="t"><thead><tr><th>Заказ</th><th>Причина</th><th class="r">Сумма</th><th>Статус</th></tr></thead><tbody>${[['Z-24152','Болезнь туриста, справка','520 000','выплачен'],['Z-24098','Отмена рейса авиакомпанией','1 240 000','ждёт оператора'],['Z-24077','Отказ в визе','388 000','выплачен']].map(r=>`<tr><td><b>${r[0]}</b></td><td class="mini">${r[1]}</td><td class="r mono">${r[2]}</td><td><span class="tag ${r[3]==='выплачен'?'g':'w'}">${r[3]}</span></td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:12px">Долг партнёрам</h3>${[['Туроператор «Анатолия Трэвел»','21,6 млн','15.10'],['SkyLine KZ · блоки мест','12,1 млн','13.10'],['Отели Египта (прямые)','4,7 млн','18.10']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]} · до ${x[2]}</b></div>`).join('')}</div></div>
 ${said('Добавить раздел «Финансы» с аналитикой по выручке, возвратам и задолженностям.')}`};

/* Отчёты в Excel — настоящая выгрузка */
const REPS=[['orders','Заказы по текущему фильтру','номер, туристы, рейс, отель, сумма, оплачено, долг, статус, менеджер'],['debts','Неоплаченные заказы до вылета','заказ, турист, телефон, вылет, долг'],['flight','Списки туристов по рейсу','рейс, ФИО, паспорт, телефон, отель — для авиакомпании и трансфера'],['finance','Выручка и возвраты за период','месяц, выручка, возвраты, маржа'],['managers','Продажи по менеджерам','менеджер, заказы, выручка, средний чек'],['push','Отчёт по рассылкам','рассылка, отправлено, доставлено, открыто']];
SC.reports=()=>`<div class="hd"><div><h2>Отчёты в Excel</h2><p>Любой отчёт — в Excel одной кнопкой. Попробуйте: файл скачается по-настоящему, с данными демо.</p></div></div>
 <div class="g3">${REPS.map(r=>`<div class="pan rep"><h3>${r[1]}</h3><p class="mini">${r[2]}</p><button class="bt p sm" onclick="exportXls('${r[0]}')">⇩ Скачать Excel</button></div>`).join('')}</div>
 ${said('Добавить возможность выгружать отчёты в Excel.')}`;
function exportXls(k){let head=[],rows=[],name='otchet';
 const oRow=o=>{const f=FL(o.fl);return [o.id,o.pax.map(p=>p[0]).join(', '),o.fl+' '+f.to+' '+f.d,o.hotel,o.sum,o.paid,o.st==='refund'?0:o.sum-o.paid,OSN(o.st),MGR[o.m]]};
 if(k==='orders'||k==='sel'){head=['Заказ','Туристы','Рейс','Отель','Сумма','Оплачено','Долг','Статус','Менеджер'];rows=(k==='sel'?ORDERS.filter(o=>SEL.has(o.id)):fOrders()).map(oRow);name='zakazy'}
 else if(k==='debts'){head=['Заказ','Турист','Телефон','Вылет','Долг'];rows=ORDERS.filter(o=>o.st!=='refund'&&o.paid<o.sum).map(o=>[o.id,o.pax[0][0],o.ph,FL(o.fl).d+' '+FL(o.fl).t,o.sum-o.paid]);name='dolgi'}
 else if(k==='flight'){head=['Рейс','ФИО','Паспорт','Телефон','Отель'];rows=ORDERS.flatMap(o=>o.pax.map(p=>[o.fl,p[0],p[2],o.ph,o.hotel]));name='spiski_reisov'}
 else if(k==='finance'){head=['Месяц','Выручка, млн','Возвраты, млн','Маржа, млн'];rows=SLBL.month.map((m,i)=>[m,SALES.month[i],Math.round(SALES.month[i]*.035*10)/10,Math.round(SALES.month[i]*.13*10)/10]);name='finansy'}
 else if(k==='managers'){head=['Менеджер','Заказов','Выручка, млн','Средний чек'];rows=[['Дана',41,48.2,1175600],['Тимур',31,36.9,1190300],['Асель',27,31.4,1162900],['Ерлан',22,25.5,1159100]];name='menedzhery'}
 else {head=['Когда','Рассылка','Отправлено','Доставлено','Открыли'];rows=PSENT.map(r=>[r[0],r[2],r[4],r[5],r[6]]);name='rassylki'}
 const x='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"></head><body><table border="1"><tr>'+head.map(h=>`<th style="background:#0b4f6c;color:#fff">${esc(h)}</th>`).join('')+'</tr>'+rows.map(r=>'<tr>'+r.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')+'</table></body></html>';
 try{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+x],{type:'application/vnd.ms-excel'}));a.download=name+'_'+TODAY.replace(/\./g,'-')+'.xls';document.body.appendChild(a);a.click();a.remove()}catch(e){}
 AUDIT.unshift([TODAY.slice(0,5)+' '+NOW,ROLES[role].n,role,'Отчёты',`Выгрузил в Excel «${name}»`,rows.length+' строк','Chrome · Mac']);toast(`Excel скачан: ${rows.length} строк.`)}

/* Журнал действий */
let aF='';
SC.audit=()=>{const L=AUDIT.filter(a=>!aF||a[3]===aF);return `<div class="hd"><div><h2>Журнал действий пользователей</h2><p>Каждое изменение в системе: кто, когда, что сделал, что было и что стало, с какого устройства. Ничего нельзя удалить незаметно.</p></div><div class="btns"><button class="bt" onclick="toast('Журнал выгружен в Excel.')">⇩ Excel</button></div></div>
 <div class="seg">${['','Заказы','Рейсы','Push','Финансы','Отчёты','Настройки'].map(x=>`<a class="${aF===x?'on':''}" onclick="aF='${x}';render()">${x||'Все'}</a>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Когда</th><th>Кто</th><th>Раздел</th><th>Действие</th><th>Было → стало</th><th>Устройство</th></tr></thead><tbody>${L.map(a=>`<tr><td class="mono">${a[0]}</td><td><b>${a[1]}</b><div class="sub">${a[2]}</div></td><td>${a[3]}</td><td>${esc(a[4])}</td><td class="mini">${esc(a[5])}</td><td class="mini">${a[6]}</td></tr>`).join('')}</tbody></table></div>
 ${said('Добавить журнал действий пользователей для контроля всех изменений в системе.')}`};

SC.staff=()=>{const A=[['Пульт и аналитика',{Р:2,М:1,О:1,Б:1,Мк:1}],['Заказы — все',{Р:2,О:1,Б:1}],['Заказы — свои',{Р:2,М:2,О:1}],['Рейсы, перенос',{Р:2,О:2}],['Массовые push',{Р:2,О:2,Мк:2}],['Финансы',{Р:2,Б:2}],['Журнал действий',{Р:2}],['Настройки и стиль',{Р:2}]];const R=[['Р','Руководитель'],['М','Менеджер'],['О','Авиа и опер.'],['Б','Бухгалтер'],['Мк','Маркетинг']];
 return `<div class="hd"><div><h2>Сотрудники и роли</h2><p>Каждый входит под своим логином и видит только своё. Права настраиваются без программиста.</p></div><div class="btns"><button class="bt p" onclick="toast('Приглашение отправлено на почту сотрудника.')">+ Сотрудник</button></div></div>
 <div class="tw"><table class="t mx"><thead><tr><th>Раздел</th>${R.map(r=>`<th class="c">${r[1]}</th>`).join('')}</tr></thead><tbody>${A.map(a=>`<tr><td>${a[0]}</td>${R.map(r=>`<td class="c">${a[1][r[0]]===2?'●':a[1][r[0]]===1?'○':'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="mini">● — меняет · ○ — только смотрит · — — не видит.</p>`};
