const SEED=window.MINI_CRM_DATA;
const STORAGE_KEY='pllato_mini_crm_demo_v1';
const view=document.getElementById('view'),drawer=document.getElementById('drawer'),drawerBody=document.getElementById('drawerBody'),overlay=document.getElementById('screenOverlay'),modal=document.getElementById('modal'),modalBody=document.getElementById('modalBody'),toastEl=document.getElementById('toast');
let state=loadState();
const titles={today:'Главная',sales:'Продажи',clients:'Клиенты',tasks:'Задачи',analytics:'Аналитика',settings:'Настройки'};
const guides={
  today:['С чего начать','Сначала посмотрите красные сигналы и задачи на сегодня. Отсюда владелец понимает, кому нужно позвонить и сколько денег ожидается.'],
  sales:['Как вести сделку','Откройте карточку клиента или перетащите её в следующую колонку. На телефоне этап меняется кнопкой внутри карточки.'],
  clients:['Что хранится о клиенте','Одна карточка собирает контакты, компанию, сделки и всю историю. Клиента не нужно искать в переписках менеджеров.'],
  tasks:['Как не забывать о продажах','Каждая задача связана с клиентом или сделкой. Выполните её галочкой — просрочка исчезнет с главного экрана.'],
  analytics:['Какие цифры смотреть','Малому бизнесу достаточно выручки, конверсии, среднего чека, источников и причин отказа.'],
  settings:['Настройка за 15 минут','Выберите готовую воронку, добавьте сотрудников и подключите форму сайта. Сложного внедрения не требуется.']
};
const money=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0)+' ₸';
const num=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=name=>String(name).split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function loadState(){try{const saved=localStorage.getItem(STORAGE_KEY);return saved?JSON.parse(saved):structuredClone(SEED)}catch{return structuredClone(SEED)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function route(){return new URLSearchParams(location.search).get('s')||'today'}
function go(s){history.pushState({},'',location.pathname+'?s='+s);render()}
function stage(id){return state.stages.find(x=>x.id===id)||state.stages[0]}
function pageHead(kicker,title,desc,actions=''){return `<header class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div><div class="head-actions">${actions}</div></header>`}
function guide(s){const g=guides[s]||guides.today;return `<section class="demo-guide"><i>?</i><div><b>${g[0]}</b><span>${g[1]}</span></div><button data-action="start-tour">Показать на примере →</button></section>`}
function metric(label,value,note,cls=''){return `<article class="metric ${cls}"><small>${label}</small><b>${value}</b><span class="${cls==='green'?'good':''}">${note}</span></article>`}
function openDrawer(html){drawerBody.innerHTML=html;drawer.classList.add('open');overlay.classList.add('open')}
function closeDrawer(){drawer.classList.remove('open');overlay.classList.remove('open')}
function openModal(html){modalBody.innerHTML=html;modal.classList.add('open')}
function closeModal(){modal.classList.remove('open')}
let toastTimer;function toast(text){toastEl.querySelector('span').textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2300)}
function updateChrome(s){document.getElementById('crumbTitle').textContent=titles[s]||titles.today;document.querySelectorAll('#mainNav [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===s))}

function renderToday(){
  const openDeals=state.deals.filter(d=>!['won','lost'].includes(d.stage));
  const pipeline=openDeals.reduce((a,d)=>a+d.amount,0),won=state.deals.filter(d=>d.stage==='won').reduce((a,d)=>a+d.amount,0);
  const todo=state.tasks.filter(t=>t.status==='todo'),overdue=todo.filter(t=>t.priority==='high');
  return pageHead('ПУЛЬТ МАЛОГО БИЗНЕСА','Доброе утро, Алексей','Сегодня главное — не потерять новые заявки, выполнить обещанные звонки и довести клиентов до оплаты.','<button class="secondary-btn" data-action="new-task">+ Задача</button><button class="primary-btn" data-action="new-deal">+ Сделка</button>')+
  `<section class="onboarding"><div class="onboarding-main"><span>PLLATO MINI CRM · ВСЁ ГОТОВО К РАБОТЕ</span><h2>Продажи без таблиц, блокнотов и потерянных заявок.</h2><p>Каждый клиент получает ответственного, следующий шаг и место в воронке. Владелец видит результат отдела продаж в одном экране.</p><div class="setup-steps"><div class="setup-step"><i>01</i><b>Заявка</b><span>Создаётся за 20 секунд</span></div><div class="setup-step"><i>02</i><b>Следующий шаг</b><span>CRM напомнит менеджеру</span></div><div class="setup-step"><i>03</i><b>Оплата</b><span>Попадает в отчёт владельца</span></div></div></div><aside class="onboarding-side"><span>ТРЕБУЕТ ВНИМАНИЯ</span><div class="today-actions"><div class="today-action"><i>1</i><div><b>Просрочен звонок Жанне</b><small>Сделка на 540 000 ₸ · КП отправлено</small></div><button data-open="deal" data-id="D-1033">→</button></div><div class="today-action"><i>2</i><div><b>Раушан не оплатила счёт</b><small>315 000 ₸ · обещанный срок прошёл</small></div><button data-open="deal" data-id="D-1024">→</button></div><div class="today-action"><i>3</i><div><b>2 новые заявки без ответа</b><small>Instagram и форма сайта</small></div><button data-nav="sales">→</button></div></div></aside></section>`+
  `<section class="metric-grid">${metric('Продажи в августе',money(won),'План выполнен на 9%','green')}${metric('В активной воронке',money(pipeline),openDeals.length+' сделок в работе','blue')}${metric('Новые заявки','7','2 ещё без первого контакта','red')}${metric('Задачи на сегодня',todo.length,overdue.length+' требуют внимания','red')}</section>`+
  `<section class="two-col"><article class="panel"><div class="panel-head"><div><span class="eyebrow">СЛЕДУЮЩЕЕ ДЕЙСТВИЕ</span><h2>Что сделать сегодня</h2></div><button data-nav="tasks">Все задачи →</button></div><div class="action-list">${todo.slice(0,5).map(t=>`<div class="action-row ${t.priority==='high'?'risk':''}"><i></i><div><b>${esc(t.title)}</b><span>${esc(t.client)} · ${esc(t.time)} · ${esc(t.assignee)}</span></div><button data-task-toggle="${t.id}">Готово</button></div>`).join('')}</div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">7 ДНЕЙ</span><h2>Новые заявки</h2></div><button data-nav="analytics">Отчёт →</button></div><div class="mini-chart">${[['Пн',5],['Вт',8],['Ср',6],['Чт',10],['Пт',7],['Сб',4],['Сегодня',9]].map(x=>`<div><i style="height:${x[1]*11}px"></i><span>${x[0]}</span></div>`).join('')}</div></article></section>`+
  `<section class="two-col"><article class="panel"><div class="panel-head"><div><span class="eyebrow">СДЕЛКИ</span><h2>Ближе всего к оплате</h2></div><button data-nav="sales">Открыть воронку →</button></div><div class="action-list">${state.deals.filter(d=>['offer','payment'].includes(d.stage)).map(d=>`<div class="action-row ${d.due==='overdue'?'risk':''}"><i></i><div><b>${esc(d.client)} · ${esc(d.service)}</b><span>${stage(d.stage).name} · ${esc(d.next)}</span></div><button data-open="deal" data-id="${d.id}">${money(d.amount)} →</button></div>`).join('')}</div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">ИСТОЧНИКИ</span><h2>Откуда приходят клиенты</h2></div></div><div class="source-list">${[['Instagram',31,92],['Сайт',24,72],['Рекомендации',18,55],['Google',15,46],['WhatsApp',12,36]].map(x=>`<div class="source-row"><span>${x[0]}</span><i><b style="width:${x[2]}%"></b></i><strong>${x[1]}%</strong></div>`).join('')}</div></article></section>`;
}

function dealCard(d){return `<button class="deal-card" draggable="true" data-drag-deal="${d.id}" data-open="deal" data-id="${d.id}"><small>${d.id} · ${esc(d.source)}</small><b>${esc(d.client)}</b><span>${esc(d.service)}<br>${esc(d.company||d.phone)}</span><strong>${money(d.amount)}</strong><footer><span class="${d.due==='overdue'?'overdue':''}">${esc(d.next||'Завершено')}</span><em>${esc(d.manager)}</em></footer></button>`}
function renderSales(){
  const visibleStages=state.stages.filter(s=>s.id!=='lost');
  const cols=visibleStages.map(s=>{const deals=state.deals.filter(d=>d.stage===s.id);return `<section class="kanban-col" data-drop-stage="${s.id}" style="--stage-color:${s.color}"><header class="kanban-head"><b>${s.name}</b><span>${deals.length} · ${money(deals.reduce((a,d)=>a+d.amount,0))}</span></header>${deals.map(dealCard).join('')||'<div class="empty">Пока пусто</div>'}</section>`}).join('');
  return pageHead('ЗАЯВКА → КОНТАКТ → ОПЛАТА','Воронка продаж','Все активные сделки находятся перед глазами. Карточку можно открыть или перетащить в следующий этап.','<button class="secondary-btn" data-action="sales-export">Экспорт</button><button class="primary-btn" data-action="new-deal">+ Новая сделка</button>')+
  `<section class="metric-grid">${metric('Активных сделок',state.deals.filter(d=>!['won','lost'].includes(d.stage)).length,'На '+money(state.deals.filter(d=>!['won','lost'].includes(d.stage)).reduce((a,d)=>a+d.amount,0)),'blue')}${metric('Ждут оплаты',state.deals.filter(d=>d.stage==='payment').length,money(state.deals.filter(d=>d.stage==='payment').reduce((a,d)=>a+d.amount,0)),'red')}${metric('Конверсия','28%','↑ 4 п.п. за месяц','green')}${metric('Средний чек',money(391000),'По закрытым сделкам','')}</section>`+
  `<div class="board-toolbar"><div class="tabs"><button class="active">Активные</button><button data-action="show-lost">Отказы · ${state.deals.filter(d=>d.stage==='lost').length}</button></div><div class="filters"><button>Все менеджеры⌄</button><button>Все источники⌄</button></div></div><div class="kanban-wrap"><div class="kanban">${cols}</div></div>`;
}

function clientRows(list=state.clients){return list.map(c=>`<tr class="clickable" data-open="client" data-id="${c.id}"><td><div class="client-cell"><span class="avatar">${initials(c.name)}</span><span><b>${esc(c.name)}</b><span>${esc(c.company)}</span></span></div></td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${c.deals}</td><td><b>${money(c.revenue)}</b></td><td>${esc(c.last)}</td><td><button class="secondary-btn" style="height:30px" data-open="client" data-id="${c.id}">Открыть →</button></td></tr>`).join('')}
function renderClients(){return pageHead('ЕДИНАЯ БАЗА','Клиенты','Контакты, компании, покупки и история общения находятся в одном месте.','<button class="secondary-btn" data-action="client-import">Импорт</button><button class="primary-btn" data-action="new-client">+ Новый клиент</button>')+`<section class="metric-grid">${metric('Всего клиентов','428','+18 за этот месяц','blue')}${metric('Повторные покупки','34%','↑ 6 п.п. за 90 дней','green')}${metric('Без контакта 30 дней','57','Можно вернуть в продажу','red')}${metric('Средняя ценность',money(612000),'За всё время','')}</section><div class="client-toolbar"><input class="input-search" id="clientSearch" placeholder="Поиск по имени, компании, телефону или email"><button class="secondary-btn" data-action="client-filter">Фильтры</button></div><article class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Клиент</th><th>Телефон</th><th>Email</th><th>Сделок</th><th>Оплатил</th><th>Последний контакт</th><th></th></tr></thead><tbody id="clientBody">${clientRows()}</tbody></table></div></article>`}

function taskRow(t){return `<div class="task-check ${t.status==='done'?'done':''}"><button data-task-toggle="${t.id}">${t.status==='done'?'✓':''}</button><p><b>${esc(t.title)}</b><span>${esc(t.client)} · ${esc(t.assignee)} · ${esc(t.time)}</span></p><em>${t.priority==='high'?'ВАЖНО':'ЗАДАЧА'}</em></div>`}
function renderTasks(){const active=state.tasks.filter(t=>t.status==='todo'),done=state.tasks.filter(t=>t.status==='done');return pageHead('ОБЕЩАНИЯ КЛИЕНТАМ','Задачи','Простой список звонков, встреч и напоминаний, связанных со сделками.','<button class="primary-btn" data-action="new-task">+ Новая задача</button>')+`<section class="metric-grid">${metric('На сегодня',active.filter(t=>t.time.includes('Сегодня')).length,'Запланированные действия','blue')}${metric('Просрочено',active.filter(t=>t.priority==='high').length,'Нужно закрыть первым','red')}${metric('Выполнено сегодня',done.length,'Из 6 запланированных','green')}${metric('Без следующего шага','2','Сделки могут остановиться','red')}</section><div class="task-groups"><section class="task-panel"><h2>Нужно сделать · ${active.length}</h2>${active.map(taskRow).join('')}</section><section class="task-panel"><h2>Выполнено · ${done.length}</h2>${done.map(taskRow).join('')}</section></div>`}

function renderAnalytics(){return pageHead('ПРОСТЫЕ ЦИФРЫ','Аналитика продаж','Только показатели, которые помогают владельцу малого бизнеса принимать решения.','<button class="secondary-btn" data-action="analytics-period">Август 2026⌄</button><button class="secondary-btn" data-action="analytics-export">Скачать отчёт</button>')+`<section class="finance-hero"><div class="finance-summary"><small>Выручка за август</small><b>740 000 ₸</b><span>↑ 18% к этому периоду июля</span><div class="goal-track"><i style="width:9.25%"></i></div><div class="goal-label"><span>Выполнено 9%</span><span>План 8 000 000 ₸</span></div></div><div class="revenue-chart">${[['Апр',4.2],['Май',5.1],['Июн',5.8],['Июл',6.4],['Авг',.74]].map(x=>`<div><i style="height:${Math.max(18,x[1]*25)}px"></i><b>${x[0]}</b><span>${x[1]} млн</span></div>`).join('')}</div></section><section class="metric-grid">${metric('Новых заявок','43','За выбранный период','blue')}${metric('Оплачено сделок','2','Конверсия 28%','green')}${metric('Средний чек',money(370000),'↑ 12% к июлю','')}${metric('Цикл сделки','4,6 дня','От заявки до оплаты','')}</section><section class="two-col"><article class="panel"><div class="panel-head"><div><span class="eyebrow">ИСТОЧНИКИ</span><h2>Что приносит продажи</h2></div></div><div class="source-list">${[['Рекомендации',740000,100],['Сайт',460000,62],['Google',280000,38],['Instagram',0,12]].map(x=>`<div class="source-row"><span>${x[0]}</span><i><b style="width:${x[2]}%"></b></i><strong>${money(x[1])}</strong></div>`).join('')}</div></article><article class="panel"><div class="panel-head"><div><span class="eyebrow">ОТКАЗЫ</span><h2>Почему не покупают</h2></div></div><div class="reason-list">${[['Дорого',42,75],['Не дозвонились',25,45],['Выбрали конкурента',17,30],['Отложили решение',16,28]].map(x=>`<div class="reason-row"><span>${x[0]}</span><i><b style="width:${x[2]}%"></b></i><strong>${x[1]}%</strong></div>`).join('')}</div></article></section>`}

function renderSettings(){return pageHead('БЕЗ ВНЕДРЕНИЯ','Настройки','Всё необходимое для запуска небольшой команды продаж. Настройки можно закончить за один вечер.','<button class="secondary-btn" data-action="reset-demo">Сбросить демо</button>')+`<div class="settings-grid"><section class="setting-card"><h2>Шаблон бизнеса</h2><p>Готовые названия этапов и задач. Позже их можно изменить.</p><div class="template-grid"><button class="template active" data-template="services"><b>Услуги</b><span>Заявка → КП → оплата</span></button><button class="template" data-template="trade"><b>Торговля</b><span>Заказ → счёт → выдача</span></button><button class="template" data-template="education"><b>Обучение</b><span>Лид → пробный урок → оплата</span></button><button class="template" data-template="b2b"><b>B2B-продажи</b><span>Контакт → встреча → договор</span></button></div></section><section class="setting-card"><h2>Воронка продаж</h2><p>Этапы, по которым менеджер ведёт клиента.</p><div class="pipeline-list">${state.stages.filter(s=>s.id!=='lost').map((s,i)=>`<div class="pipeline-item" style="--stage-color:${s.color}"><i></i><b>${i+1}. ${s.name}</b><span>Изменить</span></div>`).join('')}</div></section><section class="setting-card"><h2>Команда</h2><p>Владелец видит всё, менеджер — только свои сделки.</p><div class="team-row"><span class="avatar">АР</span><p><b>Алексей Романов</b><span>Владелец · полный доступ</span></p><em>АКТИВЕН</em></div><div class="team-row"><span class="avatar">ДК</span><p><b>Диана Ким</b><span>Менеджер · свои сделки</span></p><em>АКТИВНА</em></div><button class="secondary-btn" data-action="invite" style="margin-top:10px">+ Пригласить сотрудника</button></section><section class="setting-card"><h2>Получение заявок</h2><p>На старте достаточно формы сайта и быстрого создания вручную.</p><div class="pipeline-list"><div class="pipeline-item" style="--stage-color:#16a36a"><i></i><b>Форма сайта</b><span>Подключена</span></div><div class="pipeline-item" style="--stage-color:#e8a21a"><i></i><b>WhatsApp Business</b><span>Подключить</span></div><div class="pipeline-item" style="--stage-color:#e8a21a"><i></i><b>Instagram</b><span>Подключить</span></div></div><button class="primary-btn" data-action="integration" style="margin-top:10px">Настроить каналы</button></section></div>`}

function render(){const s=route();updateChrome(s);let html='';if(s==='today')html=renderToday();else if(s==='sales')html=renderSales();else if(s==='clients')html=renderClients();else if(s==='tasks')html=renderTasks();else if(s==='analytics')html=renderAnalytics();else if(s==='settings')html=renderSettings();else html=renderToday();view.innerHTML=guide(s)+html;view.focus({preventScroll:true})}

function dealDetail(d){const s=stage(d.stage),activeStages=state.stages.filter(x=>x.id!=='lost');return `<span class="eyebrow">СДЕЛКА ${d.id}</span><h2>${esc(d.client)}</h2><p class="drawer-sub">${esc(d.service)} · создана ${esc(d.created)}</p><div class="stage-line">${activeStages.map(x=>`<span class="${x.id===d.stage?'active':''}">${x.name}</span>`).join('')}</div><div class="detail-grid"><div><small>Сумма</small><b>${money(d.amount)}</b></div><div><small>Этап</small><b>${s.name}</b></div><div><small>Телефон</small><b>${esc(d.phone)}</b></div><div><small>Источник</small><b>${esc(d.source)}</b></div><div><small>Ответственный</small><b>${esc(d.manager)}</b></div><div><small>Следующий шаг</small><b>${esc(d.next||'Не назначен')}</b></div></div><div class="drawer-section"><h3>Комментарий</h3><p class="drawer-sub">${esc(d.note)}</p></div><div class="drawer-section"><h3>История</h3><div class="timeline">${d.activity.map(x=>`<div class="timeline-row">${esc(x)}</div>`).join('')}</div></div><div class="drawer-actions">${!['won','lost'].includes(d.stage)?`<button class="primary-btn" data-action="advance-deal" data-id="${d.id}">Следующий этап →</button><button class="secondary-btn" data-action="deal-task" data-id="${d.id}">+ Задача</button><button class="secondary-btn" data-action="deal-contact" data-id="${d.id}">Связаться</button>`:'<button class="secondary-btn" data-nav="sales">Вернуться в продажи</button>'}</div>`}
function clientDetail(c){const deals=state.deals.filter(d=>d.client===c.name);return `<span class="eyebrow">КЛИЕНТ ${c.id}</span><h2>${esc(c.name)}</h2><p class="drawer-sub">${esc(c.company)}</p><div class="detail-grid"><div><small>Телефон</small><b>${esc(c.phone)}</b></div><div><small>Email</small><b>${esc(c.email)}</b></div><div><small>Сделок</small><b>${c.deals}</b></div><div><small>Всего оплатил</small><b>${money(c.revenue)}</b></div></div><div class="drawer-section"><h3>Сделки клиента</h3>${deals.length?deals.map(d=>`<div class="action-row"><i></i><div><b>${esc(d.service)}</b><span>${stage(d.stage).name} · ${money(d.amount)}</span></div><button data-open="deal" data-id="${d.id}">→</button></div>`).join(''):'<p class="drawer-sub">Сделок пока нет.</p>'}</div><div class="drawer-actions"><button class="primary-btn" data-action="new-deal" data-client="${esc(c.name)}">+ Новая сделка</button><button class="secondary-btn" data-action="deal-contact">Связаться</button></div>`}
function handleOpen(el){if(modal.classList.contains('open'))closeModal();if(el.dataset.open==='deal'){const d=state.deals.find(x=>x.id===el.dataset.id);if(d)openDrawer(dealDetail(d))}else if(el.dataset.open==='client'){const c=state.clients.find(x=>x.id===el.dataset.id);if(c)openDrawer(clientDetail(c))}}

function dealForm(prefill=''){openModal(`<span class="eyebrow">НОВАЯ ПРОДАЖА</span><h2>Добавить сделку</h2><form id="dealForm"><div class="form-grid"><div class="field"><label>Клиент</label><input name="client" value="${esc(prefill)}" required placeholder="Имя клиента"></div><div class="field"><label>Телефон</label><input name="phone" required placeholder="+7 700 000-00-00"></div><div class="field full"><label>Что хочет купить</label><input name="service" required placeholder="Товар или услуга"></div><div class="field"><label>Сумма</label><input name="amount" type="number" required placeholder="150000"></div><div class="field"><label>Источник</label><select name="source"><option>Instagram</option><option>Сайт</option><option>WhatsApp</option><option>Google</option><option>Рекомендация</option></select></div><div class="field"><label>Ответственный</label><select name="manager"><option>Алексей</option><option>Диана</option></select></div><div class="field"><label>Следующее действие</label><input name="next" placeholder="Позвонить сегодня"></div></div><button class="primary-btn" type="submit">Создать сделку</button></form>`)}
function clientForm(){openModal(`<span class="eyebrow">НОВЫЙ КОНТАКТ</span><h2>Добавить клиента</h2><form id="clientForm"><div class="form-grid"><div class="field"><label>Имя</label><input name="name" required></div><div class="field"><label>Компания</label><input name="company"></div><div class="field"><label>Телефон</label><input name="phone" required></div><div class="field"><label>Email</label><input name="email" type="email"></div></div><button class="primary-btn" type="submit">Добавить клиента</button></form>`)}
function taskForm(dealId=''){const d=state.deals.find(x=>x.id===dealId);openModal(`<span class="eyebrow">СЛЕДУЮЩИЙ ШАГ</span><h2>Новая задача</h2><form id="taskForm"><div class="field"><label>Что сделать</label><input name="title" required value="${d?'Связаться с '+esc(d.client):''}"></div><div class="form-grid"><div class="field"><label>Клиент</label><input name="client" value="${d?esc(d.client):''}"></div><div class="field"><label>Срок</label><input name="time" value="Сегодня, 17:00"></div><div class="field"><label>Ответственный</label><select name="assignee"><option>Алексей</option><option>Диана</option></select></div><div class="field"><label>Важность</label><select name="priority"><option value="normal">Обычная</option><option value="high">Высокая</option></select></div></div><input type="hidden" name="deal" value="${esc(dealId)}"><button class="primary-btn" type="submit">Создать задачу</button></form>`)}
function searchModal(){const rows=state.deals.slice(0,5).map(d=>`<button class="action-row" style="width:100%;background:transparent;border-left:0;border-right:0;text-align:left" data-open="deal" data-id="${d.id}"><i></i><div><b>${esc(d.client)} · ${esc(d.service)}</b><span>${d.id} · ${stage(d.stage).name}</span></div><strong>${money(d.amount)}</strong></button>`).join('');openModal(`<span class="eyebrow">БЫСТРЫЙ ПОИСК</span><h2>Найти в Mini CRM</h2><div class="field"><input id="globalSearchInput" value="" placeholder="Имя, телефон, компания или сделка"></div><div class="drawer-section" id="searchResults">${rows}</div>`)}

function advanceDeal(id){const d=state.deals.find(x=>x.id===id),ids=state.stages.filter(x=>x.id!=='lost').map(x=>x.id),i=ids.indexOf(d.stage);if(i>=0&&i<ids.length-1){d.stage=ids[i+1];d.activity.push('Сегодня · Переведено на этап «'+stage(d.stage).name+'»');if(d.stage==='won')d.next='Передать заказ в работу';save();closeDrawer();render();toast('Сделка перемещена: '+stage(d.stage).name)}}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.status=t.status==='done'?'todo':'done';save();render();toast(t.status==='done'?'Задача выполнена':'Задача возвращена в работу')}
function resetDemo(){localStorage.removeItem(STORAGE_KEY);state=structuredClone(SEED);render();toast('Демо-данные восстановлены')}

function handleAction(a,el){if(a==='close-drawer')closeDrawer();else if(a==='close-modal')closeModal();else if(a==='new-deal')dealForm(el.dataset.client||'');else if(a==='new-client')clientForm();else if(a==='new-task')taskForm();else if(a==='global-search')searchModal();else if(a==='start-tour')startTour();else if(a==='advance-deal')advanceDeal(el.dataset.id);else if(a==='deal-task')taskForm(el.dataset.id);else if(a==='reset-demo')resetDemo();else if(a==='show-lost'){openModal(`<span class="eyebrow">АРХИВ</span><h2>Отказы</h2>${state.deals.filter(d=>d.stage==='lost').map(d=>`<div class="action-row risk"><i></i><div><b>${esc(d.client)}</b><span>${esc(d.note)}</span></div><strong>${money(d.amount)}</strong></div>`).join('')}`)}else if(['sales-export','client-import','client-filter','analytics-period','analytics-export','invite','integration','profile','deal-contact'].includes(a))toast({'sales-export':'Воронка выгружена в Excel','client-import':'Открыт импорт клиентов из Excel','client-filter':'Фильтры клиентов открыты','analytics-period':'Выбран период: август 2026','analytics-export':'Отчёт сформирован','invite':'Приглашение сотруднику создано','integration':'Открыты простые подключения заявок','profile':'Открыт профиль владельца','deal-contact':'Открыты звонок и WhatsApp клиента'}[a])}

const tourSteps=[
  {s:'today',selector:'.onboarding',title:'Вся CRM начинается с главного экрана',text:'Владелец видит новые заявки, просроченные обещания и деньги, которые находятся ближе всего к оплате.',tip:'Утром достаточно открыть этот экран и выполнить блок «Требует внимания».'},
  {s:'sales',selector:'.kanban-wrap',title:'Каждая заявка — карточка в воронке',text:'Карточки двигаются слева направо: новая заявка, контакт, предложение, ожидание оплаты и результат.',tip:'Нажмите карточку, чтобы увидеть телефон, комментарий и следующий шаг.'},
  {s:'clients',selector:'.data-table',title:'Клиентская база собирается сама',text:'После создания сделки контакт остаётся в общей базе вместе с покупками и историей.',tip:'Поиск работает по имени, компании, телефону и email.'},
  {s:'tasks',selector:'.task-groups',title:'CRM напоминает, кому нужно позвонить',text:'Задачи связываются со сделками. Просроченные действия автоматически попадают на главный экран.',tip:'Нажмите квадрат слева от задачи, чтобы отметить её выполненной.'},
  {s:'analytics',selector:'.finance-hero',title:'Только понятные цифры для владельца',text:'Выручка, план, конверсия, средний чек, источники и причины отказов — без сложных отчётов.',tip:'Если бизнес вырастет и потребует склад или производство, это уже отдельный проект Pllato.'}
];
let tourIndex=0;
function clearTarget(){document.querySelectorAll('.tour-target').forEach(x=>x.classList.remove('tour-target'))}
function showTour(){const t=tourSteps[tourIndex],layer=document.getElementById('tour');clearTarget();if(route()!==t.s){history.replaceState({},'',location.pathname+'?s='+t.s);render()}layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.getElementById('tourCounter').textContent=`ШАГ ${tourIndex+1} ИЗ ${tourSteps.length}`;document.getElementById('tourTitle').textContent=t.title;document.getElementById('tourText').textContent=t.text;document.getElementById('tourTip').textContent=t.tip;document.querySelector('[data-tour="back"]').disabled=tourIndex===0;document.querySelector('[data-tour="next"]').textContent=tourIndex===tourSteps.length-1?'Понятно, начать работу ✓':'Далее →';requestAnimationFrame(()=>{const target=document.querySelector(t.selector);if(target){target.classList.add('tour-target');target.scrollIntoView({behavior:'smooth',block:'center'})}})}
function startTour(){tourIndex=0;showTour()}
function closeTour(){document.getElementById('tour').classList.remove('open');document.getElementById('tour').setAttribute('aria-hidden','true');clearTarget();localStorage.setItem('pllato_mini_tour_v1','done')}
function moveTour(delta){if(tourIndex+delta>=tourSteps.length){closeTour();go('today');toast('Обучение завершено · можно создать первую сделку');return}tourIndex=Math.max(0,tourIndex+delta);showTour()}

document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){e.preventDefault();closeDrawer();go(nav.dataset.nav);return}const open=e.target.closest('[data-open]');if(open){e.preventDefault();handleOpen(open);return}const task=e.target.closest('[data-task-toggle]');if(task){e.preventDefault();toggleTask(task.dataset.taskToggle);return}const template=e.target.closest('[data-template]');if(template){document.querySelectorAll('[data-template]').forEach(x=>x.classList.toggle('active',x===template));toast('Шаблон «'+template.querySelector('b').textContent+'» выбран');return}const action=e.target.closest('[data-action]');if(action){e.preventDefault();handleAction(action.dataset.action,action);return}const tour=e.target.closest('[data-tour]');if(tour){e.preventDefault();if(tour.dataset.tour==='close')closeTour();else if(tour.dataset.tour==='back')moveTour(-1);else moveTour(1)}});
document.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target);if(e.target.id==='dealForm'){const client=fd.get('client').trim();const d={id:'D-'+(1043+state.deals.length),client,company:'',phone:fd.get('phone'),service:fd.get('service'),amount:Number(fd.get('amount')),stage:'new',source:fd.get('source'),manager:fd.get('manager'),created:'Только что',next:fd.get('next')||'Связаться с клиентом',due:'today',note:'Новая сделка создана в демо.',activity:['Только что · Сделка создана']};state.deals.unshift(d);if(!state.clients.some(c=>c.name===client))state.clients.unshift({id:'C-'+(402+state.clients.length),name:client,company:'Частный клиент',phone:d.phone,email:'',deals:1,revenue:0,last:'Сегодня'});save();closeModal();go('sales');toast('Сделка создана и добавлена в воронку')}else if(e.target.id==='clientForm'){state.clients.unshift({id:'C-'+(402+state.clients.length),name:fd.get('name'),company:fd.get('company')||'Частный клиент',phone:fd.get('phone'),email:fd.get('email'),deals:0,revenue:0,last:'Сегодня'});save();closeModal();render();toast('Клиент добавлен')}else if(e.target.id==='taskForm'){state.tasks.unshift({id:'T-'+(93+state.tasks.length),title:fd.get('title'),deal:fd.get('deal'),client:fd.get('client'),time:fd.get('time'),priority:fd.get('priority'),assignee:fd.get('assignee'),status:'todo'});save();closeModal();render();toast('Задача создана и назначена сотруднику')}});
document.addEventListener('input',e=>{if(e.target.id==='clientSearch'){const q=e.target.value.toLowerCase(),list=state.clients.filter(c=>[c.name,c.company,c.phone,c.email].join(' ').toLowerCase().includes(q));document.getElementById('clientBody').innerHTML=clientRows(list)}if(e.target.id==='globalSearchInput'){const q=e.target.value.toLowerCase(),list=state.deals.filter(d=>[d.id,d.client,d.company,d.phone,d.service].join(' ').toLowerCase().includes(q)).slice(0,8);document.getElementById('searchResults').innerHTML=list.map(d=>`<button class="action-row" style="width:100%;background:transparent;border-left:0;border-right:0;text-align:left" data-open="deal" data-id="${d.id}"><i></i><div><b>${esc(d.client)} · ${esc(d.service)}</b><span>${d.id} · ${stage(d.stage).name}</span></div><strong>${money(d.amount)}</strong></button>`).join('')||'<div class="empty">Ничего не найдено</div>'}});
document.addEventListener('dragstart',e=>{const card=e.target.closest('[data-drag-deal]');if(card){card.classList.add('dragging');e.dataTransfer.setData('text/plain',card.dataset.dragDeal)}});document.addEventListener('dragend',e=>{const card=e.target.closest('[data-drag-deal]');if(card)card.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(x=>x.classList.remove('drag-over'))});document.addEventListener('dragover',e=>{const col=e.target.closest('[data-drop-stage]');if(col){e.preventDefault();col.classList.add('drag-over')}});document.addEventListener('dragleave',e=>{const col=e.target.closest('[data-drop-stage]');if(col)col.classList.remove('drag-over')});document.addEventListener('drop',e=>{const col=e.target.closest('[data-drop-stage]');if(!col)return;e.preventDefault();const d=state.deals.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(d){d.stage=col.dataset.dropStage;d.activity.push('Сегодня · Перемещено в «'+stage(d.stage).name+'»');save();render();toast('Этап сделки изменён')}});
overlay.onclick=closeDrawer;window.onpopstate=render;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchModal()}if(e.key==='Escape'){closeDrawer();closeModal();closeTour()}});render();setTimeout(()=>{if(!localStorage.getItem('pllato_mini_tour_v1'))startTour()},600);
