
/* ===== База пациентов ===== */
let patF='all',patQ='';
const PATF=[['all','Все'],['active','Действующие'],['new','Новые'],['chronic','Хронические'],['risk','Риск']];
SC.patients=()=>{let L=PATIENTS.filter(p=>!patQ||(p.n+' '+p.ph+' '+p.dx).toLowerCase().includes(patQ.toLowerCase()));
 if(meDoc())L=L.filter(p=>p.doc===meDoc());
 if(patF==='active')L=L.filter(p=>['course','trial','control','risk','repeat'].includes(p.stage));if(patF==='new')L=L.filter(p=>['new','lead','booked'].includes(p.stage));if(patF==='chronic')L=L.filter(p=>p.chronic);if(patF==='risk')L=L.filter(p=>p.stage==='risk'||(p.stage==='chronic'&&daysBetween(p.last,TODAY)>365));
 return `<div class="hd"><div><h2>База пациентов${meDoc()?' · мои пациенты':''}</h2><p>Один пациент — одна карта на всю клинику: ЛОР, сурдолог, отоневролог и хирург видят общую историю. Видно, кто новый, кто на курсе, кто хронический и давно не был.</p></div><div class="btns"><button class="bt" onclick="act('import')">Импорт из текущей CRM</button><button class="bt p" onclick="card('newpat')">+ Пациент</button></div></div>
 <div class="filt"><input class="fin" placeholder="ФИО, телефон, диагноз" value="${esc(patQ)}" onkeydown="if(event.key==='Enter'){patQ=this.value;render()}">${PATF.map(f=>`<button class="${patF===f[0]?'on':''}" onclick="patF='${f[0]}';render()">${f[1]}</button>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Пациент</th><th class="r">Возраст</th><th>Отделение</th><th>Диагноз</th><th>Врач</th><th>Забота</th><th>Дисциплина</th><th>Был</th><th>Следующий</th><th>Кабинет</th><th class="r">Принёс за всё время</th></tr></thead><tbody>${L.map(p=>{const l=planOf(p.id);return `<tr onclick="openPat('${p.id}')"><td><b>${esc(p.n)}</b><span class="sub mono">${esc(p.ph)}</span></td><td class="r mono">${p.age}</td><td>${depm(p.dep)}</td><td>${esc(p.dx)}<span class="sub mono">${p.icd}</span></td><td>${esc(DOC(p.doc).s)}</td><td>${cst(p.stage)}</td><td>${l?`<span class="adh">${bar(adh(l),adh(l)<80?'var(--bad)':'var(--ok)')}<em>${adh(l)}%</em></span>`:'<span class="mini">—</span>'}</td><td class="mono">${dd(p.last)}</td><td class="mono">${p.next?dd(p.next):'<span class="neg">не записан</span>'}</td><td>${p.cab?'<span class="pos">подключён</span>':'<span class="mini">нет</span>'}</td><td class="r mono">${fmt(p.ltv)}</td></tr>`}).join('')}</tbody></table></div>`};

/* ===== Карта пациента ===== */
const AUD={P02:{R:[35,40,50,55,60,65],L:[30,40,45,55,60,70],d:'2026-08-28'},P07:{R:[50,55,65,70,75,80],L:[25,30,35,40,45,55],d:'2026-09-23'},P08:{R:[40,45,55,60,65,70],L:[40,50,55,60,70,75],d:'2025-08-20'},P12:{R:[35,40,45,50,55,60],L:[30,35,45,50,55,65],d:'2026-09-25'}};
const FREQ=['250','500','1к','2к','4к','8к'];
function audSvg(a,w,h){w=w||340;h=h||190;const x0=36,y0=16,W=w-x0-12,H=h-y0-24;const X=i=>x0+i*W/5,Y=v=>y0+v/100*H;
 const grid=[0,20,40,60,80,100].map(v=>`<line x1="${x0}" x2="${x0+W}" y1="${Y(v)}" y2="${Y(v)}" class="ag"/><text x="${x0-6}" y="${Y(v)+3}" text-anchor="end" class="at">${v}</text>`).join('')+FREQ.map((f,i)=>`<line x1="${X(i)}" x2="${X(i)}" y1="${y0}" y2="${y0+H}" class="ag"/><text x="${X(i)}" y="${h-6}" text-anchor="middle" class="at">${f}</text>`).join('');
 const zone=`<rect x="${x0}" y="${Y(0)}" width="${W}" height="${Y(25)-Y(0)}" class="az"/>`;
 const line=(arr,c,m)=>`<polyline points="${arr.map((v,i)=>X(i)+','+Y(v)).join(' ')}" fill="none" stroke="${c}" stroke-width="2"/>`+arr.map((v,i)=>m==='o'?`<circle cx="${X(i)}" cy="${Y(v)}" r="4.5" fill="var(--card)" stroke="${c}" stroke-width="2"/>`:`<path d="M${X(i)-4} ${Y(v)-4}l8 8M${X(i)+4} ${Y(v)-4}l-8 8" stroke="${c}" stroke-width="2"/>`).join('');
 return `<svg class="aud" viewBox="0 0 ${w} ${h}" width="100%">${zone}${grid}${line(a.R,'#c0392b','o')}${line(a.L,'#2f6f9e','x')}</svg>`}
const pvis=p=>{const V=[];if(p.id==='P01')V.push(['2026-09-10','D1','Первичная консультация: хр. тонзиллит, назначен курс'],['2026-09-17','D1','Промывка 1/10 · план лечения в кабинете'],['2026-09-29','D1','Промывка 5/10'],['2026-10-01','D1','Промывка 6/10']);
 else if(p.id==='P02')V.push(['2026-08-28','D3','Аудиометрия, тимпанометрия: тугоухость II ст.'],['2026-09-05','D6','Подбор: «Комфорт» × 2, пробное ношение 7 дней'],['2026-09-12','D6','Покупка 2 аппаратов, первая настройка']);
 else if(p.id==='P03')V.push(['2026-09-02','D5','Консультация хирурга, КТ пазух'],['2026-09-24','D5','Септопластика, выписка в тот же день'],['2026-09-30','D5','Звонок заботы: самочувствие хорошее']);
 else V.push([p.since,p.doc,'Первичная консультация: '+p.dx]);if(p.last!==p.since&&!['P01','P02','P03'].includes(p.id))V.push([p.last,p.doc,'Повторный визит']);return V};
SC.card=()=>{const p=PT(curPat)||PATIENTS[0];const l=planOf(p.id),R=REMS.filter(r=>r.p===p.id),A=AUD[p.id];
 return `<div class="crumb"><a onclick="go('patients')">Пациенты</a> / ${esc(p.n)}</div>
 <div class="phd"><div class="pav" style="--c:${DEPS[p.dep].c}">${esc(p.n.split(' ').slice(0,2).map(x=>x[0]).join(''))}</div><div class="phn"><h2>${esc(p.n)}</h2><p>${p.age} ${plural(p.age,['год','года','лет'])} · ${esc(p.ph)} · пациент с ${dl(p.since)} · ${esc(p.src)}</p><div class="phtags">${depm(p.dep)} ${cst(p.stage)} ${p.chronic?'<span class="flag">хронический</span>':''} ${p.transfer?'<span class="flag">трансфер</span>':''} ${p.cab?'<span class="flag ok">кабинет подключён</span>':'<span class="flag no">кабинета нет</span>'}</div></div>
  <div class="btns"><select class="osel" onchange="curPat=this.value;render()">${PATIENTS.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.n.split(' ').slice(0,2).join(' '))}</option>`).join('')}</select>${p.cab?'':`<button class="bt w" onclick="cabLink('${p.id}')">Отправить ссылку на кабинет</button>`}<button class="bt p" onclick="card('newappt','|'+'${p.id}')">Записать</button></div></div>
 <div class="g21"><div>
  <div class="pan"><h3>Диагноз и врач</h3>${[['Диагноз',esc(p.dx)],['МКБ-10',`<span class="mono">${p.icd}</span>`],['Лечащий врач',esc(DOC(p.doc).n)+' · '+esc(DOC(p.doc).sp)],['Координатор заботы','Гульмира'],['Принёс клинике',tg(p.ltv)]].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
  ${l?`<div class="pan"><h3>План лечения · ${prog(l)}% выполнено · дисциплина ${adh(l)}%</h3><p>${esc(l.goal)} · с ${dl(l.start)}, ${l.days} дн. · назначил ${esc(DOC(l.doc).s)}</p>${l.steps.map(s=>`<div class="stepr"><span class="kd k-${s.kind}">${KIND[s.kind]}</span><div><b>${esc(s.t)}</b><span>${s.freq?esc(s.freq):'дата: '+dl(s.date)}${s.miss?` · <em class="neg">пропущено ${s.miss}</em>`:''}</span></div>${s.tot?`<div class="stprog">${bar(pct(s.done,s.tot),s.miss?'var(--warn)':'var(--ok)')}<em>${s.done}/${s.tot}</em></div>`:`<div class="stprog"><em class="${s.date<TODAY?'':'mini'}">${s.date<=TODAY?'сегодня или раньше':'через '+daysBetween(TODAY,s.date)+' дн.'}</em></div>`}</div>`).join('')}<button class="bt" style="margin-top:10px" onclick="card('plan','${l.id}')">Открыть план</button></div>`:`<div class="pan"><h3>План лечения</h3><p class="mini">Пока нет. Врач назначает план прямо из приёма — шаги, частота, дни, контроль. Пациент видит его в кабинете, забота — у себя.</p><button class="bt p" onclick="card('newplan','${p.id}')">+ Назначить план</button></div>`}
  ${A?`<div class="pan"><h3>Аудиограмма от ${dl(A.d)}</h3><div class="audw">${audSvg(A,420,210)}<div class="legend"><span><i style="background:#c0392b"></i>правое ухо (O)</span><span><i style="background:#2f6f9e"></i>левое ухо (X)</span><span><i style="background:var(--ok-l);border:1px solid var(--ok)"></i>норма до 25 дБ</span></div></div></div>`:''}
 </div><div>
  <div class="pan"><h3>История визитов</h3><div class="tl">${pvis(p).slice().reverse().map((v,j)=>`<div class="tli ${j===0?'on':'ok'}"><span class="who">${dl(v[0])} · ${esc(DOC(v[1]).s)}</span><b>${esc(v[2])}</b></div>`).join('')}</div></div>
  <div class="pan"><h3>Напоминания сегодня</h3>${R.map(r=>`<div class="kv"><span><span class="mono">${r.t}</span> · ${esc(r.txt)}</span><b>${stm(RST,r.st)}</b></div>`).join('')||'<p class="mini">На сегодня нет.</p>'}</div>
  <div class="pan"><h3>Документы</h3>${[['Информированное согласие','подписано в кабинете'],['Заключение врача','PDF · видно пациенту'],A?['Аудиограмма','PDF · видно пациенту']:null,p.dep==='hir'?['Выписка после операции','PDF']:null].filter(Boolean).map(f=>`<div class="file"><i>PDF</i><div><b>${f[0]}</b><span>${f[1]}</span></div></div>`).join('')}</div>
 </div></div>`};
function cabLink(id){const p=PT(id);p.cab=true;render();toast(`Ссылка на кабинет отправлена в WhatsApp: ${esc(p.ph)}. Дальше — напоминания и план в кабинете, без платных сообщений.`)}

/* ===== Слух и аппараты ===== */
const HST=[['test','Аудиометрия'],['pick','Подбор'],['trial','Пробное ношение'],['buy','Покупка'],['tune1','Настройка · 2 недели'],['tune2','Настройка · 1 месяц'],['year','Годовой контроль']];
let HEAR=[
 {p:'P12',st:'pick',dev:'«Комфорт» × 2 — думает',sum:1040000,note:'Возражение «дорого» → предложить рассрочку 12 мес. и пробное ношение'},
 {p:'P07',st:'trial',dev:'«Комфорт», правое ухо',sum:520000,note:'День 6 из 7 · звонок 3-го дня: «слышу телевизор тише»'},
 {p:'P02',st:'tune1',dev:'«Комфорт» × 2',sum:1040000,note:'Сегодня 14:30, трансфер в 13:45'},
 {pn:'Ильясов К.',st:'tune2',dev:'«Базовый» × 2',sum:560000,note:'Сегодня 17:00'},
 {pn:'Жаксылыков Н.',st:'test',dev:'—',sum:0,note:'Сегодня аудиометрия, II–III ст., рекомендован подбор'},
 {pn:'Бекмуратова Ж.',st:'pick',dev:'подбор сегодня 12:30',sum:0,note:'Пришла по сарафану от Петровой Г. И.'},
 {p:'P08',st:'year',dev:'«Премиум» × 2 · 2023',sum:1780000,note:'Контроль просрочен на 1 месяц — пригласить с трансфером'}
];
SC.hearing=()=>{const sel=AUD[curPat]?curPat:'P02';
 return `<div class="hd"><div><h2>Слух и слуховые аппараты</h2><p>Самый большой чек клиники — и самый длинный путь: аудиометрия → подбор → пробное ношение → покупка → две настройки → годовой контроль. Каждый шаг виден, ни один пациент не теряется после покупки.</p></div><div class="btns"><button class="bt" onclick="go('price')">Прайс аппаратов</button></div></div>
 <div class="hpath">${HST.map(([k,n],i)=>{const L=HEAR.filter(h=>h.st===k);return `<div class="hp"><small>${i+1}</small><b>${n}</b><em>${L.length}</em>${L.map(h=>`<span onclick="${h.p?`curPat='${h.p}';render()`:`toast('Новый пациент: карта создаётся при первом визите.')`}">${esc(h.p?PT(h.p).n.split(' ').slice(0,2).join(' '):h.pn)}</span>`).join('')}</div>`}).join('')}</div>
 <div class="g12"><div class="pan"><h3>Аудиограмма · ${esc(PT(sel).n.split(' ').slice(0,2).join(' '))}</h3><p>${dl(AUD[sel].d)} · ${esc(PT(sel).dx)}</p>${audSvg(AUD[sel],360,200)}<div class="legend"><span><i style="background:#c0392b"></i>правое</span><span><i style="background:#2f6f9e"></i>левое</span></div><div class="filt" style="margin-top:10px">${Object.keys(AUD).map(id=>`<button class="${id===sel?'on':''}" onclick="curPat='${id}';render()">${esc(PT(id).n.split(' ')[0])}</button>`).join('')}</div></div>
 <div class="pan"><h3>Путь пациентов</h3><div class="tw"><table class="t"><thead><tr><th>Пациент</th><th>Шаг</th><th>Аппарат</th><th class="r">Сумма</th><th>Что дальше</th></tr></thead><tbody>${HEAR.map(h=>`<tr onclick="${h.p?`openPat('${h.p}')`:''}"><td>${esc(h.p?PT(h.p).n.split(' ').slice(0,2).join(' '):h.pn)}</td><td>${esc(HST.find(x=>x[0]===h.st)[1])}</td><td>${esc(h.dev)}</td><td class="r mono">${h.sum?fmt(h.sum):'—'}</td><td class="mini">${esc(h.note)}</td></tr>`).join('')}</tbody></table></div>
 <div class="kv" style="margin-top:8px"><span>Продано аппаратов в сентябре</span><b class="mono">14 шт. · 7,1 млн ₸</b></div><div class="kv"><span>Из пробного ношения в покупку</span><b class="mono">71%</b></div><div class="kv"><span>Пришли на настройку через 2 недели</span><b class="mono">93%</b></div></div></div>`};
