
/* ===== Отдел заботы ===== */
const CFLOW=['new','course','trial','control','risk','repeat','chronic','done'];
function moveStage(id,st){const p=PT(id);p.stage=st;render();if(document.getElementById('mbg').classList.contains('show'))closeM();toast(`${esc(p.n.split(' ').slice(0,2).join(' '))}: «${esc(CSTOF(st).n)}».${st==='repeat'?' Визит в расписании, напоминание за день и в день приёма.':st==='done'?' Отправлен опрос, следующий контроль — в календаре заботы.':''}`)}
function callPat(id){const p=PT(id);toast(`Звонок ${esc(p.ph)} — запись разговора прикрепится к карте. После звонка отметьте результат.`);if(p.stage==='risk'){p.stage='course';setTimeout(render,50)}}
SC.carefunnel=()=>{const L=PATIENTS.filter(p=>CFLOW.includes(p.stage));
 return `<div class="hd"><div><h2>Отдел заботы</h2><p>Как только пациент купил услугу, курс, абонемент или аппарат — он уходит из воронки продаж сюда. Здесь работают не «сделки», а люди на лечении: курс, контроль, повторный визит, хронический контроль. Отдельный отдел, отдельная доска — без каши с новыми обращениями.</p></div><div class="btns"><button class="bt" onclick="go('remind')">Напоминания сегодня</button></div></div>
 <div class="board">${CST.map(s=>{const C=L.filter(p=>p.stage===s.k);return `<div class="bcol"><div class="bh" style="--c:${s.c}"><b>${s.n}</b><span>${C.length} · ${esc(s.d)}</span></div>${C.map(p=>{const l=planOf(p.id);return `<div class="oc" onclick="openPat('${p.id}')"><div class="ocb">${depm(p.dep)}<span class="mono">${p.age} ${plural(p.age,['год','года','лет'])}</span></div><b>${esc(p.n.split(' ').slice(0,2).join(' '))}</b><span>${esc(p.dx)}</span>${l?`<div class="adh">${bar(adh(l),adh(l)<80?'var(--bad)':'var(--ok)')}<em>${adh(l)}%</em></div>`:''}<div class="ocf"><em>${p.next?'след. '+dd(p.next):'не записан'}</em>${p.transfer?'<em>трансфер</em>':''}</div><div class="ocbtn">${s.k==='risk'?`<button class="bt sm r" onclick="event.stopPropagation();callPat('${p.id}')">Позвонить</button>`:''}${['course','control','trial','risk','done','chronic'].includes(s.k)?`<button class="bt sm" onclick="event.stopPropagation();moveStage('${p.id}','repeat')">Записать</button>`:''}${s.k==='course'||s.k==='repeat'?`<button class="bt sm" onclick="event.stopPropagation();moveStage('${p.id}','done')">Завершить</button>`:''}</div></div>`}).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>
 ${said('«Чтобы это ушло в другой блок, который с действующими пациентами работает, и другой отдел этим занимался — чтобы каши не было.»','Новые обращения — в «Продажах», действующие пациенты — здесь, у Гульмиры.')}`};

/* ===== Планы лечения ===== */
SC.plans=()=>{let L=PLANS;if(meDoc())L=L.filter(l=>l.doc===meDoc());
 return `<div class="hd"><div><h2>Планы лечения</h2><p>Врач назначает план прямо в карте: что делать в клинике, что дома, как часто, сколько дней, когда контроль. Пациент получает план в кабинете и каждый день отмечает «сделал». Забота видит, кто выполняет, а кто пропускает — до того, как пациент потеряется.</p></div><div class="btns"><button class="bt p" onclick="card('newplan','P06')">+ Назначить план</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Пациент</th><th>Врач</th><th>Цель</th><th>Шаги</th><th>Выполнено</th><th>Дисциплина</th><th>Контроль</th></tr></thead><tbody>${L.map(l=>{const p=PT(l.p),v=l.steps.find(s=>s.kind==='visit'&&s.date>=TODAY);return `<tr onclick="card('plan','${l.id}')"><td><b>${esc(p.n.split(' ').slice(0,2).join(' '))}</b><span class="sub">${esc(p.dx)}</span></td><td>${esc(DOC(l.doc).s)}</td><td class="mini">${esc(l.goal)}</td><td>${l.steps.map(s=>`<span class="kd k-${s.kind}" title="${esc(s.t)}">${KIND[s.kind][0]}</span>`).join('')}</td><td><span class="adh">${bar(prog(l))}<em>${prog(l)}%</em></span></td><td><span class="adh">${bar(adh(l),adh(l)<80?'var(--bad)':'var(--ok)')}<em class="${adh(l)<80?'neg':''}">${adh(l)}%</em></span></td><td class="mono">${v?dd(v.date):'—'}</td></tr>`}).join('')}</tbody></table></div>
 <div class="g3" style="margin-top:12px"><div class="pan"><h3>Шаблоны врачей</h3>${['Хр. тонзиллит: «Тонзиллор» × 10 + полоскание 14 дн.','После септопластики: промывка 3×/день 14 дн., осмотры 7 и 14 день','Синусит: «кукушка» через 3 дня × 5 + спрей','ДППГ: гимнастика 21 день + контроль','Слуховой аппарат: 8 ч/день, настройки 2 нед. и 1 мес.'].map(x=>`<div class="li"><i>✓</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Как пациент отмечает</h3><p class="mini">В кабинете — список на сегодня крупными кнопками: «Сделал», «Не получилось», «Есть вопрос». Без ответа 2 дня подряд — карточка уходит в «Риск», заботе — задача позвонить.</p></div>
 <div class="pan"><h3>Что видит врач</h3><p class="mini">На контрольном приёме — график дисциплины по дням и вопросы пациента. Видно, помог курс или его просто не выполняли.</p></div></div>
 ${said('«ЛОР пишет: промывка через три дня, курс лечения четырнадцать дней… Вы занятой человек — вы будете забывать. А мы хотим делать пациенту здоровье, потому что забота.»')}`};

/* ===== Напоминания ===== */
function remCall(id){const r=REMS.find(x=>x.id===id);r.st='call';render();toast(`Позвонили: ${esc(PT(r.p).n.split(' ').slice(0,2).join(' '))}. Результат звонка — в карте.`)}
function remSend(){let n=0;REMS.filter(r=>r.st==='plan'&&r.t<=NOW).forEach(r=>{r.st='sent';n++});render();toast(n?`Отправлено ${n}.`:'Все напоминания до текущего часа уже ушли — остальные уйдут по расписанию.')}
SC.remind=()=>{const cab=REMS.filter(r=>r.ch==='cab').length,wa=REMS.filter(r=>r.ch==='wa').length;
 return `<div class="hd"><div><h2>Напоминания · сегодня</h2><p>Напоминания идут из плана лечения сами: в кабинет пациента (бесплатно, уведомлением на телефон) — и только важное в WhatsApp. Нет ответа — карточка в «Позвонить».</p></div><div class="btns"><button class="bt" onclick="remSend()">Отправить по расписанию</button></div></div>
 <div class="wid"><div><small>Всего на сегодня</small><b>${REMS.length}</b></div><div><small>Через кабинет</small><b class="g">${cab}</b><span>бесплатно</span></div><div><small>Через WhatsApp</small><b class="w">${wa}</b><span>только важное</span></div><div><small>Отметили «сделал»</small><b class="g">${REMS.filter(r=>r.st==='done').length}</b></div><div><small>Позвонить</small><b class="r">${REMS.filter(r=>r.st==='nores').length}</b></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Время</th><th>Пациент</th><th>Что</th><th>Канал</th><th>Статус</th><th></th></tr></thead><tbody>${REMS.slice().sort((a,b)=>a.t<b.t?-1:1).map(r=>`<tr onclick="openPat('${r.p}')"><td class="mono">${r.t}</td><td>${esc(PT(r.p).n.split(' ').slice(0,2).join(' '))}<span class="sub">${PT(r.p).age} лет</span></td><td>${esc(r.txt)}</td><td>${r.ch==='cab'?'<span class="chn cab">Кабинет</span>':'<span class="chn wa">WhatsApp</span>'}</td><td>${stm(RST,r.st)}</td><td>${r.st==='nores'?`<button class="bt sm r" onclick="event.stopPropagation();remCall('${r.id}')">Позвонил</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«Не хочу, чтобы это было в WhatsApp-переписке… это всё же деньги… и не хотелось бы зависеть от стороннего сервиса.»','Поэтому основной канал — кабинет пациента по ссылке: уведомления бесплатные, история остаётся у клиники.')}`};

/* ===== Хронические ===== */
function invite(id){const p=PT(id);p.next=addDays(TODAY,6);p.stage='repeat';render();toast(`${esc(p.n.split(' ').slice(0,2).join(' '))} приглашён(а) на ${dl(p.next)}${p.transfer?', трансфер включён':''}. Сообщение — в кабинет${p.cab?'':' и WhatsApp'}.`)}
SC.chronic=()=>{const L=PATIENTS.filter(p=>p.chronic).map(p=>{const due=p.next||addDays(p.last,p.dep==='surd'?365:180);return [p,due,daysBetween(TODAY,due)]}).sort((a,b)=>a[2]-b[2]);
 return `<div class="hd"><div><h2>Хронические пациенты · контроль</h2><p>У большинства пациентов после 30 есть хроническое заболевание: тонзиллит, синусит, тугоухость, ринит. Система сама считает, когда каждому пора на контроль, и ставит задачу заботе за 2 недели — пациент остаётся у клиники, а не уходит в поликлинику.</p></div></div>
 <div class="wid"><div><small>Хронических</small><b>${L.length}</b></div><div><small>Просрочен контроль</small><b class="r">${L.filter(x=>x[2]<0).length}</b></div><div><small>В ближайшие 14 дней</small><b class="w">${L.filter(x=>x[2]>=0&&x[2]<=14).length}</b></div><div><small>Вернулись на контроль за квартал</small><b class="g">68%</b></div><div><small>Выручка от хронических</small><b class="a">41%</b><span>от всей выручки</span></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Пациент</th><th>Заболевание</th><th>Отделение</th><th>Был</th><th>Контроль</th><th class="r">Дней</th><th>Трансфер</th><th></th></tr></thead><tbody>${L.map(([p,due,d])=>`<tr onclick="openPat('${p.id}')"><td><b>${esc(p.n.split(' ').slice(0,2).join(' '))}</b><span class="sub">${p.age} лет</span></td><td>${esc(p.dx)}</td><td>${depm(p.dep)}</td><td class="mono">${dl(p.last)}</td><td class="mono">${dl(due)}</td><td class="r mono ${d<0?'neg':d<=14?'warnt':''}"><b>${d}</b></td><td>${p.transfer?'да':'—'}</td><td>${p.stage==='repeat'?'<span class="pos">записан</span>':`<button class="bt sm p" onclick="event.stopPropagation();invite('${p.id}')">Пригласить</button>`}</td></tr>`).join('')}</tbody></table></div>
 ${said('«У каждого пациента от тридцати плюс — хронические заболевания… Я хочу оставить этого пациента у себя.»')}`};

/* ===== Отзывы ===== */
SC.feedback=()=>{const prom=FEED.filter(f=>f.nps>=9).length,det=FEED.filter(f=>f.nps<=6).length,nps=Math.round((prom-det)/FEED.length*100);
 return `<div class="hd"><div><h2>Отзывы и NPS</h2><p>После каждого визита и в конце курса пациент в кабинете ставит оценку от 0 до 10 и пишет пару слов. Низкая оценка — сразу задача руководителю: перезвонить и разобраться. Высокая — просьба оставить отзыв в 2ГИС.</p></div></div>
 <div class="wid"><div><small>NPS за сентябрь</small><b class="${nps>=50?'g':'w'}">${nps}</b></div><div><small>Оценок</small><b>${FEED.length}</b></div><div><small>Промоутеры (9–10)</small><b class="g">${prom}</b></div><div><small>Критики (0–6)</small><b class="r">${det}</b></div><div><small>Отзывов в 2ГИС</small><b>+12</b><span>за месяц</span></div></div>
 <div class="g2">${FEED.map(f=>`<div class="pan fb ${f.nps<=6?'bad':''}"><div class="fbh"><b class="nps">${f.nps}</b><div><b>${esc(f.pn||PT(f.p).n.split(' ').slice(0,2).join(' '))}</b><span>${dl(f.d)} · ${esc(DOC(f.doc).s)}</span></div></div><p>«${esc(f.txt)}»</p>${f.ans?`<div class="note" style="--tone:var(--ok)"><b>Что сделали</b><p>${esc(f.ans)}</p></div>`:''}</div>`).join('')}</div>`};

/* ===== Кабинет пациента ===== */
let cabDone={a:true,b:false,c:false};
SC.cabinet=()=>`<div class="hd"><div><h2>Кабинет пациента</h2><p>Отдельное приложение пока не нужно: пациент получает ссылку в WhatsApp один раз, открывает её в браузере и сохраняет на экран телефона. Внутри — план на сегодня, записи, трансфер, результаты и связь с отделом заботы. Крупные буквы и кнопки — для пациентов старшего возраста.</p></div><div class="btns"><button class="bt" onclick="cabLink('P08')">Отправить ссылку Ивановой Т. Н.</button></div></div>
 <div class="phones">
  <div class="phone big"><div class="pht"><b>Здравствуйте, Нурлан!</b><small>после септопластики · день 7 из 14</small></div><div class="pb"><div class="cabh">Сегодня</div>
   ${[['a','08:00','Промывка носа — утро'],['b','14:00','Промывка носа — день'],['c','20:00','Промывка носа — вечер']].map(([k,t,x])=>`<div class="cabi ${cabDone[k]?'ok':''}" onclick="cabDone.${k}=!cabDone.${k};render()"><span>${t}</span><b>${x}</b><i>${cabDone[k]?'✓ Сделал':'Отметить'}</i></div>`).join('')}
   <div class="cabn"><b>13:00 · осмотр хирурга</b><span>Байжанов Е. С. · операционная</span></div><div class="pbtn" onclick="toast('Вопрос ушёл координатору заботы — ответ придёт сюда же.')">Задать вопрос врачу</div></div></div>
  <div class="phone big"><div class="pht"><b>Галина Ивановна</b><small>слуховые аппараты · настройка</small></div><div class="pb"><div class="cabh">Ваши записи</div><div class="cabn"><b>Сегодня, 14:30 · настройка</b><span>Ким Е. В. · каб. 3</span></div><div class="cabn car"><b>Машина заберёт в 13:45</b><span>ул. Сыганак, 25 · водитель Серик</span></div><div class="cabh">Батарейки</div><div class="cabn"><b>Замена 05.10</b><span>напомним накануне</span></div><div class="pbtn" onclick="toast('Перенос записи: выберите удобное время — администратор подтвердит.')">Перенести запись</div></div></div>
  <div class="phone big"><div class="pht"><b>Как прошёл визит?</b><small>Оспанова Г. А. · курс завершён</small></div><div class="pb"><div class="npsr">${[0,1,2,3,4,5,6,7,8,9,10].map(n=>`<span class="${n===10?'on':''}">${n}</span>`).join('')}</div><div class="cabh">Результаты</div><div class="file"><i>PDF</i><div><b>Заключение ЛОР</b><span>30.09.2026</span></div></div><div class="cabh">Следующий контроль</div><div class="cabn"><b>30 декабря</b><span>напомним за 2 недели</span></div><div class="pbtn" onclick="toast('Спасибо! Отзыв в 2ГИС — по ссылке.')">Отправить оценку</div></div></div>
 </div>
 <div class="g3"><div class="note"><b>Почему не приложение сразу</b><p>Приложение в App Store и Google Play — это массовость: сотни пациентов в день и телемедицина. Для одной клиники кабинет по ссылке даёт то же самое и входит в стандартный пакет.</p></div><div class="note"><b>Уведомления</b><p>Кабинет сохраняется на экран телефона и присылает уведомления сам — без платных сообщений WhatsApp за каждое напоминание.</p></div><div class="note"><b>Что видит клиника</b><p>Каждое действие пациента: открыл, отметил, пропустил, спросил. Вы видите весь путь лечения, а не только визиты.</p></div></div>
 ${said('«Чтобы он видел, что ему пить, а мы видели все пути его действий… через приложение, чтобы не было дорого.»')}`;
