
/* ===== Воронка новых ===== */
const LNEXT={new:'contact',contact:'booked',booked:'came',came:'bought',think:'booked'};
function leadAdv(id){const l=LEADS.find(x=>x.id===id);const n=LNEXT[l.st];if(!n)return;l.st=n;render();toast(n==='bought'?`${esc(l.n)} купил(а) — карточка передана в отдел заботы, координатор Гульмира. В продажах больше не висит.`:`${esc(l.n)}: «${esc(LST.find(s=>s.k===n).n)}».`)}
SC.funnel=()=>`<div class="hd"><div><h2>Воронка новых обращений</h2><p>Только новые: Instagram, 2ГИС, сайт, наружная реклама, сарафан. Цель воронки — довести до первого визита и покупки. Купил — пациент уходит в отдел заботы, а не остаётся «сделкой» в продажах.</p></div><div class="btns"><button class="bt p" onclick="card('newlead')">+ Обращение</button></div></div>
 <div class="board">${LST.map(s=>{const C=LEADS.filter(l=>l.st===s.k);return `<div class="bcol"><div class="bh" style="--c:${s.c}"><b>${s.n}</b><span>${C.length} · ${fmt(C.reduce((a,l)=>a+l.sum,0))} ₸</span></div>${C.map(l=>`<div class="oc"><div class="ocb"><span class="src">${esc(l.src)}</span><span class="mono">${l.age} ${plural(l.age,['год','года','лет'])}</span></div><b>${esc(l.n)}</b><span>${esc(l.want)}</span>${l.why?`<span class="ocw">${esc(l.why)}</span>`:''}<div class="ocf"><strong>${fmt(l.sum)} ₸</strong><em>${STAFF[l.mgr]}</em></div>${LNEXT[l.st]?`<div class="ocbtn"><button class="bt sm p" onclick="leadAdv('${l.id}')">${{new:'Связались',contact:'Записать',booked:'Пришёл',came:'Купил',think:'Записать'}[l.st]}</button></div>`:''}</div>`).join('')||'<div class="kempty">—</div>'}</div>`}).join('')}</div>`;

/* ===== Звонки и разбор ===== */
let curCall='C1';
SC.calls=()=>{const c=CALLS.find(x=>x.id===curCall)||CALLS[0];
 return `<div class="hd"><div><h2>Звонки и разбор</h2><p>IP-телефония в системе: каждый звонок записан и привязан к пациенту. По каждому менеджеру видно, сколько звонков дошло до записи, визита и покупки, и на каком шаге разговор «сливается». Не чтобы наказать — чтобы понять, чему учить.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Менеджер</th><th class="r">Звонков</th><th class="r">Разговоров</th><th class="r">Записал</th><th class="r">Пришли</th><th class="r">Купили</th><th>Из разговора в запись</th><th class="r">Оценка звонков</th></tr></thead><tbody>${Object.entries(MGR).map(([k,m])=>`<tr><td><b>${m.n}</b></td><td class="r mono">${m.calls}</td><td class="r mono">${m.talk}</td><td class="r mono">${m.booked}</td><td class="r mono">${m.came}</td><td class="r mono">${m.bought}</td><td><span class="adh">${bar(pct(m.booked,m.talk),pct(m.booked,m.talk)<35?'var(--bad)':'var(--ok)')}<em class="${pct(m.booked,m.talk)<35?'neg':''}">${pct(m.booked,m.talk)}%</em></span></td><td class="r mono ${m.score<70?'neg':''}"><b>${m.score}</b></td></tr>`).join('')}</tbody></table></div>
 <div class="g12" style="margin-top:12px"><div class="pan"><h3>Звонки сегодня</h3>${CALLS.map(x=>`<div class="cl ${x.id===c.id?'on':''}" onclick="curCall='${x.id}';render()"><span class="mono">${x.t}</span><div><b>${esc(x.who)}</b><span>${STAFF[x.mgr]} · ${esc(x.want)} · ${x.dur}</span></div><em class="${x.score<70?'neg':'pos'}">${x.score}</em></div>`).join('')}</div>
 <div class="pan"><h3>Разбор: ${esc(c.who)} · ${STAFF[c.mgr]}</h3><div class="wave">${Array.from({length:64},(_,i)=>`<i style="height:${8+Math.round(Math.abs(Math.sin(i*1.7+c.score))*26)}px"></i>`).join('')}</div><p class="mini" style="margin:6px 0 10px">${c.dur} · ${esc(c.want)} · ${c.res==='booked'?'<b class="pos">записан</b>':c.res==='lost'?'<b class="neg">не записан</b>':'<b class="warnt">перезвонить</b>'}</p>
  ${CHK.map((x,i)=>`<div class="li ${c.chk[i]?'':'r'}"><i>${c.chk[i]?'✓':'×'}</i><span>${x}</span></div>`).join('')}
  ${c.lost?`<div class="note" style="--tone:var(--bad)"><b>Где потеряли пациента</b><p>${esc(c.lost)}</p></div><button class="bt p" style="margin-top:10px" onclick="go('trainer')">Назначить тренажёр по этому шагу</button>`:'<div class="note" style="--tone:var(--ok)"><b>Хороший звонок</b><p>Можно сохранить как образец для новых менеджеров.</p></div>'}</div></div>
 ${said('«Из десяти разговоров восемь он слил, два закрыл — чтобы понимать предметно, кто виноват, и не тыкать его, а взращивать.»')}`};

/* ===== Найм и тренажёр ===== */
const CNST={offer:['Оффер','#3e7d4e'],trainer:['Тренажёр','#2f6f9e'],interview:['Интервью','#a87a1e'],reject:['Не прошёл','#8a8f98']};
SC.trainer=()=>`<div class="hd"><div><h2>Найм и тренажёр менеджеров</h2><p>Хороший менеджер начинается с найма. Кандидат проходит тест по ссылке за 15 минут, затем тест на логику — на интервью приходят единицы из сотен откликов. На стажировке — тренажёр на реальных сценариях клиники: допуск к звонкам с 90 баллов из 100.</p></div><div class="btns"><button class="bt" onclick="act('testlink')">Скопировать ссылку на тест</button></div></div>
 <div class="hfun">${[['200','откликов'],['20','прошли тест'],['5','прошли логику'],['3','на стажировке'],['1','допущен к звонкам']].map((x,i)=>`<div style="--w:${100-i*17}%"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>
 <div class="g2"><div class="pan"><h3>Кандидаты</h3><div class="tw"><table class="t"><thead><tr><th>Кандидат</th><th>Откуда</th><th class="r">Тест</th><th class="r">Логика</th><th class="r">Тренажёр</th><th>Статус</th></tr></thead><tbody>${CANDS.map(c=>`<tr><td>${esc(c.n)}</td><td>${esc(c.src)}</td><td class="r mono ${c.test<80?'neg':''}">${c.test}</td><td class="r mono ${c.iq<120?'neg':''}">${c.iq}</td><td class="r mono">${c.trainer==null?'—':c.trainer}</td><td><span class="st" style="--sc:${CNST[c.st][1]}">${CNST[c.st][0]}</span></td></tr>`).join('')}</tbody></table></div></div>
 <div class="pan"><h3>Сценарии тренажёра</h3><p>Менеджер разговаривает с «пациентом» по сценарию, система оценивает каждый шаг. Средний балл команды:</p>${SCEN.map(s=>`<div class="fr"><span>${esc(s[0])}<span class="sub">${esc(s[1])}</span></span>${bar(s[2],s[2]<70?'var(--bad)':s[2]<85?'var(--warn)':'var(--ok)')}<b>${s[2]}</b></div>`).join('')}</div></div>
 <div class="note"><b>Отдельный модуль</b><p>Тесты и тренажёр мы уже сделали и используем для своего найма. Для клиники адаптируем под ваши сценарии — считается отдельно, по часам, один раз; ежемесячной платы нет.</p></div>`;

/* ===== Прайс и абонементы ===== */
SC.price=()=>`<div class="hd"><div><h2>Прайс и абонементы</h2><p>Один прайс на всю клинику: администратор, менеджер и кабинет пациента видят одинаковые цены. Абонементы превращают разовый визит в курс — и пациент автоматически попадает в отдел заботы.</p></div><div class="btns"><button class="bt" onclick="card('ord','№ 46-П')">Приказ о новом прайсе</button></div></div>
 <div class="abons">${ABON.map(a=>`<div class="abon" style="--c:${a.c}"><small>абонемент</small><b>${esc(a.n)}</b><span>${esc(a.what)}</span><strong>${a.price?tg(a.price):esc(a.note)}</strong><em>продано ${a.sold}</em></div>`).join('')}</div>
 <div class="g3">${['lor','surd','oto','hir','care'].map(k=>`<div class="pan"><h3>${depm(k)}</h3>${PRICE.filter(x=>x[0]===k).map(x=>`<div class="kv"><span>${esc(x[1])}</span><b class="mono">${x[2]?fmt(x[2]):'входит'}</b></div>`).join('')}</div>`).join('')}</div>`;

/* ===== Маркетинг ===== */
const SRC=[['Сарафан',38,31,21,8400000,0],['2ГИС',64,41,22,2100000,180000],['Instagram',92,37,15,3900000,450000],['Сайт',41,24,11,1900000,120000],['Наружная реклама',18,9,5,2300000,250000]];
SC.marketing=()=>`<div class="hd"><div><h2>Маркетинг и источники</h2><p>Откуда приходят пациенты и сколько стоит каждый. Видно не только заявки, но и визиты, покупки и выручку до конца — включая повторные визиты и аппараты через месяц.</p></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Источник</th><th class="r">Обращений</th><th class="r">Пришли</th><th class="r">Купили</th><th class="r">Выручка</th><th class="r">Расход</th><th class="r">Стоимость пациента</th><th class="r">Окупаемость</th></tr></thead><tbody>${SRC.map(s=>`<tr><td><b>${s[0]}</b></td><td class="r mono">${s[1]}</td><td class="r mono">${s[2]}</td><td class="r mono">${s[3]}</td><td class="r mono">${fmt(s[4])}</td><td class="r mono">${s[5]?fmt(s[5]):'—'}</td><td class="r mono">${s[5]?fmt(s[5]/s[2]):'—'}</td><td class="r mono ${s[5]&&s[4]/s[5]<5?'warnt':'pos'}">${s[5]?'×'+Math.round(s[4]/s[5]):'∞'}</td></tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Возраст пациентов</h3>${[['до 30',9],['30–45',22],['45–60',27],['60–75',31],['75+',11]].map(x=>`<div class="fr"><span>${x[0]}</span>${bar(x[1]*3)}<b>${x[1]}%</b></div>`).join('')}<p class="mini" style="margin-top:8px">Аудитория старше — поэтому трансфер, крупный кабинет и звонок дочери или сыну с разрешения пациента.</p></div>
 <div class="pan"><h3>Районы Астаны</h3>${[['Есиль',26],['Алматы',24],['Сарыарка',19],['Байконыр',17],['Нура',9],['Пригород',5]].map(x=>`<div class="fr"><span>${x[0]}</span>${bar(x[1]*3,'var(--brand2)')}<b>${x[1]}%</b></div>`).join('')}</div></div>`;
