
/* ===== Дашборд руководителя ===== */
const WEEKS=[['01.09',62,71,48],['08.09',65,74,51],['15.09',70,78,55],['22.09',74,83,58],['29.09',79,86,61]];
SC.dash=()=>`<div class="hd"><div><h2>Дашборд руководителя · сентябрь</h2><p>Не только выручка и новые пациенты, а то, ради чего строится забота: доходят ли записанные, возвращаются ли пациенты, выполняют ли лечение. Цифры появляются сами из записи, планов и кассы — без отчётов в Excel.</p></div><div class="btns"><button class="bt" onclick="act('report')">Отчёт в WhatsApp каждый вечер</button></div></div>
 <div class="wid"><div><small>Выручка за месяц</small><b class="a">18,6 млн</b><span>+14% к августу</span></div><div><small>Доходимость</small><b class="g">86%</b><span>записался → пришёл</span></div><div><small>Возвращаемость</small><b class="g">61%</b><span>пришли повторно за 90 дней</span></div><div><small>Курсы до конца</small><b>74%</b><span>выполнили план полностью</span></div><div><small>NPS</small><b class="g">${Math.round((FEED.filter(f=>f.nps>=9).length-FEED.filter(f=>f.nps<=6).length)/FEED.length*100)}</b><span>${FEED.length} оценок</span></div></div>
 <div class="g2"><div class="pan"><h3>Пять недель заботы</h3><p>С запуском отдела заботы растут все три показателя.</p><div class="wk">${WEEKS.map(w=>`<div class="wkc"><div class="wkb"><i style="height:${w[1]}%;background:var(--brand)"></i><i style="height:${w[2]}%;background:var(--ok)"></i><i style="height:${w[3]}%;background:var(--brand2)"></i></div><small>${w[0]}</small></div>`).join('')}</div><div class="legend"><span><i style="background:var(--brand)"></i>дисциплина по планам, %</span><span><i style="background:var(--ok)"></i>доходимость, %</span><span><i style="background:var(--brand2)"></i>возвращаемость, %</span></div></div>
 <div class="pan"><h3>Выручка по отделениям</h3>${[['lor',6.2],['surd',8.1],['oto',1.4],['hir',2.9]].map(x=>`<div class="fr"><span>${depm(x[0])}</span>${bar(x[1]/8.1*100,DEPS[x[0]].c)}<b>${x[1].toString().replace('.',',')} млн</b></div>`).join('')}
  <div class="split2"><div><small>От действующих пациентов</small><b>57%</b><span>курсы, контроль, настройки, абонементы</span></div><div><small>От новых</small><b>43%</b><span>первый визит, операции, аппараты</span></div></div></div></div>
 <div class="g3"><div class="pan"><h3>Врачи</h3>${DOCS.map(d=>`<div class="kv"><span>${esc(d.s)}</span><b class="mono">${{D1:'96%',D2:'91%',D3:'98%',D4:'84%',D5:'100%',D6:'93%'}[d.id]} загрузка</b></div>`).join('')}</div>
 <div class="pan"><h3>Продажи</h3>${Object.values(MGR).map(m=>`<div class="kv"><span>${m.n}</span><b class="mono">${pct(m.booked,m.talk)}% в запись · ${m.bought} покупок</b></div>`).join('')}</div>
 <div class="pan"><h3>Забота</h3>${[['Пациентов на курсах',PLANS.length],['В риске',PATIENTS.filter(p=>p.stage==='risk').length],['Просрочен контроль',PATIENTS.filter(p=>p.chronic&&daysBetween(p.last,TODAY)>365).length],['Напоминаний за месяц','1 284']].map(x=>`<div class="kv"><span>${x[0]}</span><b class="mono">${x[1]}</b></div>`).join('')}</div></div>
 ${said('«Вытаскиваем цифры дашборда… чтобы главврачи или директора уже не были слепыми во взаимодействии со своими пациентами.»')}`;

/* ===== Касса ===== */
SC.money=()=>{const tot=PAYS.reduce((s,p)=>s+p[4],0);const byM={};PAYS.forEach(p=>byM[p[3]]=(byM[p[3]]||0)+p[4]);
 return `<div class="hd"><div><h2>Касса и оплаты · сегодня</h2><p>Оплата привязана к визиту и отделению: видно, что оплачено деньгами, что списано с абонемента, что в рассрочку. Закрытие смены — сверка с терминалом и Kaspi.</p></div><div class="btns"><button class="bt" onclick="act('z')">Закрыть смену</button></div></div>
 <div class="wid"><div><small>Оплачено сегодня</small><b class="a">${tg(tot)}</b></div>${Object.entries(byM).map(([k,v])=>`<div><small>${esc(k)}</small><b>${v?tg(v):PAYS.filter(p=>p[3]===k).length+' визита'}</b></div>`).join('')}</div>
 <div class="tw"><table class="t"><thead><tr><th>Время</th><th>Пациент и услуга</th><th>Отделение</th><th>Способ</th><th class="r">Сумма</th></tr></thead><tbody>${PAYS.slice().sort((a,b)=>a[0]<b[0]?-1:1).map(p=>`<tr ${p[1]!=='X'?`onclick="openPat('${p[1]}')"`:''}><td class="mono">${p[0]}</td><td>${p[1]!=='X'?esc(PT(p[1]).n.split(' ').slice(0,2).join(' '))+' · ':''}${esc(p[2])}</td><td>${depm(p[5])}</td><td>${esc(p[3])}</td><td class="r mono">${p[4]?fmt(p[4]):'абонемент'}</td></tr>`).join('')}<tr class="total"><td colspan="4">Итого</td><td class="r mono">${fmt(tot)}</td></tr></tbody></table></div>`};

/* ===== Приказы ===== */
function signOrd(no){const o=ORDERS.find(x=>x.no===no);const me=ROLES[role].p;if(!o.need.includes(me)){toast('Ваша подпись под этим приказом не нужна — подписывают '+o.need.map(x=>STAFF[x]).join(' и ')+'.');return}if(!o.sign.includes(me))o.sign.push(me);if(o.need.every(x=>o.sign.includes(x)))o.st='ack';render();if(document.getElementById('mbg').classList.contains('show'))card('ord',no);toast(o.st==='ack'?'Приказ подписан и разослан сотрудникам — каждый отметит «ознакомлен».':'Подпись поставлена, ждём остальных.')}
SC.docs=()=>`<div class="hd"><div><h2>Приказы и подписи</h2><p>Приказы, положения и регламенты — внутри системы: подготовили, подписали электронно, разослали, сотрудники отметили «ознакомлен». Не нужны отдельные платформы для подписи и папки с бумагами.</p></div><div class="btns"><button class="bt p" onclick="card('neword')">+ Приказ</button></div></div>
 <div class="tw"><table class="t"><thead><tr><th>Номер</th><th>Дата</th><th>О чём</th><th>Подписи</th><th>Ознакомлены</th><th>Статус</th><th></th></tr></thead><tbody>${ORDERS.map(o=>`<tr onclick="card('ord','${o.no}')"><td class="mono"><b>${esc(o.no)}</b></td><td class="mono">${dd(o.d)}</td><td>${esc(o.t)}</td><td>${o.need.map(x=>`<span class="sig ${o.sign.includes(x)?'ok':''}">${esc(STAFF[x].split(' ')[0])}</span>`).join(' ')}</td><td><span class="adh">${bar(pct(o.ack[0],o.ack[1]))}<em>${o.ack[0]}/${o.ack[1]}</em></span></td><td>${o.st==='sign'?'<span class="warnt">на подписи</span>':o.st==='ack'?'<span class="acc">знакомятся</span>':'<span class="pos">исполнен</span>'}</td><td>${o.st==='sign'?`<button class="bt sm p" onclick="event.stopPropagation();signOrd('${o.no}')">Подписать</button>`:''}</td></tr>`).join('')}</tbody></table></div>
 ${said('«У всех отчёты отдельно в Excel, а для того, чтобы подписывать приказы, создаются какие-то платформы. Хочется, чтобы было всё в одном и понимали все.»')}`;

/* ===== Отчёты ===== */
let repSel='doc';
const REPS={doc:['Выручка и приёмы по врачам',['Врач','Приёмов','Новых','Повторных','Выручка'],[['Сейткали Д. М.',214,71,143,'3 410 000'],['Ахметова Ж. Е.',198,64,134,'2 790 000'],['Ким Е. В.',121,52,69,'5 260 000'],['Нурпеисов А. Б.',88,41,47,'1 380 000'],['Байжанов Е. С.',46,19,27,'2 940 000'],['Смагулова А.',73,30,43,'2 820 000']]],
 course:['Курсы лечения и дисциплина',['Отделение','Курсов','Завершено','Дисциплина','Вернулись на контроль'],[['ЛОР',58,44,'84%','71%'],['Сурдология',22,19,'90%','93%'],['Отоневрология',14,9,'72%','58%'],['Хирургия',11,11,'95%','100%']]],
 dev:['Продажи слуховых аппаратов',['Модель','Продано','Пробное → покупка','Сумма','Настройки вовремя'],[['«Базовый»',4,'67%','1 120 000','100%'],['«Комфорт»',7,'78%','3 640 000','93%'],['«Премиум»',3,'60%','2 670 000','100%']]],
 src:['Источники пациентов',['Источник','Обращений','Пришли','Купили','Выручка'],SRC.map(s=>[s[0],s[1],s[2],s[3],fmt(s[4])])]};
SC.reports=()=>{const r=REPS[repSel];
 return `<div class="hd"><div><h2>Отчёты</h2><p>Отчёты строятся из того, что сотрудники и так делают в системе: запись, приём, план, оплата, звонок. Выбрал период и отделение — получил таблицу; выгрузка в Excel и PDF одной кнопкой, если нужно отправить.</p></div><div class="btns"><button class="bt" onclick="act('xls')">Выгрузить в Excel</button><button class="bt" onclick="act('pdf')">PDF</button></div></div>
 <div class="reps">${Object.entries(REPS).map(([k,v])=>`<div class="rep ${k===repSel?'on':''}" onclick="repSel='${k}';render()"><b>${esc(v[0])}</b><span>сентябрь 2026 · вся клиника</span></div>`).join('')}</div>
 <div class="pan"><h3>${esc(r[0])} · сентябрь 2026</h3><div class="tw"><table class="t"><thead><tr>${r[1].map((h,i)=>`<th class="${i?'r':''}">${h}</th>`).join('')}</tr></thead><tbody>${r[2].map(row=>`<tr>${row.map((c,i)=>`<td class="${i?'r mono':''}">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>
 ${said('«Максимально удобно — чтобы не нужен был тяжёлый переход туда-сюда.»')}`};

/* ===== Филиалы и развитие ===== */
let BR=[{n:'Астана · основной',addr:'пр. Туран, 37',st:'live',staff:14,docs:6}];
function addBranch(){if(BR.length>1){toast('Филиал уже добавлен — в демо достаточно одного примера.');return}BR.push({n:'Астана · Сарыарка',addr:'ул. Сейфуллина, 12',st:'new',staff:0,docs:0});render();toast('Филиал создан: свои кабинеты, расписание, касса и роли. Пациенты и прайс — общие, отчёты — по каждому и вместе.')}
SC.growth=()=>`<div class="hd"><div><h2>Филиалы и развитие</h2><p>Сейчас система делается для одной клиники. Если филиальную сеть заложить с самого начала — новый филиал появляется кнопкой: свои врачи, расписание, касса и команда, общая база пациентов и сводные отчёты.</p></div><div class="btns"><button class="bt p" onclick="addBranch()">+ Филиал</button></div></div>
 <div class="brs">${BR.map(b=>`<div class="br ${b.st}"><small>${b.st==='live'?'работает':'новый'}</small><b>${esc(b.n)}</b><span>${esc(b.addr)}</span><div class="kv"><span>Сотрудников</span><b>${b.staff}</b></div><div class="kv"><span>Врачей</span><b>${b.docs}</b></div></div>`).join('')}<div class="br plan" onclick="addBranch()"><small>следующий</small><b>+ филиал</b><span>появляется за минуту, если сеть заложена сейчас</span></div></div>
 <div class="g3"><div class="pan opt"><small>Вариант 1 · сейчас</small><h3>Одна клиника</h3><b>2 500 000 ₸</b><p>Стандартный пакет: всё, что в этом демо, включая кабинет пациента по ссылке.</p></div>
 <div class="pan opt"><small>Вариант 2 · если закладываем сеть</small><h3>Филиальная сеть</h3><b>≈ 3 750 000 ₸</b><p>Примерно ×1,5 к пакету: филиалы, свои команды и роли, сводная аналитика. Дешевле, чем переделывать потом.</p></div>
 <div class="pan opt"><small>Позже · по желанию</small><h3>Приложение и телемедицина</h3><b>3 000 000 ₸</b><p>iOS и Android, когда появится массовость: онлайн-консультации, оплата, запись. Телемедицина загружает текущих врачей без новых кабинетов.</p></div></div>
 <div class="note"><b>Платформа для других клиник</b><p>Подключать сторонние медцентры как отдельных клиентов — это другая архитектура. Обсудим отдельно, когда система отработает у вас.</p></div>
 ${said('«Есть амбиции, есть желание открывать филиалы… Можем ли мы заводить других, помимо своих филиалов?»')}`;

/* ===== Роли ===== */
SC.roles=()=>{const areas=[['Расписание и запись',['AK','GV','DN','DS','EK']],['Карта пациента',['AK','GV','DS','EK','DN','GM']],['Назначение планов лечения',['AK','GV','DS','EK']],['Отдел заботы и напоминания',['AK','GM']],['Воронка и звонки',['AK','AB']],['Касса',['AK','DN']],['Приказы — подпись',['AK','GV']],['Дашборд и отчёты',['AK','GV']]];const R=Object.entries(ROLES);
 return `<div class="hd"><div><h2>Роли и права</h2><p>Врач видит своих пациентов и назначает лечение; администратор — запись, кассу и трансфер; забота — действующих пациентов; продажи — новых, без медицинских подробностей. Руководитель видит всё и меняет права сам.</p></div></div>
 <div class="tw"><table class="t mx"><thead><tr><th>Что можно</th>${R.map(([k,v])=>`<th class="c">${esc(v.av)}<span>${esc(k)}</span></th>`).join('')}</tr></thead><tbody>${areas.map(a=>`<tr><td>${a[0]}</td>${R.map(([k,v])=>`<td class="c">${a[1].includes(v.p)?'<b class="pos">●</b>':'<span class="mini">—</span>'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
 <div class="g2" style="margin-top:12px">${R.map(([k,v])=>`<div class="pan"><h3>${esc(k)} · ${esc(v.n)}</h3><p>${esc(v.note)}</p><span class="mini">${v.s.length} ${plural(v.s.length,['экран','экрана','экранов'])}</span></div>`).join('')}</div>`};

/* ===== Запуск и стоимость ===== */
SC.launch=()=>`<div class="hd"><div><h2>Запуск и стоимость</h2><p>Стандартный пакет разработки по вашему ТЗ — 2 500 000 ₸ один раз, без абонентской платы. Интеграция с 1С — отдельно, 800 000 ₸. Обычно 4–6 недель; вы торопитесь — делаем за 3–4 недели, ускорение отдельно не считаем.</p></div></div>
 <div class="pk3"><div class="on"><small>Стандартный пакет · всё ТЗ, кроме 1С</small><b>2 500 000 ₸</b><span>−10 % за скорость → 2 250 000 ₸</span></div><div><small>Интеграция с 1С · одна база</small><b>800 000 ₸</b><span>по желанию, можно позже</span></div><div><small>Пакет + 1С</small><b>3 300 000 ₸</b><span>−10 % на пакет → 3 050 000 ₸</span></div></div>
 <div class="pay3"><div><small>Старт · 10%</small><b>250 000 ₸</b><span>начинаем работу</span></div><div><small>Ядро · 45%</small><b>1 125 000 ₸</b><span>после приёмки ядра</span></div><div><small>Сдача · 45%</small><b>1 125 000 ₸</b><span>после полировки и приёмки</span></div></div>
 <div class="g2" style="margin-top:12px"><div class="pan"><h3>Ядро — первые 2 недели</h3>${['Пациент: карточка, хронология, дубли, жизненный цикл','Воронки и связи между ними, роли и права','Расписание и запись, медкарта, маршрут','Пакеты и абонементы, касса','Перенос базы из текущей CRM'].map(x=>`<div class="li"><i>✓</i><span>${x}</span></div>`).join('')}</div>
 <div class="pan"><h3>Полировка — до сдачи</h3>${['Отдел заботы, касания, реактивация, кабинет пациента','Телефония, WhatsApp, SMS, рассылки','Сквозная аналитика, LTV, сегменты, KPI, BI','Автоматизация ЕСЛИ → ТО, база знаний, журнал','1С — если выбрана'].map(x=>`<div class="li n"><i>→</i><span>${x}</span></div>`).join('')}</div></div>
 <div class="g2"><div class="pan"><h3>Отдельно, по желанию</h3>${[['Интеграция с 1С','800 000 ₸'],['Филиальная сеть с начала','≈ ×1,5 → 3 750 000 ₸'],['Приложение iOS и Android, телемедицина','3 000 000 ₸'],['Найм: тесты и тренажёр менеджеров','по часам, один раз']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
 <div class="pan"><h3>После запуска</h3><p class="mini">Доработки — 20 $ в час, считаем заранее. Если развитие идёт постоянно — подписка порядка 200 000 ₸ в месяц. Код и права ваши.</p></div></div>
 ${said('«Говорите прямо: это займёт два месяца… Мы хотим где-то до пятнадцатого запустить и посмотреть.»','Прямо: ядро — 2 недели после старта, вся система — 3–4 недели. 1С не тормозит запуск — её можно подключить следом.')}`;
