
/* ===== Карточки ===== */
const CARD={};
CARD.pat=id=>{const p=PT(id);const l=planOf(id);return [esc(p.n),`${p.age} лет · ${esc(p.dx)} · ${esc(DOC(p.doc).s)}`,`<div class="g2"><div class="pan"><h3>Пациент</h3>${[['Телефон',esc(p.ph)],['Отделение',DEPS[p.dep].n],['Стадия',CSTOF(p.stage).n],['Был',dl(p.last)],['Следующий',p.next?dl(p.next):'не записан'],['Кабинет',p.cab?'подключён':'нет']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="pan"><h3>План</h3>${l?l.steps.map(s=>`<div class="kv"><span>${esc(s.t)}</span><b>${s.tot?s.done+'/'+s.tot:dd(s.date)}</b></div>`).join(''):'<p class="mini">Нет плана.</p>'}</div></div>`]};
CARD.appt=id=>{const a=APPTS.find(x=>x.id===id);const d=DOC(a.doc);return [`${a.t} · ${esc(apN(a))}`,`${esc(d.n)} · ${esc(DEPS[d.dep].n)} · ${esc(d.room)}`,`<div class="pan"><h3>${esc(a.svc)}</h3>${[['Статус',AST[a.st].n],['Длительность',a.dur+' мин'],['Трансфер',a.tr?'да, машина заберёт за 40 минут':'нет']].map(x=>`<div class="kv"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}<div class="btns l" style="margin-top:12px">${a.st==='plan'?`<button class="bt w" onclick="setAppt('${id}','wait')">Пришёл, в холле</button><button class="bt" onclick="setAppt('${id}','noshow')">Не пришёл</button>`:''}${a.st==='wait'?`<button class="bt p" onclick="setAppt('${id}','in')">Пригласить на приём</button>`:''}${a.st==='in'?`<button class="bt g" onclick="setAppt('${id}','done')">Приём завершён</button>`:''}${a.p&&PT(a.p)?`<button class="bt" onclick="closeM();openPat('${a.p}')">Карта пациента</button>`:''}</div></div>`]};
CARD.newappt=x=>{const [dId,t]=(x||'').split('|');const pre=PT(t)?t:'';const tm=pre?'16:30':(t||'15:00');return ['Новая запись','Пациент, врач, время, трансфер',`<div class="form"><label>Пациент<select id="na_p"><option value="">Новый пациент…</option>${PATIENTS.map(p=>`<option value="${p.id}" ${p.id===pre?'selected':''}>${esc(p.n)}</option>`).join('')}</select></label><label>Врач<select id="na_d">${DOCS.map(d=>`<option value="${d.id}" ${d.id===(dId||(pre?PT(pre).doc:''))?'selected':''}>${esc(d.s)} · ${esc(DEPS[d.dep].n)}</option>`).join('')}</select></label><label>Время<select id="na_t">${SLOTS.map(s=>`<option ${s===tm?'selected':''}>${s}</option>`).join('')}</select></label><label>Услуга<select id="na_s">${PRICE.filter(p=>p[2]<100000).map(p=>`<option>${esc(p[1])}</option>`).join('')}</select></label><label>Трансфер<select id="na_tr"><option value="">не нужен</option><option value="1">нужен — заберём за 40 минут</option></select></label><label>Напоминание<select><option>в кабинет за день и за 2 часа</option><option>в WhatsApp за день</option></select></label></div><button class="bt p" onclick="newAppt()">Записать</button>`]};
function newAppt(){const v=i=>document.getElementById(i).value;const p=v('na_p'),d=v('na_d'),t=v('na_t');if(APPTS.some(a=>a.doc===d&&a.t===t)){toast('Это время у врача уже занято — выберите другое.');return}APPTS.push({id:'A'+(APPTS.length+1),doc:d,t,dur:30,p:p||'X',pn:p?'':'Новый пациент',svc:v('na_s'),st:'plan',tr:!!v('na_tr')});if(v('na_tr'))TRIPS.push({id:'T'+(TRIPS.length+1),t:'—',p:p||'',pn:p?'':'Новый пациент',addr:'адрес из карты',to:t+' · '+DOC(d).s,st:'plan',late:0});closeM();cur='schedule';schDoc='all';schDep='all';build();toast(`Записано: ${t}, ${esc(DOC(d).s)}.${v('na_tr')?' Трансфер добавлен в маршрут водителя.':''} Пациенту — подтверждение в кабинет.`)}
CARD.plan=id=>{const l=PLANS.find(x=>x.id===id),p=PT(l.p);return [`План лечения · ${esc(p.n.split(' ').slice(0,2).join(' '))}`,`${esc(p.dx)} · ${esc(DOC(l.doc).s)} · с ${dl(l.start)}, ${l.days} дн.`,`<div class="pan"><h3>${esc(l.goal)}</h3>${l.steps.map(s=>`<div class="stepr"><span class="kd k-${s.kind}">${KIND[s.kind]}</span><div><b>${esc(s.t)}</b><span>${s.freq?esc(s.freq):dl(s.date)}${s.miss?' · пропущено '+s.miss:''}</span></div><div class="stprog">${s.tot?bar(pct(s.done,s.tot))+'<em>'+s.done+'/'+s.tot+'</em>':''}</div></div>`).join('')}</div><div class="pan"><h3>Дисциплина по дням</h3><div class="days14">${Array.from({length:14},(_,i)=>{const miss=(i===4&&l.p!=='P11')||(l.p==='P04'&&[6,7,8,10].includes(i));const fut=i>9;return `<i class="${fut?'f':miss?'m':'ok'}" title="день ${i+1}"></i>`}).join('')}</div><div class="legend"><span><i style="background:var(--ok)"></i>выполнил</span><span><i style="background:var(--bad)"></i>пропустил</span><span><i style="background:var(--card3)"></i>впереди</span></div></div>`]};
CARD.newplan=pid=>{const p=PT(pid)||PATIENTS[5];return ['Назначить план лечения',`${esc(p.n)} · ${esc(p.dx)}`,`<div class="form"><label>Шаблон<select id="np_t"><option>Острый отит: капли 7 дней + контроль</option><option>Хр. тонзиллит: «Тонзиллор» × 10 + полоскание 14 дн.</option><option>Синусит: «кукушка» × 5 + спрей</option></select></label><label>Длительность, дней<input id="np_d" value="7"></label><label>Дома<input value="Капли в ухо — 3 раза в день"></label><label>Контроль<input value="${dl(addDays(TODAY,7))}"></label></div><button class="bt p" onclick="newPlan('${p.id}')">Назначить и отправить в кабинет</button>`]};
function newPlan(pid){const p=PT(pid);if(!planOf(pid))PLANS.push({id:'L'+(PLANS.length+1),p:pid,doc:p.doc,start:TODAY,days:+document.getElementById('np_d').value||7,goal:'Вылечить без осложнений',steps:[{t:'Капли в ухо',kind:'home',freq:'3 раза в день · 7 дней',tot:7,done:0},{t:'Контроль ЛОР',kind:'visit',date:addDays(TODAY,7)}]});p.stage='course';p.cab=true;closeM();render();toast(`План назначен. ${esc(p.n.split(' ').slice(0,2).join(' '))} получил ссылку на кабинет, отдел заботы видит пациента в «Курс идёт».`)}
CARD.newpat=()=>['Новый пациент','Карта создаётся один раз на всю клинику',`<div class="form"><label>ФИО<input id="nw_n" value="Ермеков Даулет Асанович"></label><label>Телефон<input id="nw_ph" value="+7 701 555 20 20"></label><label>Возраст<input id="nw_a" value="44"></label><label>Откуда узнал<select id="nw_s"><option>Instagram</option><option>2ГИС</option><option>Сарафан</option><option>Сайт</option></select></label></div><button class="bt p" onclick="newPat()">Создать карту</button>`];
function newPat(){const v=i=>document.getElementById(i).value;const id='P'+(PATIENTS.length+1);PATIENTS.push({id,n:v('nw_n'),age:+v('nw_a')||40,ph:v('nw_ph'),dep:'lor',doc:'D1',dx:'Первичное обращение',icd:'—',stage:'new',src:v('nw_s'),since:TODAY,ltv:0,last:TODAY,next:'',chronic:false,cab:false});curPat=id;closeM();go('card');toast('Карта создана. Отправьте ссылку на кабинет — и пациент получит подтверждение записи.')}
CARD.newlead=()=>['Новое обращение','Источник, интерес, менеджер',`<div class="form"><label>Имя<input id="nl_n" value="Тлеубаева Сауле"></label><label>Возраст<input id="nl_a" value="64"></label><label>Источник<select id="nl_s"><option>Instagram</option><option>2ГИС</option><option>Сарафан</option><option>Сайт</option><option>Наружная реклама</option></select></label><label>Интерес<select id="nl_w"><option>Проверка слуха</option><option>Консультация ЛОР</option><option>Слуховой аппарат</option><option>Операция</option></select></label></div><button class="bt p" onclick="newLead()">Добавить</button>`];
function newLead(){const v=i=>document.getElementById(i).value;LEADS.unshift({id:'N'+(LEADS.length+1),n:v('nl_n'),age:+v('nl_a')||50,src:v('nl_s'),want:v('nl_w'),st:'new',mgr:'AB',sum:v('nl_w')==='Слуховой аппарат'?520000:15000,d:TODAY});closeM();render();toast('Обращение в воронке, менеджеру — задача перезвонить за 15 минут.')}
CARD.ord=no=>{const o=ORDERS.find(x=>x.no===no);return [`Приказ ${esc(o.no)} от ${dl(o.d)}`,esc(o.t),`<div class="doc"><div class="dh"><div class="dlg">КАМЕРТОН<small>ЛОР-КЛИНИКА И ЦЕНТР СЛУХА · АСТАНА</small></div><div style="text-align:right;font-size:10px">${esc(o.no)}<br>${dl(o.d)}</div></div><h4>ПРИКАЗ</h4><p style="font-size:11.5px;line-height:1.7">${esc(o.t)}.</p><p style="font-size:11px;line-height:1.7">1. Утвердить порядок согласно приложению.<br>2. Ответственным ознакомить сотрудников через систему до ${dl(addDays(o.d,3))}.<br>3. Контроль исполнения оставляю за собой.</p><div class="sgn">${o.need.map(x=>`<span>${esc(STAFF[x])}: ${o.sign.includes(x)?'<b style="color:#3e7d4e">подписано ЭЦП</b>':'<u></u>'}</span>`).join('')}</div><div class="dfoot"><span>Ознакомлены: ${o.ack[0]} из ${o.ack[1]}</span><span>${o.st==='done'?'Исполнен':'В работе'}</span></div></div>${o.st==='sign'?`<button class="bt p" style="margin-top:12px" onclick="signOrd('${o.no}')">Подписать</button>`:''}`]};
CARD.neword=()=>['Новый приказ','Текст, кто подписывает, кого ознакомить',`<div class="form"><label>О чём<input id="no_t" value="О дежурствах отдела заботы в выходные"></label><label>Подписывают<select id="no_s"><option value="AK">Руководитель</option><option value="AK,GV">Руководитель и главный врач</option></select></label><label>Ознакомить<select><option>Всех сотрудников (14)</option><option>Отдел заботы (3)</option><option>Врачей (6)</option></select></label></div><button class="bt p" onclick="newOrd()">Создать и отправить на подпись</button>`];
function newOrd(){const v=i=>document.getElementById(i).value;const n=ORDERS.length+43;ORDERS.unshift({no:'№ '+n+'-П',d:TODAY,t:v('no_t'),who:ROLES[role].p,sign:[],need:v('no_s').split(','),ack:[0,14],st:'sign'});closeM();render();toast('Приказ на подписи — уведомление подписантам.')}
v2cards();
function card(k,id){const f=CARD[k];if(!f)return;let r;try{r=f(id)}catch(e){toast('Карточка не найдена');return}openM(r[0],r[1],r[2])}
function act(k){const M={report:'Каждый вечер в 20:00 руководителю: приёмы, доходимость, касса, кто в риске, что подписать.',import:'Перенос из текущей CRM: пациенты, телефоны, визиты, источники — входит в пакет.',nav:'Маршрут построен по адресам пациентов в порядке времени приёма.',z:'Смена закрыта: касса сверена с терминалом и Kaspi.',xls:'Отчёт выгружен в Excel.',pdf:'Отчёт сохранён в PDF.',testlink:'Ссылка на тест скопирована — отправьте кандидату.'};toast(M[k]||'Готово.')}
function searchDemo(v){if(!v)return;const q=v.toLowerCase().trim();const p=PATIENTS.find(x=>(x.n+' '+x.ph+' '+x.dx).toLowerCase().includes(q));if(p){openPat(p.id);return}const l=LEADS.find(x=>x.n.toLowerCase().includes(q));if(l&&allowed('funnel')){go('funnel');return}toast('Не нашлось. Ищите по ФИО, телефону или диагнозу.')}

/* ===== Каркас: шапка, вкладки-папки сверху, док разделов снизу ===== */
const ICON={an:'<path d="M4 19h16M7 16V9M12 16V5M17 16v-4"/>',day:'<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3.5 2"/>',pat:'<circle cx="12" cy="8" r="3.6"/><path d="M4.5 20c.8-4 3.8-6 7.5-6s6.7 2 7.5 6"/>',care:'<path d="M12 20s-7.5-4.6-7.5-10A4.3 4.3 0 0 1 12 7.4 4.3 4.3 0 0 1 19.5 10c0 5.4-7.5 10-7.5 10z"/>',sales:'<path d="M5 19V9M10 19V5M15 19v-7M20 19v-4"/>',mgmt:'<rect x="5" y="3.5" width="14" height="17" rx="1.5"/><path d="M8.5 8h7M8.5 12h7M8.5 16h4"/>',sys:'<circle cx="12" cy="12" r="3"/><path d="M12 3v2.5M12 18.5V21M3 12h2.5M18.5 12H21M5.6 5.6l1.8 1.8M16.6 16.6l1.8 1.8M5.6 18.4l1.8-1.8M16.6 7.4l1.8-1.8"/>'};
function renderRoles(){const r=document.getElementById('roles');if(r)r.innerHTML=Object.entries(ROLES).map(([k,v])=>`<div class="role" onclick="enter('${esc(k)}')"><div class="rav">${esc(v.av)}</div><div><b>${esc(k)}</b><span>${esc(v.n)} · ${esc(v.note)}</span></div></div>`).join('');
 const s=document.getElementById('rsel');if(s)s.innerHTML=Object.keys(ROLES).map(k=>`<option>${esc(k)}</option>`).join('')}
const allowed=k=>ROLES[role].s.indexOf(k)>=0;
function enter(k){role=ROLES[k]?k:'Руководитель';document.getElementById('gate').classList.add('hidden');document.getElementById('app').classList.remove('hidden');const s=document.getElementById('rsel');if(s)s.value=role;document.getElementById('me').textContent=ROLES[role].av;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Вы вошли как «${esc(role)}» · ${esc(ROLES[role].n)}.`)}
function switchRole(k){role=k;document.getElementById('me').textContent=ROLES[role].av;const s=document.getElementById('rsel');if(s)s.value=role;if(!allowed(cur))cur=ROLES[role].s[0];build();toast(`Роль: ${esc(role)}. ${esc(ROLES[role].note)}.`)}
function buildRail(){const on=SECOF[cur];const cnt={care:PATIENTS.filter(p=>p.stage==='risk').length+REMS.filter(r=>r.st==='nores').length,sales:LEADS.filter(l=>l.st==='new').length,mgmt:ORDERS.filter(o=>o.st==='sign').length};
 document.getElementById('rail').innerHTML=SEC.filter(s=>s.sub.some(x=>allowed(x[0]))).map(s=>`<a class="dk ${s.k===on?'on':''}" onclick="go('${s.sub.filter(x=>allowed(x[0]))[0][0]}')"><svg viewBox="0 0 24 24">${ICON[s.k]}</svg><span>${s.n}</span>${cnt[s.k]?`<em>${cnt[s.k]}</em>`:''}</a>`).join('')}
function buildSub(){const s=SEC.find(x=>x.k===SECOF[cur]);document.getElementById('sub').innerHTML=`<span class="subn">${esc(s.n)}</span>`+s.sub.filter(x=>allowed(x[0])).map(x=>`<a class="${x[0]===cur?'on':''}" onclick="go('${x[0]}')">${esc(x[1])}</a>`).join('')}
function buildNow(){const el=document.getElementById('nowc');if(!el)return;const A=APPTS;el.innerHTML=`<i></i>Сейчас: <b>${A.filter(a=>a.st==='in').length}</b> на приёме · <b>${A.filter(a=>a.st==='wait').length}</b> в холле · машина <b>${TRIPS.some(t=>t.st==='way'||t.st==='pick')?'в пути':'на месте'}</b>`}
function build(){buildRail();buildSub();render()}
function render(){const f=SC[cur]||SC.today;document.getElementById('ttl').textContent=SUBN[cur]||'Камертон';document.getElementById('content').innerHTML=`<div class="screen">${f()}</div>`;buildSub();buildRail();buildNow();
 const a=document.getElementById('addBtn');if(a)a.style.display=allowed('schedule')&&role!=='Водитель'?'':'none';try{history.replaceState(null,'','?s='+cur+(cur==='card'?'&p='+curPat:''))}catch(e){}}
function go(k){if(!allowed(k)){toast('Этой роли раздел недоступен — так работают права. Переключите роль справа вверху.');return}cur=k;build();const c=document.querySelector('.content');if(c)c.scrollTop=0}
function openM(t,s,b){document.getElementById('mt').innerHTML=t;document.getElementById('ms').innerHTML=s;document.getElementById('mbody').innerHTML=b;document.getElementById('mbg').classList.add('show');document.querySelector('.modal').scrollTop=0}
function closeM(){document.getElementById('mbg').classList.remove('show')}
let tt=null;function toast(m){const t=document.getElementById('toast');t.innerHTML=m;t.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('show'),6400)}
function applyTheme(){document.body.classList.toggle('dark',theme==='dark')}
function toggleTheme(){theme=theme==='dark'?'light':'dark';applyTheme();toast(theme==='dark'?'Тёмная тема.':'Светлая тема.')}

const TOUR=[
 ['tz','1 · Ваше ТЗ — 32 раздела, 500 пунктов — и где каждый раздел в демо. 1С — отдельной строкой.'],
 ['today','2 · Пульт клиники: кто на приёме, кто в холле, кто следующий, что требует внимания.'],
 ['life','3 · Жизненный цикл: одна сущность «Пациент» — 22 статуса, новая карточка при повторе не создаётся.'],
 ['card','4 · Карта и хронология: диагноз, протоколы, план лечения, аудиограмма, вся история.'],
 ['route','5 · Маршрут пациента: где остановился — задача ставится сама.'],
 ['funnels','6 · Воронки и связи: событие в одной воронке запускает процесс в другой.'],
 ['packs','7 · Пакеты и абонементы: автосписание, остаток, продление, заморозка.'],
 ['touches','8 · Повторные касания: 1, 3, 7, 30, 60, 90 дней, полгода, год.'],
 ['reactiv','9 · Реактивация: давно не были — сегмент, сообщение, звонок, результат.'],
 ['carefunnel','10 · Отдел заботы — отдельный отдел, а не воронка продаж.'],
 ['cabinet','11 · Кабинет пациента по ссылке: план, напоминания, отметки «сделал».'],
 ['calls','12 · Звонки и колл-центр: записи, пропущенные, разбор.'],
 ['e2e','13 · Сквозная аналитика: реклама → LTV, CPL, CAC, ROMI.'],
 ['ltv','14 · LTV, retention и когорты.'],
 ['segments','15 · Динамические сегменты.'],
 ['kpi','16 · KPI по ролям.'],
 ['lost','17 · Потерянные и причины.'],
 ['auto','18 · Автоматизация ЕСЛИ → ТО — меняете сами, без программиста.'],
 ['bi','19 · Дашборды по ролям и конструктор отчётов.'],
 ['kb','20 · База знаний, онбординг и тесты.'],
 ['integr','21 · Интеграции и API; 1С — отдельно.'],
 ['launch','22 · Стоимость: 2,5 млн, 1С — 800 000 ₸ отдельно, 10 / 45 / 45.']
];
let ti=-1,tRun=false;
function tour(){if(tRun){stopTour();return}tRun=true;ti=-1;document.getElementById('tourBtn').textContent='■';step()}
function step(){if(!tRun)return;ti++;if(ti>=TOUR.length){stopTour();toast('Сценарий закончен. Всё кликается: запись, приём, план, напоминания, забота, звонки, приказы.');return}const [k,m]=TOUR[ti];if(!allowed(k)){step();return}cur=k;if(k==='card')curPat='P01';build();toast(m);setTimeout(step,ti===0?6500:7200)}
function stopTour(){tRun=false;ti=-1;const b=document.getElementById('tourBtn');if(b)b.textContent='▶'}
(function(){renderRoles();applyTheme();const s=document.getElementById('rsel');if(s)s.addEventListener('change',e=>switchRole(e.target.value));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeM();stopTour()}});
 let q='',o='';try{const u=new URLSearchParams(location.search);q=u.get('s')||'';o=u.get('p')||''}catch(e){}if(o&&PT(o))curPat=o;
 if(q&&SECOF[q]){const r=Object.keys(ROLES).find(k=>ROLES[k].s.indexOf(q)>=0);if(r){cur=q;enter(r)}}})();
